import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 41. Generated by `npm run build-cinemas -- 2 41` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：众人道：「这个断使不得，改一句罚十杯。」桂保斟了一杯酒道：「请孙老爷后庭花饮酒。」众人重
 *   新又笑。亮功把桂保拧了一把，也喝了。下手是王文辉飞觞，桂保把嘴向孙亮功一呶，文辉会意，便
 *   道：「桃花细逐扬花落。」轮应陆宗沅、孙亮功各一杯。陆宗沅因亮功喷了他酒，便道：「无可奈何
 *   花落去。」接着杨方猷便道：「索性一总喝两杯罢。」亮功道：「很好，你说罢。」杨方本猷道：「
 *   笑隔荷花共人语。」桂保斟了两杯，孙亮功喝了。轮着桂保飞花，想了一想，说道：「好将花下承金
 *   粉。」数到又是亮功，众人说：「好。」亮功道：「不好，不好。这句是杜撰的，不是古人诗。」桂
 *   保道：「怎么是杜撰？现在是陆龟蒙的诗。」周锡爵道：「不错的，你不能不喝这杯。」亮功道：「
 *   他想了半天，有心飞到我的。他若能随口说两句飞着我，我就喝。」桂保道：「真么？你不要赖。」
 *   亮功道：「不赖，不赖。」桂保一连说了三句道：「月满花香记得无」，「漱齿花前酒半酣」，「楼
 *   上花枝笑独眠」。」众人拍手称妙，亮功无法，倒饮了三个半杯。末一杯是周锡爵，便道：「飞花寂
 *   寂燕双双。」亮功道：「你们好么，大家齐心都叫我一个人喝酒。」要周锡爵代喝，周锡爵不肯，亮
 *   功道：「我再装作小旦奉敬何如？」周锡爵笑道：「饶了我罢，我代喝就是了。」说得大家又笑，桂
 *   保笑道：「这个飞花不公，我有一个飞花最公道。」便将几朵梅花揉碎了，放在掌中，说道：「我一
 *   吹，落到人身上，都要喝的。」亮功嘻着嘴，望着桂保道：「很好，你且试吹一次，不知落到谁。」
 *   桂保故意往外一望，说道：「孙老爷家里打发人来了。」亮功扭转脸去望时，桂保对着他脸一吹，将
 *   些花瓣贴得他一脸。亮功酒多了出汗，因此花瓣黏住了，一瓣还吹进了鼻孔，打了一个喷嚏，惹得众
 *   人大笑。陆宗沅道：「这个花脸好，不用上粉。」孙亮功连忙抹下，这边桂保犹飞了一句道：「自有
 *   闲花一面春。」众人又笑了又赞，亮功要走过来不依，桂保恰好真见一个跟班进来，凑了亮功耳边说
 *   了两句。亮功登时失色，便道：「你先回去，我即刻就回。」便向王文辉道：「酒已多了，快吃饭
 *   罢。」文辉与座客均各会意，点头微笑，桂保道：「准是太太打发人来叫，回去迟了是要顶灯的。」
 *   众人又笑了一阵，文辉道：「好么，连众人一齐打趣在内。」亮功罚了桂保一杯，屁滚尿流的催饭。
 *   大家吃完，洗嗽毕，就随着亮功同散。
 *
 * Translation: The group protested unanimously, "Absolutely not! Changing a single word incurs a ten-cup
 *   penalty." Guibao poured a cup and announced, "I invite Master Sun to savor the 'Rear
 *   Courtyard Flowers' wine." The table erupted into laughter once more. Lianggong pinched
 *   Guibao playfully and drank the wine. Next, it was Wang Wenhui's turn to issue a flying
 *   toast. Guibao directed a conspicuous pout toward Sun Lianggong, and Wenhui, catching the
 *   hint, recited, "'Peach blossoms drift lazily, following the falling willow flowers.'" The
 *   count dictated that Lu Zongyuan and Sun Lianggong each drink a cup. Lu Zongyuan, still
 *   vexed by the wine sprayed in his face, quoted, "'Helplessly, the flowers fall and drift
 *   away.'" Yang Fangyou quickly followed, "Let us combine them and drink two cups together."
 *   Lianggong agreed enthusiastically, "Excellent, proceed." Yang Fangyou recited, "'Laughing
 *   across the lotus flowers, sharing words with another.'" Guibao poured two cups, and Sun
 *   Lianggong dutifully drained them. When it was Guibao's turn for the flying flower, he
 *   pondered for a moment before declaring, "'How lovely to catch the golden pollen beneath the
 *   flowers.'" The count predictably landed on Lianggong again. The guests cheered, "Splendid!"
 *   Lianggong protested vehemently, "Foul, foul! This line is utterly fabricated, it belongs to
 *   no ancient poet." Guibao retorted, "Fabricated? It is a genuine line from the poetry of Lu
 *   Guimeng." Zhou Xijue confirmed, "He is quite correct, you cannot escape this cup."
 *   Lianggong grumbled, "He pondered for an age, deliberately engineering it to land on me. If
 *   he can recite two more lines off the cuff that land on me, I will drink." Guibao
 *   challenged, "Truly? No retreating?" Lianggong affirmed, "No retreating." Guibao rattled off
 *   three lines in rapid succession: "'Do you recall the fragrant flowers beneath the full
 *   moon?'", "'Rinsing the teeth before the flowers, the wine half-consumed'", and "'In the
 *   upper chamber, the flowering branch laughs at the one who sleeps alone.'" The guests
 *   applauded wildly, praising his ingenuity. Left with no avenue of escape, Lianggong downed
 *   three and a half cups in succession. The final cup fell to Zhou Xijue, who recited, "'The
 *   flying flowers settle silently, a pair of swallows.'" Lianggong lamented, "Look at you all,
 *   conspiring together to force one man to drink all the wine." He pleaded with Zhou Xijue to
 *   drink on his behalf, but Zhou steadfastly refused. Lianggong threatened, "Shall I
 *   impersonate a female performer to present it to you again?" Zhou Xijue laughed heartily,
 *   "Spare me, I shall drink it for you." This sparked another round of laughter. Guibao
 *   smirked, "This flying flower game is inherently unfair. I possess a flying flower game of
 *   absolute impartiality." He crushed several plum blossoms, placing the petals in his palm,
 *   and announced, "I shall blow on them, whoever they land upon must drink." Lianggong,
 *   grinning broadly, watched Guibao and said, "Excellent. Try blowing once, let us see who
 *   falls victim." Guibao deliberately cast his gaze toward the door and said, "Master Sun, a
 *   messenger from your household has arrived." As Lianggong reflexively turned his head,
 *   Guibao blew forcefully, plastering Lianggong's face with petals. Flushed and sweating from
 *   the copious wine, the petals adhered stubbornly to his skin, with one drifting into his
 *   nostril, provoking a massive sneeze that sent the table into hysterics. Lu Zongyuan
 *   quipped, "What a magnificent painted face, you scarcely need theatrical makeup." Sun
 *   Lianggong hurriedly brushed the petals away. Unrelenting, Guibao flew one final line: "'The
 *   idle flowers effortlessly manifest the visage of spring.'" The guests laughed and offered
 *   renewed praise. Lianggong was preparing to lunge at Guibao in mock outrage when an actual
 *   servant entered and whispered two words in Lianggong's ear. All color drained from
 *   Lianggong's face as he instructed the servant, "Return first, I shall follow immediately."
 *   He turned to Wang Wenhui, "I have consumed too much wine, please, let us hasten the rice."
 *   Wenhui and the guests instantly grasped the situation, exchanging knowing smiles and nods.
 *   Guibao teased, "I wager the mistress has sent for you. Tarry any longer, and you shall be
 *   punished by having to balance an oil lamp on your head." The guests roared with laughter
 *   once more. Wenhui remarked, "Splendid, now you have drawn the entire table into the jest."
 *   Lianggong penalized Guibao a cup, then, in a piss-and-run panic, hurried the rice along.
 *   Once they had finished eating and rinsed their mouths, the guests dispersed in unison.
 *
 * Staging: the flower lines, Guibao’s three lines, the petals blown, and the servant’s whisper.
 */
export default defineStory({
  title: { en: 'Flying flowers', zh: '飞花' },
  description: {
    en: 'Every flower line lands on Lianggong; Guibao rattles off three more; then Guibao blows plum petals in Lianggong’s face—until a servant whispers that Madam has sent for him.',
    zh: '飞花句句数到亮功；桂保一连三句；又吹梅花贴了亮功一脸；家人来报太太叫，亮功失色催饭。',
  },
  shots: [
    {
      start: 0, end: 9,
      title: { en: 'Every line lands on him', zh: '句句飞到亮功' },
      quote: '「桃花细逐杨花落。」……「无可奈何花落去。」……「笑隔荷花共人语。」',
      caption: { en: 'Wenhui, Lu and Yang each fly a flower line, and each one lands on Lianggong.', zh: '文辉、陆宗沅、杨方猷飞花，句句数到亮功。' },
    },
    {
      start: 9, end: 18,
      title: { en: 'Three lines at once', zh: '一连说了三句' },
      quote: '桂保一连说了三句……众人拍手称妙',
      caption: { en: 'Challenged, Guibao rattles off three lines in a row; Lianggong drinks three and a half cups.', zh: '桂保一连三句，众人拍手称妙，亮功倒饮了三个半杯。' },
    },
    {
      start: 18, end: 27,
      title: { en: 'A face of petals', zh: '花瓣贴得他一脸' },
      quote: '桂保对着他脸一吹，将些花瓣贴得他一脸……打了一个喷嚏',
      caption: { en: 'Guibao crushes plum blossoms and blows them into Lianggong’s face; he sneezes. “A painted face, no powder needed!”', zh: '桂保揉碎梅花，对着亮功一吹，花瓣贴了一脸，一瓣吹进鼻孔，打了个喷嚏。' },
    },
    {
      start: 27, end: 36,
      title: { en: 'Madam has sent for him', zh: '太太打发人来叫' },
      quote: '恰好真见一个跟班进来，凑了亮功耳边说了两句。亮功登时失色',
      caption: { en: 'A real servant whispers in Lianggong’s ear; he goes pale and hurries the rice. “Madam has sent for him,” teases Guibao.', zh: '真有跟班来耳语，亮功登时失色，催饭。桂保：准是太太打发人来叫。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 4.6, zh: '文辉便道：「桃花细逐杨花落。」轮应陆宗沅、孙亮功各一杯。', en: 'Wenhui recited, “Peach blossoms drift after the willow flowers”—a cup each for Lu and Lianggong.' },
    { start: 4.6, end: 8.6, zh: '陆宗沅便道：「无可奈何花落去。」杨方猷道：「笑隔荷花共人语。」', en: 'Lu: “Helplessly the flowers fall away.” Yang: “Laughing across the lotus, talking with another.”' },
    { start: 9.4, end: 13.6, zh: '亮功道：「他若能随口说两句飞着我，我就喝。」桂保一连说了三句，', en: 'Lianggong: “If he can fly two more at me off the cuff, I’ll drink.” Guibao rattled off three lines,' },
    { start: 13.6, end: 17.6, zh: '众人拍手称妙，亮功无法，倒饮了三个半杯。', en: 'the guests applauded, and Lianggong had to drink three and a half cups.' },
    { start: 18.4, end: 22.6, zh: '桂保将几朵梅花揉碎了，说道：「我一吹，落到人身上，都要喝的。」', en: 'Guibao crushed some plum blossoms: “I’ll blow—whoever they land on must drink.”' },
    { start: 22.6, end: 26.6, zh: '对着他脸一吹，花瓣贴得他一脸，打了一个喷嚏。陆宗沅道：「这个花脸好，不用上粉。」', en: 'He blew them into Lianggong’s face; Lianggong sneezed. Lu: “A fine painted face—no powder needed!”' },
    { start: 27.4, end: 31.6, zh: '恰好真见一个跟班进来，凑了亮功耳边说了两句。亮功登时失色。', en: 'Just then a real servant came and whispered in his ear. Lianggong went pale.' },
    { start: 31.6, end: 35.6, zh: '桂保道：「准是太太打发人来叫，回去迟了是要顶灯的。」众人又笑。', en: 'Guibao: “Madam has sent for you—late home, and you’ll balance a lamp on your head!” More laughter.' },
  ],
});
