/**
 * Writes authored cinemas (story.ts + scene.ts) from compact specs. A chapter's specs live in
 * scripts/cinema/specs/chNN*.ts; run `npm run build-cinemas -- <chapter> [paragraph ...]`.
 *
 * Beats are written as code strings (e.g. "T({ place: 'study', ... })"); the writer adds the imports
 * each scene needs by looking at what its beats use.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

/** start, end, title en, title zh, quote, caption en, caption zh */
export type Shot = [number, number, string, string, string, string, string];
/** start, end, zh, en */
export type Cue = [number, number, string, string];
export type Spec = {
  /** 1-based paragraph number. */
  n: number;
  title: [string, string];
  description: [string, string];
  /** One line on how the paragraph is staged, for the file comments. */
  staging: string;
  shots: Shot[];
  beats: string[];
  subtitles: Cue[];
};

const root = join(dirname(fileURLToPath(import.meta.url)), '../..');

/** Where each beat helper comes from, relative to authored/chNN/pNN/scene.ts. */
const IMPORTS: { name: string; used: RegExp; from: string }[] = [
  { name: 'emblemBeat', used: /\bemblemBeat\(/, from: '../../../beats/album' },
  { name: 'portraitBeat', used: /\bportraitBeat\(/, from: '../../../beats/album' },
  { name: 'repertoireBeat', used: /\brepertoireBeat\(/, from: '../../../beats/album' },
  { name: 'poemBeat', used: /\bpoemBeat\(/, from: '../../../beats/album' },
  { name: 'readersBeat', used: /\breadersBeat\(/, from: '../../../beats/album' },
  { name: 'tableauBeat as T', used: /\bT\(\{/, from: '../../../beats/tableau' },
  { name: 'who', used: /\bwho\./, from: '../../../beats/tableau' },
  { name: 'coverBeat', used: /\bcoverBeat\(/, from: '../../../beats/tableau' },
  { name: 'banquetBeat', used: /\bbanquetBeat\(/, from: '../../../beats/banquet' },
  { name: 'wordsBeat', used: /\bwordsBeat\(/, from: '../../../beats/words' },
  { name: 'DAN_POSES', used: /\bDAN_POSES\b/, from: '../../../figures' },
  { name: 'ACTORS as A', used: /\bA\./, from: '../actors' },
  { name: 'BOY', used: /\bBOY\b/, from: '../actors' },
  { name: 'QIGUAN', used: /\bQIGUAN\b/, from: '../actors' },
  { name: 'QINGUAN', used: /\bQINGUAN\b/, from: '../actors' },
];

const q = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
const clean = (t = '') => t.replace(/[▉□]/g, '').replace(/\*([^*]+)\*/g, '$1').replace(/\s+/g, ' ').trim();
/** Wraps text for a JSDoc block: `width` characters per line, continuation lines indented. */
const wrap = (text: string, width: number) => {
  const out: string[] = []; let line = '';
  for (const token of text.replace(/\*\//g, '* /').split(/(?<=\s)|(?=[㐀-鿿])/u)) {
    if ((line + token).length > width && line.trim()) { out.push(line.trimEnd()); line = ''; }
    line += token;
  }
  out.push(line.trimEnd());
  return out.join('\n *   ');
};

/** The chapter's paragraphs in Chinese and English. */
async function chapterText(chapter: number) {
  const load = async (file: string, prefix: string): Promise<string[]> => {
    if (!existsSync(file)) return [];
    const value = (await import(pathToFileURL(file).href))[`${prefix}${chapter}`];
    return Array.isArray(value) ? value : value?.[chapter] ?? Object.values(value ?? {})[0] ?? [];
  };
  return {
    zh: await load(join(root, `src/chapterTranslations/chinese/chapterChinese${chapter}.ts`), 'chapterChinese'),
    en: await load(join(root, `src/chapterTranslations/chapterTranslations${chapter}.ts`), 'chapterTranslations'),
  };
}

export async function writeCinemas(chapter: number, specs: Spec[], only: number[] = []) {
  const { zh, en } = await chapterText(chapter);
  const pad = (n: number) => String(n).padStart(2, '0');
  const written: number[] = [];
  for (const spec of specs) {
    if (only.length && !only.includes(spec.n)) continue;
    const dir = join(root, `src/components/cinema/authored/ch${pad(chapter)}/p${pad(spec.n)}`);
    mkdirSync(dir, { recursive: true });
    const story = `import { defineStory } from '../../define';

/**
 * Chapter ${chapter}, paragraph ${spec.n}. Generated by \`npm run build-cinemas -- ${chapter} ${spec.n}\` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：${wrap(clean(zh[spec.n - 1]), 44)}
 *
 * Translation: ${wrap(clean(en[spec.n - 1]) || '(none yet)', 92)}
 *
 * Staging: ${spec.staging}.
 */
export default defineStory({
  title: { en: ${q(spec.title[0])}, zh: ${q(spec.title[1])} },
  description: {
    en: ${q(spec.description[0])},
    zh: ${q(spec.description[1])},
  },
  shots: [
${spec.shots.map(([s, e, te, tz, quote, ce, cz]) => `    {
      start: ${s}, end: ${e},
      title: { en: ${q(te)}, zh: ${q(tz)} },
      quote: ${q(quote)},
      caption: { en: ${q(ce)}, zh: ${q(cz)} },
    },`).join('\n')}
  ],
  subtitles: [
${spec.subtitles.map(([s, e, z, e2]) => `    { start: ${s}, end: ${e}, zh: ${q(z)}, en: ${q(e2)} },`).join('\n')}
  ],
});
`;
    const code = spec.beats.join('\n');
    const byModule = new Map<string, string[]>();
    for (const { name, used, from } of IMPORTS) if (used.test(code)) byModule.set(from, [...(byModule.get(from) ?? []), name]);
    const imports = [...byModule].map(([from, names]) => `import { ${names.join(', ')} } from '${from}';`).join('\n');
    const scene = `import { beatScene } from '../../../beats/engine';
${imports}

/** Chapter ${chapter}, paragraph ${spec.n}: ${spec.staging}. */
export default beatScene(${chapter * 1000 + spec.n}, [
${spec.beats.map(b => `  ${b},`).join('\n')}
]);
`;
    writeFileSync(join(dir, 'story.ts'), story);
    writeFileSync(join(dir, 'scene.ts'), scene);
    written.push(spec.n);
  }
  return written;
}
