import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 33. Generated by `npm run build-cinemas -- 2 33` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：仲清、王恂送了他弟兄出门进来，大家换了衣裳，在书房内晚饭对酌闲谈。王恂道：「我们这两位舅
 *   兄，真可入得《无双谱》的。」仲清道：「为什么同胞兄妹丝毫不像？假使尊夫人生了这样嘴脸，那
 *   就够你受罪了。」王恂笑道：「幸亏内人是如今这位岳母生的。你不晓得我们还有个大姨子在家，是
 *   个天老，一头的白发，那是不能嫁人的，差不多有三十岁了。」仲清问道：「听得令岳母泼妒异常，
 *   未知果否？」王恂道：
 *
 * Translation: Zhongqing and Wang Xun saw the two brothers to the door before returning inside. They
 *   changed their garments and settled in the study for an evening meal, sharing wine and
 *   casual conversation. Wang Xun mused, "These two brothers-in-law of ours are truly worthy of
 *   inclusion in the Peerless Register." Zhongqing remarked, "Why do the brothers and your wife
 *   share so little resemblance? Had your esteemed lady possessed such a visage, you would
 *   surely be suffering a bitter fate." Wang Xun laughed, "Fortunately, my wife was borne by my
 *   current mother-in-law. You are unaware that we have an older sister-in-law still residing
 *   at home. She is an albino, with a head of white hair, and quite unmarriageable; she is
 *   nearly thirty by now." Zhongqing inquired, "I have heard rumors that your mother-in-law is
 *   exceptionally fierce and jealous. Is this true?" Wang Xun confirmed:
 *
 * Staging: supper in the study, the albino sister-in-law, and the jealous mother-in-law.
 */
export default defineStory({
  title: { en: 'Fit for the Peerless Register', zh: '可入得《无双谱》' },
  description: {
    en: 'Over supper Wang Xun jokes that his brothers-in-law belong in the Peerless Register, and tells of an albino sister-in-law and a fiercely jealous mother-in-law.',
    zh: '晚饭时王恂说两位舅兄可入《无双谱》，又说家里有个天老大姨子，岳母泼妒异常。',
  },
  shots: [
    {
      start: 0, end: 12,
      title: { en: 'The Peerless Register', zh: '无双谱' },
      quote: '我们这两位舅兄，真可入得《无双谱》的。',
      caption: { en: 'Over wine, Wang Xun jokes that his two brothers-in-law are fit for the Peerless Register.', zh: '王恂笑道：这两位舅兄，真可入得《无双谱》。' },
    },
    {
      start: 12, end: 24,
      title: { en: 'An albino sister-in-law', zh: '一头的白发' },
      quote: '我们还有个大姨子在家，是个天老，一头的白发，那是不能嫁人的',
      caption: { en: 'Luckily his wife is from a different mother; there is also an elder sister-in-law at home, an albino with white hair, nearly thirty and unmarried.', zh: '幸亏内人是现在的岳母生的；家里还有个天老大姨子，一头白发，不能嫁人。' },
    },
    {
      start: 24, end: 36,
      title: { en: 'Fiercely jealous', zh: '泼妒异常' },
      quote: '听得令岳母泼妒异常，未知果否？',
      caption: { en: 'Is it true his mother-in-law is fiercely jealous? Zhongqing asks.', zh: '仲清问：听得令岳母泼妒异常，果否？' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 5, zh: '仲清、王恂送了他弟兄出门进来，大家换了衣裳，在书房内晚饭对酌闲谈。', en: 'Having seen them off, they changed clothes and had supper and wine in the study.' },
    { start: 5, end: 11.6, zh: '王恂道：「我们这两位舅兄，真可入得《无双谱》的。」', en: 'Wang Xun: “My two brothers-in-law are truly worthy of the Peerless Register.”' },
    { start: 12.4, end: 17, zh: '仲清道：「为什么同胞兄妹丝毫不像？」王恂笑道：「幸亏内人是如今这位岳母生的。', en: '“Why is your wife nothing like them?” Wang Xun laughed: “Luckily she was born of my present mother-in-law.' },
    { start: 17, end: 23.6, zh: '我们还有个大姨子在家，是个天老，一头的白发，那是不能嫁人的，差不多有三十岁了。」', en: 'There is an elder sister-in-law at home, an albino with white hair, unmarriageable, nearly thirty.”' },
    { start: 24.4, end: 35.6, zh: '仲清问道：「听得令岳母泼妒异常，未知果否？」王恂道：', en: 'Zhongqing asked, “I hear your mother-in-law is fiercely jealous—is it true?” Wang Xun said:' },
  ],
});
