import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 19. Generated by `npm run build-cinemas -- 2 19` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：文辉让聘才坐下，自己就盘起腿来，仲清坐在靠窗凳上。聘才见这大模厮样的架子，心里筹划了一筹
 *   划，便站起来道：「小侄在诸位老伯荫庇之下，一切全仗栽培。家父曾吩咐过小侄，说大人的尊范，
 *   必要位至极品。趁如今拜识拜识，将来可以提拔寒畯。」说罢取出书子来双手呈上，文辉一手接着，
 *   看看信面就放下，哈哈大笑道：「你令尊怎么这样疏远我，写起大人安启来。」又叹口气道：「可惜
 *   了令尊这一手好八股，那一年与我同案进学，我中那一科，你令尊本要中解元的。已经定了元，主考
 *   忽看见那本卷面上，画了一把刀，一枝笔，笔底下一团墨浸，直印到卷底。揭开看时，像一个人头，
 *   越揭下去越清楚，连眉目都有了。因此，知他损了阴骘，便换了人。也不晓得令尊何意，这一管好
 *   笔，不做文章去做状子，至今还是个穷秀才，也没见他发过财。每逢学台出京，我总重托的，不然，
 *   访闻了这只刀笔，还了得。」说得聘才倨促不安。文辉又手理长髯说道：「前年魏府尊选了江宁，出
 *   京时问我要个朋友，我就荐了令尊，他一口答应说要请的。后来不见你令尊的信来，我甚疑心。及魏
 *   府尊的禀帖来说，上司荐的人多，不能不请。
 *
 * Translation: Wenhui invited Pincai to take a seat, settling himself comfortably with legs crossed, while
 *   Zhongqing occupied a stool by the window. Observing Wenhui's grandiose, self-important
 *   posture, Pincai carefully calculated his approach before rising to his feet and addressing
 *   him, "I am entirely dependent upon the patronage and shelter of esteemed elders like
 *   yourself. My father once confided to me that with your distinguished countenance, you were
 *   destined to attain the highest pinnacles of office. Taking this opportunity to pay my
 *   respects, I harbor hopes that you might deign to uplift this humble scholar in the future."
 *   With that, he drew forth the letter and presented it respectfully with both hands. Wenhui
 *   accepted it with one hand, glanced at the envelope, and tossed it aside, erupting into a
 *   booming laugh. "Why does your esteemed father treat me with such distant formality,
 *   addressing me as 'Your Excellency'?" He let out a sigh, "It is a pity about your father's
 *   masterful eight-legged essays. The year we passed the district examinations together, the
 *   very session in which I succeeded, your father was slated to place first. The decision was
 *   final, but the chief examiner suddenly noticed a drawing on the cover of his exam booklet,
 *   a blade and a brush. Beneath the brush was a pool of ink that had soaked straight through
 *   to the back page. Peeling the pages apart, the stain resembled a human head, and with each
 *   subsequent page, the image grew clearer, until even the facial features were distinctly
 *   visible. Interpreting this as a sign that he had severely damaged his hidden virtues, the
 *   examiner replaced him. Heaven only knows what your father was thinking, forsaking
 *   literature to draft legal petitions with that fine brush of his. To this day, he remains an
 *   impoverished scholar, devoid of any great fortune. Whenever an education commissioner
 *   departs the capital, I make a point to put in a strong word on his behalf, otherwise, once
 *   word of his litigious activities spread, the consequences would be dire." Pincai shifted
 *   uncomfortably, mortified by the recounting. Wenhui stroked his long beard and continued,
 *   "The year before last, when Prefect Wei was appointed to Jiangning, he asked me to
 *   recommend a reliable assistant before he left the capital. I put forward your father's
 *   name, and he readily agreed to hire him. Yet, when I subsequently received no word from
 *   your father, I grew suspicious. Only later did Prefect Wei send a dispatch explaining that
 *   his superiors had forced so many recommendations upon him that he was compelled to hire
 *   them all.
 *
 * Staging: Pincai presenting the letter, Wenhui laughing it off, the haunted exam paper, and Pincai squirming.
 */
export default defineStory({
  title: { en: 'A blade and a brush', zh: '一把刀，一枝笔' },
  description: {
    en: 'Wenhui, cross-legged, tosses Pincai’s letter aside and tells how Pincai’s father lost first place: a blade, a brush, and an ink blot shaped like a head on his exam paper.',
    zh: '文辉盘腿而坐，接信即放下，讲聘才之父当年卷面上画了一把刀、一枝笔、一团墨浸成人头，因此失了解元。',
  },
  shots: [
    {
      start: 0, end: 9,
      title: { en: 'The letter', zh: '双手呈上' },
      quote: '说罢取出书子来双手呈上',
      caption: { en: 'Wenhui sits cross-legged; Pincai flatters him and presents the letter with both hands.', zh: '文辉盘起腿来；聘才恭维一番，双手呈上书信。' },
    },
    {
      start: 9, end: 18,
      title: { en: '“Your Excellency”', zh: '大人安启' },
      quote: '文辉一手接着，看看信面就放下，哈哈大笑',
      caption: { en: 'Wenhui takes it in one hand, glances at the envelope, tosses it down and laughs.', zh: '文辉一手接过，看看信面就放下，哈哈大笑。' },
    },
    {
      start: 18, end: 28,
      title: { en: 'The ink blot', zh: '一团墨浸' },
      quote: '卷面上，画了一把刀，一枝笔，笔底下一团墨浸……连眉目都有了。',
      caption: { en: 'Pincai’s father was set to place first, until the examiner saw a blade, a brush, and an ink blot soaking into the shape of a head.', zh: '其父本要中解元，主考见卷面上一把刀、一枝笔，一团墨浸成人头，便换了人。' },
    },
    {
      start: 28, end: 36,
      title: { en: 'Squirming', zh: '侷促不安' },
      quote: '说得聘才侷促不安。文辉又手理长髯',
      caption: { en: 'Pincai squirms while Wenhui strokes his beard and talks on.', zh: '聘才侷促不安；文辉手理长髯，又说下去。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 4.6, zh: '文辉让聘才坐下，自己就盘起腿来，仲清坐在靠窗凳上。', en: 'Wenhui settled himself cross-legged; Zhongqing sat on a stool by the window.' },
    { start: 4.6, end: 8.6, zh: '聘才便站起来道：「大人的尊范，必要位至极品。」说罢取出书子来双手呈上。', en: 'Pincai rose: “Your Excellency is destined for the highest office,” and presented the letter with both hands.' },
    { start: 9.4, end: 13.6, zh: '文辉一手接着，看看信面就放下，哈哈大笑道：', en: 'Wenhui took it in one hand, glanced at the envelope, tossed it aside and laughed:' },
    { start: 13.6, end: 17.6, zh: '「你令尊怎么这样疏远我，写起大人安启来。」', en: '“Why does your father treat me so formally—‘To His Excellency’?”' },
    { start: 18.4, end: 23, zh: '「那一年与我同案进学，你令尊本要中解元的。主考忽看见那本卷面上，画了一把刀，一枝笔，', en: '“The year we sat together, your father was to place first—until the examiner saw a blade and a brush on his paper,' },
    { start: 23, end: 27.6, zh: '笔底下一团墨浸，揭开看时，像一个人头，连眉目都有了。」', en: 'and an ink blot beneath the brush that, page by page, became a human head, eyes and all.”' },
    { start: 28.4, end: 32, zh: '「这一管好笔，不做文章去做状子，至今还是个穷秀才。」', en: '“He used that fine brush for lawsuits instead of essays, and is still a poor scholar.”' },
    { start: 32, end: 35.6, zh: '说得聘才侷促不安。文辉又手理长髯说道：', en: 'Pincai squirmed. Wenhui stroked his long beard and went on:' },
  ],
});
