import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 7. Generated by `npm run build-cinemas -- 2 7` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：又吩咐同了他们的来人，去搬取行李，才到上房去了。
 *
 * Translation: He further directed their attendant to retrieve their luggage before retiring to the main
 *   residence.
 *
 * Staging: servants carrying the luggage in, and Shixie retiring.
 */
export default defineStory({
  title: { en: 'The luggage', zh: '搬取行李' },
  description: {
    en: 'Shixie has the visitors’ luggage fetched, then retires to the main house.',
    zh: '士燮吩咐搬取行李，才到上房去了。',
  },
  shots: [
    {
      start: 0, end: 18,
      title: { en: 'Fetching the luggage', zh: '搬取行李' },
      quote: '又吩咐同了他们的来人，去搬取行李',
      caption: { en: 'Servants go with the visitors’ man to bring in the luggage.', zh: '吩咐同他们的来人去搬取行李。' },
    },
    {
      start: 18, end: 36,
      title: { en: 'To the main house', zh: '到上房去了' },
      quote: '才到上房去了。',
      caption: { en: 'Then Shixie goes to the main residence.', zh: '士燮才到上房去了。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 17.6, zh: '又吩咐同了他们的来人，去搬取行李，', en: 'He further directed their attendant to retrieve their luggage,' },
    { start: 18.4, end: 35.6, zh: '才到上房去了。', en: 'before retiring to the main residence.' },
  ],
});
