/** Chinese paragraphs 2–16 (chapter 25) — full translations, one per \n\n block */
export const mid = [
  `The garden ran some three or four li around its circuit. The small hills within were piled from Lake Tai rock; the long ridge of great hills sat on packed-earth footings crowned with towering peaks, dressed in flowers and trees and framed by pavilions — indistinguishable from living mountains. Inside the grottoes water was secretly pumped with chain-pumps and sprayed upward to form cascading waterfalls.`,

  `The pool belt linked to an outer river, winding and circling, broad or narrow as terrain allowed. Within the grounds stood also archery ranges, ball courts, fishing lodges, rice paddies, wineshops, tea arbors — all run by gardeners, uniformly neat and clean — to occupy those with duties in the garden and keep them from slipping outside to neglect work: such was Duxiang's arrangement. Formal courtyards and halls numbered twenty-four in all — linked yet broken apart, never repetitive — if one toured conscientiously, a whole day might cover only three or four spots; eight or nine days were needed to finish the whole.`,

  `Even the garden's lord might not recall every turn at once. At the center rose a great hall named Han Wan Lou — "embracing the myriad things and resolving them into light" — the garden's chief building, windows on every face, spirit vast and open. Outside stretched a stone terrace with rails on three sides and seven tiers of steps at center. Before it ran a belt of parasol trees screening like a folding screen; beyond rose tier on tier of towers and galleries. Along the eastern willows lay the sheet of water connecting to the Chanting-Autumn Waterside Pavilion — lotus now in countless bloom, white and red, emerald canopies and feathered parasols — a slight breeze and fragrance filled every courtyard.`,

  `At that moment Ziyun welcomed Wenze; they seated themselves below Han Wan Lou. Ziyun asked after Baoding; Wenze told his news, then asked: "Besides Young Master Hua, what notable guests come today?" Ziyun said: "Several elderly gentlemen in gauze caps would have nothing to say to Young Master Hua — they care only rank and stipend — better not invite — only Zhang the Second might join — he sits outside refined circles yet pours wine well — otherwise we five alone."`,

  `Wenze asked where Cixian was. Ziyun said: "Jingyi rehearses today's new plays — staging and modes still grate — he corrects each passage himself — he comes soon." While they spoke Zhang Zhongyu arrived; Ziyun rose to greet him; Wenze welcomed him.`,

  `Wenze said to Ziyun: "Zhang the Second is thoroughly capable — sharp in every line — abroad he will shine as an official — fame and fortune await." Ziyun laughed: "Fame and fortune yes — superiors delighted — ordinary folk may fare worse." Wenze guffawed — Zhongyu overheard and fired back pleasantries — all three laughed.`,

  `After a pause footsteps rustled everywhere — one figure in sixth-rank robes rounded the artificial hill; next four retainers in caps and feathers bore a sedan-chair — Young Master Hua inside in lustrous silk and stitched gold — some twenty followers trailing — Ziyun led the party forward to greet him.`,

  `It emerged that Lord Hua and Duke Xu had been deepest friends twenty years and served two campaigns together — friendship moss-thick as hill herbs, oath-bound as metal and stone. Xu Ziyun and Young Master Hua had sworn brotherhood and revived the tie between houses. Ziyun was five years elder; Young Master honored him as elder brother — courteous and yielding. At once Ziyun yielded Young Master Hua the seat of honor while servants poured tea. Young Master Hua said: "Days ago I meant to pay respects — imperial escort duties stacked up and heat warned against disturbing you. Today cooler — we may talk half the day happily — pity one city wall divides us — we cannot carry lamps all night — hard to satisfy the heart." Ziyun said: "Repeatedly you honor us — glory reaches grove and spring. I idle alone, lazy as habit — long wished to invite you yet feared official duty left no leisure — and the wall between blunts cheer. Tonight I hoped to detain you till dawn — will you lodge one night in the humble hall?" Young Master Hua smiled: "Your famous garden fills my dreams — I long for a full roam. Later I shall trouble your studio — not one night — I want ten days like Lord Pingyuan before this petty temper clears — today I must return — tomorrow perhaps an imperial commission waits — vulgar dust blocks refined pleasure — summer swells and the bright moon is not yet round — wait till mid-autumn for our all-night revel?" Ziyun laughed: "Sound — moonless nights dull drinking — no need for mid-autumn — seventh month will do — shall we fix late seventh month?" Young Master Hua agreed: "Cooler autumn lifts the heart — pity my grounds are cramped — less than half yours — built by no master hand — little hill-and-stream surprise — summer stays sultry — only autumn and winter suit short rests."`,

  `"If elder brother does not disdain plain fare, I shall send a carriage of welcome." Ziyun said: "Excellent — whenever I cannot leave the city I shall trouble you. Your Western Garden is superbly laid — could it join the Eastern Garden it would be finer." Young Master Hua said: "So many main halls stand between — cannot link — and the east quarter lodges many guests — mixed folk — nowhere to ornament." While they spoke drums and pipes sounded behind; Ziyun urged Young Master Hua inward; past the vestibule they reached Chengyin Hall steps — three men inside advanced to the gallery to greet him — all old friends — Young Master Hua exchanged bows with each.`,

  `He bowed to Cixian: "Master Jingyi took trouble to arrange these plays — how shall we watchers repay? Today we offer a few extra cups." Cixian laughed loudly: "Rustic tunes may wound refined ears — if you nod once I shall gladly drain a full cup for everyone." All agreed it was good — wine was ready — servants bore jars forward — Ziyun poured and set seats — Young Master Hua held chief east seat with Zhongyu attending; Wenze chief west with Cixian attending; Ziyun played host beside Young Master Hua's table.`,

  `Young Master Hua said: "No further guests — only our five. Why not one table? Distance muffles talk — once opera rises speech stops." Wenze said: "Then combine." Ziyun said: "Good — crowded — swap to a round table — seat by seniority — avoid pushing rank." They agreed; servants fitted a round top and merged the banquet.`,

  `The opening plays were "Li Ling Returns to Han" and "The Bright Consort Enters the Pass." Next came "The Talented Scholar Receives the Edict" — principal male role — imperial wine and golden flowers bestowed, farewell money along the route — bearing proud and free, tones bold and grave — conjuring Li Bai's wandering soul entire. When singing ceased a figure emerged — guests fancied Li Bai himself had stepped down.`,

  `The second bill was "The Yang Consort Enters Shu." Yang Guozhong died first; Chen Yuanli instructed emperor and minister on mutual duty; the six armies thundered approval. The Bright Emperor halted at Omei inn with the consort on the tower; he blew the jade flute while she sang "Qingping"; peach-sleeved ladies danced "Returning Wind"; Li Guinian backed on eight-tone instruments — grandeur beyond telling.`,

  `Those two performances ran long. Ziyun, seeing Young Master Hua's spirits soar, halted the show and summoned the ten performers still in full face-paint — each stepping forward with a huge cup. Young Master Hua refused nothing — smiled and drank — demanded others match — their capacities failed — they shrank to smaller cups — laughter rolled round after round.`,

  `Everyone stared — a tray blazing with gold ingots — lucky shapes, ruyi shapes, plum shapes, water-chestnut tips — each above one tael, perhaps a hundred pieces — portioned among the ten performers. After Shanzhi handed them out the ten kowtowed thanks; Ziyun hastened thanks as well.`,
];
