import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 20. Generated by `npm run build-cinemas -- 2 20` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：又说侯石翁又硬荐了两个亲戚。只好代为设法，或转荐别处。
 *
 * Translation: "He also mentioned that Hou Shiweng had ruthlessly imposed two of his own relatives on him.
 *   He had no choice but to offer alternative arrangements or recommend him elsewhere.
 *
 * Staging: Wenhui talking on from his couch.
 */
export default defineStory({
  title: { en: 'Two relatives forced on him', zh: '硬荐了两个亲戚' },
  description: {
    en: 'Wenhui recalls recommending Pincai’s father to Prefect Wei, whose superiors forced other men on him.',
    zh: '文辉说当年荐聘才之父给魏府尊，上司与侯石翁硬荐了人。',
  },
  shots: [
    {
      start: 0, end: 18,
      title: { en: 'Hou Shiweng’s relatives', zh: '侯石翁' },
      quote: '又说侯石翁又硬荐了两个亲戚。',
      caption: { en: 'Hou Shiweng had forced two of his own relatives on the Prefect.', zh: '侯石翁又硬荐了两个亲戚。' },
    },
    {
      start: 18, end: 36,
      title: { en: 'Recommend him elsewhere', zh: '转荐别处' },
      quote: '只好代为设法，或转荐别处。',
      caption: { en: 'So the Prefect could only find him some other post.', zh: '只好代为设法，或转荐别处。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 17.6, zh: '「又说侯石翁又硬荐了两个亲戚。', en: '“He also said Hou Shiweng had forced two relatives on him.' },
    { start: 18.4, end: 35.6, zh: '只好代为设法，或转荐别处。', en: 'He could only make other arrangements, or recommend him elsewhere.' },
  ],
});
