import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 42. Generated by `npm run build-cinemas -- 2 42` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：文辉赏了桂保二十两银子，桂保谢了，走到书房来找王恂、仲清，谈了一会，说道：「我们班里新来
 *   了两个：一个叫琴官，一个叫琪官，生得色艺惧佳，只怕史竹君的《花选》又要翻刻了。」又坐了一
 *   会也自回去。不知后事如何，且听下回分解。
 *
 * Translation: Wenhui rewarded Guibao with twenty taels of silver. After expressing his gratitude, Guibao
 *   made his way to the study in search of Wang Xun and Zhongqing. They conversed for a time
 *   before Guibao revealed, "Two new performers have recently joined our troupe, one named
 *   Qinguan, the other Qiguan. Both are exquisitely beautiful and remarkably talented. I fear
 *   Shi Zhujun's Selection of Flowers will require yet another printing." He lingered a while
 *   longer before finally departing for home. As for what unfolded next, you must listen to the
 *   following chapter for the explanation.
 *
 * Staging: the reward, Guibao’s news in the study, and the two new actors in moonlight.
 */
export default defineStory({
  title: { en: 'Qinguan and Qiguan', zh: '琴官、琪官' },
  description: {
    en: 'Wenhui rewards Guibao with twenty taels; in the study Guibao tells Wang Xun and Zhongqing that two new boys have joined the troupe—Qinguan and Qiguan.',
    zh: '文辉赏桂保二十两；桂保到书房告诉王恂、仲清，班里新来了琴官、琪官。',
  },
  shots: [
    {
      start: 0, end: 12,
      title: { en: 'Twenty taels', zh: '二十两银子' },
      quote: '文辉赏了桂保二十两银子，桂保谢了',
      caption: { en: 'Wenhui rewards Guibao with twenty taels of silver.', zh: '文辉赏了桂保二十两银子。' },
    },
    {
      start: 12, end: 24,
      title: { en: 'Two new boys', zh: '新来了两个' },
      quote: '我们班里新来了两个：一个叫琴官，一个叫琪官',
      caption: { en: 'In the study, Guibao tells Wang Xun and Zhongqing: two new boys have joined the troupe.', zh: '桂保到书房说：我们班里新来了两个。' },
    },
    {
      start: 24, end: 36,
      title: { en: 'The Flower Manual reprinted', zh: '《花选》又要翻刻了' },
      quote: '生得色艺俱佳，只怕史竹君的《花选》又要翻刻了。',
      caption: { en: 'Qinguan and Qiguan, fine in looks and art: Nanxiang’s Flower Manual will need a new printing.', zh: '琴官、琪官色艺俱佳，只怕《花选》又要翻刻了。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 11.6, zh: '文辉赏了桂保二十两银子，桂保谢了，走到书房来找王恂、仲清，', en: 'Wenhui rewarded Guibao with twenty taels; he thanked him and went to find Wang Xun and Zhongqing in the study.' },
    { start: 12.4, end: 18, zh: '谈了一会，说道：「我们班里新来了两个：', en: 'After a while he said, “Two new ones have joined our troupe:' },
    { start: 18, end: 23.6, zh: '一个叫琴官，一个叫琪官，', en: 'one called Qinguan, the other Qiguan—' },
    { start: 24.4, end: 30, zh: '生得色艺俱佳，只怕史竹君的《花选》又要翻刻了。」', en: 'both beautiful and gifted. I fear Shi Zhujun’s Flower Manual will need a new printing.”' },
    { start: 30, end: 35.6, zh: '不知后事如何，且听下回分解。', en: 'To know what happens next, listen to the next chapter.' },
  ],
});
