import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 35. Generated by `npm run build-cinemas -- 2 35` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：却说孙亮功同了桂保进来，见过主人。不多一刻，客已全到，便安起席来。这些客都是文辉同年，论
 *   年纪孙亮功最长，因系姻亲，便让兵部员外杨方猷坐了首席。对面是光禄寺少卿周锡爵。监察御史陆
 *   宗沅坐了第三席，孙亮功坐了第四席，文辉坐了主席。桂保斟了一巡酒，杨方猷命他入席，对着王文
 *   辉坐了。文辉问他哥哥兰保为什么不来，桂保道：「今日本都在怡园逛了一天，徐老爷知道这里请
 *   客，才打发我来的。兰保、宝珠、蕙芳、漱芳、玉林都还没有散，只怕总要到四五更天才散呢。」文
 *   辉道：「这徐度香也算人间第一个快乐人了。」陆宗沅道：「听说他这个怡园共花了五十多万银子才
 *   造成。」杨方猷道：「本来地方也大，也造得过于精致。」文辉道：「我前月逛了一天，还没有逛到
 *   一半。」桂保说：「我们今日逛了梅崦与东风昨夜楼两处，这两处就有正百间屋子。实在造得也奇极
 *   了，几几乎进去了出不来。」孙亮功道：「你应该打个地洞，藏在里头。」说得大家都笑。桂保
 *   道：「你会骂人。」便斟了一大杯酒来罚他，亮功始不肯喝，桂保要灌，便也喝了。
 *
 * Translation: Meanwhile, Sun Lianggong entered with Guibao and formally greeted the host. Within a short
 *   time, all the guests had arrived, and they arranged themselves for the banquet. These
 *   guests were all Wang Wenhui's fellow graduates. As Sun Lianggong was the eldest and a
 *   relative by marriage, they offered the seat of honor to Yang Fangyou, a Vice Director in
 *   the Ministry of War. Seated opposite him was Zhou Xijue, Vice Minister of the Court of
 *   Imperial Entertainments. Investigating Censor Lu Zongyuan took the third seat, Sun
 *   Lianggong the fourth, while Wenhui presided as the host. Guibao poured a round of wine,
 *   after which Yang Fangyou invited him to join the table, seating him opposite Wang Wenhui.
 *   Wenhui inquired why his brother Lanbao had not attended. Guibao explained, "Today we spent
 *   the entire day touring the Garden of Contentment. Master Xu only dispatched me here upon
 *   learning you were hosting a banquet. Lanbao, Baozhu, Huifang, Shufang, and Yulin have not
 *   yet dispersed; I suspect they will linger until the fourth or fifth watch." Wenhui
 *   remarked, "This Xu Duxiang is truly the most carefree and joyous man in the mortal realm."
 *   Lu Zongyuan added, "I have heard that constructing his Garden of Contentment cost over half
 *   a million taels of silver." Yang Fangyou noted, "The grounds are vast, and the
 *   craftsmanship is exquisitely refined." Wenhui shared, "I spent a full day touring it last
 *   month and still did not see half of it." Guibao chimed in, "Today we explored the Plum
 *   Knoll and the East Wind Last Night Pavilion. Those two sections alone boast a full hundred
 *   rooms. The layout is astonishingly complex, you step inside and can scarcely find your way
 *   out." Sun Lianggong quipped, "You ought to dig a tunnel and secrete yourself within." The
 *   table erupted in laughter. Guibao retorted, "You are too fond of insulting people," and
 *   promptly poured a large cup of wine as a penalty. Lianggong initially refused, but Guibao
 *   threatened to force it down his throat, leaving him no choice but to drink.
 *
 * Staging: arrival, the six seated, talk of the Garden of Contentment, and Guibao’s penalty cup.
 */
export default defineStory({
  title: { en: 'The banquet', zh: '安起席来' },
  description: {
    en: 'The guests take their seats by rank; Guibao pours and joins the table, tells of a day in Xu Duxiang’s vast Garden of Contentment, and makes Lianggong drink a penalty.',
    zh: '客到齐按序入席，桂保斟酒入座，讲怡园之大；亮功取笑，被桂保罚酒。',
  },
  shots: [
    {
      start: 0, end: 9,
      title: { en: 'Lianggong and Guibao enter', zh: '见过主人' },
      quote: '却说孙亮功同了桂保进来，见过主人。',
      caption: { en: 'Lianggong and Guibao greet their host.', zh: '孙亮功同桂保进来，见过主人。' },
    },
    {
      start: 9, end: 18,
      title: { en: 'Seated by rank', zh: '安起席来' },
      quote: '便让兵部员外杨方猷坐了首席……文辉坐了主席。',
      caption: { en: 'Yang takes the seat of honour, then Zhou, Lu and Sun; Wenhui is host. Guibao pours, then sits facing Wenhui.', zh: '杨方猷首席，周锡爵、陆宗沅、孙亮功依次，文辉主席；桂保斟酒入席。' },
    },
    {
      start: 18, end: 27,
      title: { en: 'The Garden of Contentment', zh: '怡园' },
      quote: '今日本都在怡园逛了一天……几几乎进去了出不来。',
      caption: { en: 'Guibao has spent the day in Xu Duxiang’s garden—half a million taels, a hundred rooms, a maze.', zh: '桂保在徐度香的怡园逛了一天：花了五十多万银子，进去了几乎出不来。' },
    },
    {
      start: 27, end: 36,
      title: { en: 'A penalty cup', zh: '罚他' },
      quote: '你应该打个地洞，藏在里头。……便斟了一大杯酒来罚他',
      caption: { en: 'Lianggong jokes that Guibao should dig a burrow and hide in it; Guibao makes him drink a big penalty cup.', zh: '亮功取笑桂保该打个地洞藏在里头；桂保斟一大杯罚他，灌他喝了。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 4.4, zh: '却说孙亮功同了桂保进来，见过主人。不多一刻，客已全到，便安起席来。', en: 'Sun Lianggong came in with Guibao and greeted the host; soon all the guests had arrived.' },
    { start: 4.4, end: 8.6, zh: '这些客都是文辉同年。', en: 'They were all Wenhui’s fellow graduates.' },
    { start: 9.4, end: 13.6, zh: '便让兵部员外杨方猷坐了首席，对面是光禄寺少卿周锡爵，', en: 'Yang Fangyou of the Ministry of War took the seat of honor; opposite him, Zhou Xijue;' },
    { start: 13.6, end: 17.6, zh: '陆宗沅坐了第三席，孙亮功第四，文辉坐了主席。桂保斟了一巡酒，入席对着文辉坐了。', en: 'Lu Zongyuan third, Sun Lianggong fourth, Wenhui as host. Guibao poured a round and sat opposite Wenhui.' },
    { start: 18.4, end: 22.6, zh: '桂保道：「今日本都在怡园逛了一天，徐老爷知道这里请客，才打发我来的。」', en: 'Guibao: “We spent all day in the Garden of Contentment; Master Xu sent me when he heard of your banquet.”' },
    { start: 22.6, end: 26.6, zh: '陆宗沅道：「听说他这个怡园共花了五十多万银子才造成。」', en: 'Lu Zongyuan: “I hear that garden cost over half a million taels.”' },
    { start: 27.4, end: 31.6, zh: '孙亮功道：「你应该打个地洞，藏在里头。」说得大家都笑。', en: 'Sun Lianggong: “You ought to dig a burrow and hide in it.” Everyone laughed.' },
    { start: 31.6, end: 35.6, zh: '桂保道：「你会骂人。」便斟了一大杯酒来罚他，桂保要灌，便也喝了。', en: '“You love insulting people,” said Guibao, pouring a big penalty cup and forcing him to drink.' },
  ],
});
