import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 8. Generated by `npm run build-cinemas -- 2 8` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：这边子玉引李、魏二人到了书房，性全已知道他儿子来了，等他叩见过了，然后与魏聘才见礼，问了
 *   姓名，性全让他上坐，聘才只是不肯。子玉想了一想：「先生父子乍见，定然有些说话。」就引聘才
 *   到对面船房内坐下，云儿与俊儿送了茶。聘才笑道、「世兄可还认得小弟么？」子玉道：「面善的
 *   很，实在想不起了。」聘才笑道：「从来说贵人多忘事，是不差的。那一年，世兄同着老伯母进京，
 *   小弟送到船上。世兄双手拉住了腰带，定要叫小弟同伴进京，老伯母好容易哄编，方才放手，难道竟
 *   不记得了？」子玉笑道：「题起来却也有些记得。那时弟只得五岁，似乎仁兄名字有个珍字。」聘才
 *   道：「正是。我原说像吾兄这样天聪天明的人，既蒙见爱，定是忘不了的。」子玉问道：「仁兄同李
 *   世兄来，还是水路来的，还是起旱来的？」聘才道：「虽是坐船，还算水陆并行。说也话长，既在这
 *   里叨扰，容小弟慢慢的细讲。」正说着，见云儿走来请吃饭，遂一同到书房来。性全忙让聘才首坐，
 *   聘才如何肯僭，仍让先生坐了，次聘才，元茂与子玉坐在下面。席间性全问起一路来的光景，又谢聘
 *   才照应。聘才谦让未逞，又赞了元茂许多好处。性全也觉喜欢，道是儿子或者长进了些。那李元茂闷
 *   着头不敢言语。用完了晚饭，那时行李已取到，房间亦已打扫。
 *
 * Translation: In the study, Ziyu guided Li and Wei to meet Li Xingquan, who was already aware of his
 *   son's arrival. Once the son had offered his filial respects, introductions were made with
 *   Wei Pincai. Li Xingquan courteously offered Pincai the seat of honor, an offer Pincai
 *   repeatedly declined. Ziyu, sensing that father and son, newly reunited, would cherish a
 *   moment to converse in private, tactfully escorted Pincai to the boat-shaped annex across
 *   the courtyard, where Yuner and Junner soon served them tea. Pincai smiled warmly and asked,
 *   "Does my elder brother still recognize me?" Ziyu replied apologetically, "Your face is
 *   familiar, but I confess I cannot quite place you." Pincai laughed, "They say men of
 *   distinction have fleeting memories, and it seems to be true. The year your esteemed mother
 *   traveled to the capital and you accompanied her, I saw you off at the docks. You clung to
 *   my sash with both hands, insisting I join you as your companion. It took quite a bit of
 *   gentle coaxing from your mother to make you let go. Have you truly forgotten?" Ziyu smiled
 *   in realization, "Now that you mention it, a vague memory returns. I was but five at the
 *   time. If I recall correctly, your name contained the character 'zhen.'" Pincai nodded,
 *   "Exactly right. I knew that a man of your natural brilliance, having once shown such
 *   affection, could not entirely forget." Ziyu inquired, "Did you and Brother Li journey by
 *   water or by land?" Pincai answered, "Partly by boat, though it was more a combination of
 *   both. It is a lengthy tale. Since I will be imposing on your hospitality for a time, allow
 *   me to recount it to you gradually." Just then, Yuner arrived to summon them for dinner, and
 *   they returned to the study together. Li Xingquan eagerly offered Pincai the head seat.
 *   Pincai firmly refused, deferring to the teacher, and took a subordinate place, while
 *   Yuanmao and Ziyu sat below. Over the meal, Li Xingquan asked after their journey and
 *   expressed his gratitude to Pincai for looking after his son. Pincai responded with modest
 *   demurrers and offered effusive praise of Yuanmao. Li Xingquan was deeply gratified, hoping
 *   his son had perhaps matured. Throughout the meal, Li Yuanmao kept his head bowed, not
 *   daring to utter a single word. By the time they finished, their luggage had been delivered,
 *   and their rooms were fully prepared.
 *
 * Staging: the tutor and his son, tea in the boat-room, a remembered quayside, and dinner.
 */
export default defineStory({
  title: { en: '“Do you still know me?”', zh: '世兄可还认得小弟么' },
  description: {
    en: 'Yuanmao greets his father; over tea Pincai reminds Ziyu how, at five, he clung to Pincai’s sash at the dock; at dinner Pincai praises Yuanmao.',
    zh: '元茂拜见父亲；聘才茶叙中提起子玉五岁时在船边拉住他腰带；席间聘才夸赞元茂。',
  },
  shots: [
    {
      start: 0, end: 9,
      title: { en: 'Father and son', zh: '先生父子' },
      quote: '性全已知道他儿子来了，等他叩见过了',
      caption: { en: 'Yuanmao kowtows to his father, the tutor Li Xingquan; Pincai declines the seat of honor.', zh: '元茂叩见父亲李性全；聘才不肯上坐。' },
    },
    {
      start: 9, end: 19,
      title: { en: 'Tea in the boat-room', zh: '船房内坐下' },
      quote: '就引聘才到对面船房内坐下……「世兄可还认得小弟么？」',
      caption: { en: 'Ziyu takes Pincai to the boat-shaped annex for tea. “Do you still know me?”', zh: '子玉引聘才到船房吃茶。聘才：「世兄可还认得小弟么？」' },
    },
    {
      start: 19, end: 27,
      title: { en: 'Clinging to his sash', zh: '双手拉住了腰带' },
      quote: '世兄双手拉住了腰带，定要叫小弟同伴进京',
      caption: { en: 'At five, seeing Pincai off at the boat, Ziyu clung to his sash and would not let go.', zh: '子玉五岁时在船上双手拉住聘才腰带，定要他同伴进京。' },
    },
    {
      start: 27, end: 36,
      title: { en: 'Dinner in the study', zh: '同到书房吃饭' },
      quote: '席间性全问起一路来的光景……那李元茂闷着头不敢言语。',
      caption: { en: 'At dinner Pincai praises Yuanmao to his father, while Yuanmao keeps his head down and says nothing.', zh: '席间聘才夸赞元茂；元茂闷着头不敢言语。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 4.6, zh: '子玉引李、魏二人到了书房，性全已知道他儿子来了，等他叩见过了，', en: 'In the study, Li Xingquan received his son’s filial kowtow,' },
    { start: 4.6, end: 8.6, zh: '然后与魏聘才见礼，性全让他上坐，聘才只是不肯。', en: 'then greeted Wei Pincai and offered him the seat of honor, which Pincai declined.' },
    { start: 9.4, end: 14, zh: '子玉就引聘才到对面船房内坐下，云儿与俊儿送了茶。', en: 'Ziyu took Pincai to the boat-shaped annex, where Yun’er and Jun’er served tea.' },
    { start: 14, end: 18.6, zh: '聘才笑道：「世兄可还认得小弟么？」子玉道：「面善的很，实在想不起了。」', en: '“Do you still recognize me?” “Your face is familiar, but I cannot place you.”' },
    { start: 19.4, end: 23.4, zh: '「那一年，世兄同着老伯母进京，小弟送到船上。世兄双手拉住了腰带，', en: '“The year you came to the capital with your mother, I saw you off at the boat. You clung to my sash,' },
    { start: 23.4, end: 26.6, zh: '定要叫小弟同伴进京。」子玉笑道：「那时弟只得五岁。」', en: 'insisting I come along.” Ziyu smiled: “I was only five then.”' },
    { start: 27.4, end: 31.6, zh: '席间性全问起一路来的光景，聘才又赞了元茂许多好处。', en: 'Over dinner the tutor asked about the journey, and Pincai praised Yuanmao at length.' },
    { start: 31.6, end: 35.6, zh: '性全也觉喜欢。那李元茂闷着头不敢言语。', en: 'The tutor was gratified; Li Yuanmao kept his head bowed, not daring to speak.' },
  ],
});
