import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 1. Generated by `npm run build-cinemas -- 2 1` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：话说子玉在车里，一路想那所见的绝色美童。到了家，见门口一车三马，认得王通政的家人，知道通
 *   政在此。便进来到书房，见他父亲陪着王文辉在那里说话，上前见了，说道：「方才到舅舅处请
 *   安。」文辉笑容可掬的道：「我一早出来，还未到家。」子玉站在一旁，见文辉说：「开春同年团
 *   拜，已定了联锦班，在姑苏会馆唱戏。这回只怕人不多，现在放外任与出差的不少，大约不过三四桌
 *   人。」梅学士道：「袁海楼巡抚云南，苏列侯奉命山右。其余学差者有二人，司道出京者三人，余下
 *   不过此眼前数人，大约还不满四席了。」王文辉又到里头去见了颜夫人，彼此道了些家常闲话，即提
 *   起他次女琼华十六岁了，尚未字人，托士燮留心物色。士燮答应，随又说道：「择女婿也是一件难
 *   事，尽有外貌甚好，内里平常。也有小时聪明，大来变坏的。」颜夫人接口说道：「这总是各人的姻
 *   缘。非但拣女婿难，就是要替你外甥定一头亲事也是不容易的。文辉道：「要像外甥这样好的，那里
 *   去选呢？」正说着，只见一个仆妇，手里拿着两个红帖走进二门。士燮问道：「有谁来了？」仆妇将
 *   帖呈上说道：「门上说是家乡来的，现在二门外等回话。」士燮看时，一个全帖上写着：世愚侄魏聘
 *   才；一个写着：门下晚学生李元茂。
 *
 * Translation: As the story goes, Ziyu rode home in his carriage, his mind lingering the entire way upon
 *   the exquisitely beautiful youths he had glimpsed. Arriving at the gate, he noticed a
 *   carriage and three horses; recognizing the servants of Commissioner Wang of the Office of
 *   Transmission, he knew the Commissioner was within. Proceeding to the study, he found his
 *   father engaged in conversation with Wang Wenhui. Ziyu stepped forward to offer his
 *   greetings, saying, "I have just returned from paying respects to my uncle." Wenhui, his
 *   face wreathed in smiles, replied, "I departed early this morning and had not yet returned."
 *   Ziyu stood respectfully aside as Wenhui continued, "For the spring gathering to exchange
 *   New Year greetings, the Lianjin troupe has already been engaged to perform at the Suzhou
 *   Guild Hall. I fear attendance may be sparse this time, as quite a few have been appointed
 *   to provincial posts or dispatched on official duties, we will likely fill no more than
 *   three or four tables." Academician Mei observed, "Provincial Governor Yuan Hailou is in
 *   Yunnan, and Marquis Su has been ordered to Shanxi. Two others are serving as Education
 *   Commissioners, while three have departed the capital as Provincial Administration and
 *   Surveillance Commissioners. The remainder are merely the few of us present, hardly enough
 *   to occupy four tables." Wang Wenhui then went into the inner chambers to greet Lady Yan.
 *   After exchanging familial pleasantries, he mentioned that his second daughter, Qionghua,
 *   was now sixteen and yet to be betrothed, entrusting Shixie to seek out a suitable match.
 *   Shixie agreed, yet added a caveat, "Choosing a son-in-law is a daunting endeavor. There are
 *   those with handsome exteriors who prove unremarkable within, equally, some show early
 *   brilliance only to falter in adulthood." Lady Yan chimed in, "Such matters are ultimately
 *   governed by destiny. It is not merely finding a son-in-law that poses a challenge,
 *   arranging a fitting match for your own nephew is no simple task." Wenhui sighed, "Where
 *   indeed could one find someone as exceptional as my nephew?" As they conversed, a
 *   maidservant passed through the middle gate bearing two red calling cards. Shixie asked who
 *   had arrived. Presenting the cards, the maidservant replied, "The gatekeeper reports they
 *   are visitors from our home province, waiting outside the middle gate for a response."
 *   Shixie examined the cards, one read, "Your humble nephew of the next generation, Wei
 *   Pincai," while the other read, "Your devoted later student, Li Yuanmao."
 *
 * Staging: Ziyu’s cart at the gate, the fathers in the study, Wenhui with Lady Yan, and the two red cards.
 */
export default defineStory({
  title: { en: 'Two red calling cards', zh: '两个红帖' },
  description: {
    en: 'Ziyu comes home to find Wang Wenhui with his father, talking of the spring gathering and a match for Qionghua, when two visiting cards arrive from the south.',
    zh: '子玉回家，王文辉正与梅学士谈同年团拜、琼华亲事；忽有家乡来的两个红帖。',
  },
  shots: [
    {
      start: 0, end: 8,
      title: { en: 'A carriage and three horses', zh: '一车三马' },
      quote: '到了家，见门口一车三马，认得王通政的家人',
      caption: { en: 'Ziyu rides home still dreaming of the boy; at his gate stand Commissioner Wang’s carriage and horses.', zh: '子玉一路想那绝色美童；到家见门口一车三马，知道王通政在此。' },
    },
    {
      start: 8, end: 17,
      title: { en: 'The spring gathering', zh: '开春同年团拜' },
      quote: '开春同年团拜，已定了联锦班，在姑苏会馆唱戏。',
      caption: { en: 'Wenhui has booked the Lianjin troupe at the Suzhou Guild Hall for the spring gathering of their examination year.', zh: '文辉说开春同年团拜，已定了联锦班在姑苏会馆唱戏。' },
    },
    {
      start: 17, end: 27,
      title: { en: 'A match for Qionghua', zh: '琼华尚未字人' },
      quote: '即提起他次女琼华十六岁了，尚未字人，托士燮留心物色。',
      caption: { en: 'With Lady Yan, Wenhui asks Shixie to look for a husband for his daughter Qionghua, sixteen.', zh: '文辉托士燮为十六岁的琼华物色女婿。' },
    },
    {
      start: 27, end: 36,
      title: { en: 'Two red cards', zh: '两个红帖' },
      quote: '一个全帖上写着：世愚侄魏聘才；一个写着：门下晚学生李元茂。',
      caption: { en: 'A maid brings two red cards: “Your humble nephew Wei Pincai” and “Your devoted later student Li Yuanmao.”', zh: '仆妇呈上两个红帖：世愚侄魏聘才，门下晚学生李元茂。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 4, zh: '话说子玉在车里，一路想那所见的绝色美童。', en: 'Ziyu rode home, his mind lingering on the exquisite youths he had glimpsed.' },
    { start: 4, end: 7.6, zh: '到了家，见门口一车三马，认得王通政的家人。', en: 'At the gate stood a carriage and three horses: Commissioner Wang was within.' },
    { start: 8.4, end: 12.6, zh: '文辉道：「开春同年团拜，已定了联锦班，在姑苏会馆唱戏。', en: 'Wenhui said: “For the spring gathering, the Lianjin troupe is engaged at the Suzhou Guild Hall.' },
    { start: 12.6, end: 16.6, zh: '这回只怕人不多，大约不过三四桌人。」', en: 'I fear attendance will be sparse—no more than three or four tables.”' },
    { start: 17.4, end: 22, zh: '文辉又到里头见了颜夫人，提起他次女琼华十六岁了，尚未字人，', en: 'In the inner chambers he mentioned that his daughter Qionghua, sixteen, was not yet betrothed,' },
    { start: 22, end: 26.6, zh: '托士燮留心物色。士燮道：「择女婿也是一件难事。」', en: 'and asked Shixie to find a match. “Choosing a son-in-law is a daunting task,” said Shixie.' },
    { start: 27.4, end: 31, zh: '只见一个仆妇，手里拿着两个红帖走进二门。', en: 'A maidservant came through the middle gate bearing two red calling cards.' },
    { start: 31, end: 35.6, zh: '一个写着：世愚侄魏聘才；一个写着：门下晚学生李元茂。', en: 'One read “Your humble nephew, Wei Pincai”; the other, “Your devoted later student, Li Yuanmao.”' },
  ],
});
