import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 37. Generated by `npm run build-cinemas -- 2 37` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：文辉道：「不必累赘，我们六个人竟以六杯为率，不必增减，准他一杯化作几杯就是了。也没有闷雷
 *   霹雷，那个猜着，就依令而行，最为剪截。」桂保便问杨方猷道：「第一杯怎样喝？」杨方猷道：「
 *   一杯化作三杯，找人豁拳。」又问孙亮功：「第二三杯怎样喝？」亮功道：「两杯都装作小旦敬
 *   人。」周锡爵道：「我们这样的胡子，倒有些难装。」亮功道：「只要做作得好，便有胡子也不
 *   妨。」桂保又问陆宗沅道：「第四杯呢？」陆宗沅道：「把瓜子抓一把，数到谁就是谁。」桂保道：
 *
 * Translation: Wenhui declared, "Let us not overcomplicate matters. The six of us will strictly adhere to
 *   six cups each, without addition or subtraction. Whoever wins a cup may divide it into as
 *   many smaller portions as they wish. Furthermore, let us dispense with complex rules
 *   regarding sequential drinking, whoever guesses correctly simply executes the game's
 *   designated action. That is the most straightforward method." Guibao then turned to Yang
 *   Fangyou, "What is the rule for the first cup?" Yang Fangyou replied, "One cup becomes
 *   three, finger-guessing with your partner." He then asked Sun Lianggong, "What about the
 *   second and third cups?" Lianggong decreed, "Both cups entail impersonating a young female
 *   performer presenting wine." Zhou Xijue interjected, "With our prominent beards, that will
 *   prove somewhat challenging to act out." Lianggong reassured him, "So long as the
 *   performance is convincing, a beard poses no obstacle." Guibao then asked Lu Zongyuan, "And
 *   the fourth cup?" Lu Zongyuan instructed, "Grab a handful of melon seeds, count them out,
 *   and whoever the count lands on must drink." Guibao commented:
 *
 * Staging: Wenhui laying down the rules, the rules written out, and the bearded guests laughing at the dan rule.
 */
export default defineStory({
  title: { en: 'Six cups, six rules', zh: '六杯为率' },
  description: {
    en: 'Wenhui sets six cups; each guest names a rule: finger-guessing, impersonating a young dan, counting melon seeds, and the flying-flower verse.',
    zh: '文辉定六杯为率；众人各出一令：豁拳、装小旦敬人、抓瓜子、花字飞觞。',
  },
  shots: [
    {
      start: 0, end: 12,
      title: { en: 'Six cups', zh: '六杯为率' },
      quote: '我们六个人竟以六杯为率，不必增减',
      caption: { en: 'Six men, six cups: whoever guesses right performs that cup’s rule.', zh: '六个人六杯为率，猜着的依令而行。' },
    },
    {
      start: 12, end: 24,
      title: { en: 'The rules', zh: '一杯化作三杯' },
      quote: '一杯化作三杯，找人豁拳。……两杯都装作小旦敬人。',
      caption: { en: 'Yang: finger-guessing. Lianggong: impersonate a young dan presenting wine. Lu: melon seeds.', zh: '杨：豁拳；亮功：装作小旦敬人；陆：抓瓜子。' },
    },
    {
      start: 24, end: 36,
      title: { en: 'Beards and all', zh: '胡子' },
      quote: '我们这样的胡子，倒有些难装。……只要做作得好，便有胡子也不妨。',
      caption: { en: 'Zhou: with beards like ours, that’s hard to act. Lianggong: a good performance makes a beard no obstacle.', zh: '周：我们这样的胡子难装；亮功：做作得好，有胡子也不妨。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 6, zh: '文辉道：「我们六个人竟以六杯为率，不必增减，准他一杯化作几杯就是了。', en: 'Wenhui: “Six of us, six cups each; whoever wins a cup may split it as he likes.' },
    { start: 6, end: 11.6, zh: '那个猜着，就依令而行，最为剪截。」', en: 'Whoever guesses right carries out the rule. Simplest that way.”' },
    { start: 12.4, end: 16, zh: '杨方猷道：「一杯化作三杯，找人豁拳。」', en: 'Yang Fangyou: “One cup becomes three—finger-guessing with a partner.”' },
    { start: 16, end: 20, zh: '亮功道：「两杯都装作小旦敬人。」', en: 'Lianggong: “Two cups—both impersonating a young dan presenting wine.”' },
    { start: 20, end: 23.6, zh: '陆宗沅道：「把瓜子抓一把，数到谁就是谁。」', en: 'Lu Zongyuan: “Grab a handful of melon seeds; whoever the count lands on drinks.”' },
    { start: 24.4, end: 30, zh: '周锡爵道：「我们这样的胡子，倒有些难装。」', en: 'Zhou Xijue: “With beards like ours, that will be hard to act.”' },
    { start: 30, end: 35.6, zh: '亮功道：「只要做作得好，便有胡子也不妨。」', en: 'Lianggong: “So long as the performance is good, a beard is no obstacle.”' },
  ],
});
