import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 12. Generated by `npm run build-cinemas -- 2 12` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：就是王公大人，也与他们并起并坐。至于那中等官宦，倒还有些去巴结他的，像要借他的声气，在些
 *   阔老面前吹嘘吹嘘。叫他陪一天酒要给他几十两银了，那小旦谢也不谢一声，是有的么？」子玉笑
 *   道：「或者有之，但我不出门，所以也不大知道外面的事。」聘才道：「戏是总听过的，那些小旦到
 *   底生得怎样好呢？」子玉道：「我就没有见过好的。这京里的风气，只要是个小旦，那些人嘴里讲讲
 *   都是快活，因此相习成风，不可挽回。」聘才道：「我也是这么说，南京的戏子本来不好，小旦也有
 *   三四十岁了，从没有见过叫这些人陪酒。但如今现在出了两个小旦，竟是神仙落劫，与我一路同来，
 *   且在一个船里，直到了张家湾起旱。也是同一天到京的。」子玉笑道：「怎么叫做神仙落劫？」聘才
 *   道：「这神仙里头，只怕还要选一选呢。若是下八洞的神仙，恐还变不出这个模样，京里有个什么四
 *   大名班，请了一个教师到苏州买了十个孩予，都不过十四五岁，还有十二三岁的；用两个太平船，由
 *   水路进京。我从家乡起身时，先搭了个客货船，到了扬州，在一个店里，遇见了这位李世兄，说起来
 *   也是到这里来的，就结了伴同走。本来要起旱，因车价过贵，想起个便船从水路来，遂遇见了这两个
 *   戏子船在扬州。那个教师姓叶叫茂林．是苏州人。从前在过秦淮河卞家河房里，教过曲子，我认得
 *   他。承他好意，就叫我们搭他的船进京。在运河里粮船拥挤，就走了四个多月。见他们天天的学戏，
 *   倒也听会了许多。我们这个船上，有五个孩子，顶好的有两个：一个小旦叫琪官，年十四岁。他的颜
 *   色就像花粉和了姻脂水，勾匀的搓成，一弹就破的。另有一股清气，晕在眉梢眼角里头。唱起戏来，
 *   比那画眉、黄鹂的声音还要清脆几分。
 *
 * Translation: "It is said that even princes and high ministers share their tables as equals. As for
 *   mid-ranking officials, some actively court and flatter them, seemingly borrowing their
 *   luster to flaunt before wealthy and influential patrons. Retaining one's company for a
 *   day's drinking can cost tens of taels of silver, yet the performer may not utter a single
 *   word of gratitude. Is this truly the case?" Ziyu laughed softly, "Perhaps in certain
 *   circles, but as I rarely venture out, I know little of such worldly affairs." Pincai
 *   pressed, "Surely you have attended performances. What are these young actors truly like?"
 *   Ziyu replied dismissively, "I have never encountered a truly exceptional one. Such is the
 *   fashion in the capital: so long as a man is a young dan, people take pleasure in merely
 *   talking of him. It has hardened into a custom that cannot be reversed." Pincai nodded in
 *   agreement, "That has always been my impression as well. The actors from Nanjing are utterly
 *   unexceptional, with the female roles played by men in their thirties or forties, I had
 *   never heard of gentlemen drinking with them. Yet, quite recently, two young performers have
 *   emerged who are akin to immortals banished to the mortal realm. They traveled with me on
 *   the very same boat as far as Zhangjiawan, and we entered the capital on the exact same
 *   day." Ziyu asked, "What do you mean by 'immortals banished to the mortal realm'?" Pincai
 *   elaborated with dramatic flair, "Even among the divine, these two would be chosen as
 *   unparalleled. The lesser deities of the lower eight caverns could not conjure such
 *   breathtaking visages. One of the four great troupes in Beijing employed a master who
 *   traveled to Suzhou and purchased ten youths, most fourteen or fifteen, some barely twelve
 *   or thirteen, bringing them north via the waterways in two grand vessels. When I departed my
 *   home, I initially boarded a cargo ship, and upon reaching Yangzhou, I chanced upon Brother
 *   Li at an inn, who was also bound for the capital. We joined forces, initially planning to
 *   journey overland, but finding the carriage fares exorbitant, we sought a passenger boat. It
 *   was then we encountered these theatrical vessels in Yangzhou. The master was a man named Ye
 *   Maolin, a native of Suzhou. He had previously taught singing at the Bian family's riverside
 *   estate on the Qinhuai, and I was acquainted with him. He graciously allowed us passage on
 *   his boat to the capital. Amidst the throngs of grain barges congesting the Grand Canal, the
 *   voyage stretched over four months. We observed them rehearsing their roles daily, absorbing
 *   many of their melodies by ear. Aboard our vessel were five youths, and the two most
 *   brilliant were a young dan named Qiguan, fourteen years of age. His complexion was like
 *   rouge and fine powder masterfully blended, forming a flawless visage that seemed fragile
 *   enough to shatter at a touch. A singular aura of fresh purity lingered about his brows and
 *   the corners of his eyes. When he sang, his voice rang several degrees clearer and more
 *   resplendent than a thrush or an oriole.
 *
 * Staging: the talk by lamplight, the troupe boats on the Grand Canal, the boys rehearsing, and Qiguan.
 */
export default defineStory({
  title: { en: 'Immortals banished to earth', zh: '神仙落劫' },
  description: {
    en: 'Pincai tells of the long canal voyage north with a troupe master and ten boys bought in Suzhou—and of Qiguan, fourteen, fragile as blended rouge.',
    zh: '聘才讲与戏班同船北上四个多月，及琪官年十四，颜色如花粉和胭脂。',
  },
  shots: [
    {
      start: 0, end: 9,
      title: { en: 'Princes sit beside them', zh: '王公大人并起并坐' },
      quote: '就是王公大人，也与他们并起并坐。',
      caption: { en: 'Pincai hears that princes sit with the actors as equals; Ziyu says he knows little of such things.', zh: '聘才听说王公大人与小旦并起并坐；子玉说不出门，不大知道。' },
    },
    {
      start: 9, end: 18,
      title: { en: 'Four months on the canal', zh: '运河里走了四个多月' },
      quote: '用两个太平船，由水路进京……就走了四个多月。',
      caption: { en: 'A troupe master bought ten boys in Suzhou and brought them north by canal; Pincai and Yuanmao rode along—four months among the grain barges.', zh: '教师在苏州买了十个孩子，由水路进京；聘才搭船同行，走了四个多月。' },
    },
    {
      start: 18, end: 27,
      title: { en: 'Rehearsing every day', zh: '天天的学戏' },
      quote: '见他们天天的学戏，倒也听会了许多。',
      caption: { en: 'Every day the boys rehearsed under the master Ye Maolin.', zh: '孩子们天天学戏，教师叶茂林是苏州人。' },
    },
    {
      start: 27, end: 36,
      title: { en: 'Qiguan', zh: '琪官' },
      quote: '一个小旦叫琪官，年十四岁。他的颜色就像花粉和了胭脂水',
      caption: { en: 'Qiguan, fourteen: his coloring like rouge and powder blended, fragile enough to break at a touch, his voice clearer than an oriole’s.', zh: '琪官年十四，颜色如花粉和胭脂，一弹就破，唱起来比黄鹂还清脆。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 4.6, zh: '「就是王公大人，也与他们并起并坐，是有的么？」', en: '“Is it true that even princes share their tables as equals?”' },
    { start: 4.6, end: 8.6, zh: '子玉笑道：「或者有之，但我不出门，所以也不大知道。」', en: 'Ziyu laughed: “Perhaps, but I rarely go out and know little of it.”' },
    { start: 9.4, end: 13.6, zh: '「如今出了两个小旦，竟是神仙落劫，与我一路同来，且在一个船里。', en: '“Two young dan have appeared, immortals banished to earth; they came on my very boat.' },
    { start: 13.6, end: 17.6, zh: '京里一个名班请了个教师到苏州买了十个孩子，由水路进京。」', en: 'A troupe master bought ten boys in Suzhou and brought them north by water.”' },
    { start: 18.4, end: 22.6, zh: '「在运河里粮船拥挤，就走了四个多月。', en: '“Amid the crowding grain barges, the voyage took over four months.' },
    { start: 22.6, end: 26.6, zh: '见他们天天的学戏，倒也听会了许多。」', en: 'Watching them rehearse daily, I learned many of their tunes.”' },
    { start: 27.4, end: 31.6, zh: '「一个小旦叫琪官，年十四岁。他的颜色就像花粉和了胭脂水，一弹就破的。', en: '“One is Qiguan, fourteen—his complexion like powder and rouge blended, fragile enough to break at a touch.' },
    { start: 31.6, end: 35.6, zh: '唱起戏来，比那画眉、黄鹂的声音还要清脆几分。」', en: 'When he sings, his voice is clearer than a thrush or an oriole.”' },
  ],
});
