import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 38. Generated by `npm run build-cinemas -- 2 38` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：「这杯便宜了。」又问周锡爵道：「五六两杯行什么令？」
 *
 * Translation: "That cup got off lightly." He then asked Zhou Xijue, "What are the rules for the fifth and
 *   sixth cups?"
 *
 * Staging: Guibao laughing over the seeds, then turning to Zhou.
 */
export default defineStory({
  title: { en: 'Off lightly', zh: '这杯便宜了' },
  description: {
    en: 'Guibao says the seed rule gets off lightly, and asks Zhou for the fifth and sixth cups.',
    zh: '桂保说数瓜子这杯便宜了，又问周锡爵五六两杯。',
  },
  shots: [
    {
      start: 0, end: 18,
      title: { en: 'Off lightly', zh: '这杯便宜了' },
      quote: '「这杯便宜了。」',
      caption: { en: '“That cup gets off lightly,” laughs Guibao.', zh: '桂保笑道：「这杯便宜了。」' },
    },
    {
      start: 18, end: 36,
      title: { en: 'The fifth and sixth cups', zh: '五六两杯' },
      quote: '又问周锡爵道：「五六两杯行什么令？」',
      caption: { en: 'He asks Zhou what the fifth and sixth cups shall be.', zh: '又问周锡爵五六两杯行什么令。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 17.6, zh: '「这杯便宜了。」', en: '“That cup got off lightly.”' },
    { start: 18.4, end: 35.6, zh: '又问周锡爵道：「五六两杯行什么令？」', en: 'He then asked Zhou Xijue, “What are the rules for the fifth and sixth cups?”' },
  ],
});
