import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 23. Generated by `npm run build-cinemas -- 2 23` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：「这倒好。一年有多少修金呢？」聘才道：「也有三百金。」文辉道：「也够浇裹了。论起来我做了
 *   三品京堂，一年的俸银，也不过如此。」说罢又仰面而笑。聘才也无话可说，正想告辞，忽见一个俊
 *   俏跟班，打扮得十分华丽，凑着文辉耳边说了一句话。聘才是乖觉人，知道有事，便起身告辞，文辉
 *   要送出去，聘才道：「还同颜大哥有话讲，大人请便。」文辉便住了脚，弯一弯腰，大摇大摆的进去
 *   了。仲清送出了门，聘才想道：「这个老头儿好大架子，不及梅老伯远甚。」便自回梅宅不题。
 *
 * Translation: "That is much better. What is his annual remuneration?" Pincai replied, "He earns around
 *   three hundred taels." Wenhui remarked, "That should suffice for daily expenses. Truth be
 *   told, as a third-rank metropolitan official, my own annual stipend scarcely amounts to
 *   more." With that, he threw his head back and laughed. Left with nothing further to say,
 *   Pincai was contemplating his departure when a strikingly handsome attendant, dressed in
 *   splendid attire, leaned in to whisper something in Wenhui's ear. Pincai, perceptive to a
 *   fault, recognized that a private matter required attention and promptly rose to take his
 *   leave. Wenhui made a gesture to escort him out, but Pincai demurred, "I still have a few
 *   words for Brother Yan. Please, Your Excellency, attend to your affairs." Wenhui halted,
 *   offered a perfunctory bow, and swaggered into the inner chambers with an exaggerated sway.
 *   Zhongqing escorted Pincai to the door, while Pincai thought to himself, "This old man is
 *   incredibly arrogant, a far cry from the graciousness of Uncle Mei." He then made his way
 *   back to the Mei residence, which needs no further recounting.
 *
 * Staging: the stipend, the whispering servant, Wenhui swaggering off, and Pincai leaving.
 */
export default defineStory({
  title: { en: 'Three hundred taels', zh: '三百金' },
  description: {
    en: 'Wenhui compares the father’s three hundred taels to his own stipend and laughs; a dandy servant whispers, and Wenhui swaggers off. Pincai thinks him far too grand.',
    zh: '文辉以三百金比自己三品俸银，仰面而笑；俊俏跟班耳语，文辉大摇大摆进去。聘才暗想好大架子。',
  },
  shots: [
    {
      start: 0, end: 10,
      title: { en: 'As much as a third-rank stipend', zh: '三品京堂' },
      quote: '论起来我做了三品京堂，一年的俸银，也不过如此。',
      caption: { en: 'Three hundred taels—as much as Wenhui’s own stipend as a third-rank official. He laughs.', zh: '三百金，与文辉三品京堂一年俸银不过如此；说罢仰面而笑。' },
    },
    {
      start: 10, end: 20,
      title: { en: 'A whisper', zh: '凑着耳边说了一句话' },
      quote: '忽见一个俊俏跟班，打扮得十分华丽，凑着文辉耳边说了一句话。',
      caption: { en: 'A handsome, splendidly dressed attendant whispers in Wenhui’s ear; Pincai takes the hint.', zh: '一个华丽的俊俏跟班凑着文辉耳边说话；聘才知道有事。' },
    },
    {
      start: 20, end: 28,
      title: { en: 'Swaggering in', zh: '大摇大摆的进去了' },
      quote: '文辉便住了脚，弯一弯腰，大摇大摆的进去了。',
      caption: { en: 'Wenhui gives a perfunctory bow and swaggers inside.', zh: '文辉弯一弯腰，大摇大摆的进去了。' },
    },
    {
      start: 28, end: 36,
      title: { en: 'Far too grand', zh: '好大架子' },
      quote: '这个老头儿好大架子，不及梅老伯远甚。',
      caption: { en: 'Pincai thinks: what airs—nothing like gracious Uncle Mei.', zh: '聘才想：这个老头儿好大架子，不及梅老伯远甚。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 4, zh: '「一年有多少修金呢？」聘才道：「也有三百金。」', en: '“What is his annual pay?” “About three hundred taels.”' },
    { start: 4, end: 9.6, zh: '文辉道：「论起来我做了三品京堂，一年的俸银，也不过如此。」说罢又仰面而笑。', en: '“As a third-rank official, my own stipend is scarcely more.” He threw back his head and laughed.' },
    { start: 10.4, end: 15, zh: '忽见一个俊俏跟班，打扮得十分华丽，凑着文辉耳边说了一句话。', en: 'A handsome, splendidly dressed attendant leaned in to whisper in Wenhui’s ear.' },
    { start: 15, end: 19.6, zh: '聘才是乖觉人，知道有事，便起身告辞。', en: 'Pincai, quick to perceive, rose to take his leave.' },
    { start: 20.4, end: 27.6, zh: '文辉便住了脚，弯一弯腰，大摇大摆的进去了。', en: 'Wenhui halted, gave a perfunctory bow, and swaggered inside.' },
    { start: 28.4, end: 32, zh: '仲清送出了门，聘才想道：「这个老头儿好大架子，', en: 'Zhongqing saw him out; Pincai thought: “What an arrogant old man—' },
    { start: 32, end: 35.6, zh: '不及梅老伯远甚。」便自回梅宅不题。', en: 'a far cry from Uncle Mei.” And he returned to the Mei house.' },
  ],
});
