import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 28. Generated by `npm run build-cinemas -- 2 28` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：「哥、哥、哥你这句话说、说错了，怎么把鸟来比起人来，你、你、你还要将箭射、射、射他，那就
 *   更岂有此理了。」嗣徽道：「老二，你到底腹中空空如也，不知运化书卷之妙。这是我腹笥便便，不
 *   啻若自其口出。这句「鸟倦飞而知还」，是出在《古文观止》上的。若说鸟不可以比人，那《大学》
 *   上为什么说「可以人而不如鸟乎」呢？」仲清暗笑道：天下也有这样蠢材，便道：「大哥的鸟论极
 *   通，岂特大哥如鸟，只怕鸟还不如大哥。要晓得靖节先生此言，原是引以自喻的。」嗣徽侧耳而听，
 *   又说道：「老兄所看的《古文观止》，只怕是翻板的。小弟记得逼真，做这篇古文是个姓陶的，并不
 *   是姓秦。」王恂忍不住，装作解手出去，抿着嘴笑了一会。仲清笑道：「大哥实在渊博之至，连那做
 *   古文的姓都知道。」嗣徽只道仲清果真佩服他，便意气扬扬，脸上的红疙瘩，如出花灌了浆一样，一
 *   颗颗的亮澄澄起来，便对嗣元道：「老二，但凡我们读书人，天分记性是并行不悖，缺一不可的。」
 *   嗣元道；「敢、敢、敢子，若不是记性好，也不、不、不把狗来对人了。若不是天分好，也不把牛来
 *   对先生了。」说着大笑，那只吊眼皮的眼睛已淌下泪来。那嗣徽便生了气，两腮鼓起就像癞虾蟆一
 *   样。仲清故意问道：「想必令兄又是引经据典，倒要请教请教。」嗣元道；「论、论、论文理呢，家
 *   兄到底多读两年书，小、小、小弟原赶、赶、赶不上，但是错的地方极多。有一天先生出、出、出了
 *   一个对，是叫将书对书的。上对是：「人能弘道。」家、家、家兄却对得快，写了出来是：狗、狗、
 *   狗无恒心。先生道：「这不是书。」家、家、家兄道：「是《孟子》上的。」先生道：
 *
 * Translation: "B-b-brother, your phrase is s-s-spoken in error. How can you c-c-compare a bird to a
 *   human, and furthermore, you w-w-wish to shoot an arrow at him? That is simply
 *   p-p-preposterous." Sihui retorted disdainfully, "Number Two, your mind is a hollow void,
 *   utterly devoid of the subtle alchemy of scholarship. This flows effortlessly from my
 *   profound erudition, tumbling spontaneously from my lips. This phrase, 'the weary bird knows
 *   to return,' originates from the Finest of Ancient Prose. If you argue a bird cannot be
 *   compared to a human, then why does the Great Learning state, 'Can a human be inferior to a
 *   bird?'" Zhongqing chuckled inwardly at the sheer magnitude of such stupidity and remarked
 *   aloud, "Brother's avian discourse is profoundly logical. Not only is Brother akin to a
 *   bird, but I fear the bird is scarcely a match for Brother. One must understand that Master
 *   Jingjie originally employed this phrase as a metaphor for himself." Sihui tilted his head,
 *   listening intently, before countering, "I fear the edition of the Finest of Ancient Prose
 *   my esteemed brother has perused is a pirated copy. My memory is flawless; the author of
 *   this ancient text was surnamed Tao, not Qin." Wang Xun, unable to contain himself any
 *   longer, feigned the need to use the washroom and hurried out, his lips pressed tightly
 *   together to stifle his laughter. Zhongqing replied with a smile, "Brother is truly a
 *   wellspring of profound knowledge, even knowing the author's surname." Sihui, assuming
 *   Zhongqing genuinely admired him, swelled with pride. The red lumps on his face swelled and
 *   shone one by one, like smallpox pustules filling with pus. He turned to Siyuan, "Number
 *   Two, for us scholars, natural talent and a robust memory must advance in tandem, neither
 *   can be lacking." Siyuan scoffed, "B-b-brilliant! If your memory were not so exceptional,
 *   you w-w-wouldn't have mistaken a dog for a human. And if your talent were not so
 *   formidable, you w-w-wouldn't have mistaken an ox for a teacher." As he laughed
 *   uproariously, a tear trickled from his slanted eye. Sihui flared with indignation, his
 *   cheeks puffing out like a toad's. Zhongqing deliberately inquired, "It seems your esteemed
 *   brother was once again citing the classics, I should very much like to hear this tale."
 *   Siyuan elaborated, "In t-t-terms of literary skill, my brother has studied two years
 *   l-l-longer than I, and I confess I c-c-cannot match him. However, his errors are legion.
 *   One day, our t-t-teacher set us a couplet exercise, requiring us to match a classical text
 *   with another. The first line was: 'Man can enlarge the Way.' My b-b-brother answered
 *   swiftly, writing down: 'The d-d-dog has no constant heart.' The teacher said, 'This is not
 *   from the classics.' My b-b-brother insisted, 'It is from Mencius.' The teacher retorted,
 *
 * Staging: the stammer stamped out, Sihui preening, the brothers quarrelling, and the dog couplet.
 */
export default defineStory({
  title: { en: '“B-b-brother, you’re wrong”', zh: '哥、哥、哥你这句话说错了' },
  description: {
    en: 'Siyuan stammers that birds can’t be compared to men; Sihui defends his learning, Zhongqing teases, Wang Xun flees to laugh, and Siyuan recounts his brother’s couplet: “The d-d-dog has no constant heart.”',
    zh: '嗣元结结巴巴驳哥哥；嗣徽引经自辩；仲清取笑，王恂躲出去笑；嗣元讲哥哥对对子「狗无恒心」。',
  },
  shots: [
    {
      start: 0, end: 9,
      title: { en: 'The stammer', zh: '哥、哥、哥' },
      quote: '哥、哥、哥你这句话说、说错了',
      caption: { en: 'Siyuan: “B-b-brother, your phrase is s-s-spoken in error—how can you c-c-compare a bird to a man?”', zh: '嗣元：「哥、哥、哥你这句话说、说错了。」' },
    },
    {
      start: 9, end: 18,
      title: { en: 'Profound erudition', zh: '腹笥便便' },
      quote: '老二，你到底腹中空空如也，不知运化书卷之妙。',
      caption: { en: 'Sihui scorns his brother’s empty head and cites the classics; Wang Xun pretends to need the washroom and slips out to laugh.', zh: '嗣徽说老二腹中空空；王恂装作解手出去，抿着嘴笑。' },
    },
    {
      start: 18, end: 27,
      title: { en: 'Pimples shining with pride', zh: '红疙瘩亮澄澄' },
      quote: '脸上的红疙瘩，如出花灌了浆一样，一颗颗的亮澄澄起来',
      caption: { en: 'Flattered, Sihui glows—every pimple shining; mocked, he puffs up like a toad while Siyuan laughs to tears.', zh: '嗣徽得意，红疙瘩亮澄澄；被弟弟一笑，两腮鼓起像癞虾蟆。' },
    },
    {
      start: 27, end: 36,
      title: { en: 'The dog couplet', zh: '狗无恒心' },
      quote: '上对是：「人能弘道。」家、家、家兄却对得快，写了出来是：狗、狗、狗无恒心。',
      caption: { en: 'Set to match “Man can enlarge the Way,” Sihui wrote: “The d-d-dog has no constant heart.”', zh: '先生出对「人能弘道」，家兄对了「狗无恒心」。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 4.6, zh: '「哥、哥、哥你这句话说、说错了，怎么把鸟来比起人来，', en: '“B-b-brother, your phrase is s-s-spoken in error. How can you compare a bird to a man,' },
    { start: 4.6, end: 8.6, zh: '你、你、你还要将箭射、射、射他，那就更岂有此理了。」', en: 'and then w-w-want to shoot him? That’s p-p-preposterous.”' },
    { start: 9.4, end: 13.6, zh: '嗣徽道：「老二，你到底腹中空空如也，不知运化书卷之妙。', en: 'Sihui: “Number Two, your belly is empty; you know nothing of the alchemy of scholarship.”' },
    { start: 13.6, end: 17.6, zh: '王恂忍不住，装作解手出去，抿着嘴笑了一会。', en: 'Wang Xun could bear it no longer, feigned a trip to the washroom, and laughed outside.' },
    { start: 18.4, end: 22.6, zh: '嗣徽只道仲清果真佩服他，脸上的红疙瘩，一颗颗的亮澄澄起来。', en: 'Thinking Zhongqing truly admired him, Sihui swelled with pride; his red pimples shone one by one.' },
    { start: 22.6, end: 26.6, zh: '嗣元说着大笑，那只吊眼皮的眼睛已淌下泪来。嗣徽两腮鼓起就像癞虾蟆一样。', en: 'Siyuan laughed until his slanted eye wept; Sihui’s cheeks puffed out like a toad’s.' },
    { start: 27.4, end: 31.6, zh: '「有一天先生出了一个对，上对是：「人能弘道。」', en: '“One day our teacher set a couplet: ‘Man can enlarge the Way.’' },
    { start: 31.6, end: 35.6, zh: '家、家、家兄却对得快，写了出来是：狗、狗、狗无恒心。」', en: 'My b-b-brother answered fast: ‘The d-d-dog has no constant heart.’”' },
  ],
});
