import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 4. Generated by `npm run build-cinemas -- 2 4` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：「请他们在花厅上坐，说我就出来。」文辉也就起身告辞，士燮送到门口，转身到花厅垂花门首，即
 *   叫跟班的到书房去请少爷出来，遂即踱进花厅。
 *
 * Translation: "Invite them to take a seat in the flower hall and inform them I shall be out shortly."
 *   Wenhui then rose to take his leave. Shixie saw him to the door, turned back to the hanging
 *   flower gate of the hall, and instructed his attendant to summon the young master from the
 *   study before strolling inside.
 *
 * Staging: Wenhui seen off at the gate, and Shixie entering the flower hall.
 */
export default defineStory({
  title: { en: 'To the flower hall', zh: '请到花厅' },
  description: {
    en: 'The visitors are shown to the flower hall; Wenhui leaves, and Shixie strolls in through the hanging-flower gate.',
    zh: '请客人花厅坐；文辉告辞，士燮踱进花厅。',
  },
  shots: [
    {
      start: 0, end: 14,
      title: { en: 'Wenhui takes his leave', zh: '文辉告辞' },
      quote: '文辉也就起身告辞，士燮送到门口',
      caption: { en: '“Seat them in the flower hall; I shall be out shortly.” Wenhui leaves, and Shixie sees him to the gate.', zh: '「请他们在花厅上坐。」文辉告辞，士燮送到门口。' },
    },
    {
      start: 14, end: 36,
      title: { en: 'The hanging-flower gate', zh: '垂花门' },
      quote: '转身到花厅垂花门首……遂即踱进花厅。',
      caption: { en: 'Shixie turns back through the hanging-flower gate, sends for his son, and strolls into the hall.', zh: '士燮转到垂花门首，叫人去请少爷，踱进花厅。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 6, zh: '「请他们在花厅上坐，说我就出来。」', en: '“Invite them to sit in the flower hall; tell them I shall be out shortly.”' },
    { start: 6, end: 13.6, zh: '文辉也就起身告辞，士燮送到门口，', en: 'Wenhui rose to take his leave; Shixie saw him to the door,' },
    { start: 14.4, end: 25, zh: '转身到花厅垂花门首，即叫跟班的到书房去请少爷出来，', en: 'turned back to the hanging-flower gate, and sent an attendant to summon the young master,' },
    { start: 25, end: 35.6, zh: '遂即踱进花厅。', en: 'before strolling into the hall.' },
  ],
});
