import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 9. Generated by `npm run build-cinemas -- 2 9` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：喝了一会茶，说了些南边年岁光景，聘才知道元茂不能熬夜，起身告辞，性全也体谅他们路上辛苦，
 *   就叫元茂跟了过去，子玉送他们进屋，见已铺设好了，说声：「早些安歇罢！」也就叫俊儿提灯，照
 *   进上房去了。
 *
 * Translation: They lingered over tea for a while, discussing the state of affairs in the south. Pincai,
 *   aware that Yuanmao could not abide late hours, eventually rose to take his leave. Li
 *   Xingquan, understanding the exhaustion of their travels, sent Yuanmao along with him. Ziyu
 *   escorted them to their quarters, ensuring everything was appropriately arranged. Bidding
 *   them to rest early, he called for Junner to light a lantern and made his way back to the
 *   main house.
 *
 * Staging: tea in the study, and the guests’ room at night.
 */
export default defineStory({
  title: { en: 'Rest early', zh: '早些安歇罢' },
  description: {
    en: 'After tea, Pincai takes the sleepy Yuanmao to their rooms; Ziyu sees them settled and goes back with a lantern.',
    zh: '茶后聘才领元茂回房安歇，子玉送他们进屋，叫俊儿提灯回上房。',
  },
  shots: [
    {
      start: 0, end: 14,
      title: { en: 'Talk of the south', zh: '南边年岁光景' },
      quote: '喝了一会茶，说了些南边年岁光景',
      caption: { en: 'Over tea they talk of the south; Pincai knows Yuanmao cannot stay up late.', zh: '喝茶说些南边光景；聘才知元茂不能熬夜。' },
    },
    {
      start: 14, end: 36,
      title: { en: '“Rest early”', zh: '早些安歇罢' },
      quote: '子玉送他们进屋，见已铺设好了，说声：「早些安歇罢！」',
      caption: { en: 'Ziyu sees them to their room, bids them rest early, and goes back by lantern light.', zh: '子玉送他们进屋，说声「早些安歇罢」，叫俊儿提灯回上房。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 7, zh: '喝了一会茶，说了些南边年岁光景，', en: 'They lingered over tea, talking of affairs in the south.' },
    { start: 7, end: 13.6, zh: '聘才知道元茂不能熬夜，起身告辞。', en: 'Pincai, knowing Yuanmao could not abide late hours, rose to take his leave.' },
    { start: 14.4, end: 22, zh: '子玉送他们进屋，见已铺设好了，说声：「早些安歇罢！」', en: 'Ziyu saw them to their room, all arranged, and said, “Rest early!”' },
    { start: 22, end: 35.6, zh: '也就叫俊儿提灯，照进上房去了。', en: 'Then he had Jun’er light a lantern and went back to the main house.' },
  ],
});
