import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 14. Generated by `npm run build-cinemas -- 2 14` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：子玉不觉笑起来，心里想道：「他这般称赞是 不可信的，但他形容这两个人，倒可以移到我前日车
 *   里所见的那两个身上，倒是一毫不错的。世间既生了这两个，怎么还能再生两个出来？断无是理，不
 *   必信他。」即说道：「吾兄说得这样好，天下只怕真投这个人。」聘才道：「这是你可以见得着的，
 *   他们与我同一天到京，此时自然已经进了班子；难道将来不上台唱戏的？那时吾兄见了，才信小弟这
 *   对眼睛，是个识宝回回，不是轻易赞好的。就是一样，这两个相貌好了，脾气恰不好。凭你怎样巴结
 *   他，要他一句好言好语也不能。
 *
 * Translation: Ziyu could not suppress a laugh. Inwardly, he reasoned, "Such extravagant praise cannot be
 *   entirely trusted. Yet, his description mirrors the two youths I beheld in the carriage the
 *   other day with uncanny precision, not a single detail is amiss. Since those two exist in
 *   reality, how could heaven possibly forge an identical pair? It is simply impossible, there
 *   is no need to lend full credence to his words." Aloud, he remarked, "From your description,
 *   Brother, they sound truly peerless. It is doubtful anyone else in this world could rival
 *   them." Pincai declared, "You shall see for yourself. They arrived in the capital on the
 *   exact same day as I did, and by now they must be formally bound to a troupe. Are they not
 *   destined to grace the stage one day? Once you set eyes upon them, you will trust my
 *   judgment, for these eyes of mine are a Persian gem-appraiser's and do not praise cheaply.
 *   There is, however, one caveat: their beauty is matched only by their forbidding
 *   temperaments. No matter how ardently one attempts to please them, not a single kind word
 *   can be coaxed from their lips.
 *
 * Staging: Ziyu remembering the cart, and Pincai boasting of his eye.
 */
export default defineStory({
  title: { en: 'A gem-appraiser’s eyes', zh: '识宝回回' },
  description: {
    en: 'Ziyu laughs, thinking the praise fits the two boys in the cart exactly; Pincai insists his eyes never praise cheaply—though the two have forbidding tempers.',
    zh: '子玉暗想这番形容正合车中所见两人；聘才自夸眼光是识宝回回，只是二人脾气不好。',
  },
  shots: [
    {
      start: 0, end: 16,
      title: { en: 'It fits the two in the cart', zh: '移到车里所见的那两个身上' },
      quote: '但他形容这两个人，倒可以移到我前日车里所见的那两个身上',
      caption: { en: 'Ziyu laughs: such praise can’t be trusted—yet it fits the two he saw in the cart exactly.', zh: '子玉暗笑：这般称赞不可信，却正合前日车中所见两人。' },
    },
    {
      start: 16, end: 36,
      title: { en: 'Not easily impressed', zh: '不是轻易赞好的' },
      quote: '那时吾兄见了，才信小弟这对眼睛，是个识宝回回，不是轻易赞好的。',
      caption: { en: 'Pincai: you’ll see them on stage and trust my eyes. Only—their tempers are as forbidding as their looks are fine.', zh: '聘才：吾兄见了，才信我这对眼睛是识宝回回；只是这两个脾气不好。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 5, zh: '子玉不觉笑起来，心里想道：「他这般称赞是不可信的，', en: 'Ziyu couldn’t help laughing, thinking: “Such praise can’t be trusted,' },
    { start: 5, end: 10.6, zh: '但他形容这两个人，倒可以移到我前日车里所见的那两个身上，一毫不错。', en: 'yet it fits the two I saw in the carriage the other day, to the last detail.' },
    { start: 10.6, end: 15.6, zh: '世间既生了这两个，怎么还能再生两个出来？」', en: 'Since those two exist, how could heaven make another pair?”' },
    { start: 16.4, end: 21, zh: '聘才道：「他们与我同一天到京，此时自然已经进了班子。', en: 'Pincai: “They reached the capital the same day as I; by now they’ve joined a troupe.' },
    { start: 21, end: 27, zh: '那时吾兄见了，才信小弟这对眼睛，是个识宝回回，不是轻易赞好的。', en: 'When you see them, you’ll trust these eyes of mine—a gem-appraiser’s that don’t praise cheaply.' },
    { start: 27, end: 35.6, zh: '就是这两个相貌好了，脾气恰不好，凭你怎样巴结他，要他一句好言好语也不能。」', en: 'Only, their tempers are as bad as their looks are fine; flatter all you like, you won’t get a kind word.”' },
  ],
});
