import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 16. Generated by `npm run build-cinemas -- 2 16` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：子玉心里想道：「他说这两个人，与他同一天进京。我那日看见那两人之后，他就到了，不要他说的
 *   就是我见的，那一班人却像从南边来的模样。」便又问道：「你说那个顶好的叫什么名字？」聘才
 *   道：「叫琴官。那个叫琪官。」子玉道：「琴官进城那一天穿的什么衣裳？」聘才道：「都是蓝绉绸
 *   皮袄，酱色呢得胜褂。」子玉见衣服已经对了，又问：「他一人一个车呢，还与人同坐一个车？」聘
 *   才道：「他与琪官、叶茂林同坐一个车，那车围是蓝布的，骡子是白的。」子玉又道：「那叶茂林有
 *   多少岁数了？」聘才道：「五十以外。」子玉不禁拍手笑道：「我已见过这两人，你果然赞得不错，
 *   真要算绝色了。」聘才大乐道：「何如，你几时见过的？」子玉就将那日挤了路，见四辆车都是些小
 *   孩子，头一辆就是这三个人。那琪官已经好了，那琴官真可说天下无双。聘才乐得受不得，便又问
 *   道：
 *
 * Translation: Ziyu reflected silently, "He claims these two entered the capital on the exact same day as
 *   he did. They arrived precisely after I saw those two on that very day, could the ones he
 *   speaks of be the very ones I saw? That group did indeed appear to be travelers from the
 *   south." He then asked, "What did you say the most beautiful one was named?" Pincai replied,
 *   "He is named Qinguan. The other is Qiguan." Ziyu pressed on, "What garments was Qinguan
 *   wearing on the day he entered the city?" Pincai described, "Both wore fur coats of blue
 *   crepe silk beneath outer riding jackets of dark brown wool." Ziyu, noting the match in
 *   attire, probed further, "Did each ride in his own carriage, or did they share one?" Pincai
 *   answered, "He shared a carriage with Qiguan and Ye Maolin. The carriage awning was of blue
 *   cloth, drawn by a white mule." Ziyu asked, "And how old is this Ye Maolin?" Pincai said,
 *   "Past fifty." Unable to contain himself, Ziyu clapped his hands and laughed, "I have
 *   already seen these two! Your praise is not misplaced in the slightest, they are truly
 *   unparalleled beauties." Pincai, overjoyed, exclaimed, "You see? But when did you happen to
 *   see them?" Ziyu recounted how he had been caught in the throng that day and had observed
 *   four carriages filled with young boys, the foremost bearing those very three. Qiguan was
 *   already exceptional, but Qinguan was truly without equal beneath the heavens. Pincai was
 *   beside himself with delight and pressed further:
 *
 * Staging: Ziyu realising, the clothes described, the cart remembered through its window, and the two friends delighted.
 */
export default defineStory({
  title: { en: '“I have seen them”', zh: '我已见过这两人' },
  description: {
    en: 'Ziyu checks the details—blue crepe fur coats, a blue-hooded cart and a white mule, a master past fifty—and claps his hands: these are the boys he saw.',
    zh: '子玉逐一问明：蓝绉绸皮袄、蓝布车围白骡子、五十以外的叶茂林——拍手笑道：我已见过这两人。',
  },
  shots: [
    {
      start: 0, end: 8,
      title: { en: 'The same day', zh: '同一天进京' },
      quote: '他说这两个人，与他同一天进京。……不要他说的就是我见的',
      caption: { en: 'They entered the capital the same day as Pincai—could they be the ones Ziyu saw?', zh: '同一天进京——不要他说的就是我见的？' },
    },
    {
      start: 8, end: 18,
      title: { en: 'Blue crepe fur coats', zh: '蓝绉绸皮袄' },
      quote: '都是蓝绉绸皮袄，酱色呢得胜褂。',
      caption: { en: 'What was Qinguan wearing? Blue crepe fur coats under dark brown riding jackets. It matches.', zh: '琴官进城穿的是蓝绉绸皮袄，酱色呢得胜褂——衣服对了。' },
    },
    {
      start: 18, end: 27,
      title: { en: 'A white mule', zh: '骡子是白的' },
      quote: '他与琪官、叶茂林同坐一个车，那车围是蓝布的，骡子是白的。',
      caption: { en: 'He rode with Qiguan and Ye Maolin, past fifty, in a blue-hooded cart drawn by a white mule.', zh: '与琪官、叶茂林同车，蓝布车围，白骡子；叶茂林五十以外。' },
    },
    {
      start: 27, end: 36,
      title: { en: '“I have seen them!”', zh: '拍手笑道' },
      quote: '子玉不禁拍手笑道：「我已见过这两人，你果然赞得不错，真要算绝色了。」',
      caption: { en: 'Ziyu claps his hands and laughs: “I have seen them! You praised them rightly.” Pincai is overjoyed.', zh: '子玉拍手笑道：我已见过这两人，真要算绝色了。聘才大乐。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 4, zh: '子玉心里想道：「他说这两个人，与他同一天进京。', en: 'Ziyu thought: “He says these two entered the capital the same day as he did.' },
    { start: 4, end: 7.6, zh: '不要他说的就是我见的？」', en: 'Could they be the very ones I saw?”' },
    { start: 8.4, end: 12.6, zh: '「你说那个顶好的叫什么名字？」「叫琴官。那个叫琪官。」', en: '“What is the best one called?” “Qinguan. The other is Qiguan.”' },
    { start: 12.6, end: 17.6, zh: '「琴官进城那一天穿的什么衣裳？」「都是蓝绉绸皮袄，酱色呢得胜褂。」', en: '“What was Qinguan wearing that day?” “Blue crepe fur coats under dark brown riding jackets.”' },
    { start: 18.4, end: 23, zh: '「他与琪官、叶茂林同坐一个车，那车围是蓝布的，骡子是白的。」', en: '“He shared a cart with Qiguan and Ye Maolin—blue cloth awning, a white mule.”' },
    { start: 23, end: 26.6, zh: '「那叶茂林有多少岁数了？」「五十以外。」', en: '“How old is Ye Maolin?” “Past fifty.”' },
    { start: 27.4, end: 32, zh: '子玉不禁拍手笑道：「我已见过这两人，你果然赞得不错，真要算绝色了。」', en: 'Ziyu clapped his hands: “I have seen them! Your praise is right—they are truly peerless.”' },
    { start: 32, end: 35.6, zh: '那琪官已经好了，那琴官真可说天下无双。聘才乐得受不得。', en: 'Qiguan was fine indeed, but Qinguan was without equal. Pincai was beside himself with delight.' },
  ],
});
