import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 25. Generated by `npm run build-cinemas -- 2 25` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：将他们的外貌内才比起王恂来，真有天渊之隔。这嗣徽生得缩颈堆腮，脸色倒还白净，就是肺火太
 *   重，一年四季总是满脸的红疙瘩，已堆得面无余地，而鼻上更多，已变了一个红鼻子。
 *
 * Translation: Compared to Wang Xun in both physical appearance and intellectual capacity, the difference
 *   was as vast as that between heaven and the abyss. Sihui possessed a hunched neck and
 *   bulging cheeks, his complexion passably fair were it not marred by a severe excess of
 *   internal heat. Year-round, his face was blanketed in a dense crop of red pustules, leaving
 *   virtually no skin untouched, with the affliction clustering most aggressively upon his
 *   nose, transforming it into a bright, inflamed bulb.
 *
 * Staging: Wang Xun beside Sihui, then Sihui’s portrait.
 */
export default defineStory({
  title: { en: 'A bright red nose', zh: '红鼻子' },
  description: {
    en: 'Beside Wang Xun the brothers are heaven and abyss; Sihui has a sunken neck, puffed cheeks, and a face of red pimples crowned by a red nose.',
    zh: '二人比王恂有天渊之隔；嗣徽缩颈堆腮，满脸红疙瘩，鼻上更多，变了红鼻子。',
  },
  shots: [
    {
      start: 0, end: 14,
      title: { en: 'Heaven and the abyss', zh: '天渊之隔' },
      quote: '将他们的外貌内才比起王恂来，真有天渊之隔。',
      caption: { en: 'Beside Wang Xun, in looks and wits, the difference is heaven and the abyss.', zh: '比起王恂，外貌内才真有天渊之隔。' },
    },
    {
      start: 14, end: 36,
      title: { en: 'Sun Sihui', zh: '孙嗣徽' },
      quote: '这嗣徽生得缩颈堆腮……已变了一个红鼻子。',
      caption: { en: 'Sihui: a sunken neck, bulging cheeks, a fair skin buried under red pimples, thickest on his nose.', zh: '嗣徽缩颈堆腮，满脸红疙瘩，鼻上更多，变了个红鼻子。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 13.6, zh: '将他们的外貌内才比起王恂来，真有天渊之隔。', en: 'Compared with Wang Xun in looks and intellect, the difference was as heaven to the abyss.' },
    { start: 14.4, end: 22, zh: '这嗣徽生得缩颈堆腮，脸色倒还白净，', en: 'Sihui had a hunched neck and bulging cheeks, his complexion passably fair,' },
    { start: 22, end: 28.6, zh: '就是肺火太重，一年四季总是满脸的红疙瘩，', en: 'but from excess internal heat his face was covered year-round in red pimples,' },
    { start: 28.6, end: 35.6, zh: '而鼻上更多，已变了一个红鼻子。', en: 'thickest of all on his nose, which had become a bright red bulb.' },
  ],
});
