import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 29. Generated by `npm run build-cinemas -- 2 29` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：「岂、岂、岂有此理。」家兄只当先生忘了，便乐、乐、乐得了不得，连忙翻、翻、翻出来看，原来
 *   是草字头的苟字，不是反犬旁的狗字。」仲清笑了一笑道：「若不是狗记错了，倒是一副好对子。」
 *   嗣元道：「又一日，先生出了一个做起讲的题、题、题目，是：「先生将何之。」家兄就、就、就
 *   将「牛何之」做了起头。先、先生拿笔叉、叉、叉了几叉，痛骂了一顿。」这一番说得嗣徽羞忿难
 *   耐，便在屋子里乱踱起来，说道：「屁话，屁话！」便起身告辞。王恂也恐他们弟兄斗气，不便挽
 *   留，同仲清送了出来。
 *
 * Translation: "'P-p-preposterous!' My brother assumed the teacher had forgotten, and was d-d-delighted
 *   beyond measure, hastily flipping through the text to show him. It turned out to be the
 *   character 'gou' (if/careless) with the grass radical, not the character 'gou' (dog) with
 *   the dog radical." Zhongqing let out a soft laugh and commented, "If not for the canine
 *   confusion, it would have been an excellent couplet." Siyuan continued, "On another
 *   occasion, the teacher set a theme for the opening argument of an essay: 'Where is the
 *   master going?' My brother immediately b-b-began his essay with 'Where is the ox going?' The
 *   t-t-teacher aggressively crossed it out with his brush and delivered a scathing reprimand."
 *   This recounting left Sihui so overwhelmed with shame and fury that he began pacing wildly
 *   around the room, sputtering, "Bullshit! Bullshit!" before storming out to take his leave.
 *   Wang Xun, fearing their sibling rivalry might escalate unpleasantly, deemed it unwise to
 *   insist they stay, and together with Zhongqing, escorted them out.
 *
 * Staging: the two gou characters, the ox essay, and Sihui pacing and storming out.
 */
export default defineStory({
  title: { en: '“Where is the ox going?”', zh: '牛何之' },
  description: {
    en: 'The Mencius line has the grass-radical gou, not the dog; and Sihui once began an essay with “Where is the ox going?” Sihui storms out.',
    zh: '《孟子》上原是草字头的苟字；嗣徽又以「牛何之」起讲。嗣徽羞忿，乱踱告辞。',
  },
  shots: [
    {
      start: 0, end: 12,
      title: { en: 'Grass, not dog', zh: '草字头的苟字' },
      quote: '原来是草字头的苟字，不是反犬旁的狗字。',
      caption: { en: 'The Mencius line uses gou with the grass radical, “if,” not gou with the dog radical.', zh: '原来是草字头的「苟」，不是反犬旁的「狗」。' },
    },
    {
      start: 12, end: 22,
      title: { en: 'The ox essay', zh: '牛何之' },
      quote: '先生出了一个做起讲的题目，是：「先生将何之。」家兄就将「牛何之」做了起头。',
      caption: { en: 'Set “Where is the master going?”, Sihui began: “Where is the ox going?”', zh: '题目「先生将何之」，家兄以「牛何之」起头。' },
    },
    {
      start: 22, end: 36,
      title: { en: '“Nonsense!”', zh: '屁话，屁话' },
      quote: '便在屋子里乱踱起来，说道：「屁话，屁话！」便起身告辞。',
      caption: { en: 'Sihui paces the room sputtering “Nonsense!” and storms out; Wang Xun and Zhongqing see them off.', zh: '嗣徽乱踱，骂道「屁话」，起身告辞；王恂、仲清送了出来。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 5, zh: '先生道：「岂、岂、岂有此理。」家兄只当先生忘了，连忙翻、翻、翻出来看，', en: '“P-p-preposterous!” said the teacher. My brother, delighted, flipped open the book to show him—' },
    { start: 5, end: 11.6, zh: '原来是草字头的苟字，不是反犬旁的狗字。」仲清笑道：「若不是狗记错了，倒是一副好对子。」', en: 'it was gou with the grass radical, not the dog. Zhongqing laughed: “But for the dog, a fine couplet.”' },
    { start: 12.4, end: 17, zh: '「又一日，先生出了一个做起讲的题、题、题目，是：「先生将何之。」', en: '“Another day the teacher set the theme: ‘Where is the master going?’' },
    { start: 17, end: 21.6, zh: '家兄就、就、就将「牛何之」做了起头。先生痛骂了一顿。」', en: 'My brother b-b-began with ‘Where is the ox going?’ The teacher crossed it out and scolded him.”' },
    { start: 22.4, end: 28, zh: '这一番说得嗣徽羞忿难耐，便在屋子里乱踱起来，说道：「屁话，屁话！」', en: 'Sihui, burning with shame and fury, paced the room sputtering, “Nonsense! Nonsense!”' },
    { start: 28, end: 35.6, zh: '便起身告辞。王恂恐他们弟兄斗气，不便挽留，同仲清送了出来。', en: 'and took his leave. Fearing a quarrel, Wang Xun did not detain them, and saw them out with Zhongqing.' },
  ],
});
