import { readFileSync, writeFileSync, existsSync } from 'fs';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const require = createRequire(import.meta.url);
const dotenv = require('dotenv');
dotenv.config({ path: join(root, '.env') });

const API_KEY = process.env.ANTHROPIC_API_KEY;
if (!API_KEY) {
  console.error('Missing ANTHROPIC_API_KEY in .env');
  process.exit(1);
}

const Anthropic = (await import('@anthropic-ai/sdk')).default;
const client = new Anthropic({ apiKey: API_KEY });

const chapterData = JSON.parse(readFileSync(join(root, 'src/chapterData.json'), 'utf8'));
const chaptersToTranslate = chapterData.chapters.filter(ch => ch.id >= 3 && ch.id <= 60);

const SYSTEM_PROMPT = `You are a literary translator specializing in classical Chinese fiction.
Translate each paragraph from the 19th-century Chinese novel "Pinhua Baojian" (品花宝鉴) into fluid, scholarly English prose.
Romanize proper names (people and places) using pinyin without tone marks.
Render classical allusions and official titles in English with the Chinese term in parentheses where helpful.
Match the elevated, literary register of the source.
Return ONLY the translations — no headings, no numbering, no commentary.`;

async function translateChapter(chapter, attempt = 1) {
  const paragraphs = chapter.content.split('\n\n');
  const N = paragraphs.length;

  const userPrompt = `Translate the following ${N} paragraphs from Chapter ${chapter.id} of Pinhua Baojian into English.
Return EXACTLY ${N} English translations, each separated by a blank line (two newlines), in the same order as the source.
Do NOT add any extra paragraphs, headings, numbering, or commentary — only the ${N} translations.

Source paragraphs:
${chapter.content}`;

  const message = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 8192,
    system: SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userPrompt }],
  });

  const text = message.content[0].text.trim();
  const translations = text.split('\n\n').map(s => s.trim()).filter(s => s.length > 0);

  if (translations.length !== N) {
    if (attempt <= 3) {
      console.warn(`  Ch${chapter.id}: got ${translations.length} paragraphs, expected ${N}. Retry ${attempt}/3...`);
      await sleep(2000);
      return translateChapter(chapter, attempt + 1);
    }
    console.warn(`  Ch${chapter.id}: alignment failed after 3 retries. Padding/trimming to ${N}.`);
    while (translations.length < N) translations.push('');
    return translations.slice(0, N);
  }

  return translations;
}

function sleep(ms) {
  return new Promise(r => setTimeout(r, ms));
}

const OUTPUT_FILE = join(root, 'src/chapterTranslations3to60.ts');

let results = {};
if (existsSync(OUTPUT_FILE)) {
  const existing = readFileSync(OUTPUT_FILE, 'utf8');
  const match = existing.match(/\/\/ PROGRESS: (\{[^}]*\})/);
  if (match) {
    try { results = JSON.parse(match[1]); } catch {}
  }
  const done = Object.keys(results).length;
  if (done > 0) console.log(`Resuming — already have ${done} chapters: ${Object.keys(results).join(', ')}`);
}

function writeOutput() {
  const entries = Object.entries(results)
    .sort((a, b) => Number(a[0]) - Number(b[0]))
    .map(([id, translations]) => {
      const escaped = translations.map(t => JSON.stringify(t)).join(',\n    ');
      return `  ${id}: [\n    ${escaped}\n  ]`;
    })
    .join(',\n');

  const progressKeys = Object.keys(results);
  const ts = `// AUTO-GENERATED by scripts/generateTranslations.mjs — do not edit manually
// PROGRESS: ${JSON.stringify(progressKeys)}
export const chapterTranslations3to60: Record<number, string[]> = {
${entries}
};
`;
  writeFileSync(OUTPUT_FILE, ts, 'utf8');
}

let count = 0;
for (const chapter of chaptersToTranslate) {
  if (results[chapter.id] !== undefined) {
    console.log(`Ch${chapter.id}: already translated, skipping.`);
    continue;
  }

  const N = chapter.content.split('\n\n').length;
  console.log(`Translating Ch${chapter.id} (${N} paragraphs)...`);
  try {
    const translations = await translateChapter(chapter);
    results[chapter.id] = translations;
    count++;
    console.log(`  Ch${chapter.id}: done (${translations.length} paragraphs)`);
  } catch (err) {
    console.error(`  Ch${chapter.id}: ERROR — ${err.message}`);
    writeOutput();
    process.exit(1);
  }

  writeOutput();
  await sleep(500);
}

console.log(`\nDone! Translated ${count} new chapters. Output: src/chapterTranslations3to60.ts`);
