import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 11. Generated by `npm run build-cinemas -- 2 11` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：一日晚上，元茂睡了，子玉与聘才闲谈。聘才问道：「京里的戏是甲于天下的。我听得说那些小旦称
 *   呼相公，好不扬气。
 *
 * Translation: One evening, while Yuanmao slept, Ziyu and Pincai sat chatting together. Pincai inquired,
 *   "The theater of the capital is renowned as the finest beneath the heavens. I have heard
 *   that the young performers of female roles, addressed as 'xianggong,' carry themselves with
 *   an extraordinary air of distinction.
 *
 * Staging: Ziyu and Pincai at a lamp-lit table.
 */
export default defineStory({
  title: { en: 'Talk by lamplight', zh: '灯下闲谈' },
  description: {
    en: 'One evening, with Yuanmao asleep, Pincai asks Ziyu about the capital’s famous young actors.',
    zh: '一日晚上元茂睡了，聘才与子玉闲谈京中小旦。',
  },
  shots: [
    {
      start: 0, end: 14,
      title: { en: 'One evening', zh: '一日晚上' },
      quote: '一日晚上，元茂睡了，子玉与聘才闲谈。',
      caption: { en: 'One evening, while Yuanmao sleeps, Ziyu and Pincai sit talking.', zh: '一日晚上，元茂睡了，子玉与聘才闲谈。' },
    },
    {
      start: 14, end: 36,
      title: { en: 'The xianggong', zh: '称呼相公' },
      quote: '京里的戏是甲于天下的。我听得说那些小旦称呼相公，好不扬气。',
      caption: { en: 'Pincai: the capital’s theatre is the finest in the land, and its young dan, called xianggong, carry themselves so grandly.', zh: '聘才：京里的戏甲于天下，小旦称呼相公，好不扬气。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 13.6, zh: '一日晚上，元茂睡了，子玉与聘才闲谈。', en: 'One evening, while Yuanmao slept, Ziyu and Pincai sat chatting.' },
    { start: 14.4, end: 24, zh: '聘才问道：「京里的戏是甲于天下的。', en: 'Pincai asked: “The theatre of the capital is the finest beneath heaven.' },
    { start: 24, end: 35.6, zh: '我听得说那些小旦称呼相公，好不扬气。」', en: 'I hear the young dan, addressed as xianggong, carry themselves with such an air.”' },
  ],
});
