import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 30. Generated by `npm run build-cinemas -- 2 30` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：刚到二门口，可巧碰见孙亮功进来，孙氏弟兄站在一边。
 *
 * Translation: Just as they reached the inner gate, it happened that Sun Lianggong was making his
 *   entrance, and the Sun brothers respectfully stood aside.
 *
 * Staging: the inner gate, the father arriving and the sons stepping aside.
 */
export default defineStory({
  title: { en: 'At the inner gate', zh: '二门口' },
  description: {
    en: 'At the inner gate they meet Sun Lianggong coming in; his sons stand aside.',
    zh: '刚到二门口，碰见孙亮功进来，孙氏弟兄站在一边。',
  },
  shots: [
    {
      start: 0, end: 18,
      title: { en: 'Sun Lianggong arrives', zh: '孙亮功进来' },
      quote: '刚到二门口，可巧碰见孙亮功进来',
      caption: { en: 'Just at the inner gate, Sun Lianggong comes in.', zh: '刚到二门口，碰见孙亮功进来。' },
    },
    {
      start: 18, end: 36,
      title: { en: 'The sons stand aside', zh: '站在一边' },
      quote: '孙氏弟兄站在一边。',
      caption: { en: 'The Sun brothers stand respectfully aside.', zh: '孙氏弟兄站在一边。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 17.6, zh: '刚到二门口，可巧碰见孙亮功进来，', en: 'Just as they reached the inner gate, Sun Lianggong came in,' },
    { start: 18.4, end: 35.6, zh: '孙氏弟兄站在一边。', en: 'and the Sun brothers stood respectfully aside.' },
  ],
});
