// Auto-generated specific relationship specs for pairs with co-occurrence >= 8
import { Relationship } from './types';

export const cooccurrenceSpecificRelationships: Relationship[] = [
  { source: 'char-0', target: 'char-10', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-0', target: 'char-102', type: "Message-Carrying Page & Master", typeZh: "骑马传信小厮" },
  { source: 'char-0', target: 'char-159', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-0', target: 'char-2', type: "Chivalrous Cousin-Friend", typeZh: "侠义表兄与文会同道" },
  { source: 'char-0', target: 'char-23', type: "Literary Confidant & Performer", typeZh: "清高琴友与画中知音" },
  { source: 'char-0', target: 'char-25', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-26', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-27', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-28', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-29', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-3', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-0', target: 'char-30', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-4', type: "Maternal Cousin & Opera Host", typeZh: "表兄弟与戏曲文席同好" },
  { source: 'char-0', target: 'char-42', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-47', type: "Strict Confucian Father & Son", typeZh: "翰林严父与功名期望" },
  { source: 'char-0', target: 'char-48', type: "Imperial Official & Salon Scholar", typeZh: "朝廷官员与京师名士" },
  { source: 'char-0', target: 'char-86', type: "Protective Mother & Son", typeZh: "道德守护慈母与顺从子" },
  { source: 'char-0', target: 'char-90', type: "Betrothed Spouse & Literary Partner", typeZh: "诗文缔姻与正室伉俪" },
  { source: 'char-10', target: 'char-102', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-10', target: 'char-2', type: "Witty Tribute Student & Hongji Temple Peer", typeZh: "鸿济寺幽默拔贡与戏考同好" },
  { source: 'char-10', target: 'char-23', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-10', target: 'char-25', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-10', target: 'char-26', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-10', target: 'char-27', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-10', target: 'char-28', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-10', target: 'char-29', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-10', target: 'char-3', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-10', target: 'char-4', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-10', target: 'char-42', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-10', target: 'char-48', type: "Imperial Official & Salon Scholar", typeZh: "朝廷官员与京师名士" },
  { source: 'char-10', target: 'char-86', type: "Inner Household Lady & Scholar Cousin", typeZh: "闺阁内眷与文人表亲" },
  { source: 'char-102', target: 'char-2', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-102', target: 'char-23', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-102', target: 'char-25', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-102', target: 'char-26', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-102', target: 'char-27', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-102', target: 'char-28', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-102', target: 'char-4', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-102', target: 'char-42', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-102', target: 'char-48', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-102', target: 'char-86', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-159', target: 'char-23', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-2', target: 'char-23', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-2', target: 'char-25', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-2', target: 'char-26', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-2', target: 'char-27', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-2', target: 'char-28', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-2', target: 'char-29', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-2', target: 'char-3', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-2', target: 'char-30', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-2', target: 'char-4', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-2', target: 'char-42', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-2', target: 'char-47', type: "Imperial Official & Salon Scholar", typeZh: "朝廷官员与京师名士" },
  { source: 'char-2', target: 'char-48', type: "Imperial Official & Salon Scholar", typeZh: "朝廷官员与京师名士" },
  { source: 'char-2', target: 'char-86', type: "Inner Household Lady & Scholar Cousin", typeZh: "闺阁内眷与文人表亲" },
  { source: 'char-23', target: 'char-25', type: "Top Flower Rank Performers", typeZh: "花榜状元探花与画艺文友" },
  { source: 'char-23', target: 'char-26', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-23', target: 'char-27', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-23', target: 'char-28', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-23', target: 'char-29', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-23', target: 'char-3', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-23', target: 'char-30', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-23', target: 'char-4', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-23', target: 'char-42', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-23', target: 'char-48', type: "High Official & Opera Patron", typeZh: "高官达贵与堂名戏子" },
  { source: 'char-23', target: 'char-86', type: "Inner Household Lady & Invited Actor", typeZh: "内宅主母与受邀名伶" },
  { source: 'char-25', target: 'char-26', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-25', target: 'char-27', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-25', target: 'char-28', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-25', target: 'char-29', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-25', target: 'char-3', type: "Passionate Lover & Calligraphy Confidant", typeZh: "痴情金兰与书法知己" },
  { source: 'char-25', target: 'char-30', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-25', target: 'char-4', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-25', target: 'char-42', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-25', target: 'char-48', type: "High Official & Opera Patron", typeZh: "高官达贵与堂名戏子" },
  { source: 'char-25', target: 'char-86', type: "Inner Household Lady & Invited Actor", typeZh: "内宅主母与受邀名伶" },
  { source: 'char-26', target: 'char-27', type: "Lianzhu Troupe Musicians", typeZh: "联珠班笛师与乐艺琴友" },
  { source: 'char-26', target: 'char-28', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-26', target: 'char-29', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-26', target: 'char-3', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-26', target: 'char-30', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-26', target: 'char-4', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-26', target: 'char-48', type: "High Official & Opera Patron", typeZh: "高官达贵与堂名戏子" },
  { source: 'char-26', target: 'char-86', type: "Inner Household Lady & Invited Actor", typeZh: "内宅主母与受邀名伶" },
  { source: 'char-27', target: 'char-28', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-27', target: 'char-29', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-27', target: 'char-3', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-27', target: 'char-30', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-27', target: 'char-4', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-27', target: 'char-42', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-28', target: 'char-29', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-28', target: 'char-3', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-28', target: 'char-30', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-28', target: 'char-4', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-28', target: 'char-42', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-29', target: 'char-3', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-29', target: 'char-30', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-29', target: 'char-4', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-3', target: 'char-30', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-3', target: 'char-4', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-30', target: 'char-4', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-4', target: 'char-42', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-4', target: 'char-48', type: "Imperial Official & Salon Scholar", typeZh: "朝廷官员与京师名士" },
  { source: 'char-4', target: 'char-86', type: "Inner Household Lady & Scholar Cousin", typeZh: "闺阁内眷与文人表亲" },
  { source: 'char-42', target: 'char-86', type: "Inner Household Lady & Invited Actor", typeZh: "内宅主母与受邀名伶" },
  { source: 'char-47', target: 'char-86', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-48', target: 'char-86', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-0', target: 'char-1', type: "Platonic Soulmates", typeZh: "精神知己与生死契" },
  { source: 'char-0', target: 'char-112', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-0', target: 'char-121', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-0', target: 'char-21', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-0', target: 'char-24', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-31', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-5', type: "Parasitic Guest & Household Gossip", typeZh: "寄居造谣与家庭嫌隙" },
  { source: 'char-0', target: 'char-6', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-1', target: 'char-10', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-1', target: 'char-102', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-1', target: 'char-112', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-1', target: 'char-121', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-1', target: 'char-2', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-1', target: 'char-21', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-1', target: 'char-23', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-1', target: 'char-24', type: "High-Principled Allies & Redemption Strategists", typeZh: "机智助赎身之同道" },
  { source: 'char-1', target: 'char-26', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-1', target: 'char-27', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-1', target: 'char-28', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-1', target: 'char-29', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-1', target: 'char-31', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-1', target: 'char-4', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-1', target: 'char-47', type: "High Official & Opera Patron", typeZh: "高官达贵与堂名戏子" },
  { source: 'char-1', target: 'char-48', type: "High Official & Opera Patron", typeZh: "高官达贵与堂名戏子" },
  { source: 'char-1', target: 'char-5', type: "Scheming Hanger-on & Victim", typeZh: "利诱陷害与同路受害者" },
  { source: 'char-1', target: 'char-6', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-1', target: 'char-86', type: "Inner Household Lady & Invited Actor", typeZh: "内宅主母与受邀名伶" },
  { source: 'char-10', target: 'char-24', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-10', target: 'char-5', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-102', target: 'char-24', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-102', target: 'char-5', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-102', target: 'char-6', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-112', target: 'char-121', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-112', target: 'char-5', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-112', target: 'char-6', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-121', target: 'char-2', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-121', target: 'char-23', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-121', target: 'char-24', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-121', target: 'char-31', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-121', target: 'char-4', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-121', target: 'char-5', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-121', target: 'char-6', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-2', target: 'char-24', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-2', target: 'char-31', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-2', target: 'char-5', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-2', target: 'char-6', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-21', target: 'char-5', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-21', target: 'char-6', type: "Comic Targets & Matrilocal In-Laws", typeZh: "东园笑柄与招赘姻亲" },
  { source: 'char-23', target: 'char-24', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-23', target: 'char-31', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-23', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-23', target: 'char-6', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-24', target: 'char-26', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-24', target: 'char-27', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-24', target: 'char-28', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-24', target: 'char-29', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-24', target: 'char-31', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-24', target: 'char-4', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-24', target: 'char-48', type: "High Official & Opera Patron", typeZh: "高官达贵与堂名戏子" },
  { source: 'char-24', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-24', target: 'char-6', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-24', target: 'char-86', type: "Inner Household Lady & Invited Actor", typeZh: "内宅主母与受邀名伶" },
  { source: 'char-26', target: 'char-31', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-26', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-27', target: 'char-31', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-27', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-28', target: 'char-31', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-28', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-29', target: 'char-31', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-29', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-31', target: 'char-4', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-31', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-31', target: 'char-6', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-4', target: 'char-5', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-4', target: 'char-6', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-48', target: 'char-5', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-5', target: 'char-6', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-5', target: 'char-86', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-6', target: 'char-86', type: "Inner Household Lady & Scholar Cousin", typeZh: "闺阁内眷与文人表亲" },
  { source: 'char-0', target: 'char-119', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-0', target: 'char-123', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-0', target: 'char-32', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-53', type: "Imperial Official & Salon Scholar", typeZh: "朝廷官员与京师名士" },
  { source: 'char-0', target: 'char-56', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-72', type: "Persecutor of Qinyan & Depraved Merchant", typeZh: "逼迫琴言之市井恶少" },
  { source: 'char-1', target: 'char-119', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-1', target: 'char-123', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-1', target: 'char-32', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-1', target: 'char-56', type: "Troupe Master & Star Apprentice", typeZh: "师傅与摇钱树徒弟" },
  { source: 'char-1', target: 'char-72', type: "Depraved Merchant Harasser & Victim", typeZh: "纠缠逼迫之恶少与受害者" },
  { source: 'char-119', target: 'char-123', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-119', target: 'char-5', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-119', target: 'char-72', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-121', target: 'char-72', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-123', target: 'char-5', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-123', target: 'char-6', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-123', target: 'char-72', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-31', target: 'char-72', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-32', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-32', target: 'char-72', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-5', target: 'char-53', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-5', target: 'char-56', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-5', target: 'char-72', type: "Sycophantic Cronies & Opium/Gambling Partners", typeZh: "附势帮凶与烟赌同恶" },
  { source: 'char-56', target: 'char-72', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-56', target: 'char-86', type: "Inner Household Lady & Invited Actor", typeZh: "内宅主母与受邀名伶" },
  { source: 'char-6', target: 'char-72', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-72', target: 'char-86', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-0', target: 'char-15', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-0', target: 'char-7', type: "Yiyuan Salon Host & Guest", typeZh: "怡园雅集主宾与艺术知音" },
  { source: 'char-1', target: 'char-15', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-1', target: 'char-30', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-1', target: 'char-7', type: "Redeemer Patron & Mentor", typeZh: "重金赎身恩主与艺术知己" },
  { source: 'char-15', target: 'char-2', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-15', target: 'char-23', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-15', target: 'char-29', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-15', target: 'char-30', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-15', target: 'char-31', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-15', target: 'char-32', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-15', target: 'char-4', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-15', target: 'char-5', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-15', target: 'char-6', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-15', target: 'char-7', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-2', target: 'char-7', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-23', target: 'char-32', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-23', target: 'char-7', type: "Yiyuan Patron & Flower Champion", typeZh: "怡园主人与花榜状元知音" },
  { source: 'char-30', target: 'char-31', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-30', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-4', target: 'char-7', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-5', target: 'char-7', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-6', target: 'char-7', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-0', target: 'char-55', type: "Romantic Rival & Aristocratic Antagonist", typeZh: "夺琴之仇与贵戚宿敌" },
  { source: 'char-0', target: 'char-8', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-1', target: 'char-159', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-1', target: 'char-3', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-1', target: 'char-42', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-1', target: 'char-55', type: "Captor & Forcible Abduction Victim", typeZh: "强纳锦春园之霸占与受害者" },
  { source: 'char-1', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-112', target: 'char-55', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-119', target: 'char-2', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-119', target: 'char-23', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-119', target: 'char-55', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-119', target: 'char-8', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-121', target: 'char-55', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-121', target: 'char-8', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-159', target: 'char-55', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-2', target: 'char-55', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-2', target: 'char-72', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-2', target: 'char-8', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-23', target: 'char-55', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-23', target: 'char-72', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-23', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-3', target: 'char-5', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-3', target: 'char-55', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-3', target: 'char-72', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-3', target: 'char-8', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-30', target: 'char-55', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-30', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-31', target: 'char-55', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-31', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-32', target: 'char-55', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-4', target: 'char-55', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-4', target: 'char-72', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-4', target: 'char-8', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-42', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-42', target: 'char-55', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-42', target: 'char-72', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-42', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-5', target: 'char-55', type: "Sycophantic Parasite & Noble Patron", typeZh: "投机附势与奢靡公府" },
  { source: 'char-5', target: 'char-8', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-55', target: 'char-6', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-55', target: 'char-72', type: "Dissolute Noble & Depraved Merchant Allies", typeZh: "纨绔侯门与广东富商恶少" },
  { source: 'char-55', target: 'char-8', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-55', target: 'char-86', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-6', target: 'char-8', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-72', target: 'char-8', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-8', target: 'char-86', type: "Inner Household Lady & Scholar Cousin", typeZh: "闺阁内眷与文人表亲" },
  { source: 'char-0', target: 'char-11', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-0', target: 'char-14', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-0', target: 'char-9', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-1', target: 'char-11', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-1', target: 'char-14', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-1', target: 'char-25', type: "Loyal Allies in Qinyan Redemption", typeZh: "苦心促成重逢之盟友" },
  { source: 'char-1', target: 'char-9', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-10', target: 'char-11', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-10', target: 'char-55', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-10', target: 'char-72', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-10', target: 'char-9', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-102', target: 'char-55', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-11', target: 'char-14', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-11', target: 'char-2', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-11', target: 'char-23', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-11', target: 'char-25', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-11', target: 'char-26', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-11', target: 'char-27', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-11', target: 'char-4', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-11', target: 'char-48', type: "Imperial Official & Salon Scholar", typeZh: "朝廷官员与京师名士" },
  { source: 'char-11', target: 'char-5', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-11', target: 'char-55', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-11', target: 'char-6', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-11', target: 'char-72', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-11', target: 'char-9', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-123', target: 'char-55', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-14', target: 'char-23', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-14', target: 'char-5', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-14', target: 'char-55', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-2', target: 'char-9', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-23', target: 'char-9', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-25', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-25', target: 'char-55', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-25', target: 'char-6', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-25', target: 'char-72', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-25', target: 'char-9', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-26', target: 'char-55', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-26', target: 'char-72', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-26', target: 'char-9', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-27', target: 'char-55', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-27', target: 'char-72', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-27', target: 'char-9', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-3', target: 'char-9', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-4', target: 'char-9', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-48', target: 'char-55', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-48', target: 'char-9', type: "Imperial Official & Salon Scholar", typeZh: "朝廷官员与京师名士" },
  { source: 'char-5', target: 'char-9', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-55', target: 'char-9', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-6', target: 'char-9', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-72', target: 'char-9', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-86', target: 'char-9', type: "Inner Household Lady & Scholar Cousin", typeZh: "闺阁内眷与文人表亲" },
  { source: 'char-0', target: 'char-141', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-1', target: 'char-141', type: "Adoptive Father & Spiritual Master", typeZh: "屈道翁义父与琴仙宗师" },
  { source: 'char-10', target: 'char-141', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-141', target: 'char-2', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-141', target: 'char-23', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-141', target: 'char-24', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-141', target: 'char-25', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-141', target: 'char-26', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-141', target: 'char-27', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-141', target: 'char-3', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-141', target: 'char-4', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-141', target: 'char-9', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-24', target: 'char-25', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-24', target: 'char-3', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-24', target: 'char-9', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-139', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-0', target: 'char-75', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-1', target: 'char-139', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-1', target: 'char-75', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-11', target: 'char-121', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-11', target: 'char-31', type: "Grand Secretary Nephew & Opera Patron", typeZh: "阁学之侄与名伶追捧者" },
  { source: 'char-121', target: 'char-9', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-139', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-31', target: 'char-9', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-45', target: 'char-5', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-5', target: 'char-75', type: "Sycophantic Cronies & Opium Partners", typeZh: "投机帮凶与烟赌恶少" },
  { source: 'char-10', target: 'char-8', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-102', target: 'char-8', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-11', target: 'char-28', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-11', target: 'char-8', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-121', target: 'char-25', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-141', target: 'char-28', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-141', target: 'char-8', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-25', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-26', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-27', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-28', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-28', target: 'char-9', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-8', target: 'char-9', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-10', target: 'char-7', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-25', target: 'char-7', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-55', target: 'char-7', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-7', target: 'char-8', type: "Yiyuan Designers & Polymath Intimates", typeZh: "怡园营造同道与莫逆之交" },
  { source: 'char-7', target: 'char-9', type: "Banquet Host & Yiyuan Patron", typeZh: "侍郎之子与怡园主客" },
  { source: 'char-11', target: 'char-15', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-11', target: 'char-24', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-14', target: 'char-15', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-14', target: 'char-24', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-15', target: 'char-24', type: "Romantic Soulmates & Exam Laureate", typeZh: "情投意合与状元知己" },
  { source: 'char-15', target: 'char-25', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-15', target: 'char-26', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-15', target: 'char-3', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-15', target: 'char-8', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-15', target: 'char-86', type: "Inner Household Lady & Scholar Cousin", typeZh: "闺阁内眷与文人表亲" },
  { source: 'char-15', target: 'char-9', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-23', target: 'char-56', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-24', target: 'char-30', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-24', target: 'char-56', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-24', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-25', target: 'char-56', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-30', target: 'char-9', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-48', target: 'char-8', type: "Imperial Official & Salon Scholar", typeZh: "朝廷官员与京师名士" },
  { source: 'char-56', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-119', target: 'char-25', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-119', target: 'char-9', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-55', target: 'char-56', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-0', target: 'char-137', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-1', target: 'char-137', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-10', target: 'char-15', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-139', target: 'char-24', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-15', target: 'char-27', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-15', target: 'char-28', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-25', target: 'char-31', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-29', target: 'char-8', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-29', target: 'char-9', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-11', target: 'char-42', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-11', target: 'char-7', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-15', target: 'char-42', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-15', target: 'char-55', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-15', target: 'char-72', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-24', target: 'char-32', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-24', target: 'char-42', type: "Troupe Performers & Flower Rank Peers", typeZh: "花榜名伶与同台场友" },
  { source: 'char-24', target: 'char-55', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-24', target: 'char-7', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-24', target: 'char-72', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-7', target: 'char-72', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-28', target: 'char-55', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-28', target: 'char-72', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-29', target: 'char-55', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-29', target: 'char-72', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-15', target: 'char-75', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-2', target: 'char-75', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-23', target: 'char-75', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-24', target: 'char-75', type: "Harassed Performer & Entangled Villain", typeZh: "名伶与纠缠市井恶少" },
  { source: 'char-75', target: 'char-8', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-119', target: 'char-15', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
  { source: 'char-119', target: 'char-24', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-119', target: 'char-75', type: "Shared Chapter Co-presence", typeZh: "同回目场景交集" },
  { source: 'char-72', target: 'char-75', type: "Dissolute Monk & Opium Den Partners", typeZh: "宏济寺酒肉和尚与烟赌同伙" },
  { source: 'char-141', target: 'char-15', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-141', target: 'char-55', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-141', target: 'char-72', type: "Literary Circle & Parasitic Villain", typeZh: "雅集名士与投机恶少" },
  { source: 'char-0', target: 'char-17', type: "Senior Literary Arbiter & Historian", typeZh: "文坛耆宿与结语名士" },
  { source: 'char-1', target: 'char-17', type: "Literary Patron & Opera Performer", typeZh: "雅集名士与应酬名伶" },
  { source: 'char-141', target: 'char-17', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-15', target: 'char-17', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-17', target: 'char-8', type: "Yiyuan Salon Scholar Peers", typeZh: "怡园雅集同道文人" },
  { source: 'char-119', target: 'char-141', type: "Household Retainer & Scholar Master", typeZh: "府上跟班与京师名士" },
];
