/** English work/opera titles and Chinese-key mappings for glow + italic. */
export const ENGLISH_WORK_TITLES = [
  "Examination of Era Names from Five Dynasties and North–South",
  "Green Pearl Throws Herself from the Golden Valley Garden",
  "Li the Banished Immortal Receives the Edict at Yelang",
  "Selling One's Son to Cast Himself into the Abyss",
  "Longing for One's Parents, Abandoning the Feast",
  "Pan Jinlian Teases Her Uncle-in-Law in the Snow",
  "Seeing Lord Wang of Xiangyuan Home to His Villa",
  "Consort Yang Follows the Carriage at Mawei Post",
  "A Stroll in the Garden and Waking from a Dream",
  "Du the Remonstrator Honored in the Golden Hall",
  "On Rectifying the Root and Clearing the Source",
  "Court Poem on Snow on Human Day in the Garden",
  "Complete Library of Ancient and Modern Books",
  "Raising a Ruckus at Court, Pouncing on a Dog",
  "In the Style of Du Fu's Northern Expedition",
  "Inquiry into the Six-Department Regulations",
  "Essential Techniques for the Common People",
  "On Phoenix Terrace Remembering the Flute.",
  "Longing for Parents, Abandoning the Feast",
  "Unofficial Biography of the Noble Consort",
  "Linked-Needle and Continuous-Hemp Command",
  "Stele for Repairing the Confucius Temple",
  "On the Pros and Cons of Salt Law Reforms",
  "Searching the Mountain, Driving the Cart",
  "Picture of the Immortals' Grand Assembly",
  "Attacking the Inn; Stealing the Chicken",
  "New Songs from the Jade Terrace Preface",
  "Admonishing the Son with a Single Saber",
  "Parting from Mother amid Flying Arrows",
  "Preface to the Pavilion of Prince Teng",
  "Flower-Viewing Assembly on the Qinhuai",
  "Rainbow Skirt and Feathered-Robe Dance",
  "Confucius Temple Ritual Vessels Stele",
  "Courtyard of Cloud-Recline Fragrance",
  "Three Variations on the Plum Blossom",
  "Ballad of Lady Gongsun's Sword Dance",
  "Bibliographic Treatise of the Hanshu",
  "Posthumous Writings of Fragrant Snow",
  "Precious Mirror for Judging Flowers",
  "Pavilion of Wind-and-Dew Quiet Song",
  "The Awakening from Sleep Collection",
  "Night Banquet Bestowing a Courtesan",
  "Purification Rite on the Long River",
  "Autumn Beats Upon the Painted Hall",
  "Wild Geese Alighting on Level Sand",
  "Red Slave Trimming the Silver Lamp",
  "Rhapsody on the Goddess of the Luo",
  "Ascending the Xiangyang City Tower",
  "Immortal Chen Tuan Attains the Way",
  "Rhapsodies on Categorized Affairs",
  "Picture of Shouyang Forehead Dots",
  "Borrowing an Umbrella on the Lake",
  "Abridged Ministry of Rites Rhymes",
  "Song of a Beauty Combing Her Hair",
  "Han Changli's South Mountain Poem",
  "Biography of Master Fragrant Snow",
  "Cherishing What's Left of Spring",
  "Ancient Fragrance Woodland Lodge",
  "Harmonious Grade Among Immortals",
  "Pine, Crane and Cinnabar Chamber",
  "The Crow Has Eight or Nine Young",
  "Picture of Worshipping the Stone",
  "Spring Dawn in the Grotto Heaven",
  "Four Dreams of the Jade Tea Hall",
  "Young Gallants Gathering Clients",
  "Clustered Cassia Mountain Lodge",
  "Pavilion of Spring Breeze Drunk",
  "Autumn-Chant Waterside Pavilion",
  "Transmission of the Lamp Record",
  "Epitaph of the Works Department",
  "Eighteen Songs of a Nomad Flute",
  "Affixing the Kingfisher Command",
  "Congratulations on the New Cool",
  "Eight Odes from the Snow Window",
  "Splendid Grade Among Immortals",
  "Cease-Cloud Tell-Rain Pavilion",
  "Seek-the-Stream Immortal Villa",
  "Rhapsody on the Three Capitals",
  "Records of the Grand Historian",
  "Farewell at the Garden of Ease",
  "Bright Consort Enters the Pass",
  "Stele Sacrificing to Confucius",
  "Nine Works from Red Snow Tower",
  "Paying Respects to the Teacher",
  "Rhyme Treasury Jade Collection",
  "Preface to the Garden of Ease",
  "Sable Coat Exchanged for Wine",
  "Escaped Grade Among Immortals",
  "Leader of the Immortal Circle",
  "Upright Grade Among Immortals",
  "The Opera Stage Flower Manual",
  "Exegesis of the Five Classics",
  "Taichi Elbow-Backup Formulary",
  "Bright Consort Returns to Han",
  "Sequel to the Western Chamber",
  "Joyous Grade Among Immortals",
  "Heart-of-Stamen Pearl Palace",
  "The Envoy Receives the Edict",
  "Miscellaneous Secret Affairs",
  "Ballad of a Luoyang Daughter",
  "Record of Strange Gatherings",
  "Upper Grade Among Immortals",
  "Witty Grade Among Immortals",
  "Mid-Autumn to Zhang Gongcao",
  "Lofty Grade Among Immortals",
  "Sword Dance of Lady Gongsun",
  "Too Lazy to Paint the Brows",
  "Arts and Literature Preface",
  "Inscription on Jinqiu Mound",
  "Cases of the Dragon Diagram",
  "Judgment in the Underworld",
  "Stealing the Command Token",
  "Wild Grade Among Immortals",
  "Yellow-Fragrance East Plot",
  "The Crouching Tiger Scroll",
  "Bold Grade Among Immortals",
  "Song of Everlasting Sorrow",
  "Cool Tranquil Poetic Realm",
  "Sacrificing to the Flowers",
  "Luofu on the Mulberry Path",
  "Fine Night, Wind and Moon",
  "Dream of the Plum Blossom",
  "Stele Urging Enthronement",
  "Rhapsody on Mount Tiantai",
  "On the Moon, with Feeling",
  "Travel Drafts from Yantai",
  "Revolving Brocade Picture",
  "Immortals' Grand Assembly",
  "Removing the Cloth Jacket",
  "Section by Section Higher",
  "Meeting the Capital Envoy",
  "Accumulate-Jade Pavilion",
  "Dream of the Red Chamber",
  "Terrifying the Simpleton",
  "The Willow Floss Terrace",
  "Appreciating the Lotuses",
  "Plucking a Willow Branch",
  "Dancing with the Platter",
  "Tang Poems Three Hundred",
  "The Pavilion of Gossamer",
  "also known as He Xinlang",
  "Ballad of the Army Carts",
  "Winning the Flower Queen",
  "Interrogating the Beauty",
  "Ministry of Rites Rhymes",
  "Bronze Plate Inscription",
  "Integrated Rhyme Studies",
  "Hall of Quiet Blessings",
  "Lone Boat on the Stream",
  "Encountering Sorrow",
  "Returning from the Hunt",
  "Visiting Hengyue Temple",
  "Lady Ding's Ten Laments",
  "Double Seventh Festival",
  "Three-Character Classic",
  "Knight-Errant in Hiding",
  "Record of the South Sea",
  "Lament on the Riverbank",
  "Immortals of Mount Emei",
  "Cases of Magistrate Shi",
  "Consort Yang Enters Shu",
  "Policy on River Control",
  "Lantern and Moon Lyrics",
  "Prince Dan Destroys Qin",
  "Yantai Flower Selection",
  "Sleeping amid Fragrance",
  "Song of the Stone Drums",
  "Rhapsody on the Goddess",
  "Looking at the Stocking",
  "Empty Valley Fragrance",
  "Red Tea Immortal Lodge",
  "Feast in Clear Capital",
  "Admonishing the Prince",
  "Declining the Pavilion",
  "Flirting with a Zither",
  "Sobering the Courtesan",
  "Li Ling Returns to Han",
  "Searching in the Dream",
  "The Liangzhou Prologue",
  "Essay on the Great Man",
  "Visiting the Courtyard",
  "Slow Magnolia Blossoms",
  "Sound of Geese Passing",
  "The Peach Blossom Fan",
  "The Classic of Poetry",
  "The Flying Bear Dream",
  "Chasing the Messenger",
  "Frightening the Clown",
  "Picking Up a Painting",
  "Startled from a Dream",
  "Immortal by the River",
  "Crows Crying at Night",
  "Lament for the Prince",
  "Female Ballad-Singing",
  "Prelude to Water Tune",
  "Snow on River and Sky",
  "Three Beats of Yuyang",
  "Demanding the Hairpin",
  "Leaping into the Well",
  "One Stretch of Cloud",
  "Treading on the Moon",
  "Tumbling in the Snow",
  "Refining Autumn Loft",
  "Catalogue of Flowers",
  "Misty Faint Pavilion",
  "Selection of Flowers",
  "Stealing the Chicken",
  "Plucking the Eyebrow",
  "East Wind Last Night",
  "Duping the Ding Clan",
  "Four-Tone Cut Rhymes",
  "Great Music Rhapsody",
  "Great Rites Rhapsody",
  "Mount Yi Inscription",
  "Exclusive Possession",
  "Jade Terrace Preface",
  "Stone to Mend Heaven",
  "Discussing the Sword",
  "Visiting Lu Hongjian",
  "Wine Shop at Jinling",
  "Brocade-Wrapped Road",
  "Kneeling at the Pool",
  "The Female Musician",
  "Snapping the Willow",
  "Killing in the Boat",
  "Brocade Tent Spring",
  "Waking from a Dream",
  "Composing on a Song",
  "Red-Snow West Manor",
  "Assassinating Liang",
  "Watching a Painting",
  "Inscribing the Song",
  "Dancing on the Tray",
  "Beauty Combing Hair",
  "The Barbarian Child",
  "The Buddhist Healer",
  "Sealing the Chamber",
  "The Drunken Consort",
  "Composing the Verse",
  "Waking and Sleeping",
  "Northern Expedition",
  "Composing the Score",
  "Revising the Letter",
  "Supporting the Head",
  "Picking Up the Gold",
  "Flinging the Dipper",
  "Three Hundred Poems",
  "Do Not Wash the Red",
  "Selling the Hairpin",
  "Stele of Abdication",
  "Shi Clan Supplement",
  "Great Hunt Rhapsody",
  "Breaking the Willow",
  "Willow at Yang Pass",
  "Draft Tang Memorial",
  "Lifting the Curtain",
  "Bright Pearl Record",
  "Waves Scouring Sand",
  "Moon over Mount Gou",
  "Appreciating Autumn",
  "Dreaming of Li Bai",
  "Subduing the Tiger",
  "Little Red Citadel",
  "Falling on the Ice",
  "Peach-Blossom Cove",
  "The Infernal Judge",
  "Chrysanthemum Beds",
  "Stealing the Token",
  "Mountain Fragrance",
  "Lotus-Picking Song",
  "Twenty-Two Masters",
  "Releasing the Easy",
  "Singing the Ballad",
  "Entrusting the Son",
  "Airs of the States",
  "The Monastery Gate",
  "Pursuing the Dream",
  "Golden-Thread Song",
  "Departing the Soul",
  "High Sunny Terrace",
  "The Piteous Appeal",
  "Borrowing the Boot",
  "Eight-Tone Ganzhou",
  "Seizing the Beauty",
  "A Spray of Flowers",
  "Stored Admonitions",
  "Hundred Yuan Plays",
  "Entering the Dream",
  "Underworld Inquest",
  "Dividing the Shoes",
  "Ten Kinds of Songs",
  "Chattering Command",
  "Book of Lord Shang",
  "Startled by Change",
  "Spring Palace Song",
  "Peach Blossom Song",
  "Autumn at the Tray",
  "Book of Yue Annals",
  "Sending Red Thread",
  "Silver Button Silk",
  "Classic of Poetry",
  "The Five Classics",
  "Slaying the Tiger",
  "Searching the Cup",
  "Thirteen Classics",
  "Heartbreak Lyrics",
  "Preface to Yiyuan",
  "Book of Documents",
  "Double Red Record",
  "Setting the Score",
  "Stealing the Poem",
  "Poetic Categories",
  "Breaking the Loom",
  "Feigning Jealousy",
  "Hearing the Bells",
  "Sweeping Away Qin",
  "Sweeping the Pine",
  "Attacking the Inn",
  "The Small Banquet",
  "The Mountain Gate",
  "Three Times Drunk",
  "Nine-Palace Score",
  "Nine Linked Rings",
  "Stealing the Song",
  "Going on the Hunt",
  "Ten Non-Idle Acts",
  "Counter-Deception",
  "Book of Later Han",
  "Ode to Lord Zhang",
  "Annoying the Lord",
  "Peerless Register",
  "Cao Jingwan Stele",
  "Rolling Silk Ball",
  "Story of the Pipa",
  "Complete Library",
  "Pawned Headscarf",
  "Power and Profit",
  "Piercing the Eye",
  "Visiting the Rat",
  "Cutting the Foot",
  "The Jade Terrace",
  "Sweeping Flowers",
  "Fleeing the Pass",
  "Qin's Temptation",
  "Burying the Jade",
  "Forgetting Death",
  "Grass Chancellor",
  "Pavilion Meeting",
  "Bell in the Rain",
  "Drunk in Penglai",
  "Seeing the Ghost",
  "The Stone Grotto",
  "Raven-Roost Song",
  "Fifth-Watch Bell",
  "Liangzhou Melody",
  "Prior Enticement",
  "Later Enticement",
  "Rhapsody on Lust",
  "Fixing Affection",
  "Little Peach Red",
  "Zhaojun's Lament",
  "Clear Peace Tune",
  "Classic of Birds",
  "Pieced White Fur",
  "Mount Heng Stele",
  "Driving the Cart",
  "Heavenly Consort",
  "Collected Rhymes",
  "Rhapsody on Snow",
  "Rhyme Supplement",
  "Besotted Maiden",
  "Clear Peace Joy",
  "Removing Armour",
  "Book of Changes",
  "The Palace of Eternal Life",
  "Flower Register",
  "Water-Tune Song",
  "West-River Moon",
  "Stealing Poetry",
  "Splashing Gruel",
  "Stealing a Poem",
  "Opening the Eye",
  "A Trace of Sand",
  "The Three Tomes",
  "Record of Music",
  "Orchid Pavilion",
  "Ancient Cypress",
  "Sending the Fan",
  "Expanded Rhymes",
  "Draft Han Edict",
  "Moon Rises High",
  "Gazing at Jimen",
  "Narcissus Lyric",
  "Capturing Alive",
  "Barbarian Child",
  "White Snow Song",
  "Mutual Scolding",
  "Hiding the Boat",
  "Viewing Flowers",
  "Walking in Snow",
  "Galloping Horse",
  "Horse-Head Tune",
  "Peeking at Bath",
  "Little Banquet",
  "The Four Books",
  "Pinhua Baojian",
  "Pass Qin Tower",
  "The Green Gate",
  "Rainbow Skirts",
  "The Rendezvous",
  "The Secret Vow",
  "Floss Pavilion",
  "South Mountain",
  "Great Learning",
  "Hidden Marvels",
  "History of Jin",
  "Mulberry Grove",
  "The Swallow Letter",
  "Secret Affairs",
  "Circular Edict",
  "Zhuge Yan Nian",
  "Boudoir Lament",
  "Rhyme Assembly",
  "Title Register",
  "Qin Courtship",
  "Magpie Bridge",
  "Female Bandit",
  "Book of Songs",
  "Killing Xishi",
  "Hearing Bells",
  "The Tea-House",
  "Stealing Song",
  "Teaching Song",
  "Powerful Monk",
  "The Rice-Shop",
  "Small Banquet",
  "Qutai Huaxuan",
  "The Southern Shore",
  "Merit Banquet",
  "Finest of Ancient Prose",
  "Book of Shang",
  "Whirling Wind",
  "Palace Lyrics",
  "To Censor Han",
  "Zuo Tradition",
  "Calendar Book",
  "The River Runs Red",
  "Cutting Cloth",
  "Poetic Rhymes",
  "Golden Thread",
  "Long Yearning",
  "Sound of Snow",
  "Snow Mountain",
  "Jade Terrace",
  "Chezhong Ren",
  "Liangzhou Xu",
  "Young Wander",
  "Finding Gold",
  "Hinny Bandit",
  "Jealous Qiao",
  "Female Thief",
  "Eating Chaff",
  "Spring Sleep",
  "Songs of Chu",
  "Romance of the Three Kingdoms",
  "Luoyang Girl",
  "Like a Dream",
  "Checking Han",
  "Grass Bridge",
  "Twelve Hours",
  "Jin Ping Mei",
  "Autumn River",
  "Willow Tower",
  "Yiqing Yishi",
  "Water Margin",
  "Two Capitals",
  "Opening Aria",
  "Book of Tang",
  "Night Yellow",
  "Mount Tianmu",
  "Closing Aria",
  "Cypress Beam",
  "Zhen and Wei",
  "Stately Lady",
  "Grass Ground",
  "Mochou's Joy",
  "Visiting Cui",
  "Jinling Song",
  "Hemp Ground",
  "Flower Drum",
  "Orchid Path",
  "Lychee Lane",
  "Long Regret",
  "Flower Lady",
  "Visiting Su",
  "Yan Ge Xing",
  "Wine Tavern",
  "Wu Mountain",
  "Bright Moon",
  "Pine Shrine",
  "Tang poetry",
  "Shanglin Fu",
  "Nine Mounds",
  "Ode on Snow",
  "Tang Rhymes",
  "Clear Peace",
  "Road to Shu",
  "Snow Pagoda",
  "Snow Screen",
  "Snow Shadow",
  "Snow Beauty",
  "Power Monk",
  "The Tavern",
  "In Search of the Supernatural",
  "earth-lamb",
  "Red Maiden",
  "Secret Vow",
  "The Peony Pavilion",
  "Wine Tower",
  "The Western Chamber",
  "Fire Judge",
  "Cut Rhymes",
  "Four Tones",
  "Four Books",
  "Level Sand",
  "River Full",
  "Oily Gourd",
  "Snow Arhat",
  "Yuchi Cup",
  "Naozhuang",
  "Plum Cove",
  "Yu Bao Du",
  "Male Monk",
  "Song of the Pipa",
  "Book Shop",
  "Rain Bell",
  "Crabapple",
  "Hard Road",
  "Yang Pass",
  "Snow Mood",
  "Snow Lamp",
  "Snow Lion",
  "Han Stele",
  "Record of Strange Things",
  "Xiaoshao",
  "Strange Tales from a Chinese Studio",
  "Rhapsody on the Red Cliff",
  "Journey to the West",
  "Jinlü Qu",
  "Liu Tang",
  "Midnight",
  "Untitled",
  "Snow Cat",
  "Snow Hue",
  "Mao Shi",
  "Yanggao",
  "Nishang",
  "Pan Qiu",
  "Guofeng",
  "Ice Bed",
  "Zixu Fu",
  "Mencius",
  "History of the Former Han",
  "Poetry",
  "Eulogy",
  "Yutai",
  "Liji",
  "Odes",
] as const;

export const ENGLISH_WORK_TITLE_SET = new Set<string>(ENGLISH_WORK_TITLES);

/**
 * Documented false positives when English titles are matched as bare substrings.
 * Chapter English uses isolated match `(?<!\w)title(?!\w)` (longest titles first).
 */
export const ENGLISH_WORK_WRONG_SUBSTRING_MATCHES = [
  { title: 'Odes', exampleWord: 'modesty', note: 'Ch.1: "humble modesty" must not highlight 雅' },
  { title: 'Odes', exampleWord: 'modestly', note: 'Ch.59 and elsewhere' },
  { title: 'Odes', exampleWord: 'false modesty', note: 'Ch.60' },
] as const;

/** Exact English phrasing in aligned translations, keyed by 《…》 inner text. */
export const WORK_ENGLISH_BY_CHINESE: Record<string, string> = {
  "哀江头": "Lament on the Riverbank",
  "哀王孙": "Lament for the Prince",
  "八月十五夜赠张功曹": "Mid-Autumn to Zhang Gongcao",
  "拔眉": "Plucking the Eyebrow",
  "白雪歌": "White Snow Song",
  "柏梁": "Cypress Beam",
  "拜石图": "Picture of Worshipping the Stone",
  "北征": "Northern Expedition",
  "别母乱箭": "Parting from Mother amid Flying Arrows",
  "冰床": "Ice Bed",
  "兵车行": "Ballad of the Army Carts",
  "补天石": "Stone to Mend Heaven",
  "裁衣": "Cutting Cloth",
  "采莲歌": "Lotus-Picking Song",
  "采莲曲": "Lotus-Picking Song",
  "藏舟": "Hiding the Boat",
  "曹景完碑": "Cao Jingwan Stele",
  "草地": "Grass Ground",
  "草桥": "Grass Bridge",
  "草相": "Grass Chancellor",
  "茶房": "The Tea-House",
  "车中人": "Chezhong Ren",
  "陈抟得道仙翁": "Immortal Chen Tuan Attains the Way",
  "吃糠": "Eating Chaff",
  "赤壁赋": "Rhapsody on the Red Cliff",
  "出猎": "Going on the Hunt",
  "储谏": "Stored Admonitions",
  "楚词": "Songs of Chu",
  "传灯录": "Transmission of the Lamp Record",
  "春宫曲": "Spring Palace Song",
  "春睡": "Spring Sleep",
  "辞阁": "Declining the Pavilion",
  "刺虎": "Slaying the Tiger",
  "刺梁": "Assassinating Liang",
  "刺目": "Opening the Eye",
  "打店": "Attacking the Inn",
  "打店偷鸡": "Attacking the Inn; Stealing the Chicken",
  "大乐赋": "Great Music Rhapsody",
  "大礼赋": "Great Rites Rhapsody",
  "大人先生论": "Essay on the Great Man",
  "大搜赋": "Great Hunt Rhapsody",
  "大学": "Great Learning",
  "弹词": "Singing the Ballad",
  "当巾": "Pawned Headscarf",
  "挡汉": "Checking Han",
  "叨叨令": "Chattering Command",
  "盗令": "Stealing the Token",
  "灯月词": "Lantern and Moon Lyrics",
  "登襄城楼": "Ascending the Xiangyang City Tower",
  "跌雪": "Tumbling in the Snow",
  "丁娘十索": "Lady Ding's Ten Laments",
  "顶针续麻令": "Linked-Needle and Continuous-Hemp Command",
  "定情": "Fixing Affection",
  "洞天春晓": "Spring Dawn in the Grotto Heaven",
  "独占": "Exclusive Possession",
  "杜拾遗金殿承恩": "Du the Remonstrator Honored in the Golden Hall",
  "断肠词": "Heartbreak Lyrics",
  "断机": "Breaking the Loom",
  "堕冰": "Falling on the Ice",
  "峨嵋山群仙": "Immortals of Mount Emei",
  "番儿": "Barbarian Child",
  "反诳": "Counter-Deception",
  "饭店": "The Rice-Shop",
  "访翠": "Visiting Cui",
  "访陆鸿渐": "Visiting Lu Hongjian",
  "访鼠": "Visiting the Rat",
  "访素": "Visiting Su",
  "放易": "Releasing the Easy",
  "飞熊梦": "The Flying Bear Dream",
  "分鞋": "Dividing the Shoes",
  "封房": "Sealing the Chamber",
  "逢入京使": "Meeting the Capital Envoy",
  "伏虎": "Subduing the Tiger",
  "伏虎韬": "The Crouching Tiger Scroll",
  "佛医": "The Buddhist Healer",
  "扶头": "Supporting the Head",
  "改书": "Revising the Letter",
  "赶车": "Driving the Cart",
  "诰圆": "Circular Edict",
  "工部墓志": "Epitaph of the Works Department",
  "公孙大娘舞剑器": "Sword Dance of Lady Gongsun",
  "公孙大娘舞剑器行": "Ballad of Lady Gongsun's Sword Dance",
  "功宴": "Merit Banquet",
  "宫词": "Palace Lyrics",
  "缑山月": "Moon over Mount Gou",
  "古柏行": "Ancient Cypress",
  "古今图书集成": "Complete Library",
  "古文观止": "Finest of Ancient Prose",
  "观画": "Watching a Painting",
  "广韵": "Expanded Rhymes",
  "闺怨": "Boudoir Lament",
  "贵妃外传": "Unofficial Biography of the Noble Consort",
  "跪池": "Kneeling at the Pool",
  "滚绣球": "Rolling Silk Ball",
  "国风": "Airs of the States",
  "海棠": "Crabapple",
  "韩碑": "Han Stele",
  "韩昌黎南山诗": "Han Changli's South Mountain Poem",
  "汉书": "History of the Former Han",
  "汉书艺文志": "Bibliographic Treatise of the Hanshu",
  "好色赋": "Rhapsody on Lust",
  "河满子": "River Full",
  "贺新凉": "Congratulations on the New Cool",
  "衡岳碑": "Mount Heng Stele",
  "哄丁": "Duping the Ding Clan",
  "红楼": "Dream of the Red Chamber",
  "红楼梦": "Dream of the Red Chamber",
  "红雪楼九种": "Nine Works from Red Snow Tower",
  "后汉书": "Book of Later Han",
  "后诱": "Later Enticement",
  "胡笳十八拍": "Eighteen Songs of a Nomad Flute",
  "胡筋十八拍": "Eighteen Songs of a Nomad Flute",
  "花鼓": "Flower Drum",
  "花婆": "Flower Lady",
  "花谱": "Catalogue of Flowers",
  "花选": "Selection of Flowers",
  "回风": "Whirling Wind",
  "回猎": "Returning from the Hunt",
  "活捉": "Capturing Alive",
  "火判": "Fire Judge",
  "集异记": "Record of Strange Gatherings",
  "集韵": "Collected Rhymes",
  "寄韩谏议": "To Censor Han",
  "寄扇": "Sending the Fan",
  "寄子": "Entrusting the Son",
  "祭花": "Sacrificing to the Flowers",
  "见鬼": "Seeing the Ghost",
  "江天雪": "Snow on River and Sky",
  "教歌": "Teaching Song",
  "节节高": "Section by Section Higher",
  "结客少年场": "Young Gallants Gathering Clients",
  "借靴": "Borrowing the Boot",
  "金谷园绿珠投楼": "Green Pearl Throws Herself from the Golden Valley Garden",
  "金陵酒肆": "Wine Shop at Jinling",
  "金陵曲": "Jinling Song",
  "金缕": "Golden Thread",
  "金缕曲": "also known as He Xinlang",
  "金瓶梅": "Jin Ping Mei",
  "锦缠道": "Brocade-Wrapped Road",
  "晋史": "History of Jin",
  "惊变": "Startled by Change",
  "惊丑": "Frightening the Clown",
  "惊梦": "Waking from a Dream",
  "九宫谱": "Nine-Palace Score",
  "九连环": "Nine Linked Rings",
  "九丘": "Nine Mounds",
  "酒楼": "The Tavern",
  "钧天": "Heavenly Consort",
  "开眼": "Opening the Eye",
  "看袜": "Looking at the Stocking",
  "拷艳": "Interrogating the Beauty",
  "空谷香": "Empty Valley Fragrance",
  "孔庙礼器碑": "Confucius Temple Ritual Vessels Stele",
  "窥浴": "Peeking at Bath",
  "兰亭": "Orchid Pavilion",
  "懒画眉": "Too Lazy to Paint the Brows",
  "浪淘沙": "Waves Scouring Sand",
  "乐记": "Record of Music",
  "离魂": "Departing the Soul",
  "离骚": "Encountering Sorrow",
  "礼部韵": "Ministry of Rites Rhymes",
  "礼部韵略": "Abridged Ministry of Rites Rhymes",
  "礼记": "Liji",
  "李陵返汉": "Li Ling Returns to Han",
  "李谪仙夜郎奉诏": "Li the Banished Immortal Receives the Edict at Yelang",
  "良宵风月图": "Fine Night, Wind and Moon",
  "凉州曲": "Liangzhou Melody",
  "梁州序": "The Liangzhou Prologue",
  "两京": "Two Capitals",
  "聊斋": "Strange Tales from a Chinese Studio",
  "临江仙": "Immortal by the River",
  "刘唐": "Liu Tang",
  "龙图公案": "Cases of the Dragon Diagram",
  "罗敷陌上桑": "Luofu on the Mulberry Path",
  "洛神赋": "Rhapsody on the Goddess of the Luo",
  "洛阳女儿行": "Ballad of a Luoyang Daughter",
  "麻地": "Hemp Ground",
  "马头调": "Horse-Head Tune",
  "马嵬驿杨妃随驾": "Consort Yang Follows the Carriage at Mawei Post",
  "埋玉": "Burying the Jade",
  "卖钗": "Selling the Hairpin",
  "卖子投渊": "Selling One's Son to Cast Himself into the Abyss",
  "满江红": "The River Runs Red",
  "毛诗": "Mao Shi",
  "梅花梦": "Dream of the Plum Blossom",
  "梅花三弄": "Three Variations on the Plum Blossom",
  "美人梳头歌": "Song of a Beauty Combing Her Hair",
  "孟子": "Mencius",
  "梦太白": "Dreaming of Li Bai",
  "秘辛": "Secret Affairs",
  "密誓": "The Secret Vow",
  "眠香": "Sleeping amid Fragrance",
  "明妃归汉": "Bright Consort Returns to Han",
  "明妃入关": "Bright Consort Enters the Pass",
  "明珠记": "Bright Pearl Record",
  "冥勘": "Underworld Inquest",
  "冥判": "The Infernal Judge",
  "莫愁乐": "Mochou's Joy",
  "牡丹亭": "The Peony Pavilion",
  "木兰花慢": "Slow Magnolia Blossoms",
  "南海记": "Record of the South Sea",
  "南浦": "The Southern Shore",
  "南山": "South Mountain",
  "恼公": "Annoying the Lord",
  "闹朝扑犬": "Raising a Ruckus at Court, Pouncing on a Dog",
  "闹庄": "Naozhuang",
  "霓裳": "Nishang",
  "霓裳羽衣舞": "Rainbow Skirt and Feathered-Robe Dance",
  "拟杜少陵北征诗": "In the Style of Du Fu's Northern Expedition",
  "拟汉诏": "Draft Han Edict",
  "拟唐疏": "Draft Tang Memorial",
  "廿二子": "Twenty-Two Masters",
  "女弹": "The Female Musician",
  "女弹词": "Female Ballad-Singing",
  "女盗": "Female Thief",
  "潘金莲雪天戏叔": "Pan Jinlian Teases Her Uncle-in-Law in the Snow",
  "盘秋": "Autumn at the Tray",
  "琵琶记": "Story of the Pipa",
  "琵琶行": "Song of the Pipa",
  "嫖院": "Visiting the Courtyard",
  "撇斗": "Flinging the Dipper",
  "品花宝鉴": "Pinhua Baojian",
  "牝贼": "Hinny Bandit",
  "平沙": "Level Sand",
  "平沙落雁": "Wild Geese Alighting on Level Sand",
  "泼粥": "Splashing Gruel",
  "七夕": "Double Seventh Festival",
  "齐民要术": "Essential Techniques for the Common People",
  "前腔": "Opening Aria",
  "前诱": "Prior Enticement",
  "抢娇": "Seizing the Beauty",
  "乔醋": "Feigning Jealousy",
  "切脚": "Cutting the Foot",
  "切韵": "Cut Rhymes",
  "秦淮河看花大会": "Flower-Viewing Assembly on the Qinhuai",
  "琴挑": "Flirting with a Zither",
  "禽经": "Classic of Birds",
  "溱洧": "Zhen and Wei",
  "青门": "The Green Gate",
  "清平": "Clear Peace",
  "清平调": "Clear Peace Tune",
  "秋江": "Autumn River",
  "曲台花谱": "The Opera Stage Flower Manual",
  "曲台花选": "Qutai Huaxuan",
  "劝进碑": "Stele Urging Enthronement",
  "鹊桥": "Magpie Bridge",
  "群仙高会": "Immortals' Grand Assembly",
  "群仙高会图": "Picture of the Immortals' Grand Assembly",
  "群仙领袖": "Leader of the Immortal Circle",
  "入梦": "Entering the Dream",
  "三百篇": "Three Hundred Poems",
  "三百首": "Three Hundred Poems",
  "三都": "Rhapsody on the Three Capitals",
  "三坟": "The Three Tomes",
  "三国演义": "Romance of the Three Kingdoms",
  "三字经": "Three-Character Classic",
  "三醉": "Three Times Drunk",
  "桑中": "Mulberry Grove",
  "扫花": "Sweeping Flowers",
  "扫秦": "Sweeping Away Qin",
  "扫松": "Sweeping the Pine",
  "杀惜": "Killing Xishi",
  "杀舟": "Killing in the Boat",
  "山门": "The Monastery Gate",
  "山香曲": "Mountain Fragrance",
  "商君书": "Book of Lord Shang",
  "商子": "Book of Shang",
  "赏荷": "Appreciating the Lotuses",
  "赏花": "Viewing Flowers",
  "赏秋": "Appreciating Autumn",
  "上林": "Shanglin Fu",
  "神女赋": "Rhapsody on the Goddess",
  "诗": "Poetry",
  "诗经": "The Classic of Poetry",
  "诗品": "Poetic Categories",
  "诗韵": "Poetic Rhymes",
  "施公案": "Cases of Magistrate Shi",
  "十不闲": "Ten Non-Idle Acts",
  "十三经": "Thirteen Classics",
  "十种曲": "Ten Kinds of Songs",
  "石洞": "The Stone Grotto",
  "石鼓歌": "Song of the Stone Drums",
  "时宪书": "Calendar Book",
  "拾画": "Picking Up a Painting",
  "拾金": "Finding Gold",
  "史记": "Records of the Grand Historian",
  "史氏外编": "Shi Clan Supplement",
  "事类赋": "Rhapsodies on Categorized Affairs",
  "势利": "Power and Profit",
  "势僧": "Powerful Monk",
  "寿阳点额图": "Picture of Shouyang Forehead Dots",
  "受禅碑": "Stele of Abdication",
  "书馆": "Book Shop",
  "书经": "Book of Documents",
  "蜀道": "Road to Shu",
  "述异": "Record of Strange Things",
  "双红记": "Double Red Record",
  "水调歌": "Water-Tune Song",
  "水调歌头": "Prelude to Water Tune",
  "水浒传": "Water Margin",
  "水仙操": "Narcissus Lyric",
  "硕人": "Stately Lady",
  "思亲罢宴": "Longing for One's Parents, Abandoning the Feast",
  "四声": "Four Tones",
  "四声切韵": "Four-Tone Cut Rhymes",
  "四书": "The Four Books",
  "四子书": "Four Books",
  "祀孔子碑": "Stele Sacrificing to Confucius",
  "送红线": "Sending Red Thread",
  "送襄垣王君归别墅": "Seeing Lord Wang of Xiangyuan Home to His Villa",
  "颂": "Eulogy",
  "搜杯": "Searching the Cup",
  "搜山打车": "Searching the Mountain, Driving the Cart",
  "搜神": "In Search of the Supernatural",
  "踏月": "Treading on the Moon",
  "太乙肘后备捡": "Taichi Elbow-Backup Formulary",
  "唐诗": "Tang poetry",
  "唐诗三百首": "Tang Poems Three Hundred",
  "唐书": "Book of Tang",
  "唐韵": "Tang Rhymes",
  "逃关": "Fleeing the Pass",
  "桃花曲": "Peach Blossom Song",
  "桃花扇": "The Peach Blossom Fan",
  "讨钗": "Demanding the Hairpin",
  "滕王阁序": "Preface to the Pavilion of Prince Teng",
  "题锦秋墩": "Inscription on Jinqiu Mound",
  "题名录": "Title Register",
  "题曲": "Inscribing the Song",
  "天姥": "Mount Tianmu",
  "天台山赋": "Rhapsody on Mount Tiantai",
  "挑帘": "Lifting the Curtain",
  "贴翠令": "Affixing the Kingfisher Command",
  "亭会": "Pavilion Meeting",
  "铜盘铭": "Bronze Plate Inscription",
  "偷鸡": "Stealing the Chicken",
  "偷曲": "Stealing the Song",
  "偷诗": "Stealing the Poem",
  "投井": "Leaping into the Well",
  "图书集成": "Complete Library of Ancient and Modern Books",
  "脱布衫": "Removing the Cloth Jacket",
  "忘死集": "Forgetting Death",
  "望蓟门": "Gazing at Jimen",
  "望月有感": "On the Moon, with Feeling",
  "尾声": "Closing Aria",
  "闻铃": "Hearing the Bells",
  "问酌六科则例": "Inquiry into the Six-Department Regulations",
  "乌栖曲": "Raven-Roost Song",
  "乌生八九子": "The Crow Has Eight or Nine Young",
  "乌夜啼": "Crows Crying at Night",
  "无双谱": "Peerless Register",
  "无题": "Untitled",
  "五代南北朝年号考": "Examination of Era Names from Five Dynasties and North–South",
  "五更钟": "Fifth-Watch Bell",
  "五经": "The Five Classics",
  "五经条解": "Exegesis of the Five Classics",
  "舞盘": "Dancing on the Tray",
  "西厢": "The Western Chamber",
  "西游记": "Journey to the West",
  "侠隐": "Knight-Errant in Hiding",
  "吓痴": "Terrifying the Simpleton",
  "仙中高品": "Lofty Grade Among Immortals",
  "仙中豪品": "Bold Grade Among Immortals",
  "仙中和品": "Harmonious Grade Among Immortals",
  "仙中华品": "Splendid Grade Among Immortals",
  "仙中狂品": "Wild Grade Among Immortals",
  "仙中乐品": "Joyous Grade Among Immortals",
  "仙中趣品": "Witty Grade Among Immortals",
  "仙中上品": "Upper Grade Among Immortals",
  "仙中逸品": "Escaped Grade Among Immortals",
  "仙中正品": "Upright Grade Among Immortals",
  "相骂": "Mutual Scolding",
  "相约": "The Rendezvous",
  "香雪先生传": "Biography of Master Fragrant Snow",
  "香雪遗稿": "Posthumous Writings of Fragrant Snow",
  "箫韶": "Xiaoshao",
  "小桃红": "Little Peach Red",
  "小宴": "The Small Banquet",
  "卸甲": "Removing Armour",
  "行路难": "Hard Road",
  "醒妓": "Sobering the Courtesan",
  "醒睡集": "The Awakening from Sleep Collection",
  "休洗红": "Do Not Wash the Red",
  "修孔子庙碑": "Stele for Repairing the Confucius Temple",
  "续西厢": "Sequel to the Western Chamber",
  "絮阁": "The Pavilion of Gossamer",
  "璇玑图": "Revolving Brocade Picture",
  "雪窗八咏": "Eight Odes from the Snow Window",
  "雪灯": "Snow Lamp",
  "雪赋": "Rhapsody on Snow",
  "雪罗汉": "Snow Arhat",
  "雪猫": "Snow Cat",
  "雪美人": "Snow Beauty",
  "雪屏": "Snow Screen",
  "雪色": "Snow Hue",
  "雪山": "Snow Mountain",
  "雪声": "Sound of Snow",
  "雪狮": "Snow Lion",
  "雪塔": "Snow Pagoda",
  "雪意": "Snow Mood",
  "雪影": "Snow Shadow",
  "寻梦": "Pursuing the Dream",
  "训子单刀": "Admonishing the Son with a Single Saber",
  "雅": "Odes",
  "雁过声": "Sound of Geese Passing",
  "燕丹灭秦": "Prince Dan Destroys Qin",
  "燕歌行": "Yan Ge Xing",
  "燕台花选": "Yantai Flower Selection",
  "燕台旅稿": "Travel Drafts from Yantai",
  "燕子笺": "The Swallow Letter",
  "阳告": "The Piteous Appeal",
  "阳关": "Yang Pass",
  "杨妃入蜀": "Consort Yang Enters Shu",
  "瑶台": "The Jade Terrace",
  "夜黄": "Night Yellow",
  "夜宴赠妓": "Night Banquet Bestowing a Courtesan",
  "谒衡岳庙": "Visiting Hengyue Temple",
  "谒师": "Paying Respects to the Teacher",
  "一痕沙": "A Trace of Sand",
  "一枝花": "A Spray of Flowers",
  "仪郎奉诏": "The Envoy Receives the Edict",
  "怡情佚史": "Yiqing Yishi",
  "怡园饯别图": "Farewell at the Garden of Ease",
  "怡园序": "Preface to the Garden of Ease",
  "艺文序": "Arts and Literature Preface",
  "议剑": "Discussing the Sword",
  "峄山铭": "Mount Yi Inscription",
  "易": "Book of Changes",
  "易经": "Book of Changes",
  "银钮丝": "Silver Button Silk",
  "咏雪": "Ode on Snow",
  "幽怪": "Hidden Marvels",
  "油葫芦": "Oily Gourd",
  "游湖借伞": "Borrowing an Umbrella on the Lake",
  "游园惊梦": "A Stroll in the Garden and Waking from a Dream",
  "渔阳三挝": "Three Beats of Yuyang",
  "雨铃": "Bell in the Rain",
  "玉抱肚": "Yu Bao Du",
  "玉茗堂四梦": "Four Dreams of the Jade Tea Hall",
  "玉台新咏序": "New Songs from the Jade Terrace Preface",
  "玉台序": "Jade Terrace Preface",
  "元人百种曲": "Hundred Yuan Plays",
  "苑中人日遇雪应制": "Court Poem on Snow on Human Day in the Garden",
  "月儿高": "Moon Rises High",
  "越绝书": "Book of Yue Annals",
  "韵补": "Rhyme Supplement",
  "韵府群玉": "Rhyme Treasury Jade Collection",
  "韵会": "Rhyme Assembly",
  "韵学集成": "Integrated Rhyme Studies",
  "杂事秘辛": "Miscellaneous Secret Affairs",
  "增损盐法利弊": "On the Pros and Cons of Salt Law Reforms",
  "占花魁": "Winning the Flower Queen",
  "张君颂": "Ode to Lord Zhang",
  "长河修禊": "Purification Rite on the Long River",
  "长恨歌": "Song of Everlasting Sorrow",
  "长生殿": "The Palace of Eternal Life",
  "长相思": "Long Yearning",
  "昭君怨": "Zhaojun's Lament",
  "折柳": "Plucking a Willow Branch",
  "折柳阳关": "Willow at Yang Pass",
  "折杨柳": "Breaking the Willow",
  "正本清源论": "On Rectifying the Root and Clearing the Source",
  "制谱": "Composing the Score",
  "治河策": "Policy on River Control",
  "朱奴剔银灯": "Red Slave Trimming the Silver Lamp",
  "诸葛延年": "Zhuge Yan Nian",
  "追信": "Chasing the Messenger",
  "缀白裘": "Pieced White Fur",
  "子虚": "Zixu Fu",
  "子夜": "Midnight",
  "走马行": "Galloping Horse",
  "走雪": "Walking in Snow",
  "醉妃": "The Drunken Consort",
  "左传": "Zuo Tradition",
};
