/** English work/opera titles and Chinese-key mappings for glow + italic. */
export const ENGLISH_WORK_TITLES = [
  "Longing for One's Parents, Abandoning the Feast",
  "A Stroll in the Garden and Waking from a Dream",
  "Complete Library of Ancient and Modern Books",
  "On Phoenix Terrace Remembering the Flute.",
  "Longing for Parents, Abandoning the Feast",
  "Courtyard of Cloud-Recline Fragrance",
  "Three Variations on the Plum Blossom",
  "Precious Mirror for Judging Flowers",
  "Pavilion of Wind-and-Dew Quiet Song",
  "The Awakening from Sleep Collection",
  "Autumn Beats Upon the Painted Hall",
  "Rhapsodies on Categorized Affairs",
  "Cherishing What's Left of Spring",
  "Ancient Fragrance Woodland Lodge",
  "Harmonious Grade Among Immortals",
  "Pine, Crane and Cinnabar Chamber",
  "Clustered Cassia Mountain Lodge",
  "Pavilion of Spring Breeze Drunk",
  "Autumn-Chant Waterside Pavilion",
  "Splendid Grade Among Immortals",
  "Cease-Cloud Tell-Rain Pavilion",
  "Seek-the-Stream Immortal Villa",
  "Preface to the Garden of Ease",
  "Sable Coat Exchanged for Wine",
  "Escaped Grade Among Immortals",
  "Leader of the Immortal Circle",
  "Upright Grade Among Immortals",
  "The Opera Stage Flower Manual",
  "Joyous Grade Among Immortals",
  "Heart-of-Stamen Pearl Palace",
  "Upper Grade Among Immortals",
  "Witty Grade Among Immortals",
  "Mid-Autumn to Zhang Gongcao",
  "Lofty Grade Among Immortals",
  "Judgment in the Underworld",
  "Stealing the Command Token",
  "Wild Grade Among Immortals",
  "Yellow-Fragrance East Plot",
  "The Crouching Tiger Scroll",
  "Bold Grade Among Immortals",
  "Song of Everlasting Sorrow",
  "Cool Tranquil Poetic Realm",
  "Fine Night, Wind and Moon",
  "Dream of the Plum Blossom",
  "Accumulate-Jade Pavilion",
  "Dream of the Red Chamber",
  "Terrifying the Simpleton",
  "The Willow Floss Terrace",
  "Appreciating the Lotuses",
  "Plucking a Willow Branch",
  "Dancing with the Platter",
  "Tang Poems Three Hundred",
  "The Pavilion of Gossamer",
  "Hall of Quiet Blessings",
  "Lone Boat on the Stream",
  "On Encountering Trouble",
  "Returning from the Hunt",
  "Visiting Hengyue Temple",
  "Empty Valley Fragrance",
  "Red Tea Immortal Lodge",
  "Feast in Clear Capital",
  "Admonishing the Prince",
  "Declining the Pavilion",
  "Flirting with a Zither",
  "Sobering the Courtesan",
  "Li Ling Returns to Han",
  "Searching in the Dream",
  "The Liangzhou Prologue",
  "The Peach Blossom Fan",
  "The Classic of Poetry",
  "The Flying Bear Dream",
  "Chasing the Messenger",
  "Frightening the Clown",
  "Picking Up a Painting",
  "Startled from a Dream",
  "One Stretch of Cloud",
  "Treading on the Moon",
  "Tumbling in the Snow",
  "Refining Autumn Loft",
  "Catalogue of Flowers",
  "Misty Faint Pavilion",
  "Selection of Flowers",
  "Stealing the Chicken",
  "Plucking the Eyebrow",
  "East Wind Last Night",
  "Duping the Ding Clan",
  "The Female Musician",
  "Snapping the Willow",
  "Killing in the Boat",
  "Brocade Tent Spring",
  "Waking from a Dream",
  "Composing on a Song",
  "Red-Snow West Manor",
  "Assassinating Liang",
  "Watching a Painting",
  "Inscribing the Song",
  "Dancing on the Tray",
  "Beauty Combing Hair",
  "The Barbarian Child",
  "The Buddhist Healer",
  "Sealing the Chamber",
  "The Drunken Consort",
  "Composing the Verse",
  "Waking and Sleeping",
  "Northern Expedition",
  "Composing the Score",
  "Revising the Letter",
  "Supporting the Head",
  "Picking Up the Gold",
  "Flinging the Dipper",
  "Dreaming of Li Bai",
  "Subduing the Tiger",
  "Little Red Citadel",
  "Falling on the Ice",
  "Peach-Blossom Cove",
  "The Infernal Judge",
  "Chrysanthemum Beds",
  "Stealing the Token",
  "Mountain Fragrance",
  "Lotus-Picking Song",
  "Twenty-Two Masters",
  "Releasing the Easy",
  "Singing the Ballad",
  "Entrusting the Son",
  "Airs of the States",
  "The Monastery Gate",
  "Pursuing the Dream",
  "Golden-Thread Song",
  "Departing the Soul",
  "High Sunny Terrace",
  "The Piteous Appeal",
  "Borrowing the Boot",
  "Eight-Tone Ganzhou",
  "Seizing the Beauty",
  "Classic of Poetry",
  "The Five Classics",
  "Slaying the Tiger",
  "Searching the Cup",
  "Thirteen Classics",
  "Heartbreak Lyrics",
  "Preface to Yiyuan",
  "Book of Documents",
  "Double Red Record",
  "Setting the Score",
  "Stealing the Poem",
  "Poetic Categories",
  "Breaking the Loom",
  "Feigning Jealousy",
  "Hearing the Bells",
  "Sweeping Away Qin",
  "Sweeping the Pine",
  "Attacking the Inn",
  "The Small Banquet",
  "The Mountain Gate",
  "Complete Library",
  "Pawned Headscarf",
  "Power and Profit",
  "Piercing the Eye",
  "Visiting the Rat",
  "Cutting the Foot",
  "The Jade Terrace",
  "Sweeping Flowers",
  "Fleeing the Pass",
  "Qin's Temptation",
  "Burying the Jade",
  "Forgetting Death",
  "Grass Chancellor",
  "Pavilion Meeting",
  "Bell in the Rain",
  "Drunk in Penglai",
  "Seeing the Ghost",
  "The Stone Grotto",
  "Besotted Maiden",
  "Clear Peace Joy",
  "Removing Armour",
  "Book of Changes",
  "Changsheng Dian",
  "Flower Register",
  "Water-Tune Song",
  "West-River Moon",
  "Stealing Poetry",
  "Splashing Gruel",
  "Stealing a Poem",
  "Opening the Eye",
  "Little Banquet",
  "The Four Books",
  "Pinhua Baojian",
  "Pass Qin Tower",
  "The Green Gate",
  "Rainbow Skirts",
  "The Rendezvous",
  "The Secret Vow",
  "Floss Pavilion",
  "South Mountain",
  "Qin Courtship",
  "Magpie Bridge",
  "Female Bandit",
  "Book of Songs",
  "Killing Xishi",
  "Hearing Bells",
  "The Tea-House",
  "Stealing Song",
  "Teaching Song",
  "Powerful Monk",
  "The Rice-Shop",
  "Small Banquet",
  "Jade Terrace",
  "Chezhong Ren",
  "Liangzhou Xu",
  "Young Wander",
  "Finding Gold",
  "Hinny Bandit",
  "Jealous Qiao",
  "Female Thief",
  "Eating Chaff",
  "Spring Sleep",
  "Songs of Chu",
  "Sanguo Yanyi",
  "Luoyang Girl",
  "Like a Dream",
  "Checking Han",
  "Grass Bridge",
  "Twelve Hours",
  "Jin Ping Mei",
  "Autumn River",
  "Willow Tower",
  "Yiqing Yishi",
  "Water Margin",
  "Hemp Ground",
  "Flower Drum",
  "Orchid Path",
  "Lychee Lane",
  "Long Regret",
  "Taohua Shan",
  "Flower Lady",
  "Changhen Ge",
  "Visiting Su",
  "Yan Ge Xing",
  "Wine Tavern",
  "Wu Mountain",
  "Bright Moon",
  "Pine Shrine",
  "Power Monk",
  "The Tavern",
  "Soushen ji",
  "earth-lamb",
  "Red Maiden",
  "Soushen Ji",
  "Secret Vow",
  "Mudan Ting",
  "Wine Tower",
  "Yanzi Jian",
  "Xixiang Ji",
  "Fire Judge",
  "Yuchi Cup",
  "Naozhuang",
  "Plum Cove",
  "Yu Bao Du",
  "Male Monk",
  "Pipa Xing",
  "Book Shop",
  "Rain Bell",
  "Shuyi ji",
  "Xiaoshao",
  "Liaozhai",
  "Chibi Fu",
  "Xiyou Ji",
  "Jinlü Qu",
  "Liu Tang",
  "Mao Shi",
  "Yanggao",
  "Nishang",
  "Pan Qiu",
  "Guofeng",
  "Hanshu",
  "Yutai",
  "Liji",
  "Qutai Huaxuan",
  "also known as He Xinlang",
  "Nanpu usually",
  "Tang poetry",
] as const;

export const ENGLISH_WORK_TITLE_SET = new Set<string>(ENGLISH_WORK_TITLES);

/** Exact English phrasing in aligned translations, keyed by 《…》 inner text. */
export const WORK_ENGLISH_BY_CHINESE: Record<string, string> = {
  "三国演义": "Sanguo Yanyi",
  "乔醋": "Feigning Jealousy",
  "事类赋": "Rhapsodies on Categorized Affairs",
  "五经": "The Five Classics",
  "偷诗": "Stealing the Poem",
  "制谱": "Composing the Score",
  "南浦": "Nanpu usually",
  "品花宝鉴": "Pinhua Baojian",
  "唐诗": "Tang poetry",
  "四书": "The Four Books",
  "回猎": "Returning from the Hunt",
  "国风": "Airs of the States",
  "密誓": "The Secret Vow",
  "寻梦": "Pursuing the Dream",
  "小宴": "The Small Banquet",
  "山门": "The Monastery Gate",
  "怡情佚史": "Yiqing Yishi",
  "惊梦": "Waking from a Dream",
  "扫花": "Sweeping Flowers",
  "折柳": "Plucking a Willow Branch",
  "拾金": "Finding Gold",
  "搜神": "Soushen ji",
  "曲台花谱": "The Opera Stage Flower Manual",
  "曲台花选": "Qutai Huaxuan",
  "杀舟": "Killing in the Boat",
  "李陵返汉": "Li Ling Returns to Han",
  "桃花扇": "Taohua Shan",
  "梁州序": "The Liangzhou Prologue",
  "梅花梦": "Dream of the Plum Blossom",
  "楚词": "Songs of Chu",
  "汉书": "Hanshu",
  "游园惊梦": "A Stroll in the Garden and Waking from a Dream",
  "牡丹亭": "Mudan Ting",
  "琴挑": "Flirting with a Zither",
  "琵琶行": "Pipa Xing",
  "瑶台": "The Jade Terrace",
  "盗令": "Stealing the Token",
  "相约": "The Rendezvous",
  "礼记": "Liji",
  "离骚": "On Encountering Trouble",
  "秋江": "Autumn River",
  "红楼": "Dream of the Red Chamber",
  "红楼梦": "Dream of the Red Chamber",
  "絮阁": "The Pavilion of Gossamer",
  "聊斋": "Liaozhai",
  "舞盘": "Dancing on the Tray",
  "花选": "Selection of Flowers",
  "西厢": "Xixiang Ji",
  "西游记": "Xiyou Ji",
  "诗经": "The Classic of Poetry",
  "赏荷": "Appreciating the Lotuses",
  "赤壁赋": "Chibi Fu",
  "车中人": "Chezhong Ren",
  "述异": "Shuyi ji",
  "酒楼": "The Tavern",
  "醒睡集": "The Awakening from Sleep Collection",
  "金缕曲": "also known as He Xinlang",
  "长恨歌": "Changhen Ge",
  "长生殿": "Changsheng Dian",
  "闻铃": "Hearing the Bells",
  "阳告": "The Piteous Appeal",
  "题曲": "Inscribing the Song",
};
