export const summaries11to20: Record<number, { zh: string; en: string }> = {
  11: {
    zh: `徐子云归宅，与袁夫人谈及梅子玉与琴言的深情，袁夫人将相公们与自家丫鬟相比，子云则娓娓辩称这些少年\"面有女容、身无女体\"，可娱目而制心，两全其美。次日袁夫人携六红盛妆赴华光宿夫人生日之宴，珠光宝气，香车如云。华府中苏浣香才貌双绝，十婢皆以\"珠\"为名，府邸的繁华令人目眩。席间诸夫人小姐行酒令，俏婢们争相搅闹，热闹至极。华公子年方二十一，骑射词赋皆精，养尊处优，气焰虽豪而性情纯粹——这位令人忌惮的人物就此登场，为后续风波埋下伏笔。`,
    en: "Returning home after seeing Mei Ziyu off, Xu Ziyun recounts to his wife Yuan the tender bond between Ziyu and Qinyan. When Yuan wonders aloud what advantage these dan performers hold over her own lovely maids, Ziyun offers a studied defence: they possess the face of a woman yet the body of a man, pleasing the eye while stilling desire — the best of both worlds. The next day Yuan herself rides out in silks and furs to the birthday banquet of Hua Guangsu's wife, Lady Su Huanxiang. The Hua household dazzles: Lady Su is peerless in beauty and accomplishment, attended by ten maids each named with the character for 'pearl.' Among games, poems, and drinking forfeits the ladies hold elegant court, while the maids create cheerful mayhem. Hua Guangsu himself is introduced — twenty-one, accomplished in archery, verse, and aristocratic leisure, outwardly pure yet surrounded by wealth and power that will shadow everyone around him.",
  },
  12: {
    zh: `袁夫人归来，将华府宴上所行酒令一一讲与子云，子云背着夫人将那十六个令刻版印行，题诗传世，外号\"群鸦噪凤令\"，一时传为佳话。光阴流转，仲春时节，书中引出一位新要角——田春航，字湘帆，金陵才子，自幼丧父，由贤母抚养成才。他仪表堂堂，情致风流，诗文名动苏杭，却三试不第，囊空入京。进京后迷上听戏，花尽盘缠，亦不悔。旅中绕道泰岱、华山方抵京，寓于城南宏济寺。京城妓女粗俗令他毫无兴致，反倒被台上的相公们深深吸引，散钱般将情意抛洒，毫无章法，却也赤诚。`,
    en: "Lady Yuan returns from the Hua banquet and recounts every drinking game to Ziyun, who secretly has all sixteen forfeits engraved and circulated among friends — the set becomes known as the 'Crows Crying Round the Phoenix' forfeits and earns wide admiration. Time moves on to mid-spring, and the narrator pauses to introduce a vital new figure: Tian Chunhang, styled Xiangfan, a handsome twenty-three-year-old scholar from Nanjing now lodging near the southern city. Raised by a widowed mother of formidable learning, he passed his district examinations at thirteen, won praise from Suzhou to Hangzhou, yet failed three times at the provincial level. He arrives in Beijing flush with patronage money, only to squander it entirely on theatre-going and lavishing gifts on young performers — not from licentiousness but from a recklessly generous heart. Beijing's coarse courtesans hold no charm for him; the graceful dan actors of the stage are another matter entirely.",
  },
  13: {
    zh: "颜仲清激怒春航后，暗中托王恂送去百金助其度日。走投无路的春航寄食于高品处，却仍每日守在联锦班戏园门口，痴痴等候苏蕙芳。蕙芳留意到这个神清骨秀、衣衫憔悴却不失风雅的身影，心生怜念，终于叫人将他请进门来。二人于花满院落的小客厅中初次对坐，蕙芳吐属雅洁，春航感激涕零，两人相视无言，默契已生。蕙芳引春航入内室，陈设精雅，仇十洲画悬壁，三蓝绒毯铺地，一尘不染。春航甫一踏入，便知此后心上的归处。",
    en: "After Yan Zhongqing's deliberate provocation leaves Tian Chunhang furious and penniless, Wang Xun quietly delivers a hundred taels to see him through. Reduced to accepting meals from Gao Pin, Chunhang still haunts the theatre entrance of the Lianjin troupe daily, waiting for a glimpse of Su Huifang. Huifang has noticed this persistent, elegantly dishevelled stranger whose ardent gaze follows her every movement, and is moved by his obvious sincerity. One afternoon she sends a servant to invite him in. They meet at last in a small reception room blooming with early-spring flowers. Huifang speaks with a refinement that astonishes Chunhang; he responds with heartfelt eloquence. Sitting side by side in the quiet courtyard, they fall into a charged, wordless understanding. Huifang then leads him deeper into her private rooms — refined hangings, spotless indigo carpets, a painting of the Immortals' Gathering — and Chunhang knows at once that he has found, in this unlikely place, something like home.",
  },
  14: {
    zh: `蕙芳为春航换上新衣，二人对镜而照，两张玉颜并影，春航情动而自持，强压邪念，敛神还礼。蕙芳取出春航随身携带的诗稿《燕台旅稿》，轻声吟诵其中一首香艳的七言古风，句句点评精妙，知音之态令春航惊叹。诗中有\"飘烟抱月一尺腰，星眸欲妒春云娇\"等句，蕙芳将其与班中同伴暗暗比对，猜测诗中佳人是谁，春航含笑不语，只说是\"寓言空空\"之人。两人在书房中诗来词往，笑语温柔，俨然是一对忘年知己，情愫在字里行间悄然滋生。`,
    en: "Huifang dresses Chunhang in fresh clothes from her own wardrobe, and when she holds up a mirror so they can see themselves side by side, two luminous faces reflected together, Chunhang feels a sudden surge of longing that he wrestles down with conscious effort, reminding himself that she is his companion in hardship, not an object of desire. Huifang, seemingly unaware, picks up his travel manuscript 'Capital Journey Drafts' and begins reading aloud a richly sensuous heptasyllabic poem. Her commentary is dazzling — she identifies the influence of Wen Tingyun and Li Shangyin, praises the deftness of individual couplets, and playfully tries to guess which of her troupe-mates the poem's beloved resembles. Chunhang smiles and says only that the subject is an imagined figure. The exchange flows naturally into an afternoon of shared verse and easy laughter, and both are aware — without saying so — that something rare has taken root between them.",
  },
  15: {
    zh: "史南湘归来，向王恂、仲清讲起春航与蕙芳的相处情形，众人艳羡不已。另一头，梅子玉家中传来喜讯——父亲梅士燮放了江西学差，府中张灯结彩，宾客络绎，子玉却心系琴言，只好将相思暂时搁置。士燮临行前为二女儿与王家订定婚事，礼数周全，颜夫人操持内外，井井有条。子玉与聘才、元茂将父亲送出城外三十五里，依依惜别，洒泪而返。家中顿显冷清，子玉的课业与情怀都悬在空中，既无人约束，亦无人共诉，唯有在书卷与暗思之间独自度日。",
    en: "Shi Nanxiang returns to Wang Xun and Yan Zhongqing's company and describes the budding romance between Chunhang and Huifang, leaving both men warmly envious. Meanwhile, glad news reaches the Mei household: Mei Shize has been appointed Academic Commissioner for Jiangxi, and the house fills at once with congratulating visitors. Ziyu is delighted for his father but privately mourns the lost chance to call on Qinyan — Pincai had arranged a meeting, and it must now be postponed. Before departing, Shize formalises the engagement of his second daughter to the Wang family, entrusting the ceremonial details to Lady Yan, who manages everything with her customary precision. Ziyu, Wei Pincai, and Li Yuanmao escort Shize thirty-five li beyond the city gates before turning back in tears. The Mei residence feels strangely quiet afterwards, and Ziyu is left to his studies and his unspoken longing, with no one to supervise him and no one in whom to confide.",
  },
  16: {
    zh: "梅士燮赴任之后，梅宅内由颜夫人主掌，外由管家许顺经理，秩序如故。子玉专心攻读，花晨月夕偶邀刘文泽、颜仲清等知己小聚，把酒清谈，题诗分韵，悠然自得。魏聘才则百无聊赖，思谋着自谋出路，辗转托富三爷引荐，进了华光宿门下做食客。华公子府中门客数百，奴仆横行，聘才进去一月，始终见不着主人一面，尽是赔累，内心郁郁。贫富之间的落差、富贵场中的势利人情，借聘才的眼睛一一呈现，嘲弄之意隐于字里行间。",
    en: "With Shize gone to Jiangxi, the Mei household settles into a gentle routine: Lady Yan manages domestic affairs, the steward Xu Shun oversees the outer staff, and Ziyu bends himself to his studies. On fine days he gathers Liu Wenze, Yan Zhongqing, and a few other kindred spirits for poetry parties — brushes, ink, and wine on a clean table, the world held at bay. Wei Pincai, by contrast, grows restless and schemes his way into the household of Hua Guangsu as a resident guest, imagining that proximity to such wealth and influence must lead somewhere. He is quickly disillusioned. Hundreds of parasites already crowd the Hua establishment; the servants are arrogant; Hua himself remains invisible behind a wall of engagements and excuses. Pincai endures a month of thankless socialising and mounting expenditure, unable to secure even a proper introduction to his host. The chapter offers a dry, sharp-eyed portrait of a great household's social machinery — glamorous from the outside, suffocating within.",
  },
  17: {
    zh: "入夜后，高品、史南湘、颜仲清、王恂相携来访，众人在子玉书房中畅谈，提议趁苏蕙芳生日，邀集众名士与当红相公在刘文泽宅中大聚，共成一段风雅佳话。王恂点将，将琴言也列入名单，子玉心中一动，却又惦记着琴言病体未愈，忧喜交织。大家定妥人数、席位，子玉独自挥毫，写就一封情文并茂的邀帖，送与怡园的徐子云和萧次贤，措辞既典雅又真挚。春航自与蕙芳订交后闭门读书，名动京师，又经高品从中调解，与仲清重归于好。众缘汇聚，花会前夕，一股欢欣的期待弥漫于字里行间。",
    en: "That evening Gao Pin, Shi Nanxiang, Yan Zhongqing, and Wang Xun arrive together at Ziyu's study, their mood buoyant. Wang Xun proposes a grand gathering at Liu Wenze's residence to celebrate Su Huifang's birthday — scholars and celebrated performers together, a day of poetry, wine, and music. The guest list is refined with care: Xu Ziyun and Xiao Cixian from the Garden of Ease, the scholars, and a constellation of dan performers including — after some pointed prompting — Du Qinyan himself. Ziyu's pulse quickens at the name but he worries: Qinyan has been ill. After the others leave he sits alone and composes an invitation letter to Ziyun and Cixian that is half formal note, half lyric poem, its courtesy barely concealing his longing. Separately, Gao Pin has quietly brokered a reconciliation between Chunhang and Zhongqing; Chunhang, now contentedly anchored by Huifang, is writing the best verse of his life. All threads are converging on a single luminous afternoon.",
  },
  18: {
    zh: `琴言病体未痊，闭门谢客，子玉屡次登门皆未能相见，两人各自悬念，情愫在缺席中愈发深浓。作者借此插入一段对梨园师傅\"兔、狐、虎、狗\"四变的犀利讽刺，将剥削相公的师傅们刻画得入木三分。魏聘才进华府后一事无成，某日出城偶遇张仲雨，二人在酒楼小酌，仲雨借机传授\"处世十样要诀\"与\"三等人七字诀\"，言语诙谐，机锋暗藏。聘才听得若有所悟，却又自知学不全，只得苦笑。这一章于儿女情长之外，别开生面，以讽喻笔法勾勒出京师社会的多重面貌。`,
    en: "Qinyan remains confined by illness, sending away all visitors. Ziyu calls at his lodgings but is repeatedly turned away — the tutor is entertaining, or there is business, or the moment is simply wrong. Each missed encounter deepens the ache on both sides, though neither yet knows how close the other has come. The narrator uses the pause to deliver a caustic digression on the four stages of a theatre master's career: the coveted boy, the preening adult, the exploitative master, and finally the degraded bit-player — a lifecycle of use and discardment painted in bitter strokes. Wei Pincai, meanwhile, wanders out of the city in low spirits and falls in with the worldly Zhang Zhongyu, who treats him to wine and a lecture on social survival: ten qualities required of a second-rank gentleman (all modified by 'but not'), and a wry shorthand for the third rank. Pincai laughs and admits he barely qualifies for the third. The chapter balances romantic longing with satirical comedy, mapping a city where feeling and calculation run in parallel streams.",
  },
  19: {
    zh: "聘才依张仲雨所授，在华府内先从林珊枝处下手，以昆曲技艺一鸣惊人，获珊枝赞誉，渐入华公子视野。他又广撒小恩小惠，将府中上下打点得熨熨帖帖，人人称好。某日趁华公子出门，聘才约了张笑梅出城，到冯子佩家中闲聚，又遇杨梅窗，四人相携到酒楼小饮。席间叫来相公，琴言、玉林皆以病辞，蓉官赴约，聘才心知琴言对除子玉以外的人始终冷淡。觥筹交错、嬉笑取闹之间，聘才自报进了华公府，二喜等顿时另眼相看。繁华热闹的表面下，众人各怀算盘，情义与利益的边界日渐模糊。",
    en: "Acting on Zhang Zhongyu's advice, Pincai begins his campaign to win Hua Guangsu's favour by targeting Lin Shanzhi, the troupe's most trusted performer. When Pincai is discovered to have a fine voice for kunqu opera, Shanzhi is genuinely impressed and begins praising him to Hua at every opportunity. Pincai simultaneously cultivates goodwill throughout the household with small gifts and unfailing good humour, and within a month has made himself popular where others have only made enemies. On a free afternoon he escapes the city with Zhang Xiaomei to visit the charming Feng Zipei, where they encounter Yang Meichuang and the four spend a loose, laughing afternoon at a restaurant. They send for performers: Qinyan pleads illness and declines — unsurprisingly, since he responds warmly only to Ziyu — and the one who does come is met with decent but unremarkable company. When Pincai casually mentions he is now installed at the Hua household, the shift in deference around the table is immediate and telling.",
  },
  20: {
    zh: "端午前夕，徐子云与萧次贤邀众名士至怡园赏榴花、观龙舟。王恂、仲清因家中有事未能成行，子云、次贤、春航、南湘四人骑马穿越园中胜景，峭壁、古松、缥缈亭、十亩方塘，一一入目，春航诗兴大发。停云叙雨之斋内，一副华光宿手书的对联令众人刮目相看，子云为其辩护，指出豪门公子也自有胸中丘壑。不多时，宝珠、蕙芳、素兰、漱芳等人乘画舫摇橹而来，榴花映水，彩裙点波，五位名旦登岸与众名士汇聚，水榭之上，一幅绝世的端午行乐图就此铺展开来。",
    en: "As the Dragon Boat Festival approaches, Xu Ziyun and Xiao Cixian host a garden excursion at the Garden of Ease for the remaining scholars — Wang Xun and Yan Zhongqing are held back by a birthday celebration at the Wang household. The four who come mount horses and ride through a landscape of stacked crags, ancient pines, and the summit pavilion called 'Misty Heights,' from which Chunhang exclaims that the Lushan peaks themselves could scarcely surpass it. In the Pavilion of Gathering Clouds they discover a couplet brushed in bold calligraphy by Hua Guangsu, and Ziyun gently defends the notorious young aristocrat: his taste and his circumstances, he suggests, are entirely at odds. Then, gliding through a ten-acre lotus pond, come two painted pleasure boats carrying Yuan Baozhu, Su Huifang, Lu Sulan, and two others — five celebrated performers in holiday dress, a pomegranate flower tucked into a braid, a slender bamboo pole used to punt the ducks aside. The scholars and the performers come together at the water pavilion, and for a long afternoon the world outside the garden simply ceases to exist.",
  },
};
