export const summaries41to50: Record<number, { zh: string; en: string }> = {
  41: {
    zh: `春光烂漫，华光宿携苏浣香泛舟西园，画船穿桥过堤，碧桃夹岸，流水鸣环，金龄、玉龄等侍女抢着操桨却手忙脚乱，几乎把船摇翻，满船笑声飞入花影。留仙院中酒肴已备，夫妻与侍婢消遣春昼，处处是富贵家常的温柔。可华公子心中并不全在花水之间：杜琴言奔丧假期已满，迟迟不归，留青精舍空着，像一枚缺失的音。苏浣香虽知丈夫念他，却只以闲话轻轻带过，豪门内室仍按旧日节奏运转。此回看似一段春日浮生图，实则写华府在琴言缺席后的空心繁华；船行水上，笑声不断，水底却已有暗流，牵向长庆师娘、出师赎身与琴言命运的新转折。`,
    en: `Spring floods the Hua garden. Hua Guangsu takes Su Huanxiang onto a painted boat that glides under bridges and along willow causeways, past banks of pink-and-white peach blossom and water chiming against the fittings. The maids Jin Ling and Yu Ling seize the oars with more zeal than skill, spin the boat helplessly, splash themselves, and nearly overturn the party, sending laughter through the flowers. Wine and sweets await in Liuxian Courtyard; husband, wife, and attendants spend the day in the soft weather of aristocratic leisure. Yet Hua's pleasure has a hollow at its centre. Du Qinyan's mourning leave has long expired, and still he has not returned; the Liuqing Study stands empty like a missing note in a piece of music. Su Huanxiang senses her husband's preoccupation but lets it pass into light talk, while the household continues its jeweled routine. The chapter seems at first a spring pleasure-scroll, but the brightness is built around absence. The boat moves, the maids laugh, the blossoms flare — and beneath the water runs the current that will lead toward Changqing's widow, the question of redemption, and Qinyan's next change of fate.`,
  },
  42: {
    zh: `曹长庆尸骨才寒，长庆师娘便把哭声收进算盘。她拦住杜琴言，细数家中一年用度，开口要他每月二百吊养膳，软说师徒恩情，硬说若不出钱便休想出师，仍须终身挂在她名下。琴言听得心灰：他并不知华府究竟给过长庆多少银子，也不敢向华光宿开口讨价，更无私财可作凭据；若贸然应承，便是把自己未来又抵押一次。师娘见他迟疑，越发步步紧逼，话里话外都把死人恩义折成活人债务。琴言只得推说须回府商议，暂缓一时。此回把丧事后的凄凉陡然转为经济盘剥，长庆虽死，梨园师徒制度并未死；琴言要挣脱的，已不只是一位师傅，而是一整套把人标价、按月收租的旧网。`,
    en: `Cao Changqing is barely buried before Changqing Shiniang folds her mourning into an abacus. She corners Du Qinyan after breakfast and lays out the household's annual expenses with ledger-like precision: he must provide two hundred strings a month for maintenance. She speaks softly of teacherly kindness and harshly of consequences, hinting that without payment he can forget any hope of leaving apprenticeship and must remain forever under her name. Qinyan is trapped. He does not know how much the Hua household has been paying Changqing; he cannot ask Hua Guangsu to bargain over him; he has no private funds with which to pledge himself. To agree rashly would be to mortgage his future a second time. The widow presses harder, converting the dead master's "kindness" into a living debt. Qinyan can only say he must return to the mansion and consult, buying a little time. The chapter turns funeral grief abruptly into financial predation. Changqing is dead, but the theatre apprenticeship system survives him: Qinyan must escape not one master, but an entire net that prices a person and collects rent by the month.`,
  },
  43: {
    zh: `袁宝珠、陆素兰闻知师娘索钱，立刻替琴言盘算。素兰先断言：若每月给钱，无异长久受制；不如一举出师，清清楚楚赎出自由。难处在银数巨大，三千两从何而来？二人把京中诸友一一衡量，富者未必肯真心，肯者未必有余力，最后自然想到徐子云。子云爱才重义，待琴言原有知己之情，又有财力周全体面；若由他出面，以正式赎身之名满足师娘贪心，琴言便可不负师门名义而脱离桎梏。计议既定，众人仍照常去赏杏花，谈笑如常，仿佛只是春日闲游；但落英飞处，一桩关乎人身自由的密谋已经成形。此回的美妙正在轻与重并置：花开得烂漫，算盘却打得惊心；笑声越从容，越见朋友相救的深情。`,
    en: `When Yuan Baozhu and Lu Sulan hear of Changqing Shiniang's demand, they immediately begin planning on Qinyan's behalf. Sulan sees the danger clearly: to pay month by month is merely to remain controlled; better to buy out the apprenticeship in one decisive act and make freedom clean. The obstacle is the sum — three thousand taels. They weigh the friends of the capital one by one: the rich may not be sincere, the sincere may not be rich. Inevitably the name Xu Ziyun rises. Ziyun loves talent, values loyalty, already cherishes Qinyan, and possesses both the money and the social grace to do the thing without ugliness. If he formally redeems Qinyan from the widow, her greed is satisfied, the forms of teacherly obligation are preserved, and Qinyan gains a dignified path out. The plan settles quickly, almost quietly. The company then goes on to view apricot blossoms as though nothing heavier than spring amusement were in the air. But beneath the falling petals a conspiracy of rescue has taken shape. The chapter's beauty lies in its contrast: flowers bloom lightly, the abacus clicks gravely; the calmer the laughter, the more moving the friendship behind it.`,
  },
  44: {
    zh: `徐子云果然出手，在日新银号兑出二千四百五十两银票，替杜琴言办妥出师赎身。偏在同日，华府姚贤奉命出城催人回府，到长庆家只见麻子守门，含糊说有江南人替琴言出了师，人已走了。姚贤惊慌乱问，辗转遇见子云家人孟七，才在面馆酒桌上听明白：银票已交，师娘收讫，文书也成，琴言从此不属曹家，更不必回华府听用。消息传回华光宿耳中，他又怒又羞，想追究却无名目，因当初本未正式买身，只靠每月银子维系；如今手续齐备，连权势也难夺已成之局。琴言则已悄然入怡园，旧日秋水堂、留青精舍都成前尘。此回以姚贤奔走的慌张，反衬子云布局的稳密：救人不靠口舌激愤，而靠银票、文书、时机，一刀切断缠身旧网。`,
    en: `Xu Ziyun acts. At the Rixin money-house he converts drafts totaling two thousand four hundred and fifty taels and uses them to complete Du Qinyan's formal release from apprenticeship. On that same day Hua's servant Yao Xian is sent out to fetch Qinyan back to the mansion. At Changqing's house he finds only the pockmarked Mazi, who says, maddeningly, that someone from Jiangnan has bought the boy out and taken him away. Yao rushes about in alarm until he encounters Meng Qi from Ziyun's household; over wine in a noodle shop the truth comes out. The drafts have been paid, Changqing Shiniang has accepted, the documents are complete: Qinyan no longer belongs to the Cao household and need not return to Hua's service. When the news reaches Hua Guangsu, anger and humiliation flare together, but there is little he can do. He never formally bought Qinyan; the arrangement rested on monthly payments and pressure, and Ziyun has cut through it with proper papers. Qinyan has already slipped quietly into Yiyuan. Autumn Water Studio and the Liuqing Study fall behind him like previous lives. The chapter uses Yao's frantic errand to reveal the calm precision of Ziyun's rescue: not noisy indignation, but silver, documents, timing, and one clean severing of the old net.`,
  },
  45: {
    zh: `琴言入怡园后，徐子云、萧次贤不急于追问，只以花事、清谈、琴书慢慢养他。牡丹台、芍药圃、海棠春圃日日有文人名旦流连，袁宝珠、陆素兰等也时来相伴，琴言的眉间愁色才渐渐松动。梅子玉久闻他已自由入园，碍于礼法与病后体弱，直到一弯新月初上，才独自悄悄来访。二人在海棠花下相遇，一时竟似把前番惊险离别都隔在月外。子玉借花说情，说海棠之香不同兰麝，不肯远播，藏在花肌深处，须凝眸久看、以心相闻，方知其真；琴言俯身嗅花，初无所得，继而会心一笑。二人凭栏缓语，月色如水，花影微摇，所有未说出的思念都借海棠暗香回到彼此身边。此回不是轰然团圆，而是劫后情意重新呼吸，轻得像香，深得像夜。`,
    en: `After Qinyan enters Yiyuan, Xu Ziyun and Xiao Cixian do not press him with questions. They heal him by means of flowers, books, music, and tact. The peony terrace, the herbaceous peony beds, and the crabapple grove draw scholars and performers day after day; Yuan Baozhu, Lu Sulan, and the others come often, and the sorrow between Qinyan's brows slowly loosens. Mei Ziyu hears that Qinyan is free and living in the garden, but propriety, illness, and hesitation delay him until one evening, under a new crescent moon, he comes alone. The two meet in the crabapple grove, and for a moment the humiliations and separations behind them seem outside the moonlight. Ziyu speaks of the crabapple's fragrance as though speaking of feeling itself: unlike orchid or musk, it does not travel outward in display, but hides inside the flower's flesh; only one who gazes long enough and listens with the heart can perceive it. Qinyan bends a branch down, inhales, at first finds nothing, then understands and smiles. They lean by the railing and talk softly while shadows move through the blossoms. This is not a thunderous reunion. It is feeling learning to breathe again after danger — as light as fragrance, as deep as night.`,
  },
  46: {
    zh: `屈道翁入住怡园后，见琴言聪慧清苦，遂收为义子，改名琴仙，晨夕亲授经史、诗法、古文、书诀。琴仙本有灵根，经此名师点化，读书过目能诵，发问直入肯綮，半月之间文理大进，举止也由名旦之妍转出书生之骨。道翁又为怡园作序，笔力苍润，徐子云大喜，欲勒石传久。二十八日，子云大开园会，诸名士齐集含万楼；道翁因楼中藏书丰美，改题"赐书楼"，并书长联，上括经史诸子，下纳山川岁月，气象宏阔，满座叹服。众人分题赋对，品园中亭台花木，也品琴仙新学成色；酒杯往还之间，怡园从风月游赏之地升为文脉相传之所。琴言得自由只是第一步，至此他又得父师、得名字、得学问，命运在花影书声中真正改换。`,
    en: `After Qu Daoweng settles in Yiyuan, he recognizes in Qinyan a rare intelligence sharpened by suffering. He formally adopts him, renames him Qinxian, and teaches him morning and evening: classics, history, poetic method, ancient prose, calligraphy, and the pulse of parallel style. Qinxian proves astonishing. He memorizes on first reading, asks questions that go straight to the marrow, and within half a month his literary understanding visibly advances; the beauty of the celebrated actor begins to acquire the bone of a scholar. Qu also composes a preface for the garden, so grave and polished that Xu Ziyun immediately wants it carved in stone. On the twenty-eighth, Ziyun opens the garden for a great assembly in Hanwan Tower. Seeing the richness of its books, Qu renames it the Tower of Imperial Books and brushes a long couplet whose sweep runs from the classics and philosophers to mountains, rivers, and the long body of history. The company is awed. Guests compose on assigned topics, praise pavilions and flowers, and quietly assess Qinxian's transformation. Through wine and inscription, Yiyuan changes character: no longer only a place of refined pleasure, it becomes a site of transmission. Qinyan has gained freedom; now, as Qinxian, he gains father, name, and learning.`,
  },
  47: {
    zh: `会试殿试消息如春雷落地：田春航高中状元，史南湘亦列高第。苏蕙芳喜极，仿佛自己多年积蓄、操持、劝学与守望都在这一榜上开花；春航则由贫寒落魄一跃为天子门生，京中贺客、拜谒、迁居诸事纷至沓来。徐子云慷慨邀他暂住怡园，春航因急欲迎老母家眷北上，另觅新宅，蕙芳便替他料理银钱、器物、人事，忙得无一刻闲，却只能以"苏大爷"的暧昧身份站在家门边缘。另一线写奚十一病后虽暂愈，旧日荒淫留下隐疾，内外皆难应酬，越骄横越狼狈。他往宏济寺谢神，偶见寺旁新开医馆，门前各色怪人游医杂立，江湖气扑面而来，便动了求治之念。于是科名的荣耀与肉身的败坏并行：春航因情义扶持而登云路，奚十一因纵欲作恶而入歧途。`,
    en: `The examination news lands like spring thunder: Tian Chunhang has taken first place in the palace examination, becoming zhuangyuan, while Shi Nanxiang also places high. Su Huifang's joy seems even greater than the winner's. Years of savings, arranging, exhortation, and loyalty appear to flower on the list. Chunhang rises at once from shabby brilliance to Son of Heaven's scholar, and the machinery of congratulations, calls on examiners, banquets, and relocation begins. Xu Ziyun generously offers lodging at Yiyuan, but Chunhang, eager to bring his mother and household north, seeks a separate residence. Huifang manages money, furnishings, servants, and social obligations tirelessly, yet can only stand at the threshold under the ambiguous honour of "Master Su." Against this ascent runs Xi Shiyi's degradation. Though outwardly recovered, his earlier excesses have left a private affliction that makes both inner and outer life miserable. Proud, desperate, and still unreformed, he goes to Hongji Temple to give thanks and notices beside it a new clinic crowded with odd practitioners and charlatan energy. He begins to think of a cure. The chapter sets two consequences beside each other: Chunhang, lifted by devotion and discipline, enters the cloud road of official success; Xi, damaged by lust and cruelty, steps toward comic medical humiliation.`,
  },
  48: {
    zh: `屈道翁得授南昌通判，即将携琴仙离京，怡园诸友轮番饯别，子玉尤觉魂销。琴仙初得父师与学问，便又要随官南下，花园中每一杯酒都像预先尝到离别。春航这边高中状元后，苏侯一见倾倒，本欲招为女婿，闻其已有妻室而罢；不料家书忽至，说原配已于二月暴病身亡，春航悲喜交攻，一时不知命运究竟厚他还是薄他。老母与舅父又将北上，另立门户迫在眉睫，苏蕙芳便一力置办新宅、调度仆役、筹划迎亲迎母诸事，把多年积蓄与心血都投进去。可他身份终究尴尬，既非妻妾，又胜过寻常知己，冷暖只在自己心上。春航感其深恩，命下人从此称蕙芳为"苏大爷"。这一声称呼没有名分，却含着感激、亏欠、敬重与无声承诺；与琴仙将别的愁云交织，构成本回两种难舍。`,
    en: `Qu Daoweng receives appointment as assistant prefect of Nanchang and must leave Beijing with Qinxian. Farewell banquets ripple through Yiyuan; for Ziyu especially, the departure feels like a second tearing-away. Qinxian has only just gained father, name, and learning, and already official duty carries him south. Each cup in the garden tastes ahead of parting. At the same time Tian Chunhang lives inside the afterglow of becoming zhuangyuan. The powerful Su Hou meets him, is enchanted, and would gladly make him a son-in-law, but withdraws when he hears Chunhang has a wife. Then a letter arrives from home: that wife died suddenly in the second month. Chunhang is struck down by grief amid triumph, unable to tell whether fate is favouring or wounding him. His mother and uncle are coming north, so a separate household must be prepared at once. Su Huifang takes charge without being asked — house, furnishings, servants, money, reception — pouring years of savings and devotion into Chunhang's new life. Yet Huifang's position remains painfully ambiguous: neither spouse nor servant, more than friend and less than kin. Chunhang, knowing the debt, orders the household to call him "Master Su." The title grants no legal place, but it carries gratitude, guilt, honour, and a promise without words. Qinxian's impending departure and Huifang's nameless loyalty form the chapter's twin sorrows.`,
  },
  49: {
    zh: `琴仙随屈道翁南去，梅子玉送至城门，望尘而返，痛哭成疾，旧症复发，足月方能起身。春航新宅里，田太夫人北来后不惯京中粗使丫头，连换数人，不是嘴碎便是举止村俗，家务一时无人得力。赶车的周小三举荐其三姐徐三姐。三姐初来，衣饰朴素而眉目精明，腰细如柳，言笑周到，既能服侍老太太，又会料理厨账针线，春航惊其能干，太夫人也十分喜欢。苏蕙芳在家中本以"苏大爷"身份主持内外，见三姐伶俐妥帖，心中另生一种说不清的亲近；三姐亦知蕙芳虽非主人名分，却是家中真正倚重之人，言语格外温柔。一日蕙芳独坐书房，三姐奉点心而入，轻轻一声"苏大爷"，使二人各自心事都在静处一动。此回由子玉失琴仙之痛转入春航内宅新局，写情感如何在名分缝隙里悄悄换形。`,
    en: `Qinxian leaves south with Qu Daoweng, and Mei Ziyu escorts him to the city gate, watches the carriage disappear into dust, and returns undone. His old illness flares again; a full month passes before he can rise. In Tian Chunhang's new household, another problem emerges. Lady Tian has come north but cannot tolerate the coarse Beijing maids tried in succession: one gossips endlessly, another carries tavern habits into the inner rooms, none can serve properly. The coachman Zhou Xiaosan recommends his own sister, Xu Sanjie. She arrives modestly dressed, quick-eyed, willow-waisted, and immediately capable: she can attend the old lady, manage kitchen accounts, sew, speak, and move with exactly the right measure of deference. Chunhang is startled by her competence; Lady Tian is won over. Su Huifang, who effectively manages the household under the ambiguous title "Master Su," feels an unexpected warmth toward this clever, tactful woman. Sanjie, for her part, understands that Huifang has no formal status but is the person on whom the house truly relies, and she addresses him with special softness. One afternoon, bringing refreshments into the study, she says "Master Su," and something in both of them stirs. The chapter moves from Ziyu's grief over Qinxian to a new domestic configuration in Chunhang's house, showing feeling quietly changing shape in the gaps where formal names fail.`,
  },
  50: {
    zh: `盛夏炎炎，田春航因原配已亡，终与苏侯之女定亲，婚期排在七夕，科名、姻缘、家业都向新局推进。刘文泽新授吏部，办事路过林春喜寓门，顺道入访。春喜书室小而幽雅，后院芭蕉叶上密密写满大小字，原来他以蕉叶作纸，日日练腕；前院支小卷篷，窗下盆景错落，清暑有致。春喜取出一柄团扇，上绘螳螂捕蝉，须爪翅目无不生动，令文泽惊叹。原来他数月来暗学丹青，临摹揣摩，不求人赏，画艺已大进；袁宝珠适来，也称其笔有生意，连素来挑剔的瑶卿都不能轻视。文泽爱扇欲索，春喜半推半就另赠一柄，宾主笑语而散。此回在大婚将临的喧热旁，写一个小名旦静静习字学画：风雅不只在大宴高会，也在芭蕉叶上一笔一笔消夏成形。`,
    en: `Midsummer presses down on the capital. Tian Chunhang, now widowed, has been betrothed to Su Hou's daughter, the wedding fixed for the Double Seventh; office, marriage, and household all move toward a new order. Liu Wenze, newly appointed to the Board of Personnel, happens to pass Lin Chunxi's door while on errands and stops in. Chunxi's study is small but elegant. In the rear courtyard banana leaves are covered on both sides with characters of every size: he has been using them as practice paper, writing, wiping, and writing again. A small awning shades the front, and miniature landscapes line the windows. Then Chunxi brings out a round fan painted with a mantis seizing a cicada — claws, wings, bulging eyes, and predatory tension all rendered with startling life. Wenze is astonished. Chunxi has spent months secretly studying painting, copying, experimenting, and improving without asking for praise; Yuan Baozhu happens by and admires the work too, and even the fastidious Yaoqing can no longer dismiss him. Wenze wants the fan, and after playful resistance Chunxi gives him another. Set beside the heat and the approaching grand wedding, the chapter offers a quieter kind of cultivation: elegance forming not only at banquets, but stroke by stroke on banana leaves in summer shade.`,
  },
};
