export const summaries21to30: Record<number, { zh: string; en: string }> = {
  21: {
    zh: "魏聘才寄居华府日久，渐生骄纵之气，竟雇车耀武扬威地登门探视病中的梅子玉。子玉缠绵榻上已逾月，心病难医，唯知症结全在杜琴言。聘才话锋一转，竟贬琴言冷若冰霜，不及府中诸人。子玉拍案而起，以高花冬月为喻，力辩琴言之挚情深韵非俗人所能领略，言辞间不觉将聘才比作粗鄙之流。聘才面有愠色，强颜附和，心中已暗生嫉恨，离去前假意允诺传话，却打定主意另行算计。",
    en: "Wei Pincai, emboldened by weeks of comfortable lodging in the Hua mansion, arrives at the Mei household in a hired lacquer carriage, putting on airs as he comes to visit the ailing Mei Ziyu. Ziyu has languished in bed for over a month, his illness no medicine can touch — only Du Qinyan's presence could cure him. Pincai, angling to diminish the boy in Ziyu's eyes, sneers that Qinyan is cold and distant, hardly worth pining for. Ziyu rises to Qinyan's defence with passionate eloquence, comparing him to a high-growing flower whose inaccessibility only perfects its fragrance, and to a winter moon whose chill makes its radiance the purer. The speech inadvertently casts Pincai as a coarse, uncomprehending clod. Pincai swallows his humiliation with forced agreement, but leaves nursing a quiet resentment and schemes already forming against the performer he professes to admire.",
  },
  22: {
    zh: "为成全琴言与子玉的再会，陆素兰苦心筹划，借逛运河为名，悄悄租下一艘装点雅致的船，又以徐子云名义致书梅宅。子玉见信，沉锁心头的愁雾顿散，病已去了九分，欣然回函应约。然而素兰前往传喜讯时，却撞见琴言寓中险象横生——奚十一的爪牙登门撒野，粗声喝骂，威逼琴言出来陪酒。琴言的家人跪地求饶，送钱了事方才打发走这伙恶人。一喜一惊之间，运河相会的期盼愈发显得珍贵而脆弱。",
    en: "Lu Sulan devises a scheme to reunite the two lovesick young men: she hires a tastefully furnished canal boat under the pretext of a leisure excursion, and sends an invitation to the Mei household in Xu Ziyun's name so as not to raise suspicion. When Ziyu breaks the seal and reads the letter — revealing Sulan's hand and the promise of seeing Qinyan — his month-long melancholy evaporates in an instant; he dashes off an eager reply. But when Sulan goes to deliver the glad news to Qinyan, she peers through a window to find thuggish henchmen of Xi Shiyi rampaging through the rooms, cursing and threatening Qinyan for refusing to receive them. The household servants prostrate themselves in apology and buy the bullies off with coin. The joyful anticipation of the canal reunion is shadowed from the outset by the violence that circles Qinyan like a gathering storm.",
  },
  23: {
    zh: "这一回插叙迂腐书生李元茂游荡东园的笑话。元茂向子玉借了八吊钱，换成票子揣在怀里，志得意满地出门寻欢。误入土窑子，被两个市井流氓花言巧语哄进门，随即遭土棍洗劫一空，衣裤尽脱，只能围着草帘子无法出来，引来众人围观哄笑，险些将那破屋子都挤塌。元茂灰头土脸、狼狈不堪地脱身而去。此番丑事成为京城一时笑谈，衬托出那班名士圈子外的世相百态，也从侧面折射出金钱与人心的复杂纠葛。",
    en: "Chapter twenty-three steps away from the central romance to deliver a comic interlude. The bookish Li Yuanmao, having borrowed eight strings of cash from Ziyu, converts it into banknotes and ventures out in high spirits. Drawn by curiosity toward the dingy pleasure-dens of the East Garden, he is easily flattered by two street rogues who convince him to step inside a squalid establishment. The moment the door closes behind him, local thugs strip him bare. Trapped, he can only wrap himself in a straw curtain, unable to flee while a gathering crowd hoots with laughter until the flimsy walls of the den nearly collapse from the press of spectators. The episode, which quickly becomes the gossip of the season, provides both comic relief and a sharp social commentary — the collision between naive scholarly pretension and the raw, mercenary world just beyond the garden gate.",
  },
  24: {
    zh: "颜仲清与王恂把盏闲话，将近日京城诸事一一道来：苏蕙芳以妙计灌醉骚扰的潘三银匠，令其丑态百出；李元茂土窑子遭劫的笑话已传遍街巷；魏聘才仗势横行、派人骚扰琴言的卑劣行径也在素兰处坐实。二人继而谈及梅子玉与杜琴言那段说不清的情缘——正月初见惊鸿一瞥，怡园灯谜定情，船上久别重逢，情根何处而生，令人费解而又感叹。仲清盛赞琴言之情深，王恂则叹世间知音难求。一席谈话，将诸人命运与性情勾连，前因后果脉络渐明。",
    en: "Over wine, Yan Zhongqing and Wang Xun trade the season's choicest gossip. Zhongqing recounts how Su Huifang outmanoeuvred Pan Qiguan — getting the lecherous silver-merchant drunk until he disgraced himself — and how Li Yuanmao's strip-robbery has become the joke of the city. He then confirms what Sulan let slip: Wei Pincai dispatched ruffians to harass Qinyan on the Hua mansion's behalf. The conversation turns more reflective as the two men puzzle over the extraordinary bond between Mei Ziyu and Du Qinyan — born of a single glance at a New Year performance, deepened by a lantern-riddle at the Leisure Garden, sealed in tears at a reunion neither had dared hope for. How, Wang Xun marvels, does such a profound attachment take root so swiftly, in such improbable soil? The chapter functions as a chorus, gathering the threads of the novel's many plots into a single, searching meditation on the nature of true feeling.",
  },
  25: {
    zh: "夏末时节，华公子在怡园大摆宴席，邀请刘文泽、徐子云等人观赏新排的堂会戏。园中荷香满院，含万楼气宇轩昂，子云一一介绍园中布置之巧。然而约好的名士们借故缺席：子玉旧病复发，史竹君醉伤呕血，其余诸人亦各有推辞。文泽与张仲雨赴约，席间谈论华公子性情，话锋转向萧次贤在后台指点演员声律的细节，气氛悠闲而隐有暗流。名士圈子中，与华府的若即若离，折射出各人不同的处世态度与内心算盘。",
    en: "Late summer finds Hua Guangsu hosting an elaborate banquet at the Garden of Ease, with Xu Ziyun and Liu Wenze among the few who actually appear. Ziyun leads Wenze through the garden's engineered splendours — the cascading artificial waterfall, the lotus-covered lake, the grand Hanwan Pavilion open to the breeze on all four sides — while explaining why the expected company has failed to arrive: Ziyu has relapsed, Shi Nanxiang has drunk himself to vomiting blood, and the rest have found various pretexts. Wenze and Zhang Zhongyu make polite conversation with the host, whose magnificent indolence sits uneasily beside his evident power. Behind the scenes, Xiao Cixian coaches the theatrical troupe on musical precision, his artistic conscience a quiet counterpoint to the excess surrounding him. The chapter captures a social world of elaborate performance — both on and off the stage — in which genuine feeling is carefully rationed.",
  },
  26: {
    zh: "华公子夜归府中，在星栊卧室与十珠侍女把玩消夏，调配防风粥，笑语盈盈，奢靡生活的细节铺陈得如画卷般精致。入夜后公子召林珊枝入内室，密谈收留杜琴言之事。珊枝奉命前往魏聘才书房商议，聘才已向戏班老板长庆施压，谋划将琴言以'无身价'名义送入华府。一边是公子深闺的富贵温柔，一边是幕后运作的机心算计，琴言命运的转折悄然逼近，而他本人尚浑然不觉。",
    en: "Hua Guangsu returns to the mansion after nightfall to find his ten pearl-named maids arranged in white silk, fanning and tending him with practiced grace. He dictates a recipe for a cooling medicinal porridge — each flower-dew and medicinal powder measured to the grain — while the girls joke and tussle in the lamplight, a portrait of gilded domesticity. Once the household settles, Hua summons his confidential attendant Lin Shanzhi and dispatches him to Wei Pincai's study with instructions to arrange the acquisition of Du Qinyan. Pincai has already been leaning on the troupe manager Changqing, engineering a deal in which Qinyan will be delivered to the mansion for no upfront fee — a fiction designed to make the transaction look like generosity. The chapter juxtaposes the mansion's pampered surface with the cold machinery working beneath it, drawing Qinyan's fate inexorably closer while he remains entirely ignorant of what is being decided.",
  },
  27: {
    zh: `奚十一重金归来，与张仲雨、潘其观日日把酒看戏，肆意妄为。此人横行无忌，人称"烟熏太岁"，已将心术不正的师爷姬亮轩请入家中，二人臭味相投。奚十一的亲随巴英官仗势骄纵，风流无度。与此同时，聘才为逼长庆就范，暗中安排市井流氓屡次骚扰琴言，手段愈发阴毒。张仲雨周旋其间，左右逢源，令人不齿。诸多恶势力聚集，形成一张将琴言越逼越紧的网，命运的危机悄然逼近顶点。`,
    en: `Xi Shiyi — the 'Smoke-Blackened Grand Duke' — sweeps back into Beijing flush with remittance money from his family's foreign-trade connections and wastes no time resuming his reign of excess, spending his days carousing with Zhang Zhongyu and Pan Qiguan. He installs the morally bankrupt advisor Ji Liangxuan in his residence, the two men feeding each other's worst impulses. Xi's personal attendant Ba Yingguan, spoilt and swaggering, adds another layer of degradation to the household. Meanwhile Wei Pincai, having failed to pressure troupe manager Changqing through straightforward intimidation, arranges for hired thugs to visit Qinyan repeatedly, each visit more threatening than the last. Zhang Zhongyu floats between these circles of influence, collecting favours and dispensing loyalties to whoever holds the most leverage at any given moment. The chapter assembles the novel's forces of corruption into a single tightening net, with Qinyan at its centre.`,
  },
  28: {
    zh: "长庆迫于压力，领着琴言亲赴华府，以不收身价为名送入留青精舍听用。华公子细打量之后甚为满意，华夫人亦称赞。琴言入府后举止端谨，见到聘才只是沉默相对，无可奈何。临行前夕，琴言将一方常拭泪的罗帕并四味药草，交托素兰转呈子玉，万语千言尽在此物。子玉不知变故，数日后登门素兰处，偶遇兰保、琪官，素兰一句话便知他全然蒙在鼓里，令人心疼。情人相隔一墙，却已是两重天地，生离之悲弥漫字里行间。",
    en: "Cornered at last, Changqing escorts Du Qinyan to the Hua mansion and presents him without asking a fee — a calculated gesture that flatters the master while securing future goodwill. Hua Guangsu examines Qinyan with undisguised satisfaction; even the usually reserved Madam Hua pronounces him pleasing. Qinyan settles into the Liuqing Study and comports himself with dignified silence, meeting Wei Pincai's occasional glances with the expression of a woman who will not speak her resentment. On the eve of his transfer, Qinyan entrusted to Sulan a small parcel: a handkerchief stained with his own tears and four medicinal herbs — no letter, just objects — to be placed in Ziyu's hands. When Ziyu calls on Sulan days later, still ignorant of everything, he finds Wang Lanbao and Qiguan there and cannot understand why Sulan looks at him with such troubled eyes. The discovery that Qinyan has vanished into the Hua compound — separated by little more than a city wall, yet entirely out of reach — lands with quiet devastation.",
  },
  29: {
    zh: `颜夫人得知琴言登门，命其入内安慰病中的子玉。琴言战战兢兢走近床边，见子玉黄瘦憔悴，不禁泪如泉涌，滴落子玉脸上。子玉却在梦呓中念出"七月七日长生殿"，以为已在素兰处与琴言相会，欢喜自语，半醒半睡间又嘟囔着药方、大雨与船——全是相思入骨的梦境碎片。琴言泣不成声，屡唤不应。颜夫人在隔壁听得肝肠欲断。聘才扶起子玉净脸，子玉睁眼初见琴言，以为又是试探，冷笑拒认；待琴言侧身对光，子玉才如梦初醒，两人执手，悲喜交集，难以言表。`,
    en: "Lady Yan, learning Qinyan has come, sends him into Ziyu's sickroom to offer comfort. Qinyan approaches the curtained bed with a trembling heart and finds Ziyu alarmingly gaunt — the sight breaks the dam and tears fall onto the sleeping man's face. Ziyu stirs but does not wake; instead he murmurs lines from 'The Song of Everlasting Regret,' dreaming he is already reunited with Qinyan at Sulan's courtyard under a Mid-Autumn sky. He chuckles, mutters a herb prescription, frets about rain and a distant boat — the shards of weeks of feverish longing made audible. Qinyan weeps in silence, unable to call his name aloud with Lady Yan listening at the wall. Wei Pincai finally props Ziyu up and wipes his face with a hot cloth. Ziyu opens his eyes, sees Qinyan, and — convinced this is another cruel illusion — laughs coldly and turns away. Only when Qinyan shifts into the light and his features become unmistakable does Ziyu's resistance collapse. He reaches out; Qinyan takes his hand. Neither speaks. Lady Yan outside begins to cry.",
  },
  30: {
    zh: "琴言回府后因私自外出被华公子迁入内室，与外界全然隔绝。他独坐水晶山畔，望着一丛凤仙花沉思：花被折入金盆，失了根本，正如自己身陷华府，笑不敢笑，哭不敢哭。想及子玉病虽将愈，却内外音讯断绝，旧情复萌恐又成病，不禁泪流满面。转眼已是八月，桂香盈院，华公子筹备中秋前夕的西园夜宴，召来子云、次贤、文泽等人赏灯观戏。子玉因与华公子有亲属回避之例，只能枯坐书斋，对月独愁，与那灯火辉煌、丝竹管弦的夜宴咫尺天涯。",
    en: "Punished for slipping out to see Ziyu, Qinyan is moved to the inner apartments of the Hua mansion — a world sealed from the outside as completely as a birdcage. Sitting alone beside the crystal rockery, he watches a clump of garden balsam and finds his own image in it: flowers transplanted into gilded pots lose the companionship of their roots and the freedom of wind and rain. He who laughs on command, weeps in secret, and is forbidden to choose even his own expression is no different. He thinks of Ziyu — recovering now, perhaps, but cut off from any word — and fears the silence itself will bring the illness back. Tears fall. Weeks pass. By the twelfth of the eighth month, the osmanthus is in bloom and Hua Guangsu has arranged a grand Mid-Autumn eve banquet in the West Garden, complete with five troupes performing simultaneously under festive lanterns. Xu Ziyun, Xiao Cixian, and Liu Wenze make their way to the brilliantly lit estate while Ziyu, bound by kinship-avoidance rules, sits alone in his study with no company but the moon — its cold light falling equally on the feast he cannot attend and the face he cannot reach.",
  },
};
