export const summaries21to30: Record<number, { zh: string; en: string }> = {
  21: {
    zh: `魏聘才在华府渐得脸面，便有小人得志之态，雇了十三扇玻璃暖车，装束四儿，耀武扬威来探病中梅子玉。子玉卧病月余，药石无功，颜夫人只当他用功伤神，唯他自己明白病根全在杜琴言，非得倾心长谈一日一夜不能痊愈。聘才先夸华光宿、林珊枝与八龄班，随即说琴言虽美，却冷若高枝之花、冬夜之月，不如近手春花可爱。子玉顿起真知灼见，反以高花不受俗手攀折、冬月照梅雪而愈清为喻，力辩琴言的活色生香人人可见，深情挚性却非俗眼能识。话中无意把聘才归入俗流，聘才强笑称是，心中已被刺伤。离开后他直赴樱桃巷秋水堂，借梅府来人之名闯入琴言病室。琴言闻子玉病讯，惊痛交并，细问起居；聘才却添油加醋，既传子玉的关切，又暗窥两人深情的弱处。青窗药香、白鹦呼客、病榻低语之间，真情本该相通，却已被一个嫉妒而善钻营的人握住了传话的关节。`,
    en: `Wei Pincai, now somewhat established in the Hua mansion, begins to show the vanity of a small man suddenly favoured. He hires a fashionable glass-windowed heated carriage, dresses up Si'er, and rolls grandly to the Mei house to visit the bedridden Mei Ziyu. Ziyu has been ill for more than a month; Madam Yan thinks study has depleted him and prescribes tonics, but he knows the disease is of the heart, curable only by a long, unguarded conversation with Du Qinyan. Pincai praises Hua Guangsu, Lin Shanzhi, and the Eight-Ling boys, then turns slyly to Qinyan: beautiful, yes, but cold as a flower too high to pluck, as a winter moon too piercing to love. Ziyu answers with sudden brilliance. A flower beyond vulgar hands preserves its fragrance; a winter moon shining on plum and snow gains a purity no spring moon can equal. Qinyan's living beauty may be visible to anyone, he says, but his deep feeling is legible only to a refined heart. Without intending it, he casts Pincai among the vulgar. Pincai smiles, smarting, and leaves. Instead of merely carrying a message, he goes straight to Qinyan's Autumn Water Studio in Cherry Blossom Lane, invokes the Mei household, and is admitted past the green windows, medicinal fragrance, and white parrot crying "guest." Qinyan, sick in bed, is shaken by news of Ziyu's illness and questions him anxiously. Pincai now holds the hinge between the lovers: what should have been a clear channel of feeling has fallen into the hands of a jealous opportunist.`,
  },
  22: {
    zh: `陆素兰被琴言日催一日，苦于寓中人多、酒楼又不便倾诉，终于想出运河泛舟之计：在东便门外租一只精洁画船，搬去文玩花木，约琴言次晨先到，再借徐子云名义致书梅宅。子玉正对着徐子云所赠玉琴消磨长日，见信封字迹陌生，拆开才知是素兰相招，且暗寓可见琴言，心花顿开，病去九分，立刻回帖应约。素兰携回信去报喜，却在秋水堂听见一片喝骂：奚十一手下的恶客坐的坐、站的站，拍桌辱骂琴言装病摆架子，要他出来陪酒；家人低声下气，奉茶装烟，又许曹长庆次日登门谢罪，才把这伙人勉强劝走。素兰看在眼里，喜事忽蒙阴云，更知琴言所处已非单纯风月，而是权势与银钱的围逼。一个清雅舟会尚未开帆，恶浪已先拍到门前。`,
    en: `Lu Sulan, pressed by Qinyan day after day, can find no ordinary place private enough for the two lovers to empty their hearts. His own rooms are too busy, and a restaurant or borrowed chamber would be crude. At last he devises the canal excursion: an elegant boat hired outside the Great East Gate, furnished with his own curios, flowers, brushes, and inkstones; Qinyan is to come early, and Ziyu will be invited under Xu Ziyun's name. Ziyu, meanwhile, sits listlessly with the jade qin Ziyun gave him, rereading its inscription and feeling the day stretch like a year. When Sulan's letter arrives and he realizes it promises a meeting with Qinyan, his gloom breaks open; nine-tenths of the illness vanishes, and he writes back with trembling gratitude. Sulan carries the good news to Autumn Water Studio, only to hear shouting inside. Peering through the window, he sees Xi Shiyi's rough agents bullying Qinyan's household, cursing the sick boy for refusing calls, threatening to smash the rooms and beat the absent Cao Changqing. Servants bow, offer tea, fill pipes, promise apologies and future attendance, and finally buy the men off with submission and delay. The planned boat meeting glows all the more tenderly against this ugliness. Before the little craft has even touched the water, the violence of moneyed desire has already beaten at Qinyan's door.`,
  },
  23: {
    zh: `第二十三回把镜头从相思转向李元茂的狼狈笑史。元茂向子玉借得八吊钱，换成票子揣在怀中，自以为从此可以开眼寻欢，便独往东园一带闲逛。市井流氓见他呆头呆脑又衣冠像样，甜言蜜语引他入土窑子；门一掩，土棍们便翻脸搜身，票子银钱洗劫一空，连衣裤也剥去，只剩他围着草帘，进退不得。外头看热闹的人越聚越多，笑声几乎把破屋挤塌，元茂羞得魂飞魄散，终于灰头土脸逃出。此事转眼传遍京城，与前文雅集、舟会、品花形成滑稽反照：同是声色之门，一边有诗酒知音，一边是骗财剥衣的泥坑；同是欲望入市，书呆子的迂腐比恶棍的手段更叫人哭笑不得。`,
    en: `Chapter twenty-three turns from refined longing to the comic disaster of Li Yuanmao. Having borrowed eight strings from Ziyu and converted them into banknotes, Yuanmao feels newly equipped for pleasure and wanders alone toward the East Garden quarter. Street rogues immediately recognize the combination of decent clothing and vacant wits. With honeyed words they lure him into a low brothel; once the door closes, the local toughs strip him of notes, cash, and clothing alike. Yuanmao is left clutching a straw curtain around himself, unable either to emerge or hide. Outside, a crowd gathers to watch, laughing so hard and pressing so close that the flimsy den nearly collapses. He finally escapes in utter disgrace, and the story races through the city. Placed between scenes of garden elegance and canal-borne tenderness, the episode is more than slapstick: it shows the underside of the same pleasure economy. One doorway leads to poetry, loyalty, and carefully judged beauty; another, only a few streets away, leads to extortion, nakedness, and public ridicule. Yuanmao's foolishness and the city's predation illuminate each other with merciless comic light.`,
  },
  24: {
    zh: `颜仲清与王恂小饮闲谈，把京中近事像拈花一样一枝枝说开：苏蕙芳又用机变脱出潘其观纠缠，灌得那银号富翁丑态毕露；李元茂误入土窑子、被剥得只剩草帘的笑话，已成街谈巷议；陆素兰所见秋水堂恶客闹事，也使魏聘才、华府一线的阴谋渐有眉目。二人由此谈到梅子玉与杜琴言的情缘：正月姑苏会馆一瞥，灯夕怡园琴谜，徐子云梅崦试情，运河画船重会，桩桩都像天意暗中穿针。仲清怜琴言情深而身贱，王恂叹子玉清贵却被相思所困，二人都觉这份知音既难得又危险。此回如曲中间奏，将潘其观的色欲、元茂的丑态、聘才的势利、子玉琴言的真情一并收束，使前后因果渐渐显出纹理。`,
    en: `Yan Zhongqing and Wang Xun sit over wine and sort the city's recent stories one by one. Su Huifang has again escaped Pan Qiguan's harassment by wit, leaving the banker drunk, ridiculous, and thwarted; Li Yuanmao's straw-curtain humiliation in the low quarter has become common gossip; and Sulan's account of the uproar at Autumn Water Studio points more clearly toward Wei Pincai and the Hua mansion's pressure on Qinyan. From gossip the talk deepens into interpretation. How did Mei Ziyu and Du Qinyan come to such feeling? A glance at the Suzhou Guild Hall, the qin riddle at Yiyuan, Xu Ziyun's test at the Plum Slope, the long-postponed canal reunion — each episode seems, in retrospect, like fate threading a needle in the dark. Zhongqing pities Qinyan, whose feeling is deep but whose social position leaves him exposed; Wang Xun marvels that Ziyu, so pure and privileged, should be conquered by longing all the same. The chapter works like an interlude in music, drawing together Pan Qiguan's lust, Yuanmao's farce, Pincai's opportunism, and the lovers' sincerity until the pattern underneath begins to show.`,
  },
  25: {
    zh: `夏末秋初，华光宿借怡园设宴观新排堂会戏，欲结交徐子云、刘文泽一班名士。园中荷风渐退，含万楼高敞，水石楼台处处见萧次贤经营之巧；子云引文泽游览，一面赞园，一面解释客少缘由：梅子玉旧病复发不能来，史南湘醉伤呕血，王恂、颜仲清等又各有推辞。华公子虽豪奢，却仍有书画性灵，席间与文泽、张仲雨周旋，既显贵介公子的骄矜，也露出求名士赏识的寂寞。后台里次贤细听新戏声律，指点板眼关目，戏台上则众伶争妍。此回表面写园宴清游，实则写华府与名士圈的若即若离：子云能赏其才而不肯全附，文泽能应酬而心存冷眼，华公子越要用富贵搭起风雅场面，越显出真知己难以用银钱买来。`,
    en: `At the turn from late summer toward autumn, Hua Guangsu holds an elaborate banquet at Yiyuan to show off newly rehearsed private-theatre pieces and draw Xu Ziyun, Liu Wenze, and the scholar circle closer. The lotus scent is beginning to fade, the Hanwan Tower stands open to wind and water, and every rock, bridge, and pavilion bears traces of Xiao Cixian's designing hand. Ziyun leads Wenze through the views while explaining the thin attendance: Mei Ziyu has relapsed, Shi Nanxiang has drunk himself into vomiting blood, and Wang Xun, Yan Zhongqing, and others have found reasons to stay away. Hua, for all his extravagance, has real feeling for calligraphy, painting, and theatrical refinement; at table with Wenze and Zhang Zhongyu he appears both lordly and oddly hungry for recognition. Behind the scenes Cixian listens closely to the new performances, correcting rhythm, gesture, and musical entrances, his artistic conscience quietly at work amid luxury. The chapter is less about the feast than about social distance. Ziyun can appreciate Hua's talent without surrendering to him; Wenze can attend and still observe coolly. The more Hua tries to build elegance out of money, troupes, and lanterned space, the more the novel suggests that true fellowship cannot be purchased into existence.`,
  },
  26: {
    zh: `华光宿夜归府中，星栊卧室里十个带"珠"字的侍女罗列如玉，或摇扇，或调香，或听他讲消暑防风粥的配方，花露药末皆有斤两，笑语灯影把豪门内室铺成一幅金碧闲情图。然富贵温柔之后，便是算计。华公子想起杜琴言，召林珊枝入内密商，命他同魏聘才设法将人收来留青精舍。珊枝到聘才书房，二人把曹长庆的贪财怕势摸得透熟：表面上不出身价，实则每月由华府给银，使长庆既得实利，又不好反悔；若琴言稍有不合，还可推说暂留听用。聘才因先前受子玉言语刺伤，正有借华府压琴言之意，遂从中奔走，软硬兼施。此回一半写香闺纳凉、侍女娇憨，一半写书房密议、银钱罗网，恰似绣幕背后伸出冷手，把琴言的命运一点点推向华府高墙。`,
    en: `Hua Guangsu returns home by night to the Star-Latticed Chamber, where ten pearl-named maids attend him like arranged jade: one fans, one blends fragrance, others listen as he dictates a cooling medicinal porridge, each flower dew and powdered drug measured with fastidious luxury. The lamplight, teasing, and silk make the inner apartments look like an album leaf of aristocratic ease. Then the machinery begins. Hua remembers Du Qinyan and summons Lin Shanzhi for a private consultation, ordering him and Wei Pincai to arrange the boy's transfer to the Liuqing Study. Shanzhi goes to Pincai's room, and together they calculate Cao Changqing perfectly: no formal purchase price will be named, so the arrangement can be dressed as favour rather than sale, but the Hua household will pay a monthly allowance generous enough to keep Changqing obedient; if Qinyan displeases, the fiction of temporary service leaves room to retreat. Pincai, still smarting from Ziyu's defence of Qinyan, has his own reasons to help. He moves between pressure and persuasion, turning Hua's desire into a practical net. The chapter's beauty is deliberately double-faced: cooling porridge, perfumed maids, and summer ease on one side; behind the embroidered curtain, a cold hand arranging Qinyan's confinement.`,
  },
  27: {
    zh: `奚十一携重金回京，依旧与张仲雨、潘其观昼夜看戏饮酒，仗着洋行银根与广东豪富声势横行无忌，人送外号"烟熏太岁"。他又延请心术阴鸷的姬亮轩为师爷，二人臭味相投，专在声色场中出坏主意；亲随巴英官倚势骄纵，也学得一身浮浪恶习。华府这边，魏聘才与林珊枝催逼曹长庆，长庆既贪每月银子，又怕奚十一、潘其观旧日纠缠，左右摇摆。聘才遂暗使市井无赖三番登门，拍桌喝骂，污言秽语逼琴言出局；张仲雨则在奚、潘、华府之间穿针引线，谁有势便向谁赔笑。回中恶人各具一副面目：奚十一粗豪而淫，潘其观怯懦而贪，姬亮轩阴损，聘才机巧，长庆贪利怯祸。他们互不相同，却同向琴言逼来，像几条浊流汇成黑水。`,
    en: `Xi Shiyi returns to Beijing loaded with money and resumes his old excess at once, drinking and theatre-going with Zhang Zhongyu and Pan Qiguan under the protection of Cantonese wealth and foreign-trade silver. The city calls him the "Smoke-Blackened Grand Duke." He brings into his household the sinister secretary Ji Liangxuan, whose intelligence runs naturally toward harm, and the two encourage each other's worst inventions; Xi's attendant Ba Yingguan, swollen with borrowed power, imitates the same swaggering debauchery. In the Hua orbit, Wei Pincai and Lin Shanzhi continue pressing Cao Changqing. Changqing wants Hua's monthly silver but fears the old claims and threats of Xi and Pan, so he wavers. Pincai answers by using street roughs to harass Qinyan's rooms, each visit louder and fouler than the last, while Zhang Zhongyu slips between Xi, Pan, and the Hua mansion, smiling toward whichever side has leverage. The chapter gives each villain a distinct flavour: Xi is brutal and lustful, Pan cowardly and acquisitive, Ji Liangxuan coldly malicious, Pincai clever and resentful, Changqing greedy and afraid. Different currents, same black water — all pressing toward Qinyan.`,
  },
  28: {
    zh: `曹长庆挨打受辱后，终于同叶茂林到华府向魏聘才负荆请罪，愿即日送杜琴言入府，分文身价不取。聘才自以为前番发作果然奏效，向林珊枝报知华光宿；华公子命每月给长庆二百两银子，却声明琴言入府后不得再外出唱酒。琴言闻讯，知灾难已成，想见梅子玉一别，怕相见反添断肠；欲写书信，又万语堵心，不能成字。末了取出平日拭泪的罗帕，包上四味药草，托陆素兰亲交子玉：无一字而字字是诀别。次日长庆送琴言入华府，华公子细审形容，大为满意，华夫人见他无俗伶气，也只道一声"好"。琴言住进留青精舍，举止愈加谨慎，对魏聘才只如息夫人不言，聘才虽怀恶意，一时也无可施展。数日后子玉到素兰处，见王兰保、秦琪官在座，仍不知外间变故；素兰取出无字纸包，罗帕中滚出四味药，才说这是琴言临别所留。子玉如梦中被冷水浇醒，方知爱人已入华府高墙，城中咫尺忽成天涯。`,
    en: `After being beaten and humiliated, Cao Changqing finally goes with Ye Maolin to Wei Pincai's study in the Hua mansion and begs pardon as though bearing thorns on his back: Du Qinyan will be delivered at once, with no purchase price asked. Pincai swells with triumph, believing his earlier fury has worked, and reports through Lin Shanzhi to Hua Guangsu. Hua agrees, assigning Changqing two hundred taels a month, but decrees that once Qinyan enters his household he may no longer sing or drink outside. Qinyan understands that the disaster has closed. He longs to see Mei Ziyu once before leaving, yet fears the meeting would only break them both; he tries to write and finds ten thousand words blocking the brush. At last he takes the silk handkerchief with which he has so often dried his tears, wraps four medicinal herbs inside it, and entrusts the bundle to Lu Sulan for Ziyu: no written character, yet every fold speaks farewell. The next day Changqing brings him to the Hua mansion. Hua examines him with open pleasure, and Madam Hua, noting his frail grace and lack of vulgar actorly airs, pronounces one approving word: "Good." Qinyan is installed in the Liuqing Study, careful in every movement, meeting Pincai with the mute restraint of Lady Xi. Pincai's malice has, for the moment, no opening. Days later Ziyu visits Sulan, finds Wang Lanbao and Qin Qiguan there, and still knows nothing. Sulan produces the blank parcel; the handkerchief opens, the four herbs fall out, and only then does Ziyu learn that Qinyan has entered the Hua walls. A city distance becomes an exile.`,
  },
  29: {
    zh: `颜夫人闻杜琴言到门，虽不尽知前情，却知儿子心病所在，便命他入内相慰。琴言战战兢兢至床前，见梅子玉形容黄瘦、神气凋残，泪珠便一串串落在他脸上。子玉半梦半醒，只念"七月七日长生殿"，以为仍在素兰处与琴言相会，又嘟囔药方、大雨、画船、来迟不来迟，都是这些日子相思熬成的梦语。琴言几番低唤，泣不成声；颜夫人在隔壁听见，也忍不住肝肠寸断。魏聘才扶起子玉，用热巾净面。子玉睁眼见琴言，先以为又是徐子云当日假琴言一类的试探，冷笑不认；待琴言侧身向光，泪痕真切、眉目分明，他才如梦初醒，伸手相握。二人悲喜交并，千言万语都堵在掌心。此回最动人处，不在相见之喜，而在病梦把隐秘情事全说破：原来一切未能相见的日子，都已在子玉心中反复活过。`,
    en: `When Madam Yan hears that Du Qinyan has come, she may not know the whole story, but she understands enough of her son's heart-sickness to send him into the sickroom. Qinyan approaches the bed trembling and finds Mei Ziyu yellowed, thin, and spiritually wasted; tears spill at once onto the sleeping man's face. Ziyu stirs but does not wake. Instead he murmurs "on the seventh day of the seventh month, in the Hall of Long Life," dreaming himself still at Sulan's, reunited with Qinyan; then come fragments of herbs, rain, a painted boat, the fear of arriving late or not at all. These are the splinters of longing, made audible by fever. Qinyan calls softly and cannot steady his voice. Madam Yan, listening beyond the partition, is overcome. Wei Pincai props Ziyu up and wipes his face with a hot cloth. Ziyu opens his eyes, sees Qinyan, and first laughs coldly, convinced this must be another test like Xu Ziyun's false Qinyan. Only when the boy turns toward the light, tear marks clear and features unmistakable, does disbelief collapse. Ziyu reaches out; Qinyan takes his hand. Their speech fails, but the clasp says everything. The chapter's deepest poignancy lies not simply in reunion, but in the way Ziyu's dream has already confessed the whole hidden history: every missed meeting has been lived again inside him.`,
  },
  30: {
    zh: `杜琴言私出见梅子玉一事虽未被华光宿查明细节，却足以令他不悦，遂将琴言移入内室，外界音问从此更绝。琴言独坐水晶山旁，看一丛凤仙花，想到花在本根相依时自有天趣，一被折入金盆玉盎，虽供人爱玩，实已失其性命；修枝缚叶、取悦人眼，与囚人锁足、笑哭不得何异？人又不如花，花谢明年再开，人却一年老似一年。念及自己陷落尘埃，日后若被厌弃，便如落花扫入泥厕，越想越悲；又恐子玉病方稍愈，若知自己咫尺难通，旧病复作，泪不能止。转眼八月桂香满院，华公子想起六月曾许徐子云秋凉后相邀，便定十四夜在西园大宴，五班同演，遍设灯戏。彼时秋闱正开，刘文泽、王恂、颜仲清因亲属任考官回避，田春航、高品入场，子玉则因与华府亲戚往来有嫌，不肯登门，只在书斋对月独坐。另一边，子云、萧次贤整衣备赏，张仲雨、魏聘才、林珊枝先游西园，看玉带河六桥、归雁洲、桂树曲廊与华府十二亭台。中秋未至，灯火已明，繁华越盛，琴言与子玉的隔绝越冷。`,
    en: `Hua Guangsu never learns the full story of Du Qinyan's unauthorized visit to Mei Ziyu, but the breach is enough. He moves Qinyan into the inner apartments, sealing him more completely from the outside world. Alone beside the crystal rockery, Qinyan looks at a clump of balsam and reads his own fate in it. A flower left among its roots has natural life, even under wind and rain; plucked into a golden basin or jade urn, trimmed, bound, and arranged for human pleasure, it has already lost its nature. What is this, he thinks, but imprisonment: a person made afraid to laugh or cry? Worse, flowers bloom again next year, while people only decline. If he is one day despised and cast off, he will be no better than fallen petals swept into mud. Thinking of Ziyu, perhaps recovering but cut off from all news, he fears the silence itself will bring the illness back. By the twelfth of the eighth month the courtyard is full of cassia fragrance. Remembering a promise made in June, Hua sets a great West Garden night banquet for the fourteenth, with lantern plays and five troupes performing. The autumn examinations are underway; Liu Wenze, Wang Xun, and Yan Zhongqing must withdraw because relatives serve as examiners, while Tian Chunhang and Gao Pin enter the halls. Ziyu, unwilling to brave the Hua household and constrained by kinship propriety, remains alone in his study under the moon. Meanwhile Xu Ziyun and Xiao Cixian prepare gifts and attendants, and Zhang Zhongyu, Wei Pincai, and Lin Shanzhi tour the West Garden's Jade Belt River, six bridges, Returning Geese Islet, cassia corridors, and twelve pavilions. The nearer the lanterns come to brilliance, the colder the lovers' separation grows.`,
  },
};
