export const summaries51to60: Record<number, { zh: string; en: string }> = {
  51: {
    zh: "孙嗣徽兄弟赴通州院考，嗣徽花钱雇了枪手，嗣元却胡乱涂鸦，卷子被宗师点名嘲讽。堂上嗣徽厚颜为弟辩解，语出惊人，引得诸生哄堂大笑，宗师也斥其为疯子。考毕，元茂得了秀才，心满意足，独自在运河边散步解闷，粮船如云，市声喧嚣，一派世俗繁华，与科场闹剧遥相映衬，尽显世态炎凉。",
    en: "The Sun brothers sit for the Tongzhou prefectural examinations, each by dishonest means: Sun Sihui hires a ghostwriter while the hapless Sun Siyuan scrawls sheer gibberish on his paper. When the examiner publicly mocks the chaotic script, Sihui strides forward and, with breathtaking cheek, offers an elaborate medical excuse for his brother's incoherence — reducing the entire hall to helpless laughter before being rebuked as a madman himself. Meanwhile Li Yuanmao passes with a bare minimum of effort and, newly married and content, strolls the Grand Canal bank at dusk among grain barges and street vendors. The comic farce of the examination hall gives way to the lazy hum of everyday life, painting a vivid portrait of a society where money, connection, and bare-faced audacity count for far more than genuine learning.",
  },
  52: {
    zh: "七月，博学鸿词考期将近，四方名士云集京城。田春航迎娶苏氏女，苏家妆奁竟达数万两之巨，子云慷慨借出东厢大宅相助，园中宾客如云，两班戏子同场竞艳。席间高品借《当巾》一出暗讽春航，春航以郑元和自比巧妙还击，宾主应答机锋迭出，言笑晏晏。子玉强撑病体出席，却因琴言缺席而黯然神伤，众人皆心知肚明，却只能以欢笑相掩。",
    en: "With the Grand Examination for Broad Learning and Extensive Words approaching, scholars from across the realm converge on the capital. The focus, however, is a magnificent wedding: Tian Chunhang takes his bride from the wealthy Su family, whose dowry — two hundred acres, ten maids, twenty thousand taels of silver and three thousand in gold — staggers everyone present. Xu Ziyun lends an entire wing of his own residence to accommodate the extravagance. At the banquet, the most bustling figure rushes between guests and ledgers, the most harried person in the garden. The wit flows freely: Gao Pin stages a sly theatrical joke at Chunhang's expense, choosing the opera piece Pawned Headscarf to needle the groom, who parries brilliantly with a clever literary riposte. Only Mei Ziyu is subdued — he has forced himself out of his sickbed, but Du Qinyan's absence haunts every cheerful scene.",
  },
  53: {
    zh: "华公子索还题有桃花画的团扇，陆素兰携扇赴约，华公子命其题写《梁州序》词以赏花。素兰含羞援笔，词成字美，华公子大加叹赏，双扇互换，题诗赠别，一段风雅情缘就此结下。与此同时，蕙芳、宝珠、兰保等人齐聚商议，打算借怡园一角开设古董书画铺，盘算着分取度香园旧藏，众人畅谈兴致勃勃，一派生机盎然。",
    en: "A painted fan sets two worlds in motion. Hua Guangsu calls Lu Sulan to his garden pavilion to reclaim a peach-blossom fan inadvertently given away — but the errand becomes an occasion for art. Surrounded by autumn colour and the attentive silence of his garden, he asks Sulan to compose a lyric in the demanding 'Liangzhou Xu' mode as tribute to the painted blossoms. Sulan demurs with shy grace, then takes up the brush and writes with a fluency that leaves the connoisseur speechless. The fans are exchanged as tokens of mutual admiration; inscribed poems seal the bond. Across town, Su Huifang, Yuan Baozhu, and Wang Lanbao huddle in cheerful conspiracy, planning to open an antiques and paintings shop in a corner of the Yi Garden — stocking it with surplus books and curios from the vast Duxiang Garden collection. Their laughter and scheming feel like spring after a long winter.",
  },
  54: {
    zh: "梅子玉在对琴言的日夜思念中强打精神，应博学鸿词考试。三场下来他文思泉涌，一路过关，最终高中第二，殿试更夺魁首，授翰林编修之职。仲清、高品相继落第，子玉非但不以己之荣耀自矜，反而深感愧疚，益加谦逊。颜夫人欣喜异常，子玉的婚事也在料理之中。昔日落魄书生，如今风光入仕，命运的齿轮悄然转动，情与功名的纠缠愈发难以分解。",
    en: "Grief makes a strange fuel. Haunted by a troubling dream of Du Qinyan — gaunt and sorrowful — and weighed down by longing, Mei Ziyu nonetheless marshals every resource of his brilliant mind for the Grand Examination. Across three demanding rounds he excels: eight classical essays, two grand fu compositions, and a final round of verse written in the exact rhymes of Du Fu and Han Yu. He places second overall and wins the palace examination outright — the youngest candidate in the cohort — earning appointment as a Hanlin Compiler. Yet there is no triumph in his bearing. Yan Zhongqing and Gao Pin have both failed. Ziyu visits each in turn with quiet apologies, as though his own success were somehow their loss. Lady Yan is overjoyed, and preparations for Ziyu's marriage are set in motion. The gears of fate turn quietly — glory and longing more entangled than ever.",
  },
  55: {
    zh: "琴言随道翁顺运河南下，途经小虹园、莲花桥，扬州旧日繁华已是一片废墟荒草，触目惊心。平山堂附近游船上，两个盐商家的妇人抛来一包果品，引得道翁笑称'安仁掷果'，琴言羞红了脸。抵达南京，琴言只身前往莫愁湖，寻访杜仙女墓，荒冢红衣，玄机隐现，令他心中久久难平。这一路山水诗情与感伤交织，宛若一幕幕画卷缓缓展开。",
    en: "The journey south unfolds like a classical scroll, beautiful and melancholy in equal measure. Du Qinyan travels with Dao Weng along the Grand Canal, passing the ruins of the Little Rainbow Garden where elegant banquets were once held among famous poets — now nothing but collapsed walls, weeping trees, and the clatter of cicadas. At the Lotus Bridge two bold merchant wives on a pleasure boat toss a bundle of fruit across the water at the pretty young traveller; Dao Weng laughs at the classical allusion — 'pelting the handsome man with fruit' — while Qinyan blushes crimson and refuses to eat a single bite. In Nanjing, drawn by the oracle's words, Qinyan slips away to Mochou Lake and finds the lonely, unmarked grave of the lady Du — a red-clad spirit half-glimpsed in the light. The encounter leaves him trembling with something between recognition and dread.",
  },
  56: {
    zh: "道翁在南京一跌成疾，旧病复发，卧床不起，琴言衣不解带地悉心照料。顶风阻行，舟泊燕子矶，琴言代笔写信，心系子玉，在摇晃的船舱里构思和词，字斟句酌，直至深夜。迁入护国寺养病，道翁病势日沉，琴言在神前焚香祈愿，愿以己身相代。道翁感其孝心，心中悲悯交加，在弥留之际仍为眼前这个无依无靠的少年忧心忡忡，父子深情令人动容。",
    en: "A fall on deck breaks more than Dao Weng's body. In Nanjing, confined to a rented temple room, the old man's long-suppressed illness — years of passionate writing and hard drinking distilled into ruin — surges back. He coughs blood. He loses hours. Contrary winds pin the boat at Yanzi Cliff for days; Qinyan writes letter after letter at his guardian's dictation, then lies awake at night composing a lyric reply to Mei Ziyu's verses, choosing each word with aching care. When they move into the Huguo Temple, Qinyan tends Dao Weng through the long nights, burning incense before the shrine and praying — in words the novel records with quiet reverence — to die in the old man's place. Dao Weng, drifting in and out of lucidity, hears him and weeps: the boy has no one; what will become of him when the end comes?",
  },
  57: {
    zh: "十月，怡园重归热闹，袁绮香设宴邀请七位名门夫人赏菊。苏浣香、吴紫烟、颜蓉华、梅琼华等佳人云集宝香堂，锦褥翠幕，七层菊花堆砌如山。众人仿竹林七贤结拜姊妹，序齿排行，欢声笑语，香风盈袖。席间行酒令、联诗句，才思横溢，相互唱和，宛若群花争妍，百鸟竞鸣，京城闺秀的风雅气象尽在其中。",
    en: "October brings a different kind of gathering to the Yi Garden. Yuan Qixiang hosts six of Beijing's most accomplished ladies for a chrysanthemum party in the Precious Fragrance Hall: Su Huanxiang, Wu Ziyan, Yan Ronghua, Wang Qionghua, and others arrive in a procession of sedan chairs, perfume, and laughter. The hall is transformed — silk cushions, silver screens, seven tiers of blazing chrysanthemums in every colour. Over warm wine the women bond with the ease of old friends discovering they were always meant to meet: they form a sworn sisterhood modelled on the Seven Sages of the Bamboo Grove, rank themselves by age, pledge to abandon all deference to seniority, and rename each other with sisterly familiarity. Verse contests, shared compositions, and gentle teasing fill the afternoon; the scene shimmers with a rare sense of women fully in possession of their own wit and world.",
  },
  58: {
    zh: "表面风流的奚十一，如今债台高筑，家道中落，洋行倒闭，盐场漂没，向潘其观借贷被迫立下万两欠票，狼狈至极。深夜独自吞云吐雾，菊花无意间窥见下人春兰的丑事，心中既恼又酸，五味杂陈。当年呼风唤雨的公子哥，如今走头无路，色与财的双重衰落同步上演，世事无常，因果昭彰，报应之弦已悄然绷紧。",
    en: "The wheel turns against Xi Shiyi. The man who scattered silver like chaff through the pleasure quarters now finds himself utterly broke: his family's foreign-trade firm has collapsed, storm surge has destroyed the salt works, and a web of loans has tightened around him. A humiliating audience with creditor Pan Qiguan extracts a promissory note for ten thousand taels in exchange for two thousand — the language of charity dressed as extortion. At home that night he retreats to his opium pipe while his concubine, restless and neglected, catches the servant Chunlan in a compromising tangle behind a locked door — watching through the crack with a mixture of outrage, bitter amusement, and her own unsatisfied longing. The novel's moral architecture is precise: every coin Xi Shiyi squandered on vanity, every cruelty and manipulation, is now being quietly repaid, not through dramatic punishment but through the grinding diminishment of everything he valued.",
  },
  59: {
    zh: "琴仙在南京护国寺为道翁守灵已逾百日，盘缠耗尽，衣单食薄。刘喜在庙门口摆摊卖果，琴仙则以丹青糊口，在生纸上画花卉出售，竟颇受好评。道貌岸然的侯太史携金登门，企图趁人之危笼络琴仙，被琴仙冷脸相拒，其虚伪嘴脸暴露无遗。琴仙写信向子玉、子云、蕙芳等人求援，心中对子玉的牵念，如寒冬里一炉炭火，始终不曾熄灭。",
    en: "A hundred days of mourning have stripped Qinyan of nearly everything. The money is gone; the warm clothes are pawned. Old retainer Liu Xi sets up a modest fruit stall at the temple gate while Qinyan paints flowers on raw paper to sell to passers-by — and discovers, to his own surprise, that his brushwork commands real admiration: a peony sells for two hundred cash, a plum blossom for a hundred and fifty, and a customer commissions a full eight-panel screen. Then the distinguished Hou Taishi arrives, all unctuous concern and subtle pressure, offering money and a comfortable room in his household — with unmistakable intent. Qinyan receives him with a face like winter ice and sends him away unthanked, choosing dignified poverty over purchased comfort. Letters go out to Mei Ziyu, Xu Ziyun, and Su Huifang — careful, heartfelt, each one a lifeline cast into the distance. Through it all, Qu Daoweng's teachings sustain him like an ember in winter.",
  },
  60: {
    zh: "元宵佳节，子云大宴群友，琴仙重回京城，与众名旦、名士把酒言欢，旧日艰辛恍若隔世一梦。席间金吉甫提议以九香楼诸人入画立传，刻石传世，众人一拍即合，拈阄分赋，子玉得琴仙与杜仙女，缘分天定，令人叹服。小说以众人共绘花神图、分写传赞作结，屈道翁精神永存，一段才子佳人的传奇，于诗画流传中获得了超越时间的不朽。",
    en: "The Lantern Festival brings the novel full circle. Xu Ziyun hosts one last great gathering at the Yi Garden; fireworks turn the night sky to daylight; Du Qinyan sits among friends — no longer a theatre boy but a scholar among scholars — and feels the long nightmare of the south dissolve like fog. It is Jin Jifu who gives the evening its lasting shape: he proposes that the nine celebrated beauties of the Nine Fragrance Pavilion be commemorated in portrait and prose, carved in stone to outlast them all, enshrined as flower deities. The company draws lots for assignments with the delighted solemnity of a literary game — and the lots fall with the uncanny aptness of fate: Mei Ziyu draws Du Qinyan and the Lady Du, the two souls most entwined with his own. The novel closes not with loss but with consecration: art and friendship conspiring to make beauty permanent, the spirit of Qu Daoweng living on through the work he set in motion.",
  },
};
