export const summaries0to10: Record<number, { zh: string; en: string }> = {
  0: {
    zh: `两篇序文揭开了《品花宝鉴》的神秘面纱。第一篇序者自称"幻中了幻居士"，盛赞此书兼得"绘形"与"绘声"之妙，将其与《聊斋》《红楼梦》并列，誉为说部中"另具一格"之作。他辗转从友人处借抄，历经七月校订，才将这部险些湮没的手稿刻版流传。第二篇序文则出自作者石函氏之手，娓娓道来创作缘起：他客居京都，科场失意，借问于歌楼舞榭间消遣苦闷，由此得识梨园声色之美、伶人性情之真伪。友人比部力劝他将亲历见闻写成小说，言词间自有褒贬，此即《品花宝鉴》诞生之契机。两篇序文相互辉映，一为传播者的感慨，一为创作者的夫子自道，共同构成这部奇书的入口。`,
    en: `Two prefaces open the doors of Pinhua Baojian. The first, by a writer styling himself \"Master of Illusion within Illusion,\" lavishes praise on the novel's rare ability to evoke both image and sound — ranking it alongside Strange Tales and Dream of the Red Chamber as a singular achievement in Chinese fiction. He describes his painstaking effort to borrow and copy the manuscript from friends, spending seven months in editorial revision to rescue it from near-oblivion before it could be printed. The second preface is the author's own voice: failing the imperial examinations, he found himself stranded in Beijing, drowning his frustrations nightly in the pleasure quarters of the theater world, where he learned to distinguish genuine feeling from performance, elegance from vulgarity. A friend urged him to transform these observations into a novel — and so Pinhua Baojian was born. Together, the two prefaces frame the work beautifully: one a reader's astonished discovery, the other a writer's candid confession, both insisting that even in this world of play and artifice, something true and human can be found.`,
  },
  1: {
    zh: `全书第一回宏观铺陈，先以评品之眼将京师梨园中的缙绅公子与名旦各分十等，以"情"字为经纬，正者有情中正、情中高、情中逸，劣者则堕入淫、邪、黠、荡之流。随后笔锋一转，引出主角家世：翰林学士梅士燮，三代书香门第，夫人梦授玉郎而生子玉。这梅子玉今年十七，貌如精金良玉，才华横溢，却守身如玉，毫无纨绔气息。一日先生放学，好友颜仲清登门拜访——此人系颜夫人之侄，与子玉情同兄弟。二人相见，话题自然引向京中梨园，仲清口中那些名旦的风姿才情，令子玉心生向往。一场关于"情"的故事，就此悄然揭幕。`,
    en: `The opening chapter sets the stage with a grand taxonomy of Beijing's theater world, classifying both scholar-gentry patrons and celebrated dan performers into ten grades of \"feeling\" — from the sublime heights of pure-hearted devotion to the murky depths of lust and corruption. Against this backdrop, the protagonist emerges: Mei Ziyu, seventeen years old, son of the distinguished Hanlin academician Mei Shixie. Born after his mother dreamed of a jade-gifting deity, Ziyu has the luminous bearing to match his mythic origin — gifted in learning, unspoiled by wealth, and genuinely innocent amid a household of servants and silk. When his tutor dismisses class for the day, his good friend Yan Zhongqing — nephew of Ziyu's own mother — comes to call. Their easy friendship crackles with warmth, and the conversation turns naturally to the famous performers of the capital's opera houses. In Zhongqing's vivid descriptions, Ziyu catches his first glimpse of a world he has not yet entered — and a longing begins to stir.`,
  },
  2: {
    zh: "子玉随父归家，撞见父亲正陪着王文辉议事，话题从同年团拜选戏，到给王家次女物色佳婿，随口又论起择婿之难。不多时，两张红帖送到：一是世侄魏聘才，一是西席之子李元茂，均从外省远道投奔而来。魏聘才身材瘦小、伶俐油滑，叩头见礼时那股子讨巧劲儿一览无余；李元茂则身形笨浊、近视木讷，行礼如拜神像，咕噜了几句竟无人听懂。梅学士将二人安置于后院厢房，命子玉引他们往书房见老师性全。那厢魏聘才在账房翻到一册《曲台花选》，将八位名旦的姓名风姿一一记熟，心里盘算着何时能亲眼一睹。京城的繁华与诱惑，已悄悄向这位新来的外省少年张开了怀抱。",
    en: "Ziyu returns home to find his father entertaining Wang Wenzheng, the two men trading news of the upcoming New Year banquet and debating how best to find a suitable match for Wang's sixteen-year-old daughter. The domestic scene is interrupted by the arrival of two calling cards: Mei Shixie's young nephew-by-courtesy Wei Pincai, and the son of the family's tutor, Li Yuanmao. The contrast between them is comic: Wei Pincai is slight, sharp-eyed, and ingratiating — dropping to his knees with practised ease; Li Yuanmao is heavyset, nearsighted, and wooden, kowtowing like a man performing a ritual he barely understands. The elder Mei installs them in the back courtyard and sends Ziyu to introduce them to their tutor. Meanwhile, Wei Pincai stumbles upon a copy of the Flower Register in the household accounts room, and spends a happy hour memorizing the names and descriptions of eight celebrated dan performers. Beijing's pleasures are already calling to him — the only question is when he will find a way to answer.",
  },
  3: {
    zh: `魏聘才错过饭点回来，管事许顺热心留他在账房用饭。饭毕无聊，他随手从紫竹书架上翻出一册《曲台花选》，躺在炕上细细研读，将八位名旦的姓名才貌一一默记，心中暗叹京城名旦果然名不虚传——比起他心里念念不忘的"琴官"，也未必相让。正想着，叶茂林领着联锦班大掌班金二爷一同到访，原来是来替正月初五的堂会戏跑腿定档期的。许顺往来周旋，金二坚持要分包，许顺以梅大人之命回绝，双方相持不下，最终约定去王大人府上再商议。叶茂林留下等候，与聘才闲谈，将戏园子里的排场、行头、相公的风姿与馆子里的热闹情形说得绘声绘色，聘才听得心痒难挠，对这花花京城的向往愈发炽烈。`,
    en: `Wei Pincai misses the household meal and is hospitably invited to eat in the accounts room by the steward Xu Shun. Afterward, idling away the afternoon, he pulls a slim volume from a bamboo bookshelf: the Flower Register, a connoisseur's guide to eight celebrated dan performers. Sprawled on the heated kang, he reads it cover to cover, memorizing each performer's name and described charms, marveling that Beijing's famous beauties might truly live up to their reputations — though in his private heart, none quite displaces the memory of a certain \"Qinguan.\" The afternoon grows livelier when Ye Maolin arrives with Jin Er, the managing impresario of the Lianjin theater troupe, who has come to negotiate the New Year's banquet booking. A brisk argument ensues over whether the troupe can be \"split\" between engagements — the steward holds firm to the master's order, and the two parties part to resolve the matter at another household. Left behind, Ye Maolin regales Wei Pincai with vivid tales of theater glamour — the costumes, the performers, the restaurant revelry afterward — and Pincai's hunger for Beijing's pleasures grows nearly unbearable.`,
  },
  4: {
    zh: "腊雪忽至，一夜铺下五寸，琼装世界。先生性全感了风寒，卧床休养，子玉得了片刻自由，独坐二十四琴斋，翻阅谢惠连《雪赋》消遣。他唤来聘才、元茂，备下佳肴，共在雪景中小酌赏玩。席间他再问聘才琴官近况，聘才此时改了口风，将琴官的才情身份盛赞一番，令子玉愈加倾慕，心想若能在这雪天一见玉人，当真胜过瑶岛看花。饭后煮雪煎茶，别有韵味。不多时，颜仲清遣人送来书信一封，附有王恂初稿的《雪窗八咏》组诗——雪山、雪塔、雪屏、雪灯，逐一吟咏，工整华美。子玉阅后大为赞赏，当即着手应和，一股少年才子的诗情在雪天里自然流露，令人忘却了室外的寒意。",
    en: `An overnight snowfall blankets Beijing in five inches of white — a rare winter gift after months of dry winds. Tutor Li Xingquan, struck by the chill, retreats to bed, leaving Ziyu gloriously unsupervised. He settles into his study, the Twenty-Four Qin Chamber, to read Xie Huilian's classic \"Rhapsody on Snow,\" then invites Wei Pincai and Li Yuanmao for a snow-viewing feast. Over warm dishes and reluctant cups of wine, he draws Pincai back to the subject of Qinguan, and this time Pincai obliges with lavish praise — the performer's bearing, talent, and character painted in such glowing terms that Ziyu's longing deepens into something close to ache. He imagines meeting such a person amid this crystalline landscape and finds the thought almost unbearably beautiful. After the meal, tea brewed from melted snow sustains the mood. Then a letter arrives from Yan Zhongqing, enclosing a set of eight poems on snowy scenes — composed by Wang Xun and titled \"Eight Odes from the Snow Window.\" Ziyu reads them with delight and immediately begins drafting his own reply, his young scholar's spirit fully alive in the cold bright air.`,
  },
  5: {
    zh: "第五回将目光转向怡园的主人：徐子云，浙江山阴人，七世簪缨之后，年二十五，员外郎出身，举人及第，温文俊雅，度量过人。他将府邸前一片废园大加改造，经好友萧次贤监工历时三四年，建成楼台四百余间、曲水山石俱备的怡园，成为京城名士雅集的中心。子云爱才惜才，对史南湘《花选》中的八位名旦皆珍爱有加，而尤钟情于袁宝珠——他视这些相公如奇珍异宝、名花好鸟，只有爱惜之心，绝无亵渎之念，故众名旦皆愿对他推心置腹。一日在堂会中见到新来的琴官与琪官，子云赞叹不已，当即命人连夜赶制服饰相赠，又嘱宝珠引他们来园游览。本回亦交代了琴官的身世：父亲杜琴师以制琴为业，遭豪贵殴辱含冤而死，母亦随后悲痛离世，孤苦伶仃的琴官十三岁起入梨园，由此踏上这条华美而孤独的舞台之路。",
    en: "Chapter Five introduces Xu Ziyun — scion of seven generations of officials, twenty-five years old, holder of a minor ministry post, and possessor of a rare combination of wealth, cultivation, and genuine human warmth. His great project is Yiyuan, the Garden of Contentment: a once-derelict plot of land outside his residence transformed over three or four years, under the supervision of his brilliant friend Xiao Cixian, into a landscape of four hundred rooms, winding streams, and ancient trees that has become the beating heart of Beijing's literati world. Ziyun treasures the famous dan performers of the Flower Register as he treasures rare objects and beautiful flowers — with reverence and care, never with the grasping desire that marks lesser men. The performers sense this and give him their trust completely. When he spots the newcomers Qinguan and Qiguan at a private banquet, he is so enchanted he commissions outfits for them overnight. We also learn Qinguan's history: born Du Qinyan, son of a renowned qin-maker who was beaten to death by a powerful bully, orphaned at ten, and by thirteen compelled by poverty to enter the theater world — a world that has given him fame but cost him everything.",
  },
  6: {
    zh: "正月里京城的官场应酬热闹非凡。梅学士收到王文辉同年团拜的请帖，宾客名单寥寥十二人，较往年愈发冷清。颜夫人亦在家中设宴，请来王、孙两家亲眷——两位陆氏夫人姊妹，虽年届四旬，风韵犹存。本回以细腻的笔法刻画了孙家几位奇葩儿媳：嗣徽妻沈芸姑，书香门第出身，嫁了个红鼻子废物丈夫，只得忍辱将陪嫁丫头松儿送与他收房，自己泪洗面；嗣元妻巴来风，武将之女，性气燥烈，十七岁嫁入孙家，却遭遇了另一番窘境。本回以对比笔法写尽了官宦之家后院的参差众生相：有的夫妻和谐，有的凑合将就，有的悲苦无声。笔墨虽属旁线，却将彼时贵族婚姻的荒诞与女子命运的无奈刻画入骨。",
    en: "The New Year social season unfolds in Chapter Six. Mei Shixie receives an invitation to the usual cohort banquet — only twelve guests this year, the list shortened by postings and absences — while Lady Yan holds her own gathering for the women of connected families. The two Mrs. Lu sisters, married into the Wang and Sun households respectively, are the social anchors of the scene: both middle-aged, both still handsome, and possessing very different domestic circumstances. The chapter's sharpest observations are reserved for the Sun family's daughters-in-law: the gentle, scholar-bred Shen Yunggu, trapped with the repulsive Xie Hui and driven to the desperate expedient of offering her own maid as a concubine just to buy herself some peace; and the fierce, soldier-raised Ba Laifeng, married at seventeen to Xie Yuan, burning with a temperament that refuses to be quietly extinguished. Against the bright lanterns and New Year formalities, these women's quiet suffering and dark humor illuminate the cramped realities behind the elegant facades of Beijing's official households.",
  },
  7: {
    zh: `姑苏会馆那出戏后，子玉将琴官的身影足足想了两日，反复比较苏蕙芳、陆素兰诸人，最终仍以琴官为首。他自问：琴官若非生在梨园，天下人怎得瞻仰这样的人？由此生出一番"造化钟灵"的感慨。忽见自己所咏《车中人》诗稿被人用指甲挖去两个字，追问之下，原来是王家二姑娘看书时留下的痕迹——而小丫鬟更透露，孙家已从中做媒，将二姑娘许配给了子玉，姑娘还戴了太太一根簪子回去为信。子玉初时将信将疑，细想那二表妹的容貌竟有几分像琴官，不禁心生比较。继而又想：对方必以为他诗中"有心"想念，自己却百口莫辩，干脆认了这桩无意间结下的"冤缘"。到了初九，刘文泽再度相邀，子玉随一众好友赴宴，席间初遇史南湘、高品等人，一桌少年才子，风华各异，而子玉初次登堂，愈显卓然。`,
    en: `Two days after the Suzhou Guild Hall performance, Ziyu is still entirely in thrall to the memory of Qinguan. He ranks and re-ranks the celebrated performers in his mind, always arriving at the same conclusion: Qinguan stands alone. His reverie is interrupted by an odd discovery — two characters scratched out of his poem \"The Person in the Carriage\" by a fingernail. A maid solves the mystery: Wang's second daughter visited during Lady Yan's gathering, read the poem, and damaged those particular words. More astonishingly, the maid reports that a match has apparently been arranged — the Sun family acting as go-between, the girl returning home with one of Lady Yan's hairpins as a token. Ziyu is half-skeptical, half-delighted. He compares the girl's face with Qinguan's in his mind, surprised by the resemblance. Then he reflects wryly that she must have thought his poem was addressed to her — a misunderstanding he can never untangle, and perhaps need not. At a dinner hosted by Liu Wenze on the ninth day, he meets the compiler of the Flower Register, Shi Nanxiang, along with several other young men of talent, and the gathering crackles with the competitive energy of brilliant youth.`,
  },
  8: {
    zh: "子玉赴宴归来已是深夜，魏聘才与李元茂却不见踪影。原来二人趁子玉不在，一合计便打起了看戏的主意。囊中羞涩，聘才怂恿元茂偷取父亲箱中银两，前后凑了八九两，雇车直奔太和园联锦班。元茂初次进戏园，看得眼花缭乱，不防绊倒在门口长凳上，恰被一人双手扶起——此人正是华光宿，自此引出一条险恶支线。聘才领着元茂挤进官座，一群相公围着嘻嘻笑笑，正是他心心念念的花花世界。戏毕上馆子饮酒，口脂花香、莺声燕语，聘才如鱼得水。岂料结账时发现银两不翼而飞，二人狼狈不堪。与此同时，戏场之中另有一番情节——子玉之外，另几位公子的喜好与心思亦借看戏之机一一呈现，梨园世界的人情冷暖在台上台下同步上演。",
    en: "Ziyu returns from his dinner to find Wei Pincai and Li Yuanmao long gone. The two had seized their opportunity the moment he left: Pincai talked Yuanmao into raiding his father's strongbox for eight or nine taels of silver, and they headed straight for the Lianjin troupe at Taihe Garden. Yuanmao's entrance to the theater world is literally face-first — he trips over a bench at the gate and is hauled upright by a stranger who turns out to be Hua Guangsu, a name that will cast a long shadow. Inside, the world Pincai has been dreaming of opens up around them: privileged seats, laughing performers clustering close, wine and perfume and the sweet chaos of the backstage world. At the restaurant afterward, Pincai is in paradise. The reckoning comes at the bill — their money has vanished somewhere between the theater and the table, and the two find themselves scrambling. The chapter cuts between their misadventure and the theater's other dramas, sketching the full cast of patrons and performers whose intersecting desires will drive the story forward.",
  },
  9: {
    zh: "元宵佳节，灯火通明。聘才、元茂深夜归来狼狈收场，次日央了许顺借来钱票，悄悄托人送与叶茂林，遮掩了昨日的窘事。子玉盘问时，二人推说是张仲雨相请，遮过了实情。元宵夜，性全带元茂赴会馆吃年酒，聘才出门逛灯，子玉正感无聊，刘文泽、颜仲清、王恂联袂来邀，四人弃车步行，混入灯市。灯棚里人山人海，玻璃灯、画纱灯、灯屏灯楼次第辉映，炮竹锣鼓声中，华车秀撵鱼贯而过。子玉忽被车轴拦住去路，车内一位少妇目不转睛地凝视他，甚至展示莲足，嫣然微笑。文泽、王恂在旁悄声调侃，仲清打趣道不知是看你还是看文泽。子玉回过神来，与那少妇目光相接，颇觉局促，少妇的车才悠悠开走。灯市的繁华与人间的多情，在这一夜交织成一幅热闹而隐约暧昧的画卷。",
    en: "The Lantern Festival arrives, and Beijing ignites. Wei Pincai and Li Yuanmao quietly clear up the previous night's disaster by borrowing money from the steward and sending it anonymously to their theater contacts. When Ziyu presses them, they produce an alibi and he lets it drop. That evening, with tutor Li and Yuanmao at a guild hall feast and Pincai out sightseeing, Ziyu finds himself at loose ends — until Liu Wenze, Yan Zhongqing, and Wang Xun arrive to sweep him into the festival. The four young men abandon their carriages and walk into the lantern market on foot, swept up in the magnificent chaos of firecracker smoke, silk-curtained carriages, and every variety of lantern imaginable. Then Ziyu is stopped in his tracks — literally blocked by a carriage axle — while a young married woman inside stares at him unblinkingly, shifts her robe to display a silk-slippered foot, and smiles. His companions nudge each other and whisper. When Ziyu finally meets her gaze directly, she smiles again before her carriage glides on. It is a fleeting, wordless exchange — but in this world, such moments carry weight.",
  },
  10: {
    zh: `元宵灯会之后，怡园这边另有一番情愫暗涌。琴言自去年进京，随众名旦常往怡园，深受子云优待，却始终只把他当半个知己——因为他心上真正挂念的，是那个在进京途中梦中救过他的人。几番梦境，或与子玉相对而笑，或执手同哭，醒来怅然若失。一日子云归园，萧次贤讲起灯谜之夜子玉猜中了琴言的谜，大赞其才貌，子云听了亦颇赞许，道两家本有世谊，随口说要替琴言"觅着配对"。这句玩笑话却把琴言吓得泪如雨下，激切道只求不被人糟蹋，何来配对之说？子云自知失言，忙叫宝珠好言相劝。待宝珠轻轻道出梅庾香问起他的消息，琴言心下一动，细细追问：这位姓梅的，可是那日在姑苏会馆楼上看戏的那个人？一缕暗藏已久的幽情，就此浮出水面。`,
    en: `After the lantern festival, Chapter Ten turns to the hidden currents running beneath Yiyuan's gracious surfaces. Du Qinyan — Qinguan — has been a fixture of the garden's gatherings since arriving in Beijing, cherished by Xu Ziyun above almost all others. But Ziyun has only ever been half a confidant to him, because Qinyan's deepest feelings belong to a person he saw first in a dream: the young man who rescued him from a pit, and whom he recognized in waking life on the road to Beijing. The dreams keep returning — sometimes laughing together, sometimes weeping, sometimes a tender farewell — and each morning he wakes more entangled. When Xiao Cixian reports that Mei Ziyu solved Qinyan's lantern riddle and spoke of him with admiration, Ziyun is delighted and makes an offhand joke about finding Qinyan a \"match\" — which reduces Qinyan instantly to tears, his voice shaking as he begs only not to be humiliated. Ziyun retreats, abashed. It is Yuan Baozhu who soothes him — and who quietly mentions that a young man named Mei Yuexiang asked after him specifically. Qinyan goes still. He asks, very carefully: was this Mei Ziyu the one watching from the east gallery at the Suzhou Guild Hall? The answer he is waiting for has almost arrived.`,
  },
};
