export const summaries31to40: Record<number, { zh: string; en: string }> = {
  31: {
    zh: `华府西园夜宴入深，灯火照水，五班丝竹喧阗。华光宿命诸名旦各献所长：或琴箫相和，或临纸题诗，或笙琶竞响，或猜谜舞剑，连酒令、戏目、书画品评也层层翻新。徐子云、萧次贤、刘文泽等在席间谈艺论文，梅子玉虽未到场，他的才名与旧日言论仍被众人牵入书法诗学的争辩之中；华公子也借此显露自己非徒豪奢，实有爱才赏艺之心。杜琴言被命陪侍，却因心病与幽禁之苦托病避席，独坐屏后，听满堂笑语如隔秋水。繁华本应娱人，在他耳中却句句提醒自己已失自由：从前怡园花下可与知己清谈，如今金屋深锁，笑哭皆不由己。夜深宴散，子云又倡以戏文题目行令，众人猜射欢呼，热闹如潮；琴言的泪却在屏阴里悄然落下。此回以极盛声色反写极深孤独，一座华园成了镂金的囚笼。`,
    en: `The Hua mansion's West Garden banquet deepens into night: lanterns burn on the water, five troupes sound at once, and Hua Guangsu orders the celebrated young performers to display arts beyond ordinary singing. Some join qin and flute, some inscribe poems on fresh paper, some set sheng against pipa, some solve riddles or perform swordplay in the lamplight. Xu Ziyun, Xiao Cixian, Liu Wenze, and the others turn from wine to arguments over theatre, painting, calligraphy, and poetry; even absent Mei Ziyu is drawn into the conversation through his reputation and earlier judgments. Hua himself shows that beneath the extravagance there is genuine connoisseurship, a wish to be recognized as more than a rich young lord. Du Qinyan, however, is ordered to attend and then pleads illness, withdrawing behind the screen. The revelry that should delight him only measures his captivity. In the Yi Garden he once moved among friends and flowers; here every laugh belongs to someone else's command, and even sorrow must hide. Late in the night Ziyun proposes a game of matching opera titles, and the hall rises into noise again. Behind the screen Qinyan weeps quietly. The chapter paints pleasure at full blaze, then lets us see the gilded bars inside the light.`,
  },
  32: {
    zh: `秋雨七八日方晴，贡院放榜在即，京中举子人人魂梦不宁。高品与田春航同寓，夜不能寐，便谈往年问卜、测字、求签种种荒唐灵验与不灵验，借笑语抵住科场前的惊惶。苏蕙芳在家比春航更焦急，谢绝来客，坐卧不安，遣人四出探听，心中所系已不只是儿女私情，而是春航一生出处。报录声终于满城响起，喜忧分道：高品高中，春航落第。消息传到怡园，众人或贺高品，或慰春航，言辞虽尽体面，却掩不住科名一纸判人的冷酷。蕙芳闻信，既为高品喜，又为春航痛，深知文章才情与八股命数原不相等；春航反较淡然，以失意作养气之资。此回把雨后放晴的天空、榜前失眠的书生、门外奔走的报子、屋内焦灼的知己并列，写出功名场上最薄的一张纸，怎样压住最重的一片心。`,
    en: `After seven or eight days of autumn rain, the sky clears and the examination list is due. Every candidate in Beijing lives half outside his body. Gao Pin and Tian Chunhang, lodging together, cannot sleep; through the night they trade stories of past divinations, fortune-tellings, character analyses, and temple lots that promised everything or nothing, laughing because anxiety has left no other defence. Su Huifang waits at home with a restlessness greater than Chunhang's own. She refuses visitors, questions servants, sends people out for news, and moves between couch and window as if the result will decide not simply a lover's mood but the whole direction of his life. At last the runners' cries spread through the city. Fortune divides cleanly and cruelly: Gao Pin's name is on the list; Chunhang's is not. The news reaches Yiyuan, where congratulations and consolations are delivered with proper elegance but cannot soften the fact that one sheet of paper has judged them. Huifang receives it with a heart pulled two ways, glad for Gao Pin yet aching for Chunhang, knowing that talent and the eight-legged essay have never been the same thing. Chunhang himself bears the loss more steadily, treating failure as material for inner cultivation. Rain-cleared sky, sleepless scholars, shouting messengers, and anxious friends: the chapter shows how light a list looks, and how heavily it falls.`,
  },
  33: {
    zh: `岁暮腊寒，史南湘随任出京，众友饯别，京中知己又少一人。梅子玉出门办事，半途遇车马壅塞，恰逢袁宝珠，遂被邀入其"小琅室"。室中水仙、古梅、名画、古器，雅洁如雪后疏林；宝珠煮雪烹茶，又请陆素兰同坐，三人清谈书画、诗词与梨园旧事。谈到落难画师金吉甫，宝珠因平日资助其贫困，忽被子玉一句称赞触动心事，泪随白傅"同是天涯沦落人"之意而下；子玉忙借竹石梅花转圜，方使气氛复平。席间又有人提起子玉婚事，问江西家书何时回来，子玉只淡淡推说未定，神色却自有难言之隐。窗外寒梅暗香，室内茶烟细细，这一回没有大波澜，却把离别、义气、贫贱中的扶持、婚姻礼法的逼近，都收在一壶雪水之中。`,
    en: `In the cold of the twelfth month, Shi Nanxiang leaves Beijing with his new appointment, and the circle of intimates grows thinner again. Mei Ziyu sets out on an errand, abandons it amid traffic, and happens upon Yuan Baozhu, who invites him into the exquisite Xiaolang Chamber. Narcissus, winter plum, old paintings, bronzes, and cleanly arranged books make the room feel like a sparse grove after snow. Baozhu melts snow for tea and asks Lu Sulan to join them; the three pass the afternoon in talk of painting, poetry, theatre, and old loyalties. When the conversation turns to the disgraced painter Jin Jifu, whom Baozhu has quietly supported through poverty, Ziyu's praise unexpectedly touches a hidden bruise. Baozhu's tears fall under the shadow of Bai Juyi's line about fellow wanderers meeting in exile, and Ziyu hastily turns the subject toward bamboo, stone, and the plum branch outside. Someone also mentions Ziyu's impending marriage and asks when the Jiangxi letter will arrive; he deflects gently, saying nothing is settled, though his face carries another answer. No great plot event erupts here. Instead the chapter distills departure, friendship, loyalty to the fallen, and the pressure of arranged marriage into the steam of one pot of snow-water tea.`,
  },
  34: {
    zh: `魏聘才离开华府后寄居唐和尚寺中，年关逼近，债单却雪片般飞来，裁缝、饭馆、杂项共五百余吊，箱中虽有几件皮衣，实已无处周转。李元茂偏在此时来借四十两，聘才索性抖出一叠欠票，两人对着穷字互诉苦水，谁也不信谁真穷。唐和尚外貌僧人，骨子里却惯与闲汉游客做交易，夜间又叫聘才过去密谈，言辞吞吐，似有生财门路，也似有陷人机关。元茂厚脸留宿，呼烟要点心，支使四儿往来不休，扰得聘才装睡不理。寺中灯烟昏黄，墙外岁寒风紧，三个穷而不安分的人各怀小算盘：聘才想翻身，元茂想揩油，唐和尚想牟利。此回把富贵门客跌入僧房穷局，写得既可笑又凄凉。`,
    en: `After leaving the Hua household, Wei Pincai lodges in the temple of Tang Heshang, a monk only in costume. The new year approaches, and bills arrive like snow: tailors, restaurants, miscellaneous creditors, more than five hundred strings in all. A few fur garments remain in his trunk, but even they cannot easily be converted into relief. Li Yuanmao chooses precisely this moment to come borrowing forty taels. Pincai theatrically produces the stack of debts, and the two men complain at each other across dinner, each convinced the other must secretly have money. Tang Heshang, who has long treated religion as a cover for transactions with idlers and pleasure-seekers, summons Pincai at night for a whispered consultation, his words evasive enough to suggest both profit and danger. Yuanmao, too thick-skinned to depart, stays the night, demanding tobacco, fruit, and snacks and keeping Si'er running until Pincai turns to the wall and pretends to sleep. In the cramped temple room, yellow with lamp smoke and year-end cold, three unsatisfied calculations share one roof: Pincai wants rescue, Yuanmao wants a free ride, and Tang wants advantage. The fall from Hua-mansion glamour to monastic insolvency is comic, but the comedy has frost on it.`,
  },
  35: {
    zh: `唐和尚寺中一夜生变。魏聘才回房，箱笼拜匣全被搬空，金银、鸦片、玉器、皮衣细软俱失，只余几件棉衣和一块跌碎洋表。众人趁月搜菜园，在墙角寻得空箱，守园新伙计却已无踪。唐和尚疑心内贼，竟将种菜老夫妇绑起审问，老婆子哭天抢地，老汉吓得木立；聘才一面清点损失逾千金，一面草草报官。坊里几番传讯，方知新来蔡姓伙计乘宝珠生日、寺中人来客往之乱，偷物越墙逃去；案情虽明，人赃皆渺。此回又与袁宝珠寿筵遥遥相照：一边花烛酒歌，诸友贺寿；一边月下搜园，穷客失财。作者偏把热闹与凄凉并排摆着，令人看见京城风月并非一色繁华，欢声才落处，便有冷月照空箱。`,
    en: `The temple night turns catastrophic. Wei Pincai returns to his room and finds trunk and document-case gone, along with gold, silver, opium, jade pieces, fur garments, and other valuables worth more than a thousand taels; only a few cotton clothes and a shattered foreign watch remain. By moonlight the household searches the vegetable garden and finds the emptied trunk abandoned near the wall, while the newly hired garden-hand has vanished. Tang Heshang immediately suspects an inside job and has the old gardener and his wife bound for questioning; the wife cries to heaven, the old man stands mute with fear. Pincai drafts a rough inventory and reports the theft. After several ward-office hearings, the answer emerges: the drifter Cai, recently taken on as a helper, used the confusion of Yuan Baozhu's birthday festivities and the temple's traffic of guests to carry off the goods and escape over the wall. The facts are clear; thief and property are gone. The chapter deliberately sets two nights against each other. In one part of the city, Baozhu's birthday gleams with candles, wine, and congratulatory music; in another, a ruined hanger-on searches an empty garden under the cold moon. Beijing pleasure is not one continuous brightness. Just beyond the laughter lies the hollow trunk.`,
  },
  36: {
    zh: `元宵灯节，华光宿命杜琴言登台。琴言病体未复，心中又积满幽恨，演到伤情处竟把戏中泪唱成真泪，粉面纵横。华公子不解其苦，只当有意扫兴，当众斥责，数日不理。琴言被冷落在留青精舍后小院，独对绿萼梅、红梅相映，想起怡园旧日徐子云、萧次贤的温厚，想起梅子玉的病与梦，又恨奚十一、魏聘才、曹长庆等人一步步把自己送入牢笼。正在伤神，林珊枝忽报长庆夜间无疾而卒。琴言闻讯悲痛，又知这是出府的唯一机会，忙求华公子准其奔丧；华公子虽许，却叮嘱事毕即回，不可久留。琴言收拾衣物，乘车出门，像久囚之鸟忽得一线天光，只是丧事尽头，仍有华府高墙在等。`,
    en: `On the Lantern Festival, Hua Guangsu orders Du Qinyan onto the stage. Qinyan is still physically weak and inwardly full of grief; when the role turns sorrowful, performance breaks and real tears stream through the makeup. Hua cannot read the pain beneath the art. He takes it as deliberate gloom, rebukes Qinyan before others, and neglects him for days. Banished to the small rear courtyard of the Liuqing Study, Qinyan sits facing a white-calyxed plum and a red plum blooming together. Their paired fragrance calls up the lost gentleness of Yiyuan, Xu Ziyun and Xiao Cixian's kindness, Mei Ziyu's sickness and fever-dreams, and the chain of harm forged by Xi Shiyi, Wei Pincai, and Cao Changqing. While he is sunk in this grief, Lin Shanzhi arrives with sudden news: Changqing has died quietly in the night, without warning. Qinyan is genuinely shaken, but he also understands that mourning offers the only lawful path out of the mansion. He begs leave to attend the funeral. Hua grants it, but with a cold instruction: finish the rites and return at once. Qinyan packs and rides out, like a bird glimpsing open sky after long confinement; at the far end of mourning, however, the Hua walls still wait.`,
  },
  37: {
    zh: `琴言奔丧期间曾去探望遭盗后的魏聘才，却反遭言语算计与轻薄侮辱，含恨而归，和衣痛哭一夜，悔自己错把旧识当故人。次晨徐子云遣人来召，说梅子玉已在怡园等候，琴言虽头目昏沉，仍强起赴约。梅崦之中，茶花、玉兰先发，梅枝尚含春意；子云因花期未尽，倡作"十日梅"，不设定客，随到随饮。萧次贤信口品评京师消遣，从赌博、看戏、听鼓书到富贵子弟自己粉墨登场，妙语如珠，众人笑倒。王恂又问"人中花与花中花孰美"，引出众人围着美人、名花、知音、占有一番争辩，子云只笑而不判。袁宝珠、王桂保继至，席间谈书论艺，花下行令，梅香把昨夜羞辱、华府拘束、城中势利暂时隔开。对琴言而言，这一日不是解决苦难，而是在苦难中偷得一息清明：他与子玉同在花影里，便如身世还有可栖之枝。`,
    en: `During his mourning leave, Qinyan has gone to visit the recently robbed Wei Pincai, only to be trapped in another scene of insinuation and humiliation. He returns sick with shame, lies down fully dressed, and weeps through the night, cursing himself for mistaking an old acquaintance for a friend. The next morning Xu Ziyun sends word that Mei Ziyu is already waiting at Yiyuan. Though dizzy and hollow-eyed, Qinyan forces himself into the carriage. At the Plum Slope, camellias and magnolias have opened before the plum is fully out, and Ziyun proposes a Ten-Day Plum Gathering: no fixed guest list, no ceremony, only friends arriving when free to drink among the blossoms. Xiao Cixian offers a sparkling survey of Beijing entertainments, from gambling and theatre to storytellers, acrobatic shows, and the absurdity of rich amateurs painting their faces and invading the stage. Wang Xun poses the teasing question of which is lovelier: a flower among people or a person among flowers. The discussion turns around beauty, possession, connoisseurship, and true sympathy while Ziyun smiles and refuses judgment. Yuan Baozhu and Wang Guibao arrive; books, art, wine games, and flower-viewing fill the afternoon. The gathering does not solve Qinyan's suffering, but it grants him one lucid breath inside it. With Ziyu beside him under plum shade, the world still seems to offer one branch on which the heart may rest.`,
  },
  38: {
    zh: `徐子云又在梅崦设一高会，请来老名士屈道生。屈公少孤，连丁九年忧，半生幕游六省，以诗文清苦名世，时人比之杜少陵、孟东野；晚年丧偶归京，囊中无多，书画金石却满载而来。颜仲清、梅子玉、田春航等作陪，袁宝珠、苏蕙芳、陆素兰诸名旦捧砚侍酒，梅花之下儒林与梨园难得同席。屈公细看子玉，见他温润无矜、才气内敛，心中暗赞梅士燮有子。酒酣之后，众人由碑帖源流谈到唐诗正变：仲清主张分辨碑帖，子玉援古例层层辩驳，春航时发警句，屈公则以老成学力折衷裁断，使满座叹服。诸名旦亦各呈书画诗句，请屈公品题；他不以伶人相轻，反能指出各人性情所寄。此回把"品花"提高到真正文艺批评的层面：花不只是色相，也有笔墨、骨气、学问与可传之名。`,
    en: `Xu Ziyun holds a more elevated gathering at the Plum Slope and invites the elder scholar Qu Daosheng. Qu's life has the austerity of an old poem: orphaned young, delayed by nine continuous years of mourning, then wandering for decades as a private secretary through six provinces, admired as a latter-day Du Fu or Meng Jiao, always poor, recently widowed, and returning to Beijing with more books, paintings, and inscriptions than silver. Yan Zhongqing, Mei Ziyu, and Tian Chunhang attend; Yuan Baozhu, Su Huifang, Lu Sulan, and other celebrated performers pour wine and hold inkstones under the plum blossoms. Qu observes Ziyu closely and is delighted by his warmth without vanity and learning without display, silently judging Mei Shixie fortunate in his son. Once wine loosens the table, talk rises from the origins of stele and copybook calligraphy to the orthodox and divergent lineages of Tang poetry. Zhongqing argues from inscriptional evidence, Ziyu answers with layered historical examples, Chunhang contributes sharp observations, and Qu arbitrates with the patient authority of a lifetime's reading. The performers also present poems, calligraphy, and paintings for judgment; Qu does not condescend to them, but reads each work as an extension of temperament. The chapter lifts "grading flowers" into true artistic criticism: beauty is no longer surface only, but brushwork, bone, learning, and the possibility of lasting name.`,
  },
  39: {
    zh: `李元茂入赘孙家的婚事终于办成。王恂居中料理，魏聘才也借机奔走，想在王文辉、孙亮功处重修声气；颜夫人借出珠冠补服，十六盒彩礼虽多半仰仗周全遮掩，也总算撑起门面。吉夕，梅子玉、颜仲清、王恂陪元茂小饮，众人以诗句打趣新郎；元茂自言近视也有好处，若新人丑便看不清，若美则更添朦胧，引得满座大笑。孙宅鼓乐迎门，洞房花烛，喜气中带着几分寒素与将就：新娘本是前妻之女，不甚得继母宠爱，元茂则因有了归宿和饭碗而心满意足。聘才此前往颜家套近，却因子玉已知他在琴言事上助纣为虐，只得了冷淡礼数。婚宴的笑声之下，人情账本暗暗翻页：有人得偶，有人求势，有人失信，旧日梅宅的亲厚已经被华府阴影割出裂痕。`,
    en: `Li Yuanmao's marriage into the Sun household is finally accomplished. Wang Xun manages the arrangements, while Wei Pincai busies himself partly to repair his standing with Wang Wenhui and Sun Lianggong. Madam Yan lends a pearl coronet and ceremonial garments; the sixteen betrothal trays rely heavily on borrowed splendour, but the display passes. On the auspicious evening Mei Ziyu, Yan Zhongqing, and Wang Xun drink with the groom and tease him in mock-solemn verse. Yuanmao declares that near-sightedness has its advantages in marriage: if the bride is plain, he will not see it clearly; if she is beautiful, the blur will only improve her. Laughter covers much awkwardness. Drums and pipes greet them at the Sun residence; the bridal chamber is proper but modest. The bride, a daughter of the first wife, is not especially favoured by her stepmother, while Yuanmao is delighted simply to have acquired a household and future meals. Pincai's earlier call on the Yan house goes less happily. Ziyu, now aware of Pincai's part in the pressure on Qinyan, receives him with cool courtesy rather than old warmth. Beneath the wedding laughter the moral ledger turns another page: one man gains a match, one seeks influence, one has forfeited trust, and the shadow of the Hua mansion cuts through former intimacy.`,
  },
  40: {
    zh: `奚十一为琴言之事作恶多端，报应先从最腌臜处开花。他弃旧怜新，春兰、巴英官等早已寒心，私下数落他用机关桶子害人、以银钱凌辱少年、翻脸无情的旧账，只等看天道如何收拾。奚十一一日独入寺中，见小厮得月酣睡，色心顿起，正欲轻薄，不料得月腹泻骤发，秽物喷涌，弄得他满身狼藉，仓皇败退；淫念遇污秽，正是以其人之浊还治其浊。潘其观也在寺中赌场日久，输多赢少，赊欠烂账，又仗富商面皮赖账不还，终被众人揪住痛打，鼻青脸肿，体面扫地。奚十一一臭，潘其观一打，看似闹剧，实是小说的因果算盘清脆作响：凡以钱势欺人、以欲念害人者，未必立刻败亡，却必先在可笑处现出丑相。`,
    en: `The consequences of Xi Shiyi's conduct toward Du Qinyan and others begin in the most fittingly filthy register. He has discarded old favourites for new ones until even Chunlan and Ba Yingguan are cold with resentment; in private they catalogue his cruelties — the trick barrel that trapped victims' hands, the boys humiliated by money and force, the ease with which he turns on anyone no longer useful. They wait to see how heaven will answer. One day Xi slips alone into the temple, sees the young attendant Deyue asleep, and reaches toward him with predatory intent. At that exact moment Deyue is seized by violent diarrhea, and the eruption covers Xi in stench and humiliation. Lust meets filth; the punishment is grotesque, but morally exact. Pan Qiguan receives his own answer. Long haunting the temple gambling tables, losing more than he pays and hiding behind a merchant's face of respectability, he finally exhausts his creditors' patience and is seized and beaten until all dignity is gone. Xi is befouled; Pan is battered. The scenes are farce, but the novel's moral abacus clicks audibly beneath them: those who use money and desire to injure others may not fall at once, but their ugliness first reveals itself as ridicule.`,
  },
};
