export const summaries31to40: Record<number, { zh: string; en: string }> = {
  31: {
    zh: "华公子酒宴将散，命众旦各展所长——琴箫合奏、丹青题诗、笙琵竞鸣、猜谜舞剑，雅趣横生。杜琴言却托病离席，独坐屏后，难掩心中悲凉。座中文人互相品评书法诗词，梅子玉与众人就翰墨之道争辩不休，一时高论迭出。夜深宴罢，子云提议以戏文题目行令，众人竞猜，热闹喧天。琴言困于繁华之中，愈发思念旧日自由，悲从中来，暗自垂泪，乐声与愁绪交织，欢笑背后尽是难言的身世之感。",
    en: "As Hua Guangsu's midnight banquet winds down, the host commands each young performer to demonstrate a hidden talent beyond mere singing: Du Qinyan plays a halting qin while a flute-player soothes the room with smoother melodies, others compose verse on newly painted scrolls, juggle riddles, or brandish a sword in the lamplight. The scholars fall to debating calligraphy and poetry — Mei Ziyu holding his own against elder wits with quiet confidence. When the feast clears, Xu Ziyun proposes a round of matching opera titles, and shouts of laughter fill the hall. Yet Qinyan sits apart, pleading illness. The sound of music only deepens his longing for the freedom he has lost; trapped inside Hua's gilded cage, every burst of applause feels like another bar on the door. Surrounded by revelry and candlelight, he weeps alone behind the screen, his grief invisible to the guests and unbearable to himself. Joy and sorrow, beauty and captivity — the chapter holds them side by side without resolving the tension.",
  },
  32: {
    zh: "秋雨连绵七八日后初晴，贡院放榜在即，场中士子无不魂不守舍、寝食难安。高品与田春航彻夜长谈，忆起往年问卜中举的笑话，苦中作乐。苏蕙芳比春航更为焦急，坐卧不宁，遣人打探消息，心中挂念远胜儿女私情。报喜声终于传来，几家欢喜几家愁——高品榜上有名，春航名落孙山。消息在怡园迅速传开，众人或贺或慰。蕙芳闻讯，百感交集，深知才情不敌八股，科场公道从来难料，惟将一腔情义深埋心底。",
    en: "After a week of relentless autumn rain the sky finally clears, and the examination results are due within days. Every candidate in the capital is sleepless with anticipation — even the usually composed Gao Pin and Tian Chunhang lie awake through the night, swapping stories of divination disasters from previous sittings. Gao Pin recalls a hexagram that seemed to promise first place on the list, yet delivered nothing; both men laugh ruefully at the unreliability of omens. Su Huifang, waiting alone at home, proves more agitated than the candidates themselves: she dismisses a visiting official, presses every servant for news, and spends the afternoon pacing between the couch and the window. When the runners finally arrive, the results bring sharply mixed fortune — Gao Pin's name appears on the list, but Chunhang's does not. The news moves swiftly through the social circle, drawing congratulations and consolations that often arrive at the wrong door. Huifang receives the tidings with a complicated heart, aware that talent and the eight-legged essay are uneasy companions, and that the examination hall has never been a reliable court of justice.",
  },
  33: {
    zh: "腊月时节，史南湘随任出京，众名士相送，知己又少了几人。梅子玉偶遇袁宝珠，被邀入其精致书斋「小琅室」，见壁悬名迹、案置梅花，雅洁脱俗。两人煮雪烹茶，又邀陆素兰同来，共作清谈雅叙。宝珠忆及落难画师金粟，含泪长叹，子玉随口触动其心事，忙以竹石之语转圜解围。席间子玉婚事被一语道破，他只淡淡推说家信未回，神情间却另有隐衷。窗外寒梅暗香，室内风雅依旧，然离别与羁绊的况味，早已渗入每一壶茶香之中。",
    en: `As the year draws to a close, Shi Nanxiang departs Beijing to take up his new posting, leaving the circle of intimates noticeably thinner. Mei Ziyu, setting out on a city errand he abandons halfway, chances upon Yuan Baozhu in a lane jammed with camels and carriages. Baozhu leads him to his exquisite study, the \"Xiaolang Chamber,\" where potted narcissi, a spray of winter plum in a bronze vase, and scrolls by old masters create an atmosphere of spare refinement entirely free of official pomposity. They melt rooftop snow for tea and invite Lu Sulan to join them for an afternoon of cultured conversation. When Ziyu casually praises Baozhu's steadfast loyalty to the disgraced painter Jin Jifu — supporting him financially through disgrace and penury — Baozhu's composure suddenly gives way. Tears come unbidden; the poet White's lines about fellow wanderers fall from his lips. Ziyu hastily redirects the talk toward the plum branch outside. Someone mentions Ziyu's impending marriage; he deflects quietly, saying the family letter from Jiangxi has not arrived. The afternoon passes in elegant talk, yet beneath the refinement, longing and constraint run like cold water beneath winter ice.`,
  },
  34: {
    zh: "魏聘才从华府出走，寄居唐和尚处，债台高筑，年关将近却囊空如洗。李元茂登门借钱，聘才当场抖出一叠债单自证穷困，两人相互倒苦水，不欢而散。入夜，聘才被唐和尚邀谈密事，言辞含糊，隐现算计之意。元茂厚颜留宿，借烟吃点心，呼奴唤婢，扰得聘才不得安宁。寺中气氛暧昧，金钱纠葛与人情算计交织其间，一干闲人在岁末寒夜中各打各的算盘，市井江湖的势利面孔，在这逼仄的禅房里显得格外分明。",
    en: "Having left the Hua household, Wei Pincai takes lodgings at a temple run by the monk Tang Heshang, a host of dubious piety. The new year looms and his debts are mountainous — tailors, restaurants, and sundry creditors have all sent bills totalling over five hundred strings of cash, and he has nothing to show but a few fur coats he cannot afford to pawn. Li Yuanmao arrives that afternoon hoping to borrow forty taels; Pincai theatrically produces his entire stack of IOUs to demonstrate that he is himself bankrupt. The two men trade extravagant complaints over dinner, each convinced the other is secretly flush. Late at night Tang Heshang summons Pincai for a whispered consultation whose purpose remains strategically vague. Yuanmao, too thick-skinned to take a hint, installs himself for the night — demanding pipe tobacco, fruit, and snacks, keeping the servant rushing between rooms until well past the third watch. Pincai lies on his side and ignores everything. The cramped temple room, thick with lamp-smoke and mutual self-interest, becomes a perfect small theatre of year-end desperation: everyone plotting, no one solvent.",
  },
  35: {
    zh: "一夜之间，聘才寄存的箱笼、拜匣遭贼洗劫，金银细软悉数被盗，仅余几件棉衣和一块摔碎的洋表。众人趁月色搜查菜园，发现空箱弃于墙角，灌园伙计神秘失踪。唐和尚疑是内贼，将种菜人夫妇绑缚审问，老婆子哭天抢地。聘才清点损失逾千金，草草报了官，坊里几番审讯，终查明是那新来伙计蔡某借机逃盗，案情虽明，人却早已无踪。宝珠生日喜宴与聘才的遭窃之夜遥相对照，世间悲喜从不相让，热闹与凄凉往往只隔一墙之遥。",
    en: "The night's festivities at the temple end in catastrophe. When Pincai returns to his room he finds it stripped bare — the trunk and document-case gone, carrying off fifteen taels of gold, two hundred taels of silver, a package of opium, jade trinkets, and several fur garments, the combined loss exceeding a thousand taels. The household rushes into the moonlit vegetable garden by the light of a full moon and discovers only the emptied trunk abandoned near the wall, a pocket-watch smashed to splinters on the ground. The garden-hand who was supposed to be on night watch has vanished entirely. Tang Heshang immediately suspects an inside job and has the old gardener and his wife bound as accomplices; the wife wails her innocence to the heavens while her husband stands too frightened to speak. Pincai drafts a hasty inventory and files a report with the ward office. Several hearings follow, ultimately confirming that the real culprit is the recently hired drifter Cai Mou, who exploited the evening's confusion to rob and flee. The theft is confirmed; the thief is gone. Across the city that same night, Yuan Baozhu's birthday banquet glittered with wine and music — a reminder that fortune and ruin share the same Beijing air.",
  },
  36: {
    zh: "元宵佳节，华公子命琴言登台演戏。琴言身体欠安，心中更是悲怆，演至动情处竟真情流露、泪洒台上，华公子大为不悦，将其痛斥一番，此后数日将其晾在一旁。琴言独居小院，对着盛开的绿萼梅与红梅，满心思念怡园旧日时光，又恨奚十一当年陷害之仇。正凝神伤感间，林珊枝带来噩耗——其师傅于睡梦中猝然离世。琴言强忍悲痛，趁机出府奔丧，然华公子叮嘱不可久留，须事毕即回。这一场出走，是笼中鸟短暂的振翅，归处依然是那四面高墙。",
    en: "On the Lantern Festival, Hua Guangsu orders Du Qinyan to perform. Qinyan is unwell and burdened with grief; during the performance, moved beyond control by the scene's emotions, real tears stream down his painted face. Hua takes this as insubordination and delivers a furious dressing-down in front of the entire household, then ignores Qinyan for days. Relegated to a small side-courtyard at the back of the Liuqing study, Qinyan sits alone before two blossoming plum trees — a white-calyx variety and a red — and thinks of the Yiyuan and his unfailing gentleness, so different from this cold hierarchical household where every favour from the master breeds fresh resentment among the servants. He broods on Xi Shiyi's treachery, on the duplicity of those who arranged his captivity, on the impossibility of escape. Then Lin Shanzhi appears with news: Qinyan's master-teacher has died quietly in his sleep overnight, without illness or warning. Qinyan is granted leave to attend the funeral. He packs quickly and slips through the front gate into a waiting carriage — a caged bird briefly tasting open air. But Hua's parting instruction follows him out the door: finish the mourning rites and return immediately.",
  },
  37: {
    zh: "琴言昨日探望聘才，却遭算计受辱，含恨而归，彻夜哭泣，悔不当初。翌日清晨，徐子云遣人相召，言梅子玉已先到园中等候。梅崦中，早春的茶花与玉兰正盛，梅花尚未开遍。子云提议以十日梅叙会友，不拘人数多寡，随兴而至。萧次贤纵论时人消遣之道，从赌博看戏到登台唱曲，信口谑语，满座皆笑。王恂以「人中花与花中花孰美」为题，引得众人争辩，子云笑而不答。少顷宝珠、桂保到来，席间众人谈书论艺，月下品花，怡园一日，竟如世外桃源，暂将城中一切烦扰隔绝于梅香之外。",
    en: "Reeling from a humiliating encounter with Wei Pincai the previous afternoon, Du Qinyan returns to his room in Hua's compound, lies down fully dressed, and weeps through the night, cursing his own naivety. The next morning a messenger from Xu Ziyun arrives: Mei Ziyu is already at Yiyuan and waiting. Qinyan, dizzy and hollow-eyed, forces himself into a carriage and makes the journey. In the Meiyan pavilion, early camellia and magnolia are in full bloom; the plum itself is still coming on. Ziyun proposes a Ten-Day Plum Gathering — an open invitation for any friend with a free afternoon to come and sit among the flowers without ceremony or fixed numbers. Xiao Cixian delivers an irreverent catalogue of the lesser amusements available to Beijingers: gambling dens, trick wrestlers, blind storytellers, drum-and-gong performances, and the ultimate lowbrow pleasure of paint-faced amateurs storming the opera stage. The scholars agree that flower-viewing with wine is the summit of earthly happiness. Wang Xun teases Ziyun with the question of whether a beautiful person among flowers or a beautiful flower among people deserves greater admiration. Yuan Baozhu and Guibao arrive, and the afternoon deepens into book-talk and unhurried laughter. For a few hours, the plum garden quietly seals out the world.",
  },
  38: {
    zh: "徐子云在梅崦设宴，请来老名士屈道生，颜仲清、梅子玉、田春航等作陪，宝珠、蕙芳、素兰等名旦侍席。屈公身世坎坷，连丁九年忧、宦游四方，以诗文名重一时，时人比之杜少陵、孟东野。席间屈公细察子玉，见其温润儒雅、气象冲虚，心中大喜，暗赞「梅铁庵可为有子矣」。酒酣之际，众人就书法源流与诗歌正统展开一场高谈阔论：颜仲清主张碑帖之别，子玉援引古例力辩，屈公从容裁断，见识深远，令众人叹服。名旦们捧砚拂笺，亦得屈公一一品题，儒林与梨园在梅香中难得相遇，各见风流。",
    en: "Xu Ziyun hosts a more elevated gathering in the Meiyan pavilion: the distinguished elder scholar Qu Daosheng, lately retired from a magistracy in Jiangxi, is the guest of honour. Yan Zhongqing, Mei Ziyu, and Tian Chunhang attend as company; Yuan Baozhu, Su Huifang, and Lu Sulan serve wine and hold ink-stones at the table's edge. Qu's biography is quietly extraordinary: orphaned young, nine consecutive years of mourning rites that kept delaying his examinations, then decades of wandering as a private secretary across six provinces, admired by contemporaries as a new Du Fu or Meng Jiao, yet perpetually short of money, recently widowed, and returning to Beijing with more books and antiques than silver. At table he observes Ziyu with growing delight — the young man's bearing is warm without vanity, his learning worn lightly — and privately thinks: Mei Shixie has genuine reason to be proud. When wine has loosened tongues, a spirited debate erupts over the origins of calligraphy and the true lineage of Tang poetry. Zhongqing argues from stele inscriptions; Ziyu deploys historical precedents; Qu arbitrates with the unhurried authority of sixty years' reading. The performers, permitted to sit close and listen, receive from Qu a few words of genuine appreciation — a rare currency from the literary world to theirs.",
  },
  39: {
    zh: "李元茂的婚事终于办妥，招赘入孙家，王恂居中奔走，聘才代为料理礼仪。颜夫人借出珠冠补服，铺设十六盒彩礼，场面勉强撑得起门面。吉日当晚，子玉、仲清、王恂陪席，互赠戏谑诗句，元茂自言若新人略丑也无妨，近视眼自有近视眼的好处，引得哄堂大笑。孙宅鼓乐迎门，洞房花烛，喜气之中却带着几分将就与凑合。与此同时，聘才为向王文辉示好特意奔走，却在颜家碰了软钉子——子玉对他的态度明显冷淡，往日亲厚已成过眼云烟，种种旧账在笑语之下暗暗计算，人情冷暖尽在这一场婚宴之中。",
    en: "Li Yuanmao's long-deferred marriage to a daughter of the Sun household is finally accomplished. Wang Xun manages the logistics; Wei Pincai volunteers as go-between, partly to re-ingratiate himself with Wang Wenhui. Lady Yan lends a pearl coronet and official robes to fill the sixteen betrothal trays with enough borrowed splendour to maintain appearances. On the wedding night, Ziyu, Zhongqing, and Wang Xun join the groom for dinner and exchange mock-solemn verses: Wang Xun wishes him riches to white-haired old age, and Ziyu quotes a comic couplet about a near-sighted man squinting at his new bride. Yuanmao cheerfully declares that near-sightedness has its advantages in the bridal chamber — if she is plain, he will not notice; if she is beautiful, he is robbed. Laughter covers the awkwardness. Drums and pipes welcome the party at the Sun residence. The ceremony is quietly modest; the bride is the first wife's daughter and not especially favoured by her stepmother. Meanwhile, Pincai's earlier visit to the Yan house to pay his respects goes poorly: Ziyu, now aware of what happened at the Hua household through Pincai's connivance, is visibly cooler than before. Old warmth has curdled into polite distance, and under the wedding-night laughter the moral accounting quietly continues.",
  },
  40: {
    zh: "奚十一曾以琴言之事大闹上门，种下的恶因如今开始结出报应之果。他弃旧怜新、玩弄情义，春兰、巴英官皆对其寒心，私下历数他昔日种种不堪，尤其那只诓人的机关桶子，不知害了多少无辜。奚十一一日独自入寺，见得月酣睡，意图轻薄，不料得月腹泻骤发，秽物喷涌，弄得狼狈不堪。另一边厢，潘其观长期于寺庙赌场厮混，输多赢少，欠下烂账，终至众怒，被人揪住痛打，颜面尽失。两人一臭一打，皆因平日作恶多端，天道轮回，报应不爽，令旁观者拍手称快。",
    en: "The moral ledger begins at last to balance. Xi Shiyi, who engineered Du Qinyan's entrapment in Hua's household, has meanwhile exhausted the patience of every companion he has kept. His discarded partners Ba Yingguan and Chunlan compare grievances in private, cataloguing his habitual cruelties: the toy-box device with an internal lock that trapped two hands inside and left victims helpless, which victimised unknown numbers of young men before it was finally confiscated and smashed. They wonder aloud when heaven will call in the debt. Heaven obliges shortly afterward, in a manner both apt and undignified: sneaking alone into the temple to molest the sleeping young attendant Deyue, Xi Shiyi finds his advances interrupted by a sudden and violent bout of Deyue's stomach trouble. The scalding, malodorous eruption sends Xi Shiyi scrambling backward in total humiliation — his lust doused as thoroughly as any bucket of cold water could manage. Pan Qiguan, whose habit of haunting the temple gambling tables has accumulated unpayable debts, fares no better: his creditors finally corner him and administer a comprehensive beating. Two villains, two perfectly calibrated degradations — one drenched in filth, one battered black and blue — as the novel signals, with some relish, that accounts will be settled.",
  },
};
