export const summaries51to60: Record<number, { zh: string; en: string }> = {
  51: {
    zh: `孙嗣徽、孙嗣元兄弟赴通州院考，科场丑态尽出。嗣徽暗花银子雇枪手代笔，自以为稳妥；嗣元却在卷上胡涂乱写，字句不成文理，被宗师当堂点出讥笑。嗣徽竟厚着脸皮上前替弟分辩，说他素有痰迷心窍、手腕发颤等病，才致文章离奇，荒唐言辞惹得诸生哄堂，连宗师也斥其如疯。李元茂反倒侥幸入泮，得了秀才，心满意足，觉得从此可以在孙家抬头。考毕他独往运河边散步，见粮船如云，商贩叫卖，水陆喧阗，一派世俗热闹。此回以院考闹剧照出功名制度的破绽：有钱者买文，愚者乱涂，厚颜者强辩，而元茂这样的庸人却也能混得一纸身份。运河晚景越繁华，科场笑声越显薄凉。`,
    en: `Sun Sihui and Sun Siyuan go to the Tongzhou prefectural examination, and the examination system promptly reveals its comic seams. Sihui secretly pays a substitute writer and imagines the matter secure; Siyuan, hopeless as ever, fills his paper with incoherent scrawl until the examiner publicly mocks it. Sihui, with astonishing nerve, steps forward to defend his brother, inventing medical explanations involving phlegm, clouded consciousness, and trembling wrists to account for the nonsense. The hall erupts, and the examiner himself dismisses him as half mad. Li Yuanmao, meanwhile, somehow scrapes through and becomes a licentiate, delighted less by learning than by the new status it gives him in the Sun household. After the exam he wanders along the Grand Canal at dusk, where grain boats crowd the water, vendors call, and ordinary commerce hums with indifferent life. The chapter uses farce to expose the fragility of merit. Money buys a writer, stupidity fills a page, shamelessness argues in public, and a mediocre man still obtains a credential. Against the lively canal, the laughter of the examination hall sounds especially thin.`,
  },
  52: {
    zh: `七月博学鸿词科将近，四方名士云集京师，而田春航迎娶苏侯之女更成一时盛事。苏家妆奁丰厚骇人，田宅一时容纳不下，徐子云便借出东厢大宅襄助；园中宾客如云，车马塞巷，两班戏子争妍，苏蕙芳仍以"苏大爷"身份在内外奔走，安排席位账目，既像主人，又不能真作主人。席间高品借演《当巾》暗讽春航昔日落魄，春航即以郑元和故典巧妙还击，众人听得又笑又服；诗文戏谑之间，旧贫新贵、情义亏欠都被包进机锋。梅子玉勉强扶病赴席，见繁华满眼，却因琴仙远在南中、音问稀少而神思黯然，旁人都知他心事，只能用劝酒谈笑替他遮掩。此回把婚礼写成命运交汇处：春航得科名与新妇，蕙芳得尊称而无名分，子玉在人声鼎沸中更觉孤独。`,
    en: `By the seventh month the special Examination for Broad Learning and Extensive Words draws scholars from across the empire to Beijing, but Tian Chunhang's wedding to Su Hou's daughter becomes the more dazzling event. The Su dowry is staggering, beyond the capacity of Chunhang's own house, so Xu Ziyun lends an eastern wing of his residence. Guests crowd the garden, carriages block the lanes, two theatrical troupes compete in brilliance, and Su Huifang, still called "Master Su," rushes between seating, accounts, servants, and ceremonial details — functioning like a host without being allowed fully to be one. At the banquet Gao Pin chooses the opera piece Pawned Headscarf to needle Chunhang over his former poverty; Chunhang parries with a deft allusion to Zheng Yuanhe, turning embarrassment into wit. The table laughs, but beneath the cleverness lie old hardship, new rank, and debts of feeling. Mei Ziyu forces himself from illness to attend. Surrounded by wedding splendour, he is subdued, haunted by Qinxian's absence in the south and by the thinning of letters. Everyone understands, and everyone covers it with wine and conversation. The chapter makes the wedding a crossing of fates: Chunhang gains office and bride, Huifang gains honour without status, and Ziyu becomes lonelier in the midst of noise.`,
  },
  53: {
    zh: `华光宿追索一柄题有桃花画的团扇，陆素兰携扇赴约，本是还物小事，却在西园秋色中化为一段风雅因缘。华公子见素兰清致，命他即席填《梁州序》词咏扇上桃花；素兰含羞援笔，词意婉丽，字势秀劲，华公子击节称赏，遂以己扇相赠，又题诗酬答。二人一来一往，既有主客礼数，也有艺术相知，华府对梨园的占有欲在此暂时转作鉴赏之情。另一边，苏蕙芳、袁宝珠、王兰保等聚在一处，商议借怡园隙地开设古董书画铺，将徐子云园中多余旧藏与诸人眼力化为生计。众人计算货源、门面、分润，兴致勃勃，仿佛要在风月之外另辟一条自立之路。此回一写扇面题词，一写开铺谋生，都关乎艺术如何从玩赏之物变成人情与生计的凭据。`,
    en: `Hua Guangsu sends for Lu Sulan over a peach-blossom fan, ostensibly to reclaim an object that has passed into the wrong hands. In the autumn light of the West Garden, the errand becomes an artistic encounter. Seeing Sulan's quiet grace, Hua asks him to compose a lyric in the demanding Liangzhou Xu mode on the painted blossoms. Sulan demurs, then takes up the brush; the lyric is delicate, the calligraphy strong and elegant, and Hua is moved into genuine praise. Fans are exchanged, poems inscribed, and for a moment the Hua household's usual impulse to possess theatrical beauty is transmuted into connoisseurship. Elsewhere, Su Huifang, Yuan Baozhu, Wang Lanbao, and companions plan a more practical venture: an antiques and painting shop in a corner of Yiyuan, stocked from surplus pieces in Xu Ziyun's collection and sustained by their own eyes and reputations. They discuss goods, location, shares, and management with lively seriousness. The chapter's two halves mirror each other. A fan becomes a token of artistic recognition; a shop becomes a possible livelihood. Art is not only something to admire — it is also social currency, friendship's medium, and a path toward self-support.`,
  },
  54: {
    zh: `梅子玉日夜思念远在南中的琴仙，又梦见他憔悴悲啼，醒后心绪如焚，却仍强振精神应博学鸿词科。三场试卷，他经义、策论、赋诗皆如泉涌，八篇制义、两篇大赋、限韵诗赋无不清警，终以第二名取中，殿试更蒙钦点第一，年纪最轻而授翰林编修。荣耀骤至，他却不见骄色：颜仲清、高品皆落第，子玉反觉自己得意处正触友人失意，逐一往慰，言辞谦抑，几如致歉。颜夫人欣喜非常，梅宅上下也开始料理他与王琼华的婚事，功名与婚姻一齐逼近。此回写子玉才华终于被朝廷承认，却并不让成功冲淡相思；相反，越是金榜题名，越见琴仙缺席，越觉人生被公事、家事、情事三股线缠紧，光华之中自有清寒。`,
    en: `Mei Ziyu is consumed by thoughts of Qinxian in the south and shaken by a dream in which the beloved appears gaunt and sorrowful. Yet he forces himself into the special examination for Broad Learning and Extensive Words, and grief becomes a strange fuel. Across the three rounds his mind pours forth: classical essays, policy discussions, grand fu compositions, and poems on restricted rhymes all come with luminous ease. He places second in the main ranking and then first in the palace round, the youngest of the cohort, and is appointed Hanlin Compiler. But triumph never quite reaches his face. Yan Zhongqing and Gao Pin have both failed, and Ziyu feels his success as something that touches their disappointment; he visits each with a humility almost like apology. Madam Yan is overjoyed, and the Mei household begins preparing in earnest for his marriage to Wang Qionghua. The chapter allows Ziyu's genius public recognition, but refuses to let glory cure longing. Indeed, the higher his name rises, the more sharply Qinxian's absence is felt. Office, family marriage, and private devotion tighten around him together; the light of success has a cold edge.`,
  },
  55: {
    zh: `琴仙随屈道翁顺运河南下，舟行如展长卷，却处处含旧梦残痕。过扬州小虹园，昔日文酒名胜已成断垣荒草，蝉声满树，道翁感慨盛衰，琴仙亦觉繁华不过水上浮花。至莲花桥、平山堂一带，游船中两个盐商妇人见琴仙秀美，竟抛来果包，道翁笑称"安仁掷果"，琴仙羞得满面通红，坚不肯食。抵南京后，他因梦兆与杜姓因缘，独往莫愁湖寻杜仙女墓；湖烟荒冢之间，似见红衣影子，若有若无，既像前缘显现，又像命运警示。琴仙心神震动，久久不能平复。此回的山水不只是游览，而是身世的照影：废园照繁华易尽，掷果照色相招人，杜墓照他从琴言到琴仙仍未解尽的前生后事。`,
    en: `Qinxian travels south with Qu Daoweng along the Grand Canal, the journey opening like a handscroll whose beauty is threaded with ruin. Passing Yangzhou's Little Rainbow Garden, they find a place once famous for literary banquets reduced to broken walls, wild grass, and cicadas; Daoweng sighs over rise and decline, and Qinxian feels how easily splendour becomes a flower on water. Near Lotus Bridge and Pingshan Hall, two salt-merchant women on a pleasure boat, struck by Qinxian's beauty, toss a bundle of fruit toward him. Daoweng laughs at the classical allusion to Pan An being pelted with fruit, while Qinxian blushes fiercely and refuses to eat any of it. In Nanjing, drawn by dream omens and the resonance of the Du name, he slips alone to Mochou Lake in search of the Lady Du's grave. Among lake mist and a desolate mound, he seems to glimpse a red-clad figure, half apparition, half sign. The encounter leaves him trembling, as if past life and future warning have brushed the same sleeve. The chapter's landscapes are mirrors: ruined garden for vanished prosperity, thrown fruit for dangerous beauty, the Du grave for the unresolved mystery of Qinyan becoming Qinxian.`,
  },
  56: {
    zh: `屈道翁在南京舟中一跌，牵动积年旧疾，咳血昏沉，病势日重。逆风又阻舟泊燕子矶，行程不得前，琴仙衣不解带侍奉汤药，代道翁写信料理官事；夜深船舱摇晃，他又取出梅子玉来诗，斟酌和词，字字都像在远水中投递心声。后移居护国寺养病，道翁时醒时昏，知自己气数将尽，最放心不下的不是官职行李，而是琴仙孤身无靠。琴仙在佛前焚香叩祷，愿减己寿以代义父之死，词极哀切；道翁闻之泪下，既感其孝，又怜其命薄。其间仆从张贵、钱德等渐露不可靠之相，为后文失窃埋下阴影。此回把南行诗情忽然转入病榻寒灯，父子之义在生死边上显得格外清亮。`,
    en: `A fall aboard the boat in Nanjing awakens Qu Daoweng's long-stored illness. He coughs blood, drifts in and out of consciousness, and weakens by the day. Contrary winds trap the boat at Yanzi Cliff, delaying the journey, while Qinxian tends medicine and bedding without undressing, writes official and personal letters at Daoweng's dictation, and tries to hold the collapsing household together. At night, in the rocking cabin, he takes out Mei Ziyu's poem and composes a lyric response, weighing each word as though sending his heart across water. They move into Huguo Temple to nurse the old man, but the decline continues. Daoweng knows his end is near; what troubles him most is not office or luggage, but the future of the boy he has adopted and transformed. Qinxian burns incense before the shrine and prays to give his own life in exchange for his father's, in language of devastating simplicity. Daoweng hears and weeps, moved by the filial devotion and pierced by pity for Qinxian's loneliness. In the background, servants such as Zhang Gui and Qian De begin to show signs of unreliability, darkening the edge of the sickroom. The chapter turns the southern journey's poetry into lamp-lit mortality, where adoptive father and son are bound most clearly at the brink of death.`,
  },
  57: {
    zh: `十月怡园菊盛，袁绮香设宴于宝香堂，邀苏浣香、吴紫烟、颜蓉华、王琼华、梅琼华等名门才媛同赏。堂中锦褥翠幕，七层菊山金紫交辉，香气满袖，车轿往来如一队流动花影。诸夫人本各有门第礼数，酒过数巡，竟仿竹林七贤结为姊妹，序齿排行，改称相呼，约定日后抛却客套。席间行酒令、联诗句、评花品色，才思敏捷，不让前文男客花会；袁绮香主持风雅，苏浣香明艳，吴紫烟清旷，诸人各有声口。此回把叙事从名士、名旦转入闺阁世界，显示女性也能自成文会、自立品评尺度。菊花耐霜，正照出这些贵族女子在礼法帷幕内仍能盛放的聪慧与锋芒。`,
    en: `In the tenth month chrysanthemums fill Yiyuan, and Yuan Qixiang hosts a banquet in the Precious Fragrance Hall for the capital's accomplished women: Su Huanxiang, Wu Ziyan, Yan Ronghua, Wang Qionghua, Mei Qionghua, and others arrive in sedan chairs, perfume, and bright conversation. The hall is transformed with silk cushions, green curtains, and seven tiers of chrysanthemum displays, gold and purple blazing together. At first the ladies observe the forms of rank and household, but after several rounds of warm wine they imitate the Seven Sages of the Bamboo Grove and form a sworn sisterhood, ranking themselves by age, changing how they address one another, and agreeing to abandon stiff ceremony. Drinking games, linked verses, flower judgments, and teasing unfold with a brilliance equal to any male literary gathering earlier in the novel. Yuan Qixiang presides with elegant authority; Su Huanxiang is radiant, Wu Ziyan spacious and clear, each woman distinct in voice. The chapter shifts the narrative into the inner world and shows that women too can create a society of wit, criticism, and pleasure. Chrysanthemums endure frost; so do these women bloom within the curtains of propriety.`,
  },
  58: {
    zh: `奚十一的报应由臭与打之后，终于落到钱根上。洋行倒闭，盐场漂没，家中来信催逼，他昔日挥金如土的豪气一夕成空，只得向潘其观告贷。潘其观趁火打劫，二千两现银要他立万两欠票，满口仁义，实则剥皮；奚十一忍气签押，昔日"烟熏太岁"竟在怯商面前低头。夜归之后，他独吸鸦片，身体旧疾未除，心中烦闷；小妾白菊花因寂寞窥见下人春兰私情，既恼其放肆，又酸自己被冷落，欲怒不能，欲笑还悲。色欲场中的主仆尊卑至此颠倒成一片荒唐。此回写奚十一财色两败：钱被债票缚住，身被病根缚住，内宅也失去控制。昔日以银子践踏他人的人，如今被银子、肉身与家丑三面围困，因果之网越收越紧。`,
    en: `After stink and beating, Xi Shiyi's retribution reaches the root of money. His family's foreign-trade business collapses, storm damage ruins the salt works, and letters from home press him for funds. The man who once scattered silver through the pleasure quarters must borrow from Pan Qiguan. Pan, smelling weakness, lends two thousand taels only in exchange for a promissory note of ten thousand, wrapping extortion in the language of friendship. Xi signs in humiliation; the "Smoke-Blackened Grand Duke" bows before the timid banker he once treated as comic company. That night he returns home, smokes opium alone, still afflicted in body and spirit. His concubine Juhua, neglected and restless, spies the servant Chunlan in a compromising scene behind a closed door. She is angry at the insolence, sour with jealousy, and bitterly amused by her own abandonment. Master, servant, lover, and dependent all blur into sordid farce. The chapter shows Xi defeated on every front: money bound by debt, body bound by disease, household slipping beyond command. He who used silver to trample others is now hemmed in by silver, flesh, and domestic shame.`,
  },
  59: {
    zh: `屈道翁卒后，琴仙在南京护国寺守灵百余日，张贵、钱德卷逃财物，盘缠耗尽，衣裳典尽，随从刘喜只得在庙门卖果，琴仙则以道翁所授丹青自活，在生纸上画牡丹、梅花等花卉售人，竟得路人赏识，价钱渐起，甚至有人订八扇屏。贫寒中，他仍守孝读书，风骨不坠。侯太史闻其美名，携金而来，口称怜才，实欲趁孤危收为己有；琴仙冷若冰雪，拒不受银，也不肯移居其家，使这位道貌岸然的名士露出贪色本相。无奈之下，琴仙写信给梅子玉、徐子云、苏蕙芳等求援，信中既陈困厄，也不失礼度；对子玉一封尤为缠绵克制，像寒寺残灯中仍护着一粒炭火。此回写琴仙从被赏玩的"花"变成能以画花自养的人，贫到极处，反显出不可买的清贵。`,
    en: `After Qu Daoweng's death, Qinxian remains at Nanjing's Huguo Temple for more than a hundred days of mourning. Zhang Gui and Qian De have fled with valuables, travel funds are exhausted, warm clothing is pawned, and the loyal Liu Xi can only sell fruit at the temple gate. Qinxian survives by using the painting Daoweng taught him, brushing peonies, plum blossoms, and other flowers on raw paper for passers-by. To his surprise, people admire them; prices rise, and someone even commissions an eight-panel screen. Poverty does not strip him of discipline: he keeps mourning, reads, paints, and preserves his bearing. Then Hou Taishi arrives with gold, speaking the language of pity and talent while plainly hoping to take advantage of Qinxian's isolation. Qinxian receives him with winter-cold dignity, refuses the money, and will not move into his household, exposing the eminent scholar's lust beneath moral varnish. At last Qinxian writes to Mei Ziyu, Xu Ziyun, Su Huifang, and others for help, each letter courteous and controlled; the one to Ziyu is especially restrained and tender, like an ember guarded in a cold temple. The chapter's transformation is profound: the once-admired "flower" now paints flowers to live, and in utmost poverty becomes visibly unbuyable.`,
  },
  60: {
    zh: `元宵佳节，琴仙历尽南中病死、守灵、贫困、拒诱诸劫后重回京师，徐子云在怡园大宴群友，名士名旦灯下重聚，烟火照夜如昼，旧日艰辛恍若一梦。梅子玉与琴仙相见，悲喜都收在风雅礼数之中；众人把酒谈及屈道翁，皆感其一片苦心并未随身而灭。金吉甫于是提议，将九香楼诸花与相关人物绘成花神图，各撰传赞，勒石传世，使一时声色不随岁月零落。众人拈阄分题，偏偏子玉得琴仙与杜仙女二题，似有前缘暗合，满座称奇。席间诗画并作，诸友各以才情为花立传，也为自己这一段相知立碑。小说至此收束：琴言由名旦而琴仙，由被品评者而入画传名；子玉的情、子云的义、道翁的教、众人的风流，都在艺术中获得暂时超越生死的归宿。`,
    en: `The Lantern Festival brings Qinxian back to Beijing after the ordeals of the south: Daoweng's illness and death, mourning, poverty, temptation, and survival by the brush. Xu Ziyun hosts a great gathering at Yiyuan, where scholars and performers reunite under lanterns and fireworks bright enough to turn night into day. Mei Ziyu and Qinxian meet again, their grief and joy contained within the courtesies of refined company. Talk turns to Qu Daoweng, and everyone feels that his labour of love must not vanish with his body. Jin Jifu gives the evening its enduring form: the beauties and affiliated figures of the Nine Fragrance Pavilion should be painted as flower deities, each with a biography and encomium, then carved in stone so that a season of living beauty will not scatter with time. Lots are drawn for assignments, and fate shows its hand: Ziyu receives Qinxian and the Lady Du, the two figures most deeply bound to his own heart. Poems, portraits, and prose begin to take shape around the table. The novel closes not by undoing loss, but by consecrating it. Qinyan has become Qinxian, no longer merely appraised as a flower but preserved as one who can enter art and memory; Ziyu's feeling, Ziyun's generosity, Daoweng's teaching, and the whole fellowship's fragile brilliance find their final refuge in making beauty transmissible.`,
  },
};
