export const summaries41to50: Record<number, { zh: string; en: string }> = {
  41: {
    zh: "春光正盛，华公子携夫人泛舟园中，穿桥过堤，赏碧桃、听流水，好不惬意。然琴言假期已满迟迟未归，公子心存挂念。游罢留仙院，宴席摆开，觥筹交错间，众人谈笑风生。丫鬟金龄、玉龄划桨忙乱，险些翻船，惹得满船欢笑。这一片春日浮生，歌舞笙箫，衬得园外的波谲云诡更显遥远——不知那位令公子朝思暮想的人，此刻身在何处。",
    en: "Spring is at its most lavish in the Garden of Ease. Hua Guangsu invites his wife aboard a lacquered pleasure boat and drifts through arched bridges and willow-lined causeways, pausing to admire the pink-and-white peach blossoms of Liuxian Pavilion while the water chimes against copper fittings like a set of jade chimes. The maidservants Jin Ling and Yu Ling take the oars with more enthusiasm than skill, spinning the craft in helpless circles and drenching themselves—sending the whole party into laughter. Wine and sweetmeats are laid out in a garden pavilion, and for one luminous afternoon the world seems perfectly arranged. Yet beneath the festivity Hua's thoughts keep drifting to Du Qinyan, whose leave of absence has long expired with no word of return. The idyll is shot through with quiet unease: pleasure and longing turning slowly in the same current.",
  },
  42: {
    zh: `师父长庆刚入土，师娘便算起了经济账。她拦住琴言，开口便要一月二百吊钱的养膳，言辞软硬兼施，暗指若无钱则出师无望，此生便要挂在她门下。琴言进退两难：既不知华府每月给了多少，又难以开口向公子讨要，更不敢轻易答应一个空头承诺。师娘步步紧逼，琴言愁眉苦脸，只得以"进府商量"搪塞。这场关于钱与自由的角力，才刚刚拉开帷幕。`,
    en: `The ink on the mourning documents for the troupe master Cao Changqing is barely dry before Changqing Shiniang turns her attention to money. Cornering Qinyan after breakfast, she lays out the household's annual expenses with the precision of a ledger-keeper: three thousand strings of cash are needed each year, and two hundred a month from Qinyan alone will do nicely. She invokes loyalty, gratitude, and the specter of lifelong servitude in a single breath. Qinyan listens in stunned silence. He has no idea what the Hua household paid his late master, no courage to raise the subject with the young lord directly, and no savings of his own to offer as surety. The widow's logic is airtight and her warmth is entirely transactional. Qinyan deflects with a promise to raise the matter once he returns to the Hua estate—but both of them know that the question of his freedom has now been given a price tag.`,
  },
  43: {
    zh: "宝珠与素兰闻知师娘索钱之事，立刻各有主意。素兰一拍手便断言：出师最妙！但三千两银子从何而来？二人你来我往，盘算着谁能替琴言出这笔钱。话锋一转，议及子云——怡园的徐子云素来慷慨，且对琴言颇有情谊。若能由他出面，以赎身之名将琴言从师娘手中赎出，既解了燃眉之急，又给琴言留了余地。谋议已定，众人心照不宣地去赏杏花，让这一桩关乎命运的密谋，在春花烂漫中悄然成形。",
    en: "Yuan Baozhu and Lu Sulan arrive to find Qinyan in a fog of anxiety. The moment they hear about Changqing Shiniang's demands, Sulan slaps her palm on the table: the answer is obvious—buy out his indenture. The sum required is three thousand taels. Silence falls. Then the two begin to think aloud, turning the problem over like a merchant examining a stone for flaws. The name Xu Ziyun rises naturally: master of the Garden of Ease, patron of talent, a man whose generosity is as reliable as the seasons. If Ziyun were to offer the money under the guise of a formal redemption, it would satisfy the widow's greed while giving Qinyan a dignified path to freedom. The plan takes shape quickly, almost too quickly. As the conspirators leave together to view the apricot blossoms that Duxiang has arranged, the afternoon air feels charged—a future is being quietly negotiated beneath the falling petals.",
  },
  44: {
    zh: "琴言出师之日，华府的跑腿姚贤出城寻人，却从麻子嘴里听到一个惊天消息：有江南人替琴言出了师，人已走了！姚贤惊慌失措，辗转打探，偶遇子云家人孟七，方知真相——正是徐子云以两千四百五十两银票，替琴言赎了自由身。消息传回华府，公子大为震怒，却也无可奈何。而此刻琴言已悄然住进怡园，从牢笼般的旧日身份中挣脱出来，开始了一段崭新的人生。",
    en: "On the very day Xu Ziyun's silver drafts change hands at the Rixin money-house, Hua's manservant Yao Xian sets out from the estate to fetch Qinyan back. At the troupe house he finds only the pock-faced Mazi, who delivers the news with maddening vagueness: someone from Jiangnan has bought Qinyan out of his indenture and taken him away. Yao Xian ricochets between outrage and bewilderment, buttonholing passersby until he runs into Meng Qi, one of Xu Ziyun's household men. Over wine in a noodle shop the whole story comes tumbling out—two drafts totaling two thousand four hundred and fifty taels, signed and sealed, the widow satisfied. Qinyan is free. The news lands at the Hua estate like a stone in still water, sending ripples of fury outward. But the deed is done: Qinyan has slipped quietly into the Garden of Ease, no longer anyone's property, beginning life over on entirely new terms.",
  },
  45: {
    zh: "怡园春深，琴言在子云、次贤的悉心开导下，渐渐收拾起愁绪。牡丹台、芍药圃，每日皆有文人名旦相聚，吟花斗酒，好不风雅。入夜，子玉趁着一钩新月，独自来访。两人在海棠春圃相遇，凭栏闲话，子玉说海棠之香藏于花肌深处，非凝眸久视不得，须以心闻之。琴言俯身嗅花，若有所悟，莞尔点头。月色如水，花影婆娑，一段久别重逢的情谊，在夜风中悄悄复苏。",
    en: "The Garden of Ease receives Qinyan like a convalescent receiving clean air. Xu Ziyun and Xiao Cixian take turns drawing him out of his melancholy, and the garden's procession of flowering terraces—the peony platform today, the peony meadow tomorrow—gives the days a gentle, healing rhythm. Then one evening Mei Ziyu steals away alone under a new crescent moon, unable to wait for a more convenient occasion. He finds Qinyan in the crabapple grove, leaning against a Taihu stone in a pale blue jacket, lost in thought. They fall into conversation as naturally as if no months of estrangement had intervened. Ziyu holds forth on crabapple fragrance—a perfume so reticent, he says, that it refuses to announce itself, arriving only when you have looked at the blossom long enough to deserve it. Qinyan bends a branch down and inhales, then nods slowly, his face softening into the smile that has been absent all spring. The moon climbs; the flowers breathe. Something between the two young men, which had been held in suspension, quietly resumes.",
  },
  46: {
    zh: `屈道翁入住怡园，收琴仙为义子，日授诗词文章，晨昏对课，父慈子孝，竟如亲生。琴仙天资聪颖，过目成诵，半月之内文理大进。道翁为园作序，文采斐然，子云喜而欲勒石永存。二十八日，子云大开园会，诸名士齐聚含万楼，道翁改楼名为"赐书楼"，并题长联，语惊四座。众人分题赋对，赞颂园景，觥筹往来，笑语盈园。雅集之乐，至此达于鼎盛。`,
    en: "Scholar Qu Daoweng takes up residence in the Garden of Ease and formally adopts Qinyan as his son, renaming him Qinxian. From dawn to dusk he teaches classical texts, poetry, calligraphy, and the rhythms of parallel prose. Qinxian proves a scholar's dream: he memorizes on first reading, asks questions that go straight to the marrow of a passage, and practices his brushwork long after his teacher has retired for the night. Within a fortnight the transformation is visible. Qu Daoweng also composes a preface for the garden—a piece of such lapidary elegance that Xu Ziyun immediately commissions a stone engraving. On the twenty-eighth day of the month Ziyun throws open the garden gates for a grand literary gathering. The scholars rename the main tower Cishulou, the Tower of Imperial Books, and Daoweng brushes a paired couplet that sweeps from the classical canons to the great philosophical masters, from ten thousand li of landscape to five thousand years of history. The assembled company falls silent, then breaks into applause.",
  },
  47: {
    zh: "南湘、春航双双高中进士，蕙芳欣喜之余，为二人张罗搬迁事宜。徐子云慷慨邀请入住怡园，奈何春航急于接家眷，另觅新宅。而奚十一病愈后旧习难改，伤处留下隐疾，内外皆难应酬，苦不堪言。一日去宏济寺谢恩，偶见寺旁新开了一家奇特医馆，院中立着各色怪人，隐隐透出一股市井江湖气——奚十一的那桩荒唐求医之旅，就此埋下伏笔。",
    en: "The examination results arrive like a spring thunderclap: Tian Chunhang has taken first place in the palace examination—zhuangyuan, top of the empire—and Shi Nanxiang has placed fourth in the second tier. Su Huifang, who staked years of earnings and devotion on Chunhang's success, learns the news with a happiness that seems to exceed even the winner's own. The social machinery of the capital immediately begins to turn: visits to examiners, banquets, reassignments of lodging. Xu Ziyun generously offers accommodation, but Chunhang, eager to receive his family, seeks quarters elsewhere. Through all of it Huifang arranges, mediates, and pays, seemingly tireless. Meanwhile, across the city, Xi Shiyi has recovered from his mysterious illness but is left with a debilitating private affliction. Proud and desperate in equal measure, he seeks a cure through increasingly unorthodox channels, and a chance visit to a temple leads him past a roadside clinic staffed by practitioners whose methods appear to belong somewhere between medicine and circus. The farce that follows sets the novel's comic register against its romantic one with characteristic precision.",
  },
  48: {
    zh: `屈道翁领了南昌通判，怡园即将失去这对父子。名士们轮流为琴仙饯行，依依惜别。春航高中状元，苏侯一见倾心，欲招为东床，惜已有妻，遗憾而止。不料家书传来噩耗：春航之妻已于二月间暴病亡故。悲喜交集之际，老母与舅父又将同赴京城。蕙芳一力操持新宅事宜，感情深厚却身份尴尬，冷暖自知。春航命下人从此称蕙芳为"苏大爷"，这一声称呼，含尽了感激、亏欠与无言的承诺。`,
    en: `The Garden of Ease prepares for a departure. Qu Daoweng has received his appointment to Nanchang and will leave within days, taking Qinxian with him. The farewell banquets multiply—scholars, performers, friends who have shared the garden's charmed months—and each one carries the particular weight of partings that feel permanent. Amid the valedictions, Tian Chunhang is navigating the afterglow of his triumph. The powerful Su Hou, father-in-law to Hua and patron of letters, meets Chunhang and is enchanted; he would dearly like him as a son-in-law, but learns the young man already has a wife. Then a letter arrives from home. Chunhang's wife has died in February. The news collapses him. Su Huifang—who built this success from the ground up, spending every string of cash he had saved across years in the quarter—holds the household together without being asked. Chunhang formally instructs his servants to address Huifang as Master Su. The title confers no legal standing, but it is the most honoring thing he knows how to give.`,
  },
  49: {
    zh: `琴仙离京后，子玉大恸，旧病复发，足月方愈。春航家中断弦，太夫人无人服侍，苦于北地难觅贤婢。赶车的周小三推荐了他三姐，那三姐扎着蛾眉，腰细如柳，进门一见，令春航大为惊异。三姐千伶百俐，上下周到，老太太喜欢，蕙芳也待她有几分异样的亲近。一日蕙芳独坐书房，三姐奉命送点心进来，两人相对，各自心事，一时皆沉在那一声软软的"苏大爷"里。`,
    en: `Mei Ziyu escorts Qinxian to the city gate and watches the carriage diminish into the road dust. The grief hits him like a physical blow: his old illness returns, and he spends a month confined to bed. When he recovers, the city feels rearranged. Tian Chunhang, newly widowed, faces his own domestic crisis. His elderly mother is installed in the new house but accustomed to Southern refinement; the succession of Beijing housemaids she tries proves uniformly unsuitable—one a tireless gossip, another with the habits of a tavern regular. It is the coachman Zhou Xiaosan who solves the problem by recommending his own sister, Xu Sanjie. She arrives looking understated and capable, with a waist like a willow stem and eyes quick with intelligence, and both the old lady and Chunhang are immediately won over. Su Huifang, organizing the household as always from an ambiguous position between guest and steward, finds himself unexpectedly charmed when she addresses him one afternoon—soft-voiced, smiling—as Master Su. A small moment, but the novel watches it with careful attention.`,
  },
  50: {
    zh: "盛夏炎炎，春航已与苏侯之女订下婚约，七夕完婚在即。刘文泽路过林春喜门口，顺道拜访，见他书室幽雅，芭蕉叶上密密写满了练笔的字，院中支着小卷篷，盆景点缀其间。春喜将团扇递来，上面画着螳螂捕蝉，栩栩如生，叫文泽看得目瞪口呆。原来春喜这几个月悄悄钻研绘画，已大有长进，连素来挑剔的瑶卿也甘拜下风。文泽索扇不得，讨来一把，心满意足而去。才情与风雅，在这一片消夏的蝉声里，轻盈地流转。",
    en: "Midsummer in the capital: the heat sits on the city like a lid. Tian Chunhang is promised in marriage to Su Hou's second daughter, the wedding fixed for the Double Seventh. Liu Wenze, newly posted to the Board of Personnel, drops in on Lin Chunxi while making his rounds—more from habit than any urgent errand. He finds Chunxi in a state of cheerful self-improvement. The banana plants in the rear courtyard have been pressed into service as a practice surface: both sides of every broad leaf are covered in calligraphy of varying sizes, written, wiped clean, and written again. A small pavilion shades the front yard; miniature landscapes crowd the windowsills. Then Chunxi produces a round fan and holds it up—a mantis seizing a cicada, wings splayed, eyes bulging with predatory intensity, rendered with a confidence that stops Wenze mid-sentence. Chunxi has been studying painting in secret for months, learning from drafts and ignoring the condescension of a rival performer who refused to share technique. Yuan Baozhu, passing by, stops to admire the work. The fan changes hands over token protests. Intelligence and aesthetic ambition, the novel suggests, flourish quietly even in the hottest, most distracted season.",
  },
};
