export const summaries0to10: Record<number, { zh: string; en: string }> = {
  0: {
    zh: `两篇序文揭开了《品花宝鉴》的神秘面纱。

第一篇序者自称"幻中了幻居士"，盛赞此书兼得"绘形"与"绘声"之妙，将其与《聊斋》《红楼梦》并列，誉为说部中"另具一格"之作。他辗转从友人处借抄，历经七月校订，才将这部险些湮没的手稿刻版流传。第二篇序文则出自作者石函氏之手，娓娓道来创作缘起：他客居京都，科场失意，借问于歌楼舞榭间消遣苦闷，由此得识梨园声色之美、伶人性情之真伪。友人比部力劝他将亲历见闻写成小说，言词间自有褒贬，此即《品花宝鉴》诞生之契机。两篇序文相互辉映，一为传播者的感慨，一为创作者的夫子自道，共同构成这部奇书的入口。`,
    en: `Two prefaces open the doors of Pinhua Baojian. 

The first, by a writer styling himself "Master of Illusion within Illusion," lavishes praise on the novel's rare ability to evoke both image and sound — ranking it alongside Strange Tales from a Chinese Studio and Dream of the Red Chamber as a singular achievement in Chinese fiction. He describes his painstaking effort to borrow and copy the manuscript from friends, spending seven months in editorial revision to rescue it from near-oblivion before it could be printed. The second preface is the author's own voice: failing the imperial examinations, he found himself stranded in Beijing, drowning his frustrations nightly in the pleasure quarters of the theater world, where he learned to distinguish genuine feeling from performance, elegance from vulgarity. A friend urged him to transform these observations into a novel — and so Pinhua Baojian was born. Together, the two prefaces frame the work beautifully: one a reader's astonished discovery, the other a writer's candid confession, both insisting that even in this world of play and artifice, something true and human can be found.`,
  },
  1: {
    zh: `开卷先立一副品评的尺度。京师歌台舞榭甲于天下，作者遂以游戏之笔摹写游戏之人：将缙绅子弟按"情"字分作正、上、高、逸、华、豪、狂、趣、和、乐十等，又将梨园名旦分作至、慧、韵、醇、淑、烈、直、酣、艳、媚十等；而淫、邪、黠、荡、贪、魔、祟、蠹八种下流，则不配以"情"字相加。六十卷《品花宝鉴》的褒贬，由此定下基调。

继而引出主人翁的家世：翰林院侍读学士梅士燮，金陵阀阅，三代单传，貌肃如秋而心和似春；夫人颜夫人于二十九岁上梦神人授玉，遂生梅子玉，今年十七，貌如良玉，质比精金，虽居罗绮丛中而绝无纨绔习气。一日先生放学，表兄颜仲清偕解元史南湘联袂来访——仲清三岁失怙，其母郑氏绝食殉节，由士燮抚养成人，后赘于王文辉家为婿。南湘忽以"世间何物最能娱耳悦目、动心荡魄"相诘，见子玉支吾其词，便从靴中取出新刻的《曲台花选》，历数袁宝珠、苏蕙芳、陆素兰、金漱芳、李玉林、王兰保、王桂保、林春喜八人的色艺，每人各系品题与赠诗。子玉看罢只是冷笑，力言以色事人者身既难洁、志亦太卑，天地灵秀只钟于女子。二人不服，援《毛诗》《赤壁赋》与陆闳、陶侃诸典相驳，又以梅花南枝先发、翎羽之美独在雄鸟为喻；子玉脸红语塞，心下将信将疑。

越两日，他往访表兄王恂，王恂径拉他上戏园——满园黑相公穿梭寻主，一个名字与袁宝珠仅差一字的蠢笨少年竟来摸他的手，子玉如坐涂炭，托词先归。归途车马拥塞，忽闻一缕非兰非麝的清香，掀帘望去，对面车中并坐两个妙童：一个艳若海棠，一个以玉为骨、以月为魂。四目相接，神摇目眩，车已过去。到家犹自恍惚，方悟南湘所言竟非虚妄。`,
    en: `The novel opens by laying down a scale of judgement. Beijing's theatres outshine all the empire's, and the author proposes to paint this world of play with a playful brush: gentry patrons are graded into ten degrees of "feeling" — upright, lofty, untrammelled, splendid, gallant, wild, playful, harmonious, joyous — and the celebrated dan performers into ten of their own; while eight baser types (lechery, corruption, cunning, dissipation, greed, obsession, malice, parasitism) are denied the word "feeling" altogether. This is the moral tuning-fork for all sixty chapters of Pinhua Baojian. Then the household: Mei Shixie, Hanlin Reader-in-Waiting, of an old Jinling line three generations sole-descended, austere as autumn in his bearing and mild as spring in his heart. 

At twenty-nine his wife Lady Yan dreamed that a spirit placed jade in her hands, and bore Mei Ziyu — now seventeen, fine as tempered gold, raised amid silk without a trace of the wastrel. One idle afternoon his cousin Yan Zhongqing arrives with the provincial laureate Shi Nanxiang. (Zhongqing lost his father at three; his mother Lady Zheng starved herself to follow her husband, and Mei Shixie raised the orphan, later marrying him into Wang Wenhui's household.) Nanxiang poses a challenge — what in this world most delights the eye and shakes the soul? — and when Ziyu equivocates, produces from his boot his freshly printed Qutai Huaxuan, cataloguing the beauty and artistry of eight performers: Yuan Baozhu, Su Huifang, Lu Sulan, Jin Shufang, Li Yulin, Wang Lanbao, Wang Guibao, and Lin Chunxi, each with an appraisal and a verse. Ziyu is unmoved. Those who trade on their looks, he argues, can keep neither their bodies clean nor their ambitions high; heaven's grace settles on women alone. His friends rebut him with the Mao Shi, the Rhapsody on the Red Cliff, and the histories of Lu Hong and Tao Kan, and with homelier proofs — the plum's south branch blooms first, and among birds it is always the male that wears the splendour. Ziyu flushes and falls silent, half-persuaded. 

Two days later he calls on his cousin Wang Xun, who hauls him off to a theatre, where the aisles teem with coarse boys hunting patrons and one dull-witted youth — whose name differs by a single character from Yuan Baozhu's — takes hold of his hand. Ziyu escapes as if from hot coals. Homeward, his carriage jams in the traffic; a scent that is neither orchid nor musk reaches him, and lifting the curtain he sees two boys seated in the opposite carriage — one lovely as a crab-apple blossom, the other with jade for bone and moonlight for soul. Their eyes meet; the carriage rolls on. He reaches home still dazed, and understands at last that Nanxiang was not exaggerating.`,
  },
  2: {
    zh: `子玉一路想着车中所见的绝色，到家却撞见父亲正陪王文辉说话。二人先议开春同年团拜，已定下联锦班在姑苏会馆演戏，只是外放出差者众，怕凑不满四席；继而文辉托梅士燮为次女琼华物色佳婿，两人感叹择婿之难——尽有外貌甚好而内里平常者，也有小时聪明而大来变坏者。话未了，仆妇捧上两张红帖：一署"世愚侄魏聘才"，一署"门下晚学生李元茂"，都是自江南远道投奔而来。

花厅相见，两人判若云泥：魏聘才身材瘦小、面目伶俐，抢步上前满面堆笑便跪下叩头；李元茂却身形笨浊、浓眉近视，高高一揖后徐徐跪拜，如拜神像，掀唇咕噜一句竟无人听懂。士燮命许顺收拾书房后身两间屋子安置，又叫子玉引二人去见西席李性全。不过十日，那张千伶百俐的嘴已把满宅人哄得交口称好。

一夕元茂睡下，聘才与子玉闲话，先问相公之风，继而绘声绘色说起自己自扬州搭叶茂林的戏船北上，同舟十个苏州买来的孩子里，有琪官色如脂粉初调，更有一个姓杜的琴官，"世间的颜色比不上，画师也画不出这样神情"。子玉不动声色，逐一盘问衣色、同车何人、车围骡色、教师年纪，一一相符，这才拍手大笑——原来车中绝色正是此人。次早聘才携小厮四儿去投书，先会了颜仲清，继而王文辉归来，盘腿高坐，一面追述其父当年因刀笔损了阴骘而失掉解元，一面自夸三品京堂的俸银，说得聘才局促不安，心中暗比：这老头儿的架子，远不及梅老伯。是日王宅设宴，孙亮功携王桂保入席；席间行打擂令、飞花令，孙亮功装作小旦捧杯敬酒，学尽联锦班京丑的丑态，又被桂保吹了满脸梅花瓣，笑倒一堂，末了家人耳语一句，他便失色催饭而去。宴散，桂保得赏二十两，转到书房告诉王恂与仲清：班里新来了琴官、琪官两个，色艺俱佳，只怕史南湘的《花选》又要翻刻了。`,
    en: `Still turning over the face he glimpsed in the carriage, Ziyu comes home to find his father in conference with Wang Wenhui. The two are settling the New Year cohort banquet — the Lianjin troupe engaged, the Suzhou Guild Hall booked, though with so many colleagues posted away they may not fill four tables — after which Wenhui asks Mei Shixie to look out for a husband for his second daughter Qionghua, and the pair fall to lamenting how treacherous such choices are: handsome outsides that prove ordinary within, clever boys who curdle as they grow. A servant then brings in two red cards: one from "your unworthy nephew Wei Pincai," the other from "your humble student Li Yuanmao," both newly arrived from the south. 

In the reception hall the contrast is comic. Wei Pincai is slight and quick-eyed, springing forward all smiles to drop into a kowtow; Li Yuanmao is heavy and short-sighted, bowing high and then sinking slowly to his knees like a man saluting a temple idol, mumbling something no one can make out. Shixie has the steward Xu Shun prepare two rooms behind the study, and sends Ziyu to present them to the tutor Li Xingquan. Within ten days Pincai's nimble tongue has charmed the entire household. 

One evening, with Yuanmao asleep, he draws Ziyu into talk — first about the strange deference shown to actors in the capital, then about his own journey north, sharing a canal boat from Yangzhou with Ye Maolin and ten boys bought in Suzhou. Two were extraordinary: Qiguan, whose colour seemed mixed from powder and rouge, and a boy surnamed Du called Qinguan, whose beauty "no shade in the world can match, and no painter's brush record." Ziyu keeps his face still and cross-examines him — the colour of the robes, who shared the carriage, the blue cloth curtain, the white mule, the teacher's age — and when every detail answers, claps his hands and laughs aloud: these are the very boys. Next morning Pincai takes his page Si'er to deliver a letter, meets Yan Zhongqing, and then Wang Wenhui himself, who sits cross-legged in state, recalls how Pincai's father forfeited a provincial first place because a brush-and-knife omen appeared on his examination cover, and boasts of a third-rank stipend until his guest squirms — Pincai privately judging him far beneath the elder Mei. That evening Wang Wenhui feasts his cohort; Sun Lianggong arrives with Wang Guibao, and the drinking games turn riotous, Sun Lianggong mincing about in imitation of a dan actor to press wine on the guests, then blinded by plum petals Guibao blows into his face — until a whispered word from a servant sends him hurrying home to his formidable wife. Rewarded twenty taels, Guibao stops by the study to tell Wang Xun and Zhongqing of two newcomers, Qinguan and Qiguan, so gifted that Shi Nanxiang may have to reprint his Selection of Flowers.`,
  },
  3: {
    zh: `魏聘才误了饭点，管事许顺留他在账房同吃，饭罢从紫竹书架上翻出一册刻本《曲台花选》，袖回房中细读，将八位名旦的色艺一一记熟，暗想京中相公果然名不虚传，却又疑心琴官的姿容未必输于此辈。正想着，叶茂林同联锦班大掌班金二来定堂会戏，为"分包"一事与许顺往复争执，末了议定正月初六在姑苏会馆开演。叶茂林又把园中行头脚色、堂会排场说得天花乱坠，并告知琴官正在师傅长庆处养病，琪官则定于腊月初十登台。

次日聘才带小厮四儿独往三乐园听联珠班的戏，但见楼上楼下相公穿梭，倚肩偎坐，应接不暇。邻座来了个胖子富三爷与七品小京官贵大爷，相公蓉官过来陪坐，说起青姨奶奶、白姨奶奶摔碗打架的家务丑事，语带尖酸，笑倒一座。忽有个颈生肉瘤的卖玉老者兜售琥珀鼻烟壶，索价十两，聘才随口还他二两，不料对方一口应承；聘才身边无银，正尴尬间，台上一声齐声喝彩，他身子一动，烟壶坠地摔碎，老者遂就势讹诈六两。亏得富三爷伸手喝止，赏了四百钱了事。聘才这才知二人一名富伦、一名贵芬，富伦之父曾任江宁藩司、广东巡抚，遂盛赞其父在南京已立名宦祠、水旱瘟疫屡屡显圣，哄得富伦十分受用。

楼上另有一个青黑脸的广东豪客，气焰逼人，那卖玉老者上楼兜搭，竟被家人乱推乱撵，砸了满盘料器，含泪而下。四人转往馆子小酌，隔壁恰是那豪客与相公春兰赌气：一个骂，一个砸，杯碗尽碎，末了掀翻桌子，四条大狗抢食满地，掌柜的赔笑打圆场，还教走堂的下回换细瓷来砸，好教大老爷听个清脆。原来此人是广东巨富奚十一，携十几万银子入京捐官，正是众人眼中的冤桶。散席时富伦抢着会账，约聘才次日到东城金牌楼相访。归家夜话，子玉又问琴官脾气，聘才只说他心里嵌着一块水晶，又硬又冷，任你怎样巴结也换不来一笑。子玉听了反而神往：这般清高自爱，才算十全人物，只怕落在庸耳俗目之中反要遭人白眼；一片怜惜，就此不知不觉系在琴官身上。`,
    en: `Wei Pincai, having missed the household meal, is invited to eat in the accounts room by the steward Xu Shun, and afterwards pulls a thin printed volume — the Qutai Huaxuan — from a bamboo shelf. Back in his room he reads it through, fixing in memory the eight performers and their arts, half convinced that the capital's famous boys deserve their fame, half suspecting that Qinguan's face would outshine them all. He is interrupted by Ye Maolin, who arrives with Jin Er, chief manager of the Lianjin troupe, to book the New Year performance; the two haggle with Xu Shun over whether the troupe may "split" its engagements, and settle at last on the sixth day at the Suzhou Guild Hall. Ye Maolin then paints the theatre in glowing colours — the costumes, the casts, the splendour of private banquets — and mentions that Qinguan is convalescing at his teacher Changqing's house, while Qiguan is to take the stage on the tenth. 

The next day Pincai takes his page Si'er to the Sanle Garden to hear the Lianzhu troupe, and finds the galleries thick with performers drifting from patron to patron, leaning on shoulders, settling at elbows. At the next table sit a stout man addressed as Third Master Fu and a seventh-rank clerk called Eldest Master Gui; the actor Rongguan joins them and retails, with acid sweetness, the domestic warfare between Concubine Qing and Concubine Bai — smashed porcelain, beaten maids — until the whole table is helpless with laughter. Then an old curio hawker with a swollen growth on his neck presses an amber snuff bottle on Pincai at ten taels; Pincai idly counters with two, and to his horror the old man accepts. He has no silver on him, and while he sits paralysed a roar of applause goes up, he starts, and the bottle shatters on the floor — whereupon the hawker demands six taels for the wreckage. Third Master Fu intervenes, silences the man, and settles it with four hundred cash. Only now does Pincai learn their names: Fu Lun and Gui Fen. Told that Fu Lun's late father served as provincial treasurer at Jiangning and governor of Guangdong, he launches into flattery — a shrine to the old man now stands in Nanjing, he says, and his spirit answers prayers in flood and plague — and Fu Lun glows with pleasure. 

Upstairs sits a dark-faced Cantonese grandee whose servants, when the hawker tries his luck there, shove the old man out bodily, smashing half his tray; he limps away in tears. The four adjourn to a restaurant, where the next room holds the same grandee quarrelling with the actor Chunlan: he curses, the boy smashes a cup, he smashes another, until the table itself goes over and four dogs fight over the spilled dishes. The proprietor soothes him with smiles and instructs the waiter to bring finer porcelain next time, so the breaking will ring more sweetly. This is Xi Shiyi, a Cantonese millionaire come to buy office with a hundred thousand taels — the fattest pigeon in Beijing. Fu Lun seizes the bill and invites Pincai to call on him at the Gold Tablet Tower. Home that night, Ziyu asks again about Qinguan's temper, and Pincai says the boy has a shard of crystal set in his heart, hard and cold, and that no amount of courting will buy a single smile. The answer only deepens Ziyu's fascination: such proud self-possession is the mark of a complete soul — and precisely what the vulgar world will punish. Without knowing it, his tenderness has fastened on Qinguan.`,
  },
  4: {
    zh: `李元茂推门惊呼，原来腊雪骤至，一夜积了五寸，琼装玉琢，天地改观。西席李性全冒寒受了风，头晕咳嗽，自己抓了几味发散药蒙头睡去，子玉遂得半日清闲，独坐二十四琴斋——匾额还是其祖手笔——翻谢惠连《雪赋》消遣，读到"皓鹤夺鲜，白鹇失素"，叹古人摹绘之工。旋命厨下备馔，请魏聘才、李元茂同来赏雪。

席间又问琴官，聘才见他上心，索性改了口风，将琴官的身分性气大赞一场，说得子玉愈发倾慕，想此雪天若得见琼枝玉立，何异瑶岛看花。饭后煮雪煎茶。俄而俊儿送上颜仲清书信，附诗笺四纸：王恂的《雪山》《雪塔》《雪屏》《雪灯》，仲清的《雪狮》《雪猫》《雪罗汉》《雪美人》。子玉品评一过，觉仲清"奈他鼠辈只趋炎"一联寓意深长，才思犹在王恂之上。他不肯依韵唱和，另辟蹊径，从未下雪之前着想，以四个虚字连雪成题：《雪意》《雪影》《雪声》《雪色》，落笔便成。聘才凑了一首七绝，实是暗集《走雪》《独占》的曲文；元茂则一本正经献上五律，"白人双目近，长马四蹄轻""掘阅蜉游似，挖空狮子成"，不知所云。三卷同送过去，仲清一眼看破聘才用的是戏文，仍批"得天公玉戏之神"；至元茂诗则通篇密圈，批以"裁对工稳，用古入化"，王恂笑说挖苦得太狠。

次日雪霁，二人同车来访，路遇孙嗣徽满口之乎者也，说父母反目、请王大夫诊治，仲清叹这"虫蛀千字文"生可为名、死可为谥。到了梅宅，众人互评诗作，元茂把批语揣进怀里反复端详，又把"大作谅来多"听成皮褂虫蛀，闹了个满脸通红。仲清、王恂辞出后同往下洼子看雪，远眺怡园琪树参差、层楼耀目，路上遇见花榜最幼的林春喜，说起八人在怡园三日一聚的消寒会，今日以《冰床》命题，苏媚香夺魁，他自己与王蕊香因倒了平仄同居末座；又道班中新来琴官、琪官，琴官几与瑶卿不相上下，徐度香一见便重制衣饰相赠。正说着，对楼窗开，一位面如冠玉的美少年携蓉官、玉美、四喜等人凭窗而坐，议论戏曲，谓与其戏雅而人俗，不如人雅而戏俗，又说胡琴之声如怨如慕，听之落泪，非世人所谓淫声。仲清暗惊此人清狂绝俗，决非庸碌之辈。少年索笔在粉墙上题《浪淘沙》一阕，落款"湘帆醉笔"，飘然而去；问店家，竟无人知其姓名。`,
    en: `Li Yuanmao bursts in with an alarm that proves to be snow — five inches fallen overnight, the world remade in white jade. The tutor Li Xingquan, chilled and coughing, doses himself with a dispersing draught and takes to his bed, and Ziyu inherits a free afternoon. He settles in the Twenty-Four Qin Chamber, whose plaque was brushed by his own grandfather, and reads Xie Huilian's Rhapsody on Snow, admiring the ancient art of description in the line about cranes and silver pheasants outshone. Then he orders dishes brought and invites Wei Pincai and Li Yuanmao to view the snow with him. 

Over the cups he returns to Qinguan, and Pincai — seeing where his host's heart lies — abandons his earlier scorn and praises the boy's breeding and spirit until Ziyu's longing sharpens: to meet such a person in such a landscape would be to walk among the immortals' flowering isles. Tea is brewed from melted snow. Then his page Junner brings a letter from Yan Zhongqing enclosing four sheets of verse — Wang Xun on the snow mountain, snow pagoda, snow screen, and snow lantern; Zhongqing on the snow lion, snow cat, snow arhat, and snow beauty. Ziyu judges Zhongqing the finer hand, especially the couplet on vermin that crowd toward warmth. Rather than answer in the same rhymes he opens new ground, taking his titles from the moment before snowfall: Snow Feeling, Snow Shadow, Snow Sound, and Snow Color. Pincai contributes a quatrain quietly assembled out of the libretti of Walking in Snow and Exclusive Possession, while Yuanmao gravely produces a regulated poem of magnificent nonsense — white men with close-set eyes, long horses of light hoof, mayflies boring out and lions hollowed. All three go across the city. Zhongqing spots the stolen libretti at once but writes an indulgent line of praise; Yuanmao's effort he circles throughout and commends for its faultless parallels and masterly use of the ancients, until Wang Xun protests that the joke is too cruel. 

Next morning, in clear frozen sunlight, the two friends drive over and meet Sun Sihui on the road, who explains in unbroken classical tags that his parents have come to blows and Doctor Wang has been called — leaving Zhongqing to observe that Worm-eaten Primer is a name fit to serve the man in life and as his posthumous title too. At the Mei house the poems are traded and admired; Yuanmao tucks his notice into his jacket, rereads it repeatedly, and then mishears a compliment about his prolific verse as a remark about moths in his fur coat, blushing scarlet. Afterwards Zhongqing and Wang Xun walk out to view the snowfields, the distant Yi Garden rising in tiers of gleaming towers, and meet Lin Chunxi, youngest of the Flower Register, returning from it. He tells them of the winter club that meets there every third day — today's set topic was the Ice Bed, with Su Meixiang taking first place while he and Wang Ruixiang tied for last after muddling their tones — and of two newcomers to his troupe, Qinguan, who nearly matches Yaoqing, and Qiguan; Xu Duxiang, on seeing them, had entire new wardrobes made for both. As they talk, a window opens across the way: a young man with a face like polished jade sits with Rongguan, Yumei, Sixi, and a performer from Quanfu troupe, arguing that a vulgar opera with refined company beats a refined opera with vulgar company, and that the fiddle men call lewd sounds to him like grief itself and moves him to tears. Zhongqing marks him at once as no ordinary man. The stranger calls for a brush, writes a lyric to the tune "Waves Scouring Sand" on the whitewashed wall, signs it "Xiangfan, drunk," and departs — and the innkeeper cannot tell them his name.`,
  },
  5: {
    zh: `本回细叙怡园的来历。主人徐子云，字度香，浙江山阴人，七世簪缨，祖孙宰相、父子尚书，其父现总督两广；子云年二十五，温文俊雅，博通经史，夫人袁氏花容绝代，夫妻相敬如宾。他买下宅前五六里的废园，托挚友萧次贤费三四年心血监造，成二十四处楼台、四百余间屋宇，大山连络，曲水湾环，遂为京都游览之冠。子云声气既广，四方名士星集，而其取友不在势力而在道义；史南湘《花选》中八名旦日夕来游，他视之如奇珍名花，只有爱惜而无亵狎之念，故众人待他如慈父恩母。继叙琴官身世：父杜琴师以制琴为业，为豪贵殴辱，碎琴而卒；母逾年悲痛而亡；叔父收养三年又死，婶母改嫁，遂将他卖入梨园。

他六岁识字，过目成诵，性既爱洁，志复自高，堕落时曾数度投缳不死，后为叶茂林赎出携京。入京前夕梦见梅花如海，自己陷入深坑，一美少年提他而出，转身没入林中，树上结一玉梅——次日车中所见，正是那救他的人。袁宝珠引他往怡园道谢，途中与梅子玉两车相值，一掀帘、一含笑，转瞬风驰而过；子玉叹夜光难掩，琴官则暗认此人必是有情有义的正人。

到园中，子云、萧次贤围炉相待，问其出身，他撇去苏音，说到父母双亡、婶母再蘸，声如微风振箫。次贤叹这般灵秀不钟于香闺而钟于歌楼，实是恨事；子云遂立下规矩：不许称"老爷"，不必请安，直呼度香、静宜，一如瑶卿。又因嫌"琴官"之名不雅，命次贤替他改名琴言，取号玉侬。席间宝珠盛赞他腹中书卷更胜媚香，子云听了愈喜。归后子玉将重逢之事告知聘才，聘才顺口说出旧事：当日船到济宁，见琴言独自垂泪，他递帕子去揩，反被夺去掷入河中——本欲中伤，不料子玉听了更生敬慕。数日后聘才进城访富伦，路遇一队人马：顶马引马、绣蟒貂裘的美少年、二三十骑跟班、十几车粉妆孩子，赶车的说这是锦春园的华公子。富伦细道其详：此人名华光宿，号星北，公爵之子，年二十一，文武皆能，娶靖边侯之女，妆奁百万，府中有十珠婢；只是脾气难伺候，一席酒要三四十样菜，赏则元宝，怒则鞭挞——富伦曾荐小顺儿唱《十不闲》一曲触其厌，当场被逐，破费一千多吊反被讥为俗恶；其亲随林珊枝，是花八千两银子买来的。席间内院果然吵闹起来，青姨奶奶、白姨奶奶争执不休，富伦两头弹压不住，聘才只得草草辞出，方信蓉官所言非虚。转眼除夕，梅宅灯彩辉煌，李性全携李元茂辞岁，梅士燮亲为斟酒，席间尽是修身立行的训诲；子玉则先已约定团拜那日随王恂赴宴，聘才心中暗喜——那一天，或许就能见着琴言的戏了。`,
    en: `This chapter tells how the Yi Garden came to be. Its master is Xu Ziyun, styled Duxiang, of Shanyin in Zhejiang — seven generations of office, grandfathers and grandsons ministers, his own father now governor-general of the two Guang provinces. At twenty-five he is refined, widely read, and married to a wife of the Yuan family whose beauty is matched by her learning; the two live in courteous devotion. He bought the derelict park before his house, five or six li around, and set his sworn friend Xiao Cixian to build on it — three or four years of labour producing twenty-four terraces and four hundred rooms among linked hills and winding water, now the finest prospect in the capital. Scholars gather to him from everywhere, but he chooses friends by principle rather than influence; the eight performers of Shi Nanxiang's Selection of Flowers come and go daily, and he cherishes them as one cherishes rare birds and famous flowers, with care and never appetite, so that they treat him as they would a kind parent. Then Qinguan's history: his father Du Qinshi made and taught the qin until a powerful man beat and humiliated him, whereupon he smashed his instrument and died; his mother followed within the year; an uncle took the boy in and died three years later, and the widow, remarrying, sold him into the theatre. 

He had read since six and could recite at a glance; proud and fastidious by nature, he tried more than once to hang himself before Ye Maolin bought him out and brought him north. On the last night of that journey he dreamed of a sea of plum blossom in which he fell into a pit, and a youth of godlike beauty lifted him out and vanished into the trees, leaving a plum of carved jade on a branch — and the next day, in the crush of carriages, he saw that same face. Now Yuan Baozhu escorts him to the garden to give thanks, and on the way their carriage meets Mei Ziyu's: a curtain lifts, a smile is exchanged, and both are swept apart. Ziyu reflects that true radiance cannot be hidden; Qinguan concludes that this is a man of feeling and honour. 

At the garden Ziyun and Xiao Cixian receive him by the brazier and ask his story, and he tells it in careful northern speech, his voice like wind across a flute when he reaches his mother's death and his aunt's remarriage. Cixian laments that such grace should be born to the stage rather than the inner chambers; Ziyun lays down his house rule — no one is to be called "master," no one need kneel, he is Duxiang and his friend is Jingyi, exactly as with Yaoqing. Judging "Qinguan" too common a name, he has Cixian rename the boy Qinyan, with the style Yunong. Baozhu declares that the newcomer's reading outstrips even Meixiang's, and Ziyun is delighted. Home again, Ziyu tells Wei Pincai of the meeting, and Pincai lets slip an old grievance: on the canal at Jining he had found Qinyan weeping alone and offered a handkerchief, only to have it snatched and flung into the river. He means to injure; instead Ziyu admires the boy more. Days later Pincai rides into the city to call on Fu Lun and is passed by a cavalcade — outriders, a youth in embroidered sable, thirty mounted attendants, a dozen carriages of powdered boys — which the driver says belongs to the great young master of Jinchun Garden. Fu Lun supplies the particulars: he is Hua Guangsu, styled Xingbei, a duke's son of twenty-one, accomplished in arms and letters, married to a marquis's daughter with a dowry of a million and served by ten pearl-named maids; but he is impossible to please, requiring forty dishes at a sitting, rewarding with silver ingots and punishing with the whip. Fu Lun once engaged Xiaoshun'er to sing Ten Non-Idle Acts and so offended him that the singer was thrown out, the host spending a thousand strings only to be called vulgar; the young master's own attendant, Lin Shanzhi, cost eight thousand taels. As they talk, a quarrel erupts in the inner rooms between Concubine Qing and Concubine Bai, and Fu Lun cannot quiet it; Pincai takes his leave, satisfied that Rongguan's gossip was true. New Year's Eve arrives, the Mei house blazing with lanterns; Li Xingquan brings Li Yuanmao to pay the season's respects, Mei Shixie pours the wine himself, and the talk runs to self-cultivation and right conduct. Ziyu has already arranged to attend the cohort banquet with Wang Xun — and Pincai privately exults, for on that day he may at last see Qinyan on the stage.`,
  },
  6: {
    zh: `新正应酬络绎。初三日王文辉送来知单，同年团拜只十二位，比去年更形冷落；初五日颜夫人亦设内宴，请了王、孙两家女眷。

两位陆夫人是嫡堂姊妹，皆已四十上下而风韵不减。作者顺笔写尽孙家后院的参差：孙嗣徽之妻沈芸姑出身书香，嫁得这红鼻子丈夫，几欲自尽，回娘家又被父亲教训送回，末了只得把陪房丫头松儿与他收房，自己背地垂泪；孙嗣元之妻巴来风是总兵之女，十七岁过门，掀帐一见那期期艾艾的嘴脸便哭了半日，夜里丈夫上床动手，被她一掌打得半边脸肿，又一拳打翻在地，此后五六年犹未谙人伦之乐。席间孙亮功的陆夫人快人快语，一句"你的外甥好，我的外甥女也不错"，竟把子玉与琼华的婚事说成了；两位亲家当场对拜，陆夫人拔下颜夫人头上一枝玉燕钗替琼华戴上，羞得那位小姐几乎落泪。众少奶奶带她逛到子玉书房，见镜屏上的小照人人赞叹，独琼华走到书桌边翻出一纸《车中人》七绝，见第三、四首末句竟押着"琼""华"二字，大惊，忙用指甲挖去，红着脸走开。

次日姑苏会馆团拜，李元茂嫌衣裳不好，先借子玉的穿不进，又换梅士燮的，长得扫地，束起来成了前鸡胸后驼背，见王文辉行礼时还把人家帽子碰歪。东楼上刘文泽做主，座中有史南湘、张仲雨、高品、沈伯才、巴霖，后来冯子佩才从锦春园华星北处赶到。众人怕孙家兄弟扫兴，偏被高品、沈伯才、巴霖轮流以"红而光"三字取笑嗣徽的酒糟鼻，又替嗣元编出一部结巴的《三字经》，笑倒满座。席间王恂说破前情：那日戏园中缠住子玉的黑相公，名字与袁宝珠只差一字，子玉误认作花榜第一，众人大笑。及至开戏，《瑶台》一出，子玉惊为天人，问是何人，方知即《曲台花选》第二的苏蕙芳，自叹夏虫不可语冰。接着《惊梦》登场，琴官莲步香风而至，一句"良辰美景奈何天"字字打入心坎，子玉几乎垂泪；琴官第二次出场，眼波只往他这边流转，看得刘文泽、史南湘打趣不休，子玉红着脸有口难辩。此后陆素兰的《舞盘》、金漱芳的《题曲》、李玉林的《偷诗》接连登场，无不香艳绝伦，子玉只有向南湘一再认错。散时刘文泽约定初九日小酌清谈，子玉欣然应允。`,
    en: `The New Year visits come thick and fast. On the third day Wang Wenhui sends round the roster for the cohort banquet — only twelve names this year, thinner than the last — and on the fifth Lady Yan holds her own gathering for the women of the Wang and Sun houses. The two Madam Lu are first cousins, both around forty and both still handsome. 

The author uses the occasion to lay bare the Sun family's inner courtyard. Sun Sihui's wife Shen Yungu, bred to books, nearly took her own life on seeing the red-nosed creature she had married; sent home, she was lectured by her father and returned, and finally gave her own maid Song'er to her husband as a concubine so as to be left in peace, weeping in private thereafter. Sun Siyuan's wife Ba Laifeng, daughter of a brigade general, came at seventeen, wept half a day at the first sight of her stammering bridegroom, and when he reached for her that night slapped one side of his face swollen and knocked him to the floor with a punch; five or six years on she is a wife in name only. Over the wine Sun Lianggong's Madam Lu, blunt and cheerful, remarks that if her hostess admires her own nephew so, there is a niece to match him — and so the betrothal of Ziyu and Qionghua is settled on the spot. The two mothers bow to each other, and Madam Lu pulls a jade swallow pin from Lady Yan's hair and fixes it in the girl's, leaving her scarlet and close to tears. The young wives take her off to view Ziyu's study, where all admire his portrait on the mirror-screen; only Qionghua drifts to the desk, turns up a sheet of quatrains titled The Person in the Carriage, and finds the third and fourth closing on the very characters of her own name. 

Appalled, she scratches them out with a fingernail and slips away. The next day brings the banquet at the Suzhou Guild Hall. Li Yuanmao, ashamed of his clothes, cannot fit into Ziyu's, and in Mei Shixie's sweeps the floor until, belted up, he is all pigeon chest and hump; making his bow to Wang Wenhui he knocks the man's hat askew. Upstairs Liu Wenze presides, with Shi Nanxiang, Zhang Zhongyu, Gao Pin, Shen Bocai, and Ba Lin, and at last Feng Zipei, delayed at Hua Xingbei's Jinchun Garden. The company had hoped to avoid the Sun brothers, but instead Gao Pin, Shen Bocai, and Ba Lin take turns capping a rhyme on "red and shining" at the expense of Sihui's nose, and compose for Siyuan a stammerer's Three-Character Classic that leaves the table helpless. Wang Xun then clears up an old confusion: the coarse boy who pawed at Ziyu in the theatre bears a name differing by a single character from Yuan Baozhu's, and Ziyu had taken him for the first of the Flower Register. Then the performance begins. At The Jade Terrace Ziyu is thunderstruck and asks who this is — it is Su Huifang, second in the Qutai Huaxuan — and confesses himself a summer insect who cannot be told of ice. Next comes Waking from a Dream: Qinguan enters on a breath of perfume, and the line about fair season and lovely scene goes straight into Ziyu's heart, so that he can barely hold back tears. On the boy's second entrance his glance travels again and again to Ziyu's seat, until Liu Wenze and Shi Nanxiang tease him openly and he blushes with nothing to say. Lu Sulan's Dancing on the Tray, Jin Shufang's Inscribing the Song, and Li Yulin's Stealing the Poem follow, each more exquisite than the last, and Ziyu can only keep apologising to Nanxiang. As they part, Liu Wenze invites him to a quiet gathering on the ninth, and he gladly accepts.`,
  },
  7: {
    zh: `会馆散后，子玉把琴官的戏想了整整两日，将苏蕙芳、陆素兰、金漱芳、李玉林逐一品评，觉得蕙芳神色最胜、素兰可以匹敌，然与琴官相较，终觉毫厘之逊。他又替造化设想：这般美貌若不堕入梨园，天下人反无从瞻仰，正如生了花王，还须生许多花相来陪衬；只是好花供赏不过一季，而人之颜色可及十年，所以爱人之心自当胜于爱花。想取旧作《车中人》再续两首，却见第三、四首各被指甲挖去一字。

小丫鬟道破原委：那日太太请客，王家二姑娘曾翻他的书，还听雪儿说孙家做媒，已把二姑娘许了少爷，姑娘还戴着太太的簪子回去。子玉初时将信将疑，细想这位表妹的眉眼竟与琴官有几分相似；再一转念，才恍然自己无意间犯了"琼华"二字的讳，对方必疑他有心相思，这桩不白之冤竟无从分辩——既已订亲，被怪也就罢了。初九日刘文泽再邀，子玉更衣赴约。园中甬道曲折，太湖石叠成假山，绿竹红阑掩映，卷棚上悬着屈本立所书"倚剑眠琴之室"匾额，室内水仙半开、绿萼白梅初绽。众人叙齿入座：史南湘与高品同年二十五，颜仲清二十四，王恂二十三，子玉最幼十八，主人刘文泽二十四。

因名旦都在怡园作消寒会，席上无人相陪，众人便以对诗行令：刘文泽出"子玉人如玉"，高品应声对"卯金面是金"，说中秋摊上兔儿爷的脸原是描金的，笑倒一堂。此后拆字联对，一句"双凤云中扶辇下"，颜仲清对"孤鸿天外寄书来"，子玉对"九驾天上听琴来"，公推第一；高品却对出"八鸡露后靠舟前"，一字不连，倒转来念更成谐谑，众人笑得伏案流泪，罚酒五杯。其后"舞台收影费鸾肠""白发如丝日日新""香销南国美人尽"数令迭出，颜仲清评点甲乙，谓子玉句稳而大方，不落纤巧，众皆心服；高品则一路以《传灯录》《西游记》强作典故，屡遭叉抹，而满座笑声几乎透出街衢。饭罢已亥正二刻，众人告辞。归途中子玉赞园子幽雅，刘文泽却说这尚不及徐度香的怡园十分之一，约他同去。高品又向颜仲清透露：京中新来了一位"精品"，也是南京人，现寓宏济寺，风雅而阔绰，只是尚未往来——一段新的缘分，就此埋下伏笔。`,
    en: `For two days after the guild hall Ziyu can think of nothing but Qinguan's performance. He weighs Su Huifang, Lu Sulan, Jin Shufang, and Li Yulin in turn, granting Huifang the finest presence and Sulan an equal claim, yet finding both a hair's breadth short. He reasons on heaven's behalf: had such beauty not fallen into the theatre, no one would ever have been permitted to see it — as the king of flowers requires its attendant blossoms. But a flower can be admired for one season only, while a face lasts ten years; love of a person must therefore outrank love of a flower. 

Meaning to add to his old sequence The Person in the Carriage, he finds a character gouged from each of the third and fourth poems. A maid explains: during the ladies' visit the second Wang daughter looked through his books, and by Xue'er's account the Sun family have made a match and the girl went home wearing his mother's hairpin. Ziyu is half incredulous — then notices that this cousin's features somewhat resemble Qinguan's, and finally realises with a start that he has unwittingly rhymed on the two characters of Qionghua's name, so that she must believe the poem was written for her. It is a charge he can never answer; and since they are betrothed, he decides he can bear being blamed. On the ninth Liu Wenze's invitation takes him to a garden of winding paths, piled Taihu rock, green bamboo against red railings, and a hall whose plaque — The Chamber for Leaning on a Sword and Sleeping by the Qin — was brushed by Qu Benli, where narcissus stands half open and a white plum is just breaking bud. The company seat themselves by age: Shi Nanxiang and Gao Pin both twenty-five, Yan Zhongqing twenty-four, Wang Xun twenty-three, Ziyu youngest at eighteen, and Liu Wenze, twenty-four, as host. With every famous performer away at the Yi Garden's winter club, they entertain themselves with matching couplets. 

Wenze offers "Ziyu, a man like jade"; Gao Pin caps it instantly with a line on gilded faces, observing that the rabbit-god figures sold at Mid-Autumn are painted gold, and the table dissolves. In the character-splitting rounds, against "Twin phoenixes in cloud draw the carriage down," Zhongqing answers with a lone wild goose bearing a letter from beyond the sky, and Ziyu with nine chariots descending to hear the qin — judged the finest. Gao Pin's effort connects to nothing at all, and read backwards proves so obscene that the others weep with laughter and fine him five cups. Further rounds follow, and Zhongqing, ranking them, praises Ziyu's line as steady and ample where others are merely ingenious; all concede the point. Gao Pin meanwhile defends his nonsense with straight-faced citations from the Transmission of the Lamp Record and Journey to the West, is struck through each time, and keeps the room laughing loudly enough to be heard in the street. They eat at last near midnight and part. Walking out, Ziyu admires the garden, and Liu Wenze replies that it is not a tenth of Xu Duxiang's Yi Garden, and promises to take him. Gao Pin, meanwhile, mentions to Zhongqing that a new man of quality has come to the capital — a fellow southerner from Nanjing, lodging at the Hongji Temple, elegant and evidently rich, whom he has not yet met.`,
  },
  8: {
    zh: `子玉赴刘文泽之约归来已过二更，魏聘才、李元茂却不知去向。原来二人趁他出门，商量着要去听戏作乐。元茂手中无钱，聘才便替他细算：带相公上馆子不过七八吊京钱，折银三两有零，在南边还摆不成一台花酒；又撺掇他往父亲箱里"暂借"。元茂开箱摸出一大包碎银，拣了五六块，聘才嫌少，又添两块，共八九两掖在搭链里，雇车直奔太和园。将进园门，元茂只顾看那五花云彩、老虎花架，不防绊在一张矮板凳上栽了个倒栽葱，旁边一人抢上来双手扶起，替他拍去身上尘土，说些"幸亏拉得快"的好话——这一拍，那搭链便悄没声息地去了。

楼上遇见张仲雨，说起清早才到锦春园华府、又往怡园商议事、同起盛银号的潘三吃了饭，还约了宏济寺的唐和尚在此相候。他递过玉烟壶，元茂当作痧药猛嗅，连打七八个嚏喷，涕泪交流。不多时来了二喜和另一个黑相公，一个装烟一个倒茶，一个挨紧膀子一个挤紧腿，把元茂夹在中间，喜得他心花大放。台上琪官唱《女弹词》一出，装束华美，两楼喝彩，可他卸妆后只对聘才微微一笑，转身却上了对楼陪两个华服贵客，教聘才好不扫兴。众人转到春阳馆，二喜出了个"乐中乐、苦中苦"的酒令：一杯输了唱曲，二杯输了说笑话，三杯输了敬皮杯。元茂不会唱，求人代唱；轮到吃皮杯，二喜含酒口对口灌下，他一笑竟从鼻孔喷出，满座笑倒，那一个笑得跌落凳下，仲雨笑翻了一身酒。

唐和尚寻来催仲雨去办事，席间与二喜互相戏谑，说人间有四光：和尚脑袋、媳妇腿、老斗银包、相公嘴，说罢大笑而去。及至散席开发，元茂遍身摸索，那袋银子早已不知所终，这才想起进门跌交时被人扶起的蹊跷。两个相公不肯罢休，说回去要交账，非要跟着上门见师傅不可。正僵持间，恰遇孙嗣徽也在馆中，聘才忙请他进来。嗣徽摸着红鼻子，把一部千字文拆得七零八落，从"金生丽水"数到"骸垢想浴"，满口成章而不知所云，把聘才、元茂笑倒，两个相公也如听串戏。末了他勉强担了这笔人情，打发二人明日再来。走堂的报账，连内外共五十六吊七百八十文；掌柜的盘问了姓名住处，才勉强准其挂账，聘才只得写下鸣珂坊梅宅魏字，又添两吊酒钱。两人提着灯笼，一步步低头踱回——乘兴而来，扫兴而返。`,
    en: `Ziyu comes home from Liu Wenze's past the second watch to find Wei Pincai and Li Yuanmao gone. The two had seized his absence to go to the theatre. Yuanmao has no money, so Pincai does the arithmetic for him — taking performers to a restaurant costs only seven or eight strings of cash, barely three taels, not enough for a single flower-banquet in the south — and then suggests he "borrow" from his father's strongbox. Yuanmao digs out a heavy packet of broken silver, picks five or six pieces, adds two more at Pincai's urging until he has eight or nine taels in a waist-pouch, and they hire a carriage to Taihe Garden. At the gate, gaping at the painted clouds and tiger-frames, Yuanmao trips over a low bench and goes down head first; a bystander springs forward, lifts him with both hands, dusts him off, and remarks how lucky it was he caught him — and with that brushing the pouch is gone, unnoticed. 

Upstairs they meet Zhang Zhongyu, who has been to the Hua mansion at Jinchun Garden that morning, then to the Yi Garden on business, then to lunch with Pan Third of the Qisheng bank, and is now waiting on Monk Tang of the Hongji Temple. He offers his jade snuff bottle; Yuanmao, mistaking it for headache powder, inhales deeply and sneezes seven or eight times, streaming. Presently two dark-skinned boys attach themselves — Er Xi and another — one filling his pipe, one pouring his tea, one pressed to his shoulder and one to his knee, until Yuanmao is glowing with delight. On stage Qiguan sings Female Ballad-Singing in gorgeous costume to applause from both galleries, but after changing he gives Pincai only the faintest smile and goes to sit in the opposite gallery attending two richly dressed strangers, to Pincai's considerable chagrin. The party moves to the Chunyang Restaurant, where Er Xi proposes a drinking game: lose the first cup and sing, the second and tell a joke, the third and give a "skin cup" — wine passed mouth to mouth. Yuanmao cannot sing and begs a substitute; when the skin cup falls to him, Er Xi takes wine in his mouth and pours it into his, whereupon Yuanmao laughs and sends it jetting out of both nostrils. 

The room collapses — one boy slides off the bench to the floor, Zhongyu overturns his cup down his own front. Monk Tang arrives to hurry Zhongyu away to business, trading insults with Er Xi and declaring that the world has four shining things: a monk's skull, a wife's thighs, a patron's purse, and an actor's mouth. When the reckoning comes, Yuanmao searches himself in mounting panic; the silver is long gone, and only now does the helpful stranger at the gate make sense. The two boys refuse to let it drop — they must account to their master, and insist on coming home with him. At the impasse Pincai spots Sun Sihui in the restaurant and calls him in; rubbing his red nose, Sihui delivers an oration assembled entirely from the Thousand Character Classic, marching from gold born in water to washing filth from the body, magnificently sonorous and entirely meaningless, which leaves Pincai and Yuanmao weak with laughter while the boys listen as though to an opera. In the end he grudgingly stands surety and sends the pair off to return tomorrow. The waiter totals the bill at fifty-six strings and seven hundred eighty cash; the proprietor questions their names and lodgings before allowing credit, and Pincai has to sign it to the Mei house at Mingke Lane, adding two strings for the staff. Lantern in hand, the two walk home in silence — having set out in high spirits and returned in none.`,
  },
  9: {
    zh: `聘才、元茂三更方归，次日只得央许顺借了十吊钱的票子，分作两张，托四儿送与叶茂林转给那两个相公，算是了结；子玉盘问时，二人推说张仲雨请去听戏下馆子，将实情瞒过。转眼元宵，李性全带李元茂赴会馆吃年酒，聘才出门逛灯未回，子玉独坐无聊，恰好梅进来报：刘文泽、颜仲清、王恂三位在门口相邀。四人弃车步行，走入灯市。玻璃灯、画纱灯、灯屏灯楼次第辉映，泥筒花炮如流星赶月，锣鼓丝竹，一派太平气象。

忽有一队香车拥来，子玉被车轴拦住，车中少妇目不转睛地看他，还把身子一松，伸出一只三寸莲钩，盘好了才嫣然微笑；文泽扯着王恂低声说是"要显显他的莲瓣"，仲清偏说"焉知不是为着你"。车沿下挂的小灯上写着起盛银号潘其观的字号——这一笔闲墨，日后自有下文。继而一群妇女结队横冲直撞，一个踏了王恂的新靴，一个高个的踉跄跌来，一把揪住子玉胸前才站稳，唬得他心头乱跳；那些妇人反怪爷们睁着大眼挡路，惹得众人大笑。子玉叹道，比起方才车中人，真有天壤之别。文泽提议往怡园看灯猜谜，仲清说徐度香、萧次贤都不拘形迹，子玉这才同去。园门口彩坊高结，亭上悬着灯虎字条，四人一路猜将下去：《礼记》《易经》各中一条，"落花人独立，微雨燕双飞"打一"俩"字，又打出古人名与古乐府数题，报进去竟皆中的。萧次贤闻声出迎，与子玉一见如故。彩礼分送笔墨端砚，独子玉那一条的彩最重，是古锦囊中的瑶琴一张——原来这谜是园主人为杜玉侬而设，暗寓作合之意，琴上还要镌铭，众人皆不解其故。

次贤复引众人登石台观灯：先是数百泥筒流星，继而九连灯、万年欢、火烧红莲寺、赤壁烧兵诸般烟火，再挂出数千树灯，舞出金、青、白、乌、火五条巨龙，最后象、虎、犀、狮、黑熊、赤豹数百兽灯衔尾疾驰，鼻里生烟口中吐火，如雷轰电掣，看得子玉等神惊肤栗；次贤说这一场不过用了不到二百人，众名士叹服。中途史南湘醉得踉跄上台，当众大吐，宝珠捧上度香自制的仙桃益寿丸，一丸下去宿酒尽消，醒来却问"这是什么地方"，逗得满座大笑。众人转入宜春阁，见屈本立题额、陆素兰小楷、袁宝珠墨兰，皆精绝。子玉悄问袁宝珠可曾见着琴官，宝珠反问他二人可相好，问得他窘住，只说闻名思慕；宝珠这才告知：他如今已改名琴言，今日恰被度香带去赴席了。子玉怅然，只觉缘悭一面。临散前次贤取出两封以药名、花名藏尾的情书底稿，说昨日被一个不知姓名的少年一举猜破——众人叹此人聪明绝世，却无从访问。`,
    en: `Pincai and Yuanmao get home at the third watch, and next morning must beg ten strings' worth of notes from the steward Xu Shun, split into two, for Si'er to carry to Ye Maolin for the two boys. When Ziyu questions them they claim Zhang Zhongyu took them out, and the truth stays hidden. The Lantern Festival comes. With Li Xingquan and Li Yuanmao away at a guild feast and Pincai out among the lanterns, Ziyu sits alone until Mei Jin announces Liu Wenze, Yan Zhongqing, and Wang Xun at the gate. The four leave their carriages and walk into the lantern market, past glass lanterns and painted gauze lanterns, lantern screens and lantern towers, while firework tubes send up shooting stars and drums and strings sound on every side. 

A file of perfumed carriages presses through; Ziyu is pinned against an axle, and the young wife inside watches him steadily, then eases her body, extends a three-inch bound foot, tucks it back, and smiles. Wenze whispers to Wang Xun that she means to show off her lotus petals, while Zhongqing insists she may be looking at Wenze instead. The small lamp beneath the carriage bears the mark of Pan Qiguan's Qisheng bank — an idle stroke that will matter later. Then a pack of women comes shoving through; one treads on Wang Xun's new boot, another, tall and unsteady, lurches into Ziyu and seizes his chest to keep her feet, leaving his heart hammering — and the women complain that these gentlemen block the way and stare. Ziyu observes that between such creatures and the lady in the carriage lies the distance of heaven from earth. Wenze proposes the Yi Garden for lanterns and riddles; Zhongqing assures him that Xu Duxiang and Xiao Cixian stand on no ceremony, and Ziyu consents. Riddle slips hang from a pavilion lamp, and the four work down them — one from the Liji, one from the Book of Changes, a couplet on a solitary figure among falling petals yielding a single character, then names from antiquity and titles of old ballads — and every answer reported is right. Xiao Cixian comes out to greet them and takes to Ziyu at once. The prizes are brushes, ink, and inkstones, but Ziyu's is far the richest: a qin in an old brocade bag. It emerges that the riddle was set by the garden's master for Du Yunong, with a quiet matchmaking intent, and that the instrument is still to be inscribed — none of them understands why. 

Cixian then leads them up to a stone terrace for the display: hundreds of firework tubes, then set pieces, then several thousand lanterns blossoming in the trees, then five great dragons — gold, green, white, black, and fire — writhing together, and finally hundreds of beasts on wheels, elephants and tigers, rhinoceros and lions, black bears and red leopards, smoking at the nostrils and breathing flame, thundering past until the watchers' skin creeps. Fewer than two hundred men, Cixian remarks, and the company marvels. Mid-display Shi Nanxiang staggers up the steps hopelessly drunk and is violently sick; Yuan Baozhu brings him one of Duxiang's own Immortal Peach Longevity Pills, which dissolves the wine at a stroke, though on waking he asks where he is, to general laughter. They move to the Yichun Pavilion, hung with Qu Benli's plaque, Lu Sulan's small-character calligraphy, and Yuan Baozhu's ink orchids. Ziyu quietly asks Baozhu whether he has seen Qinguan; Baozhu asks in return whether they are close, which leaves Ziyu flustered, admitting only that he admires a reputation. Baozhu tells him the boy is now called Qinyan, and that Duxiang has taken him out to a banquet that very evening. Ziyu is left with the sense of a fate always just missing. Before they part, Cixian produces two love letters whose lines conceal the names of medicines and of flowers, solved the day before by a nameless youth whom nobody thought to detain — a mind, the company agrees, of rare brilliance.`,
  },
  10: {
    zh: `琴言自谒见徐子云之后，日日随众名旦出入怡园，子云爱之不亚于袁宝珠；然他生性高傲，任凭黄金满斗也买不动一笑，纵知感恩，也只算得半个知己——因为他心上真正挂着的，是进京路上认出的那个梦中救他出坑的人。姑苏会馆看戏那日，他从叶茂林口中得知那位公子姓梅，正应了梅花树下之兆，自此幽情如沾泥柳絮，夜夜入梦：或相对而笑，或执手同哭，或送行、或重逢，醒来又记不真切；甚至梦见袁宝珠变作那人模样，与他同唱一出《惊梦》。萧次贤将灯谜之夜梅子玉猜中瑶琴的事说与子云，又盛赞其才貌，子云随口道要替琴言"觅个配对"，竟把他吓得泪流满面，激切辩白：只求不被糟蹋，何来配对之说。子云自知失言，托词避开，留宝珠劝慰。宝珠试探着说起那位十七八岁的梅公子曾单单问起他，琴言便一句句盘问相貌，说着说着自己泄了底，把梦中情事和盘托出，二人在隔壁窃听的子云、次贤推门而出，羞得他背转身去。子云次日便去拜望子玉，约定十九日小酌，心中却另有主意：琴言脾气难测，子玉是否真情也未可知，不如用个"移花接木"之计试他一试。

是日子玉至梅崦，万树梅花围屋，榻上横陈古锦囊中的瑶琴。子云取出琴来，琴背镌着"琴心沉沉，琴德愔愔；其人如玉，相与赏音"，下署"山阴徐子云为玉侬杜琴言移赠庾香名士清赏"，又有次贤撰句、静宜手镌两方图章。子玉这才恍然玉侬即琴官，大喜称谢。子云再三试探，问他与琴言相与深浅、比之宝珠如何、若以琴言相赠当如何处之，子玉一一从容应对。

少顷宝珠引了一个"琴言"进来，眉目虽似而神采迥异；此人百般作态，倚肩贴脸，问他可知相思、可解人意，子玉初则疑惑，继而动怒，正色道人之相知贵在知心，声色之奉本非正人所尚，若务求下品，连乡党自好者都不为——说罢愤然欲去，镜屏却推之不开。子云、次贤、宝珠这才笑盈盈现身，称他是坐怀不乱的柳下惠。转入套间，另有一人背身垂泪，回过脸来才是真正的琴言，神采奕奕，丽若天仙。子玉如醉方醒，一腔心事竟说不出一字，连敬酒的坐次都错了。席间以"琴言开口"行令，他每说一句，对话者便饮一杯；宝珠改唐诗"寻常一样琴前月，才有梅花便不同"来打趣他的名字，子玉便称赞宝珠"胸有智珠"替他解围，琴言深感其情。他一笑之间美目流波，连相处将近一月的子云也是初见，不免爱极生妒，转看子玉与琴言并坐宛如一对玉人，又羡而忘妒。子玉细看真假两人，眉目手指皆不同，正自疑惑，子云唤出那假琴言——原来是华公子家八龄班中的玉龄，本是子云家人，因面貌相似而借来演这一出。疑团尽释，子玉不免赧然。饮罢，琴言恐他醉了不适，亲取仙桃益寿丸泡好吹凉喂他服下；临别悄问后会之期，子玉只勉强答以"稍有空闲，即当相聚"，两人心许目成，尽在不言之中。`,
    en: `Since first calling on Xu Ziyun, Qinyan has come daily to the Yi Garden with the other celebrated performers, cherished there scarcely less than Yuan Baozhu. Yet he is proud by nature, and no weight of gold buys a smile from him; grateful as he is, Ziyun remains only half a confidant, because the person who truly occupies him is the youth from his dream, recognised on the road into the capital. At the guild hall performance he learned from Ye Maolin that the young gentleman's surname was Mei — fulfilling the omen of the plum trees — and since then the attachment has clung to him like willow-down in mud. He dreams of the man nightly: laughing together, weeping together, seeing him off, meeting again; once he even dreamed Yuan Baozhu had taken the man's face and sang Waking from a Dream with him. When Xiao Cixian reports that Mei Ziyu solved the qin riddle and praises his talent and looks, Ziyun jokes that he will find Qinyan a "match" — and the boy dissolves in tears, protesting that he asks only not to be defiled. Ziyun withdraws, abashed, leaving Baozhu to comfort him. Baozhu mentions that a Master Mei of seventeen or eighteen asked after him by name, and Qinyan interrogates him about the man's features so eagerly that he betrays himself and pours out the whole story of the dream — whereupon Ziyun and Cixian, listening through the wall, push open the door and leave him crimson and turned away. Next day Ziyun calls on Ziyu and fixes a small banquet for the nineteenth, having privately resolved on a test: Qinyan's temper is unpredictable and Ziyu's feeling unproven, so he will graft one branch onto another and see. 

On the day, Ziyu comes to the Plum Slope, where thousands of trees enclose the rooms, and finds the brocade-bagged qin laid on a couch. Ziyun draws it out; the back is inscribed — the qin's heart is deep, its virtue still; the man is like jade, and shall share its music — and signed by Xu Ziyun of Shanyin, presenting it on behalf of Yunong, Du Qinyan, to the distinguished Mei Yuxiang, with seals recording that Cixian composed the lines and Jingyi cut them. Only now does Ziyu grasp that Yunong is Qinguan, and he bows in delighted thanks. Ziyun probes him — how well does he know Qinyan, how does he rank him against Baozhu, what would he do if Qinyan were given to him — and Ziyu answers each with composure. Then Baozhu ushers in a "Qinyan" whose features resemble the boy's but whose spirit does not. 

This creature leans on him, presses cheek to cheek, asks whether he knows what longing is; Ziyu, puzzled and then angry, declares that between friends what matters is knowledge of the heart, that the pleasures of the senses are no pursuit for an upright man, and that to grovel after the basest of them is beneath even a decent villager. He turns to leave — and the mirror-screen will not open. Ziyun, Cixian, and Baozhu appear laughing, saluting him as a paragon of continence. In the inner room another figure sits weeping with its back turned, and when it turns, it is the true Qinyan, radiant as a spirit. Ziyu is like a man waking from wine; he cannot utter a word, and takes the wrong seat when the toasts begin. A game is proposed in which every remark Qinyan makes costs his interlocutor a cup; Baozhu alters a line of Tang verse to tease him on his name, and Ziyu deflects it by praising Baozhu's quickness, for which Qinyan is quietly grateful. When the boy laughs, his eyes shining, even Ziyun — a month in his company — has never seen it, and feels a pang of jealousy that dissolves as he watches the two young men seated side by side like a matched pair of jade figures. Comparing the two faces and even the two hands, Ziyu is still perplexed, until Ziyun summons the impostor: Yuling of Young Master Hua's boys' troupe, once a servant of Ziyun's own house, borrowed back for the resemblance. The mystery clears, and Ziyu is left blushing. As the party ends, Qinyan, fearing the wine has been too much for him, fetches an Immortal Peach Longevity Pill, prepares it and blows it cool before giving it to him; and at parting he asks softly when they will meet again, to which Ziyu can only manage that he will come whenever he is free. Nothing more is said, and everything is understood.`,
  },
};
