/** Chapter 1, paragraphs 4–12 and 35–56: everyday scenes, staged with tableau beats. Build with `npm run build-cinemas -- 1`. */
import type { Spec } from '../write';

// Beat shorthands, written into scene.ts as code.
const T = (o: string) => `T({ ${o} })`;
const STUDY3 = `table: {}, cast: [who.zhongqing(-2.5, { z: -0.6 }), who.ziyu(0, { gesture: 'reading' }), who.nanxiang(2.5)]`;
const study3 = (zq = '', zy = '', nx = '', extra = '') => T(`place: 'study', table: {}, cast: [who.zhongqing(-2.5${zq ? `, { cues: ${zq} }` : ''}), who.ziyu(0, { gesture: 'reading'${zy ? `, cues: ${zy}` : ''} }), who.nanxiang(2.5${nx ? `, { cues: ${nx} }` : ''})]${extra}`);
const study2 = (a: string, b: string, extra = '') => T(`place: 'study', table: { x: -0.6, w: 6.4 }, cast: [${a}, ${b}]${extra}`);
const lines = (...l: string[]) => `lines: [${l.map(s => `'${s}'`).join(', ')}]`;
const poem = (...l: string[]) => `poemBeat([${l.map(s => `'${s}'`).join(', ')}])`;
const BAR = (xs: string[]) => xs.join(', ');

export const specs: Spec[] = [
  {
    n: 4, title: ['A father without feeling, a son all feeling', '极忘情之人，极钟情之子'],
    description: ['The Mei household: three generations of officials, Lady Yan’s dream of a jade gift, and Mei Ziyu, the jade-like son.', '梅家三代单传、颜夫人梦神人授玉，以及貌如良玉的梅子玉。'],
    staging: 'an unsigned book, the Mei ancestral hall, Lady Yan’s dream of jade, and Ziyu at his books',
    shots: [
      [0, 7, 'An unsigned book', '此书不着姓名', '此书不着姓名，究不知何代何年何地何人所作。', 'The book bears no author’s name; no one knows when, where or by whom it was written.', '此书不着姓名，不知何代何人所作。'],
      [7, 16, 'Three generations, one heir', '三代单传', '其祖名鼎，曾任吏部尚书；其父名羹调……三代单传。', 'In the Mei ancestral hall: a grandfather who was Minister of Personnel, a father who was Grand Secretary, and Mei Shixie of the Hanlin Academy, stern as autumn.', '梅氏祠堂：祖为吏部尚书，父为大学士，梅士燮官翰林院侍读学士，貌如秋肃。'],
      [16, 25, 'A dream of jade', '梦神人授玉', '二十九岁上梦神人授玉，遂生了一个玉郎，取名子玉。', 'Lady Yan dreams that an immortal hands her a piece of jade, and bears a son: Ziyu.', '颜夫人梦神人授玉，遂生子玉。'],
      [25, 36, 'Pure as jade', '守身如玉', '子玉亦能守身如玉……志在云霄。', 'At seventeen Ziyu has mastered ten thousand books, kept close by his mother and guarded pure as jade.', '子玉十七岁，万卷贯通；颜夫人爱如珍宝，子玉守身如玉。'],
    ],
    beats: [
      poem('此书不着姓名', '究不知何代何年', '何地何人所作'),
      T(`place: 'hall', cast: [{ kind: 'elder', x: -3.8, opacity: 0.45 }, { kind: 'elder', x: -1.6, opacity: 0.65 }, who.teacher(0.8)], ${lines('三代单传', '翰林院侍读学士', '梅士燮')}`),
      T(`place: 'clouds', table: { x: -2.2, w: 3.2 }, cast: [who.lady(-2.2, { gesture: 'sleeping' }), { kind: 'deity', x: 1.4, y: 1, float: 0.25, from: 1.5, opacity: 0.85 }], ${lines('梦神人授玉', '遂生玉郎')}`),
      T(`place: 'study', cast: [who.lady(-3.4, { opacity: 0.8 }), who.ziyu(-0.6, { gesture: 'reading' })], ${lines('志在云霄', '守身如玉', '质比精金', '貌如良玉')}`),
    ],
    subtitles: [
      [0.4, 6.6, '此书不着姓名，究不知何代何年何地何人所作。', 'The author of this book remains nameless: the era, place and identity are forever unknown.'],
      [7.4, 11.4, '书中开首说一极忘情之人，生一极钟情之子。这人姓梅，名士燮。', 'It begins with a man utterly detached from feeling, who sires a son devoted to feeling: Mei Shixie.'],
      [11.4, 15.6, '其祖曾任吏部尚书，其父曾任文华殿大学士，三代单传。', 'His grandfather was Minister of Personnel, his father a Grand Secretary; for three generations, a single heir.'],
      [16.4, 20.4, '夫人颜氏，德容兼备，贤淑无双。', 'His wife, Lady Yan, is a rare union of virtue and beauty.'],
      [20.4, 24.6, '二十九岁上梦神人授玉，遂生了一个玉郎，取名子玉。', 'At twenty-nine she dreamed a divine being gave her jade, and bore a jade-like son named Ziyu.'],
      [25.4, 29.4, '这梅子玉今年十七岁，貌如良玉，质比精金。', 'Mei Ziyu is now seventeen, his face as flawless as fine jade, his essence as pure as gold.'],
      [29.4, 33, '颜夫人将此子爱如珍宝，而子玉亦能守身如玉。', 'Lady Yan treasures him beyond measure, and Ziyu guards his purity like unblemished jade.'],
      [33, 35.6, '论今讨古，志在云霄。', 'Debating the present and the past, his ambitions soar to the clouds.'],
    ],
  },
  {
    n: 5, title: ['Two friends at the gate', '两个好友来看他'],
    description: ['The teacher leaves early; Ziyu sits alone until two friends arrive, one of them his cousin Yan Zhongqing.', '先生有事放学，子玉独坐，两个好友来访，其一是表兄颜仲清。'],
    staging: 'the teacher leaving the study, two friends arriving at the gate, and Yan Zhongqing introduced',
    shots: [
      [0, 12, 'Alone in the study', '子玉独坐', '一日，先生有事放学，子玉正在独坐', 'One day the teacher dismisses class early, and Ziyu sits alone with his books.', '先生有事放学，子玉独坐书房。'],
      [12, 24, 'Two friends arrive', '两个好友来看他', '却有两个好友来看他。', 'Two close companions arrive at the gate.', '两个好友来到门前。'],
      [24, 36, 'Yan Zhongqing', '颜仲清', '一个姓颜名仲清，号剑潭，现年二十三岁……为颜夫人之侄。', 'One is Yan Zhongqing, styled Jiantan, twenty-three: Lady Yan’s nephew.', '其一颜仲清，号剑潭，年二十三，颜夫人之侄。'],
    ],
    beats: [
      T(`place: 'study', table: { x: 0.8, w: 5 }, cast: [who.teacher(-1.4, { walk: [-1.4, -9, 1, 6], flip: true }), who.ziyu(0.8, { gesture: 'reading' })]`),
      T(`place: 'gate', cast: [who.page(-2.6, { gesture: 'bow', from: 5 }), who.zhongqing(8, { walk: [8, 0.4, 0.5, 7], flip: true }), who.nanxiang(9.6, { walk: [9.6, 2.2, 1, 7.6], flip: true })]`),
      T(`place: 'gate', cast: [who.zhongqing(-0.8)], ${lines('颜夫人之侄', '年二十三', '号剑潭', '颜仲清')}`),
    ],
    subtitles: [
      [0.4, 6, '一日，先生有事放学，', 'One day, the teacher dismissed his students early to attend to some affairs,'],
      [6, 11.6, '子玉正在独坐，', 'leaving Ziyu sitting in solitude,'],
      [12.4, 23.6, '却有两个好友来看他。', 'when two close companions arrived to visit him.'],
      [24.4, 29.4, '一个姓颜名仲清，号剑潭，现年二十三岁，', 'One was Yan Zhongqing, styled Jiantan, twenty-three years of age,'],
      [29.4, 35.6, '即系已故编修颜庄之子，为颜夫人之侄。', 'the son of the late Compiler Yan Zhuang, and Lady Yan’s nephew.'],
    ],
  },
  {
    n: 6, title: ['Zhongqing and Nanxiang', '仲清与南湘'],
    description: ['Zhongqing’s orphaned childhood and marriage; Shi Nanxiang, top provincial scholar; and how Zhongqing’s learning differs from Ziyu’s.', '仲清幼孤、成婚；史南湘为解元；仲清与子玉学问之别。'],
    staging: 'a memorial arch to Zhongqing’s mother, his upbringing, Nanxiang’s portrait, and the two cousins compared',
    shots: [
      [0, 10, 'A mother’s devotion', '郑氏殉节', '他夫人郑氏绝食殉节。', 'Yan Zhuang died at thirty; his wife starved herself to follow him, and an arch was raised to her.', '颜庄三十而卒，夫人郑氏绝食殉节，请旌表烈。'],
      [10, 18, 'Raised by Shixie', '士燮抚养在家', '那时仲清年甫三龄，士燮抚养在家', 'Shixie raised the three-year-old Zhongqing, who passed the examinations at nineteen and married into the Wang family.', '士燮抚养三岁的仲清；十九岁中副车，赘于王文辉家。'],
      [18, 27, 'Shi Nanxiang', '史南湘', '那一位姓史名南湘，号竹君……已中了本省解元。', 'The other visitor: Shi Nanxiang, styled Zhujun, of Hanyang, twenty-four, top scholar of his province.', '史南湘，号竹君，汉阳人，年二十四，已中解元。'],
      [27, 36, 'Purity and breadth', '纯粹与旷达', '子玉是纯粹一路，仲清是旷达一路。', 'Ziyu follows the path of purity, probing every depth; Zhongqing the path of breadth, grasping the outline.', '子玉纯粹，钩探索隐；仲清旷达，略观大概。'],
    ],
    beats: [
      T(`place: 'arch', cast: [who.lady(-4.2, { opacity: 0.4 })], ${lines('请旌表烈', '绝食殉节', '郑氏')}`),
      T(`place: 'hall', cast: [who.teacher(-1.8), who.page(0.4, { gesture: 'bow' })], ${lines('赘于王门', '十九中副车', '抚养在家')}`),
      T(`place: 'landscape', cast: [who.nanxiang(-1, { gesture: 'laughing' })], ${lines('已中解元', '汉阳人', '号竹君', '史南湘')}`),
      study2(`who.ziyu(-2.2, { gesture: 'reading' })`, `who.zhongqing(1, { cues: [[3, 'speaking'], [6, 'still']] })`, `, ${lines('仲清旷达', '子玉纯粹')}`),
    ],
    subtitles: [
      [0.4, 4.6, '这颜庄在日，与士燮既系郎舅至亲，又有雷陈至契。', 'Yan Zhuang had been Shixie’s brother-in-law and dearest friend.'],
      [4.6, 9.6, '不料于三十岁即赴召玉楼，他夫人郑氏绝食殉节。', 'He died at thirty, and his wife, Lady Zheng, starved herself to follow him.'],
      [10.4, 14, '那时仲清年甫三龄，士燮抚养在家，又与郑氏夫人请旌表烈。', 'Shixie raised three-year-old Zhongqing and petitioned for an arch to honor Lady Zheng.'],
      [14, 17.6, '到十九岁上中了个副车，赘于王文辉家为婿。', 'At nineteen Zhongqing passed as a supplementary candidate and married into Wang Wenhui’s family.'],
      [18.4, 22.6, '那一位姓史名南湘，号竹君，是湖广汉阳人，', 'The other was Shi Nanxiang, styled Zhujun, of Hanyang in Huguang,'],
      [22.6, 26.6, '现年二十四岁，已中了本省解元。', 'twenty-four, already the top scholar of his provincial examination.'],
      [27.4, 31.6, '子玉是纯粹一路，仲清是旷达一路。', 'Ziyu followed the path of purity; Zhongqing the path of expansive breadth.'],
      [31.6, 35.6, '仲清略观大概，不求甚解；子玉则钩探索隐，精益求精。', 'Zhongqing grasped the broad outlines; Ziyu probed the hidden depths.'],
    ],
  },
  {
    n: 7, title: ['Each lights the other', '互相点悟'],
    description: ['What Zhongqing scorns blooms when Ziyu explains it; what Ziyu cannot solve, one word from Zhongqing makes clear.', '仲清所鄙，经子玉讲贯而妙义环生；子玉不解，经仲清一言而白地光明。'],
    staging: 'Ziyu expounding to Zhongqing, then Zhongqing’s single word lighting up Ziyu',
    shots: [
      [0, 18, 'Endless subtle meaning', '妙义环生', '往往有仲清鄙夷不屑之学，经子玉精心讲贯，便觉妙义环生。', 'A subject Zhongqing dismisses, once Ziyu expounds it, blooms with subtle meaning.', '仲清鄙夷之学，经子玉讲贯，妙义环生。'],
      [18, 36, 'Light on barren ground', '白地光明', '亦有子玉所索解不得之理，经仲清一言点悟，顿觉白地光明。', 'A principle Ziyu cannot reach, one word from Zhongqing floods with light.', '子玉索解不得之理，仲清一言点悟，顿觉白地光明。'],
    ],
    beats: [
      study2(`who.ziyu(-2.2, { cues: [[0.6, 'speaking']] })`, `who.zhongqing(1, { cues: [[9, 'laughing']] })`, `, ${lines('妙义环生', '精心讲贯')}`),
      study2(`who.ziyu(-2.2, { gesture: 'thinking', cues: [[9, 'laughing']] })`, `who.zhongqing(1, { cues: [[5, 'pointing'], [9, 'still']] })`, `, aura: [-2.8, 0.6], ${lines('白地光明', '一言点悟')}`),
    ],
    subtitles: [
      [0.4, 9, '往往有仲清鄙夷不屑之学，', 'Often, a subject that Zhongqing would dismiss with disdain,'],
      [9, 17.6, '经子玉精心讲贯，便觉妙义环生。', 'once meticulously expounded by Ziyu, would bloom with endless, subtle meaning.'],
      [18.4, 27, '亦有子玉所索解不得之理，', 'Conversely, a principle that eluded Ziyu’s deepest searching'],
      [27, 35.6, '经仲清一言点悟，顿觉白地光明。', 'could be illuminated by a single word from Zhongqing, flooding the barren ground with light.'],
    ],
  },
  {
    n: 8, title: ['Closer than brothers', '比同胞手足更加亲密'],
    description: ['Ten years of friendship between Ziyu and Zhongqing; and Nanxiang, wild and proud, who can write ten thousand words leaning on a horse.', '子玉仲清十余年之交；南湘清狂绝俗，倚马万言。'],
    staging: 'the cousins walking together in the hills, then Nanxiang beside his horse',
    shots: [
      [0, 14, 'Ten years together', '相聚十余年', '这两个相聚十余年，其结契之厚，比同胞手足更加亲密。', 'Ten years together have made the two closer than blood brothers.', '二人相聚十余年，亲逾手足。'],
      [14, 36, 'Ten thousand words on horseback', '倚马万言', '那南湘是啸傲忘形，清狂绝俗……就只赏识子玉、仲清二人。', 'Nanxiang roars with laughter, looks down on his age, writes ten thousand words leaning on a horse, and admires only Ziyu and Zhongqing.', '南湘啸傲忘形，目空一世，倚马万言，只赏识子玉、仲清二人。'],
    ],
    beats: [
      T(`place: 'landscape', cast: [who.ziyu(-7, { walk: [-7, -1.8, 0.4, 9] }), who.zhongqing(-8.6, { walk: [-8.6, -3.4, 0.6, 9.2] })], ${lines('亲逾手足', '相聚十余年')}`),
      T(`place: 'landscape', cast: [{ kind: 'horse', x: -2.6, h: 4.4 }, who.nanxiang(0.8, { cues: [[1, 'laughing'], [8, 'pointing'], [14, 'laughing']] })], ${lines('倚马万言', '目空一世', '清狂绝俗', '啸傲忘形')}`),
    ],
    subtitles: [
      [0.4, 7, '这两个相聚十余年，', 'These two had spent over ten years in each other’s company;'],
      [7, 13.6, '其结契之厚，比同胞手足更加亲密。', 'the depth of their bond surpassed even that of blood brothers.'],
      [14.4, 20, '那南湘是啸傲忘形，清狂绝俗，', 'As for Nanxiang, he roared with laughter and transcended mere form, apart from the vulgar world.'],
      [20, 27, '目空一世，倚马万言，', 'He looked down on his whole generation, and could write ten thousand words leaning on a horse,'],
      [27, 35.6, '就只赏识子玉、仲清二人。', 'yet deigned to appreciate only Ziyu and Zhongqing.'],
    ],
  },
  {
    n: 9, title: ['Nanxiang’s question', '南湘设问'],
    description: ['In Ziyu’s study, over tea, Nanxiang tests him: what most pleases the ear and eye and stirs the soul?', '书房茶叙，南湘试问子玉：世间何物最能娱耳悦目、动心荡魄？'],
    staging: 'the friends shown into the study, tea served, and Nanxiang’s question with Ziyu’s answer',
    shots: [
      [0, 10, 'Shown straight in', '引到书房', '门上见是来惯的，是少爷至好，便一直引到书房与子玉见了。', 'The gatekeepers know the young master’s closest friends and show them straight to the study.', '门上见是少爷至好，一直引到书房。'],
      [10, 20, 'Tea in the study', '书僮送上香茗', '三人讲了些话，书僮送上香茗。', 'A pageboy serves tea; Nanxiang notes the room’s antique elegance and wonders what passions Ziyu hides.', '书僮送茶；南湘见室中清雅，欲试子玉。'],
      [20, 36, 'What stirs the soul?', '动心荡魄', '世间能使人娱耳悦目，动心荡魄的，以何物为最？', 'Nanxiang asks what most stirs the soul; Ziyu answers that every temperament differs.', '南湘问何物最能动心荡魄；子玉答：人性情各异。'],
    ],
    beats: [
      T(`place: 'gate', cast: [who.page(-2.8, { gesture: 'bow' }), who.zhongqing(7, { walk: [7, 0.2, 0.4, 7], flip: true }), who.nanxiang(8.6, { walk: [8.6, 1.8, 0.8, 7.4], flip: true })]`),
      T(`place: 'study', table: {}, cast: [who.page(-7, { walk: [-7, -4.4, 0.5, 4], gesture: 'offering', until: 8 }), who.zhongqing(-2.5), who.ziyu(0, { gesture: 'reading' }), who.nanxiang(2.5, { cues: [[6, 'thinking']] })]`),
      study3('', `[[7, 'thinking'], [9, 'speaking']]`, `[[0.3, 'pointing'], [6, 'still']]`, `, ${lines('动心荡魄', '娱耳悦目')}`),
    ],
    subtitles: [
      [0.4, 5, '这日同来看子玉，门上见是来惯的，', 'On this day they came together; the gatekeepers recognized the frequent guests,'],
      [5, 9.6, '是少爷至好，便一直引到书房与子玉见了。', 'the young master’s closest friends, and ushered them straight into the study.'],
      [10.4, 14.6, '三人讲了些话，书僮送上香茗。', 'After the three had exchanged pleasantries, a pageboy served fragrant tea.'],
      [14.6, 19.6, '南湘见这室中清雅绝尘，便想来试他一试。', 'Nanxiang noted the room’s transcendent elegance, and resolved to test him.'],
      [20.4, 25, '「庾香，我问你，世间能使人娱耳悦目，动心荡魄的，以何物为最？」', '“Yuxiang, what in this world most pleases the ear, delights the eye, and stirs the soul?”'],
      [25, 30, '子玉答道：「这句话却问得太泛，人生耳目虽同，性情各异。」', 'Ziyu replied: “Your question casts too wide a net. All men share ears and eyes, but their temperaments differ.”'],
      [30, 35.6, '南湘道：「不是这么说，我是指一种人而言。」', 'Nanxiang shook his head. “That is not my meaning. I speak of a specific kind of person.”'],
    ],
  },
  {
    n: 10, title: ['Dreadful, laughable, detestable', '可畏、可笑、可恶'],
    description: ['Nanxiang sorts the capital’s crowds: the official who inspires dread, the pedant who is laughable, the merchant who is detestable.', '南湘数京城众生：位尊望重者可畏，酸腐措大可笑，市井逐臭之夫可恶。'],
    staging: 'three caricatures in turn: the official, the pedant, the merchant',
    shots: [
      [0, 12, 'The official: dreadful', '可畏', '见位尊望重者，与之讲官话，说官箴……则可畏。', 'A man of rank, all official jargon and decorum from head to toe: he inspires dread.', '位尊望重者，满口官话，自顶至踵合乎官体：可畏。'],
      [12, 24, 'The pedant: laughable', '可笑', '见酸腐措大，拘手挛足，曲背耸肩而呻吟作推敲之势，则可笑。', 'A sour pedant, hunched and shrugging, groaning over his phrases: laughable.', '酸腐措大，曲背耸肩，呻吟推敲：可笑。'],
      [24, 36, 'The merchant: detestable', '可恶', '见市井逐臭之夫，评黄白，论市价，俗气熏人，则可恶。', 'A market vulgarian haggling over silver and prices: detestable.', '市井逐臭之夫，评黄白，论市价：可恶。'],
    ],
    beats: [
      T(`place: 'hall', cast: [{ kind: 'official', x: -0.8, h: 4.8 }], ${lines('可畏', '位尊望重')}`),
      T(`place: 'study', cast: [{ kind: 'pedant', x: -0.8, h: 4.6 }], ${lines('可笑', '酸腐措大')}`),
      T(`place: 'street', cast: [{ kind: 'merchant', x: -0.8, h: 4.6 }], ${lines('可恶', '市井逐臭')}`),
    ],
    subtitles: [
      [0.4, 5, '现在这京城里人山人海，', 'The capital today is an endless sea of humanity.'],
      [5, 11.6, '见位尊望重者，与之讲官话，说官箴，一一要合官体，则可畏。', 'A man of exalted rank, all official jargon, every inch bound by decorum—he inspires only dread.'],
      [12.4, 18, '见酸腐措大，拘手挛足，曲背耸肩，', 'A sour, pedantic scholar, hands cramped, hunching his back and shrugging his shoulders,'],
      [18, 23.6, '而呻吟作推敲之势，则可笑。', 'groaning in the pretense of deep thought—he is merely laughable.'],
      [24.4, 30, '见市井逐臭之夫，评黄白，论市价，', 'A market vulgarian chasing foul scents, haggling over silver and gold,'],
      [30, 35.6, '俗气熏人，则可恶。', 'exuding a stench of commonness—he is simply detestable.'],
    ],
  },
  {
    n: 11, title: ['Friends as a pleasure?', '二三知己'],
    description: ['Last on Nanxiang’s list, vulgar actors; Ziyu guesses the pleasure must be friends, and his friends laugh until he blushes.', '南湘末数俗优滥妓；子玉答以二三知己，二友大笑，子玉脸红。'],
    staging: 'the vulgar actor, Ziyu’s guess and the laughter, and Ziyu blushing as he explains',
    shots: [
      [0, 10, 'Vulgar actors: hateful', '可恨', '见俗优滥妓，油头粉面，无耻之极，则可恨。', 'Vulgar actors with greased hair and powdered faces: hateful.', '俗优滥妓，油头粉面：可恨。'],
      [10, 22, 'Two or three kindred spirits', '二三知己', '既然娱悦不在声色，其唯二三知己朝夕素心乎？', 'Ziyu guesses: the true pleasure must be two or three kindred friends. Zhongqing and Nanxiang burst out laughing.', '子玉答以二三知己；仲清、南湘大笑。'],
      [22, 36, 'A faint blush', '脸已微红', '子玉被他们这一笑，笑得不好意思起来，脸已微红', 'Ziyu blushes and explains: pure talk with a whisk, graceful friends in dark robes—do these not please the eye?', '子玉脸红，辩说挥麈清谈、乌衣美秀，岂不娱耳悦目。'],
    ],
    beats: [
      T(`place: 'theatre', cast: [{ kind: 'escort', x: -0.8, h: 4.6 }], ${lines('可恨', '油头粉面')}`),
      study3(`[[4, 'laughing']]`, `[[0.4, 'speaking'], [4, 'still']]`, `[[5.4, 'laughing']]`),
      study3('', `[[0.4, 'speaking']]`, '', `, ${lines('乌衣美秀', '挥麈清淡')}`).replace("gesture: 'reading', cues", "gesture: 'reading', blush: true, cues"),
    ],
    subtitles: [
      [0.4, 5, '见俗优滥妓，油头粉面，无耻之极，则可恨。', 'Vulgar actors and prostitutes, greased hair and powdered faces, shameless—thoroughly hateful.'],
      [5, 9.6, '你想，凡目中所见的，去了这些，还有那一种人？', 'Strip away all these types: what kind of person remains?'],
      [10.4, 15.6, '子玉只得说道：「既然娱悦不在声色，其唯二三知己朝夕素心乎？」', 'Ziyu offered: “Since pleasure is not in sounds and sights, does it lie in two or three kindred spirits?”'],
      [15.6, 21.6, '仲清大笑。南湘道：「岂有此理！庾香设心不良。」说罢哈哈大笑。', 'Zhongqing burst out laughing. Nanxiang: “Absurd! Yuxiang, your heart harbors ill intentions!” He laughed uproariously.'],
      [22.4, 28, '子玉被他们这一笑，脸已微红，便说道：「你们休要取笑。', 'Ziyu felt a faint blush touch his cheeks. “Cease your mockery.'],
      [28, 35.6, '挥麈清淡，乌衣美秀，难道不可娱耳，不可悦目？」', 'Pure talk with a deer-tail whisk, the grace of those in dark robes—do these not please the ear and eye?”'],
    ],
  },
  {
    n: 12, title: ['A book from his boot', '靴中取书'],
    description: ['Ziyu adds wine and an ancient sword; Nanxiang draws his newly printed 《曲台花选》 from his boot, and Ziyu opens it.', '子玉又举醇醪古剑；南湘从靴里取出新刻《曲台花选》，子玉揭开一看。'],
    staging: 'a still life of wine and sword, Nanxiang handing over his book, and the book opening',
    shots: [
      [0, 9, 'Wine and an ancient sword', '醇醪醉心，古剑照胆', '醇醪醉心，古剑照胆，交友中难道无动心荡魄处么？', 'Rich wine and an ancient sword: do these not stir the soul between friends?', '醇醪醉心，古剑照胆，交友中岂无动心荡魄处？'],
      [9, 22, 'Nanxiang’s new book', '我近刻的', '即从靴里取出一本书来，送与子玉', 'Nanxiang draws a book from his boot: those who stir the soul are among these gentlemen. Zhongqing laughs that Ziyu will never be convinced.', '南湘从靴里取出一本书送与子玉；仲清笑他如苏秦说秦王。'],
      [22, 36, 'The Opera Stage Flower Manual', '《曲台花选》', '书目是《曲台花选》……子玉见第一个题的是：', 'The title reads 《曲台花选》. Skipping the prefaces, Ziyu turns to the first entry.', '书名《曲台花选》，子玉略过序文，看第一题。'],
    ],
    beats: [
      T(`place: 'still-wine', ${lines('古剑照胆', '醇醪醉心')}`),
      study3(`[[7, 'laughing']]`, `[[4, 'still']]`, `[[0.4, 'speaking'], [3, 'pointing'], [6.6, 'still']]`),
      `coverBeat('曲台花选', ['第一题', '琼楼珠树袁宝珠'])`,
    ],
    subtitles: [
      [0.4, 8.6, '醇醪醉心，古剑照胆，交友中难道无动心荡魄处么？', 'Heart-intoxicating wine, an ancient sword reflecting courage—do these not stir the soul in friendship?'],
      [9.4, 13.4, '南湘笑道：「你总是这一间屋子里的说话，所见不广。」', 'Nanxiang smiled: “Your words never leave this single room. Your vision is not broad.”'],
      [13.4, 17.6, '即从靴里取出一本书来：「大约可以动心荡魄者，要在此数君。」', 'He drew a book from his boot: “Those who stir the soul are to be found among these few gentlemen.”'],
      [17.6, 21.6, '仲清笑道：「你将此书呈政于庾香，真似苏秦始见秦王。」', 'Zhongqing chuckled: “Presenting this to Yuxiang is like Su Qin’s first audience with the King of Qin.”'],
      [22.4, 27, '子玉便揭开一看，书目是《曲台花选》，', 'Ziyu opened it and saw the title: “The Opera Stage Flower Manual.”'],
      [27, 31.6, '南湘叫他不要看序，且看所选的人。', 'Nanxiang urged him to skip the prefaces and look at the selected individuals.'],
      [31.6, 35.6, '子玉见第一个题的是：', 'Ziyu noted that the first entry read:'],
    ],
  },
  {
    n: 35, title: ['No flawless jade', '断无全璧'],
    description: ['Ziyu’s case against the actors: they serve with their looks, feign joy for money, and on stage are blank monuments.', '子玉论小旦：以色事人，强笑假欢，缠头是爱，上台不过麒麟楦、没字碑。'],
    staging: 'Ziyu arguing in the study, an actor fawning over a patron, and a blank stele',
    shots: [
      [0, 12, 'Serving with their looks', '以色事人', '我想此辈中人，断无全壁，以色事人，不求其媚，必求其馅。', 'Ziyu: among such people there is no flawless jade; serving with their looks, they charm or they flatter.', '子玉：此辈断无全璧，以色事人，不媚必谄。'],
      [12, 24, 'Their only love is money', '缠头是爱', '强笑假欢，缠头是爱。', 'Forcing smiles, feigning joy, their only love the money thrown at them.', '强笑假欢，缠头是爱。'],
      [24, 36, 'A monument with no inscription', '没字碑', '也不过上台时效个麒麟楦，充个没字碑。', 'However well made up, on stage they are a qilin’s hide over a donkey, a stele with nothing written.', '纵使涂泽为工，上台不过麒麟楦、没字碑。'],
    ],
    beats: [
      study3('', `[[0.4, 'speaking']]`, '', `, ${lines('不媚必谄', '以色事人')}`),
      T(`place: 'theatre', cast: [{ kind: 'merchant', x: 0.6 }, { kind: 'escort', x: -1.8, cues: [[0, 'speaking'], [5, 'tugging']] }], ${lines('缠头是爱', '强笑假欢')}`),
      T(`place: 'stele', ${lines('没字碑', '麒麟楦')}`),
    ],
    subtitles: [
      [0.4, 6, '我想此辈中人，断无全璧。以色事人，不求其媚，必求其谄。', 'Among such people there cannot be a flawless jade. Serving with their looks, they charm or they flatter.'],
      [6, 11.6, '况朝秦暮楚，酒食自娱，', 'Shifting allegiances morning and night, amusing themselves with wine and food,'],
      [12.4, 18, '强笑假欢，缠头是爱。此身既难自洁，而此志亦为太卑。', 'forcing smiles and feigning joy, loving only the money thrown to them; their aspirations far too base.'],
      [18, 23.6, '所学者婢膝奴颜，所工者谑浪笑傲。', 'They study how to bend the knee; they excel at frivolous banter.'],
      [24.4, 29.4, '就使涂泽为工，描摹得态，', 'Even if their makeup is expert and their mimicry apt,'],
      [29.4, 35.6, '也不过上台时效个麒麟楦，充个没字碑。', 'on stage they merely don a qilin’s hide, or stand as blank as an uninscribed monument.'],
    ],
  },
  {
    n: 36, title: ['Stained by the mud', '出污泥而不滓'],
    description: ['Ziyu doubts any can rise from the mud unstained; a single charm in them is a thread from a sock, a knife of lead.', '子玉以为无人能出污泥而不滓；即有一技之长，亦如锦袜之线、铅水之刀。'],
    staging: 'lotus in a muddy pond, Ziyu’s comparisons in the study, and the actor once more',
    shots: [
      [0, 14, 'Out of the mud', '出污泥', '岂有出污泥而不滓，随狂流而不下者。', 'Who could rise from the mud without a stain, or drift on the flood without going under?', '岂有出污泥而不滓、随狂流而不下者。'],
      [14, 26, 'A thread from a brocade sock', '锦袜之线', '是犹拆锦袜之线，无补于缝裳。炼铅水之刀，不良于伐木。', 'A single charm is like thread pulled from a brocade sock, useless for sewing; a knife of lead, unfit for wood.', '一容一技，犹拆锦袜之线、炼铅水之刀。'],
      [26, 36, 'Foul within', '脏腑秽浊', '其脏腑秽浊，出言无章。', 'Their insides are foul and turbid, their speech without order.', '其脏腑秽浊，出言无章。'],
    ],
    beats: [
      T(`place: 'mud-lotus', ${lines('而不滓', '出污泥')}`),
      study3('', `[[0.4, 'speaking'], [8, 'pointing']]`, `[[9, 'thinking']]`, `, ${lines('炼铅水之刀', '拆锦袜之线')}`),
      T(`place: 'theatre', cast: [{ kind: 'escort', x: -0.8, h: 4.6, cues: [[4, 'speaking']] }], ${lines('出言无章', '脏腑秽浊')}`),
    ],
    subtitles: [
      [0.4, 7, '岂有出污泥而不滓，', 'How could there be one who emerges from the mud without being stained,'],
      [7, 13.6, '随狂流而不下者。', 'or drifts along the wild current without being pulled under?'],
      [14.4, 20, '且即有一容可取，一技所长，是犹拆锦袜之线，无补于缝裳。', 'Even a tolerable face or a single skill is like thread from a brocade sock—useless for sewing a garment.'],
      [20, 25.6, '炼铅水之刀，不良于伐木。', 'It is a knife forged from leaden water—unfit for chopping wood.'],
      [26.4, 35.6, '其脏腑秽浊，出言无章。', 'Their internal organs are foul and turbid; their speech lacks order and refinement.'],
    ],
  },
  {
    n: 37, title: ['True beauties of the boudoir', '红闺弱质'],
    description: ['Ziyu lists the actors’ flaws, praises the natural grace of real women, and calls their stage heroines an insult to Xishi.', '子玉数小旦之病，赞红闺佳人天然之美，谓以小旦演古之绝色，唐突西子。'],
    staging: 'four flaws written beside a faint actor, a lady in her boudoir, and Ziyu’s verdict on a scroll',
    shots: [
      [0, 12, 'Beautiful but not radiant', '色美不华', '故色虽美而不华，肌虽白而不洁，神虽妍而不清，气虽柔而不秀。', 'Their coloring is beautiful but not radiant, their skin white but not pure, their spirit pretty but not clear.', '色美而不华，肌白而不洁，神妍而不清，气柔而不秀。'],
      [12, 26, 'Maidens of the red boudoir', '红闺弱质', '若夫红闺弱质，金屋丽姝……方可称为美人，为佳人。', 'The maidens of the boudoir: tranquil spirits, natural grace, no artifice—only they are true beauties.', '红闺弱质，金屋丽姝，神气静息，妙出自然，方可称为佳人。'],
      [26, 36, 'An insult to Xishi', '唐突西子', '今以红氍毹上演古之绝代倾城，真所谓刻画无盐，唐突西子。', 'To have actors play the great beauties of old is to paint Wuyan as Xishi—an insult to true beauty.', '以小旦演古之绝代倾城，真是刻画无盐，唐突西子。'],
    ],
    beats: [
      T(`place: 'theatre', cast: [{ kind: 'dan', x: -0.8, opacity: 0.55 }], ${lines('气柔不秀', '神妍不清', '肌白不洁', '色美不华')}`),
      T(`place: 'boudoir', cast: [who.lady(-1.2), { kind: 'maid', x: -3.6, h: 3.9, gesture: 'offering' }], ${lines('妙出自然', '金屋丽姝', '红闺弱质')}`),
      poem('刻画无盐', '唐突西子'),
    ],
    subtitles: [
      [0.4, 5, '其骨节少文，举动皆俗。', 'Their bones lack culture; their every movement is vulgar.'],
      [5, 11.6, '故色虽美而不华，肌虽白而不洁，神虽妍而不清，气虽柔而不秀。', 'Their coloring is not radiant, their skin not pure, their spirit not clear, their aura not elegant.'],
      [12.4, 17, '若夫红闺弱质，金屋丽姝，质秉纯阴，体含至静，', 'The delicate maidens of the red boudoirs, the beauties of golden houses, rooted in pure stillness—'],
      [17, 21.6, '眉目自见其清扬，声音自成其娇细。姿致动作，妙出自然。', 'their eyes are naturally bright, their voices naturally sweet, their movements wondrously natural.'],
      [21.6, 25.6, '鬓影衣香，无须造作，方可称为美人，为佳人。', 'Needing no artifice—only they can be called true beauties.'],
      [26.4, 31, '今以红氍毹上演古之绝代倾城，', 'To enact the peerless beauties of antiquity on the red carpet'],
      [31, 35.6, '真所谓刻画无盐，唐突西子。', 'is truly to paint Wuyan as Xishi, deeply insulting true beauty.'],
    ],
  },
  {
    n: 38, title: ['Better the clowns', '宁看净末老丑'],
    description: ['Ziyu would rather watch clowns than young dan; Nanxiang is furious, and Zhongqing makes peace.', '子玉宁看净末老丑；南湘气恼，仲清调停。'],
    staging: 'clowns capering on stage, Nanxiang angered, and Zhongqing mediating',
    shots: [
      [0, 12, 'Clowns and painted faces', '净末老丑', '所以我不愿看小旦戏，宁看净末老丑，翻可舒荡心胸，足助欢笑。', 'Ziyu would rather watch painted faces, old men and clowns: at least they make him laugh.', '宁看净末老丑，翻可舒荡心胸，足助欢笑。'],
      [12, 24, 'Nanxiang angered', '把南湘说出气来', '这一番话，把个史南湘说出气来。', 'Ziyu says Nanxiang’s ink only wrongs the ancients; Nanxiang is furious.', '子玉说南湘为若辈增光，使古人抱恨；南湘气恼。'],
      [24, 36, 'Zhongqing mediates', '仲清笑道', '庾香之论未尝不是，而竹君之选也甚平允。', 'Zhongqing laughs: both are right; Ziyu simply does not know such people exist—like tales of marvels.', '仲清笑道：二人之论皆是，只是庾香不知天地间有此数人。'],
    ],
    beats: [
      T(`place: 'theatre', cast: [{ kind: 'clown', x: -2.2, h: 4 }, { kind: 'clown', x: 0.8, h: 4, flip: true }], ${lines('足助欢笑', '宁看净末老丑')}`),
      study3('', `[[0.4, 'speaking'], [6.4, 'still']]`, `[[6.4, 'pointing']]`),
      study3(`[[0.4, 'laughing'], [3, 'speaking']]`, '', '', `, ${lines('幽怪之书', '搜神之记')}`),
    ],
    subtitles: [
      [0.4, 6, '所以我不愿看小旦戏，宁看净末老丑，', 'That is why I would rather not watch the young dan, but the painted faces, old men and clowns,'],
      [6, 11.6, '翻可舒荡心胸，足助欢笑。', 'who at least ease the mind and provoke hearty laughter.'],
      [12.4, 18.6, '吾兄不惜笔墨，竭力铺张，为若辈增光，而使古人抱恨，', 'You spare no ink to add glory to this lot, while leaving the ancients to harbor regrets—'],
      [18.6, 23.6, '窃为吾兄有所不取。」这一番话，把个史南湘说出气来。', 'I find it lacking.” This speech infuriated Shi Nanxiang.'],
      [24.4, 29.4, '仲清笑道：「庾香之论未尝不是，而竹君之选也甚平允。', 'Zhongqing laughed: “Yuxiang is not wrong, yet Zhujun’s selections are quite fair.'],
      [29.4, 35.6, '但庾香不知天地间有此数人，譬如读《搜神》之记，《幽怪》之书。', 'Yuxiang just doesn’t know such people exist—like reading “In Search of the Supernatural.”'],
    ],
  },
  {
    n: 39, title: ['Seeing is believing', '非亲见其人不可'],
    description: ['Zhongqing proposes to take Ziyu out tomorrow and show him the actors in person.', '仲清提议明日同子玉出去，亲指一二人与他看。'],
    staging: 'Zhongqing speaking in the study, then the three setting out along the street',
    shots: [
      [0, 16, 'Who would believe it?', '又谁肯轻信', '而必欲使人实信其有，又谁肯轻信？是非亲见其人不可。', 'Who would believe such tales unless they saw these people in person?', '欲使人实信其有，非亲见其人不可。'],
      [16, 36, 'Tomorrow we take him out', '明日同他出去', '我们明日同他出去，亲指一二人与他看了', 'Tomorrow they will take him out and point out one or two; then he will believe the 《花选》.', '明日同他出去，亲指一二人与他看，他才信《花选》选的不错。'],
    ],
    beats: [
      study3(`[[0.4, 'speaking'], [8, 'pointing']]`, '', ''),
      T(`place: 'street', cast: [who.zhongqing(-7, { walk: [-7, -0.6, 0.4, 10] }), who.ziyu(-8.6, { walk: [-8.6, -2.2, 0.6, 10.2] }), who.nanxiang(-10.2, { walk: [-10.2, -3.8, 0.8, 10.4] })], ${lines('亲指一二人', '明日同他出去')}`),
    ],
    subtitles: [
      [0.4, 8, '而必欲使人实信其有，又谁肯轻信？', 'If one insists on making people believe they exist, who would readily accept it?'],
      [8, 15.6, '是非亲见其人不可。', 'It is impossible unless one sees them in person.'],
      [16.4, 26, '我们明日同他出去，亲指一二人与他看了，', 'Tomorrow, we will take him out and point out one or two of them for him to see;'],
      [26, 35.6, '他才信你这个《花选》方选的不错。', 'only then will he believe your “Selection of Flowers” has made no mistake.'],
    ],
  },
  {
    n: 40, title: ['Beauty is not only women’s', '美色不专属于女子'],
    description: ['Zhongqing cites the classics on beautiful men; Nanxiang adds plum branches, bright-plumed birds and a mirror. Ziyu, blushing, half-concedes.', '仲清引经据典论男子之美；南湘以梅枝、禽鸟、照镜为证。子玉脸红，将信将疑。'],
    staging: 'the classics on a scroll, plum and pheasant, Ziyu before a mirror, and Xishi washing silk',
    shots: [
      [0, 9, '“That beautiful person”', '彼美人兮', '如《毛诗》「彼美人兮」……南方多佳人。', 'Zhongqing quotes the classics, where men too are called beauties.', '仲清引《毛诗》、杜诗、《赤壁赋》、《后汉书》，男子亦称美人佳人。'],
      [9, 17, 'The southern branches bloom first', '梅花南枝先', '梅花南枝先，北枝后……有文采的禽鸟都是雄的', 'Nanxiang: plum blooms on its southern branches first, and the bright-plumed birds are all male.', '南湘：梅花南枝先开；有文采的禽鸟都是雄的。'],
      [17, 27, 'In the mirror', '同在镜里一照', '你如今叫你家里那些丫头们来，同在镜里一照', 'Stand before a mirror beside your maids, says Nanxiang, and see who is fairer. Ziyu blushes.', '南湘：叫丫头们同你在镜里一照，自然看得出好歹。子玉脸红。'],
      [27, 36, 'Xishi washed silk', '西子浣纱', '就是西子也曾贫贱浣纱', 'Ziyu muses: even Xishi once washed silk in poverty; perhaps heaven does make such people.', '子玉暗想：西子也曾贫贱浣纱，或者天生这一种人。'],
    ],
    beats: [
      poem('彼美人兮', '美人何为隔秋水', '望美人兮天一方', '南方多佳人'),
      T(`place: 'birds', ${lines('禽鸟雄者文采', '梅花南枝先')}`),
      T(`place: 'mirror', cast: [{ kind: 'maid', x: -3.4, h: 3.9 }, who.ziyu(-0.6, { blush: 4 }), { kind: 'maid', x: 2.2, h: 3.9 }], ${lines('同在镜里一照')}`),
      T(`place: 'river', cast: [who.lady(-2.2, { gesture: 'offering' }), who.ziyu(1.4, { gesture: 'thinking', opacity: 0.55 })], ${lines('贫贱浣纱', '西子')}`),
    ],
    subtitles: [
      [0.4, 4.6, '《毛诗》「彼美人兮」，杜诗「美人何为隔秋水」，', 'The Mao Shi: “That beautiful person!”; Du Fu: “Why is the beauty separated by autumn waters?”'],
      [4.6, 8.6, '光武叹曰：「南方多佳人。」可见美色不专属于女子。', 'Emperor Guangwu sighed, “The South has many exquisite people.” Beauty is not women’s alone.'],
      [9.4, 13, '南湘道：「梅花南枝先，北枝后。', 'Nanxiang added: “The plum’s southern branches bloom first, the northern later.'],
      [13, 16.6, '有文采的禽鸟都是雄的，可见造化之气，先钟于男。」', 'The birds with brilliant plumage are all male: nature gathers first in the male.”'],
      [17.4, 22, '「你如今叫你家里那些丫头们来，同在镜里一照，', '“Call the maids of your house and look together in a mirror,'],
      [22, 26.6, '自然你也看得出好歹。」子玉不觉脸红。', 'and you will naturally see the difference.” Ziyu unwittingly blushed.'],
      [27.4, 31.6, '就是西子也曾贫贱浣纱，或者天生这一种人，以快人间的心目。', 'Even Xishi once washed silk in poverty; perhaps heaven makes such people to delight the world.'],
      [31.6, 35.6, '南湘狂笑道：「庾香此时难算知音，我再去请教别人罢。」', 'Nanxiang laughed: “Yuxiang is no knowing friend yet. I shall seek others’ judgment.”'],
    ],
  },
  {
    n: 41, title: ['Put out of mind', '不放在心上'],
    description: ['Nanxiang drags Zhongqing away; Ziyu decides the 《花选》 is idle boasting; his teacher returns and his mother calls him in.', '南湘拉仲清去了；子玉仍以《花选》为妄言；李先生回来，颜夫人叫他进去。'],
    staging: 'the friends leaving at the gate, Ziyu alone with the book, and the teacher and Lady Yan',
    shots: [
      [0, 12, 'Dragged away', '拉了仲清去了', '便拉了仲清去了。', 'Nanxiang drags Zhongqing off; Ziyu sees them out.', '南湘拉了仲清去了，子玉送客。'],
      [12, 24, 'Nothing like the actors he knew', '一毫不对', '再想从前看过的戏，与见过的小旦一毫不对', 'Ziyu thinks back on the actors he has seen: nothing like the book. He puts it out of mind.', '子玉想起从前见过的小旦，一毫不对，便不放在心上。'],
      [24, 36, 'Back to his books', '仍在书房念书', '李先生回来，仍在书房念了一会书，颜夫人然后叫了进去。', 'Teacher Li returns; Ziyu studies a while, then Lady Yan calls him inside.', '李先生回来，子玉念了一会书，颜夫人叫他进去。'],
    ],
    beats: [
      T(`place: 'gate', cast: [who.ziyu(-2.6, { gesture: 'bow' }), who.nanxiang(0.4, { walk: [0.4, 9, 1, 8] }), who.zhongqing(1.8, { walk: [1.8, 10.4, 0.6, 8] })]`),
      T(`place: 'study', table: { x: 0, w: 5 }, cast: [who.ziyu(0, { gesture: 'thinking' })], ${lines('一毫不对', '默默一想')}`),
      T(`place: 'study', table: { x: -0.4, w: 6.4 }, cast: [who.teacher(-2.4, { cues: [[0.4, 'speaking'], [6, 'still']] }), who.ziyu(1, { gesture: 'reading' }), who.lady(-9, { walk: [-9, -5, 6.5, 9.5], cues: [[9.6, 'speaking']] })]`),
    ],
    subtitles: [
      [0.4, 11.6, '便拉了仲清去了。子玉送客转来，', 'He then dragged Zhongqing away. Ziyu saw his guests out and returned,'],
      [12.4, 18, '又将南湘的《花选》默默的一想，再想从前看过的戏，与见过的小旦一毫不对，', 'pondering the “Flower Manual”; the young dan he had seen did not match it in the slightest.'],
      [18, 23.6, '犹以南湘为妄言，便也不放在心上了。', 'He concluded Nanxiang was speaking wildly, and put it out of his mind.'],
      [24.4, 30, '李先生回来，仍在书房念了一会书，', 'Teacher Li returned; Ziyu studied in the study for a while longer,'],
      [30, 35.6, '颜夫人然后叫了进去。', 'before Lady Yan called him inside.'],
    ],
  },
  {
    n: 42, title: ['A half-day’s leave', '告了半天假'],
    description: ['Two days later Ziyu asks for a half-day’s leave to visit Nanxiang and Zhongqing.', '过了两日，子玉告半天假，去看南湘、仲清。'],
    staging: 'Ziyu bowing to his teacher, then setting out through the winter gate',
    shots: [
      [0, 16, 'Asking for leave', '告了半天假', '过了两日，子玉于早饭后告了半天假', 'Two days later, after breakfast, Ziyu asks his teacher for half a day’s leave.', '过了两日，子玉早饭后向先生告了半天假。'],
      [16, 36, 'To visit his friends', '去看南湘、仲清', '回去看南湘、仲清。', 'He sets out to visit Nanxiang and Zhongqing.', '子玉出门去看南湘、仲清。'],
    ],
    beats: [
      T(`place: 'study', cast: [who.teacher(-2.2, { cues: [[5, 'speaking'], [8, 'still']] }), who.ziyu(1, { flip: true, gesture: 'bow' })], ${lines('告了半天假', '过了两日')}`),
      T(`place: 'gate', flurry: true, cast: [who.ziyu(-1, { walk: [-1, 9, 2, 14] }), who.page(-2.4, { walk: [-2.4, 7.6, 2.4, 14.4] })]`),
    ],
    subtitles: [
      [0.4, 15.6, '过了两日，子玉于早饭后告了半天假，', 'Two days later, Ziyu requested a half-day’s leave after breakfast'],
      [16.4, 35.6, '回去看南湘、仲清。', 'and went back to visit Nanxiang and Zhongqing.'],
    ],
  },
  {
    n: 43, title: ['A lynx fur against the north wind', '葡萄猞猁裘'],
    description: ['Lady Yan wraps Ziyu in lynx fur against the north wind; two pages ride ahead of his fox-lined cart to his uncle Wang’s house, where young Wang Xun welcomes him.', '颜夫人为子玉披上猞猁裘；两个小使骑马先行，车到王通政宅，王恂出接。'],
    staging: 'Lady Yan and the fur coat, the cart and riders in the wind, and Wang Xun at his gate',
    shots: [
      [0, 12, 'A grape-patterned lynx fur', '葡萄猞猁裘', '便叫家人媳妇取出副葡萄的猞猁裘与他穿了', 'The weather is freezing; Lady Yan has a lynx fur coat brought for him and his cart lined with white fox.', '天气寒冷，颜夫人取出葡萄猞猁裘与他穿，车里换了白狐暖围。'],
      [12, 26, 'Riding into the north wind', '起了朔风', '两个小使：一个云儿，一个俊儿，骑了马', 'Two pages, Yun’er and Jun’er, ride ahead; the cart follows through the north wind.', '云儿、俊儿骑马先行，车随其后，朔风正紧。'],
      [26, 36, 'Wang Xun comes out', '少君出来接进', '适值通政出门去了，通政的少君出来接进。', 'The Commissioner is out; his son Wang Xun, styled Yong’an, twenty-two, welcomes Ziyu in.', '通政出门，少君王恂，号庸庵，年二十二，出来接进。'],
    ],
    beats: [
      T(`place: 'boudoir', cast: [who.lady(-1.4, { gesture: 'offering' }), who.ziyu(1.4, { flip: true, gesture: 'bow' })], ${lines('白狐暖围', '葡萄猞猁裘')}`),
      T(`place: 'street', flurry: true, cast: [{ kind: 'horse', x: -9, h: 2.6, walk: [-9, 9, 0.2, 9] }, who.page(-9, { y: 0.55, h: 3, walk: [-9, 9, 0.2, 9] }), { kind: 'cart', x: -13, fur: true, walk: [-13, 2, 2, 13] }]`),
      T(`place: 'gate', flurry: true, cast: [who.wangxun(0, { walk: [0, -1.4, 0.4, 2.4], cues: [[3, 'bow']] }), who.ziyu(8, { walk: [8, 1.6, 0.6, 5.4], flip: true, cues: [[5.6, 'bow']] })]`),
    ],
    subtitles: [
      [0.4, 6, '颜夫人见今日天气寒冷，起了朔风，且是冬月中旬，', 'Lady Yan saw the weather was freezing, a sharp north wind blowing in mid-winter,'],
      [6, 11.6, '便叫取出副葡萄的猞猁裘与他穿了，车里也换了白狐暖围。', 'and had a grape-patterned lynx fur brought for him, the carriage lined with white fox fur.'],
      [12.4, 19, '两个小使：一个云儿，一个俊儿，骑了马，', 'Two young pages, Yun’er and Jun’er, rode ahead on horseback.'],
      [19, 25.6, '先到他表母舅王通政宅内，', 'First they went to the residence of his uncle, Commissioner Wang.'],
      [26.4, 31, '适值通政出门去了，通政的少君出来接进。', 'The Commissioner had gone out, but his son came out to welcome him in.'],
      [31, 35.6, '这王通政的少君，名字单叫个恂字，号庸庵，年方二十二岁。', 'The young master was named Xun, styled Yong’an, twenty-two years old.'],
    ],
  },
  {
    n: 44, title: ['Wang Xun, cousin and friend', '表弟兄，莫逆之交'],
    description: ['Wang Xun: handsome, gifted and generous-hearted; Ziyu’s cousin and inseparable friend.', '王恂一表非凡，文才精通，心地浑厚，与子玉为莫逆之交。'],
    staging: 'Wang Xun’s portrait, then the two cousins greeting each other',
    shots: [
      [0, 20, 'Handsome and generous', '一表非凡', '生得一表非凡，丰华俊雅，文才既极精通，心地尤为浑厚。', 'Handsome and elegant, accomplished in letters, and generous of heart.', '一表非凡，丰华俊雅，文才精通，心地浑厚。'],
      [20, 36, 'Sworn friends', '莫逆之交', '与子玉是表弟兄，为莫逆之交。', 'A senior student sitting the northern examinations, he is Ziyu’s cousin and sworn friend.', '纳了上舍生，在北闱乡试；与子玉是表弟兄，莫逆之交。'],
    ],
    beats: [
      T(`place: 'study', cast: [who.wangxun(-0.8)], ${lines('心地浑厚', '丰华俊雅', '一表非凡', '王恂')}`),
      T(`place: 'gate', cast: [who.wangxun(-2, { gesture: 'bow' }), who.ziyu(0.8, { flip: true, gesture: 'bow' })], ${lines('莫逆之交', '表弟兄')}`),
    ],
    subtitles: [
      [0.4, 10, '生得一表非凡，丰华俊雅，', 'He possessed an extraordinary, handsome and elegant appearance.'],
      [10, 19.6, '文才既极精通，心地尤为浑厚。', 'His literary talents were accomplished, his nature exceptionally generous and sincere.'],
      [20.4, 28, '纳了个上舍生，在北闱乡试。', 'He had purchased a senior studentship and was sitting the northern provincial examinations.'],
      [28, 35.6, '与子玉是表弟兄，为莫逆之交。', 'He and Ziyu were cousins and sworn, inseparable friends.'],
    ],
  },
  {
    n: 45, title: ['The inner quarters', '进内见舅母'],
    description: ['Ziyu pays his respects to Lady Lu and his cousins; Miss Qionghua, hearing talk of a match, is too shy to come out.', '子玉入内拜见陆夫人及表嫂表姊；琼华小姐因闻联姻之语，不肯出来。'],
    staging: 'the ladies of the Wang house, Qionghua hiding, and Lady Lu chatting with Ziyu',
    shots: [
      [0, 14, 'The ladies of the house', '表舅母陆氏夫人', '先同到内里去见了表舅母陆氏夫人……表姊。', 'Ziyu greets Lady Lu, Wang Xun’s wife Lady Sun, and his cousin Ronghua, Zhongqing’s wife.', '子玉拜见陆夫人、表嫂孙氏、表姊蓉华。'],
      [14, 26, 'Miss Qionghua stays away', '琼华小姐没有出来', '还有个琼华小姐没有出来……所以不肯出来见这表兄了。', 'Qionghua, having heard her father hint at a match with Ziyu, is too shy to come out.', '琼华小姐闻父亲有联姻之意，不肯出来见表兄。'],
      [26, 36, 'Fonder each time', '见一回爱一回', '陆夫人见子玉，真是见一回爱一回', 'Lady Lu grows fonder of Ziyu each time; she keeps him to chat, then he takes his leave.', '陆夫人见子玉，见一回爱一回，留坐问家常，子玉告退。'],
    ],
    beats: [
      T(`place: 'hall', cast: [who.lady(-3.4), who.lady(-1.2, { cues: [[5, 'speaking']] }), who.lady(0.9), who.ziyu(8, { walk: [8, 3.4, 0.4, 4.4], flip: true, cues: [[4.6, 'bow']] })]`),
      T(`place: 'boudoir', cast: [who.lady(-1, { gesture: 'hiding', blush: true })], ${lines('不肯出来', '琼华小姐')}`),
      T(`place: 'hall', table: { x: -1.8, w: 3.4 }, cast: [who.lady(-1.8, { cues: [[0.5, 'speaking']] }), who.ziyu(1.6, { flip: true, cues: [[7, 'bow']] })], ${lines('见一回爱一回')}`),
    ],
    subtitles: [
      [0.4, 5, '接进了子玉。先同到内里去见了表舅母陆氏夫人。', 'He welcomed Ziyu inside; first they paid respects to his aunt, Lady Lu.'],
      [5, 9.4, '这夫人已是文辉续娶的了，今年才四十岁。', 'She was Wenhui’s second wife, only forty years old.'],
      [9.4, 13.6, '又见了王恂的妻室孙氏，仲清的妻室蓉华。', 'He also greeted Wang Xun’s wife, Lady Sun, and Zhongqing’s wife, Ronghua.'],
      [14.4, 20, '还有个琼华小姐没有出来，因听得他父亲前日说那子玉的好处，', 'Miss Qionghua did not come out: she had heard her father praise Ziyu,'],
      [20, 25.6, '其口风似要与他联姻，所以不肯出来见这表兄了。', 'hinting at a marriage between them, and was too shy to meet this cousin.'],
      [26.4, 31, '陆夫人见子玉，真是见一回爱一回，', 'Lady Lu’s affection grew every time she saw Ziyu;'],
      [31, 35.6, '留他坐了，问了一会家常话，子玉告退。', 'she kept him seated for a chat, and then Ziyu took his leave.'],
    ],
  },
  {
    n: 46, title: ['Wang Xun defends the book', '王恂也有旦癖'],
    description: ['Ziyu calls the 《花选》 exaggerated; Wang Xun says it falls short of the truth, and Ziyu drops the subject.', '子玉说《花选》失实；王恂说据实尚恐说不到，子玉便不说了。'],
    staging: 'Ziyu and Wang Xun in the study, arguing over the book',
    shots: [
      [0, 14, 'Excessively exaggerated', '过于失实', '子玉说起前日所见南湘的《花选》过于失实', 'Zhongqing has been invited out; Ziyu tells Wang Xun the 《花选》 is exaggerated.', '仲清被请出去了；子玉说南湘《花选》过于失实。'],
      [14, 36, 'It falls short, if anything', '尚恐说不到', '竹君的《花选》，据实而言，尚恐说不到，何以为失实？', 'Wang Xun: if anything it falls short. Ziyu sees his cousin shares the craze, and says no more.', '王恂：据实而言，尚恐说不到。子玉知他也有旦癖，便不说了。'],
    ],
    beats: [
      study2(`who.wangxun(-2.2)`, `who.ziyu(1, { cues: [[3, 'speaking']] })`),
      study2(`who.wangxun(-2.2, { cues: [[0.4, 'speaking'], [12, 'still']] })`, `who.ziyu(1, { cues: [[12, 'thinking']] })`, `, ${lines('尚恐说不到', '据实而言')}`),
    ],
    subtitles: [
      [0.4, 6.6, '然后同王恂到了书房，问起仲清，为高品、南湘请去。', 'He went with Wang Xun to the study and learned Zhongqing had been invited out by Gao Pin and Nanxiang.'],
      [6.6, 13.6, '子玉说起前日所见南湘的《花选》过于失实。', 'Ziyu mentioned that Nanxiang’s “Flower Manual” was excessively exaggerated.'],
      [14.4, 20, '王恂道：「竹君的《花选》，据实而言，尚恐说不到，何以为失实？', 'Wang Xun: “Truly, one should fear it falls short; how is it exaggerated?'],
      [20, 26, '现在那些宝贝得了这番品题，又长了些声价，你也应该见过这些人。」', 'Those treasures have grown in prestige; you really ought to have seen them.”'],
      [26, 35.6, '子玉听了，知王恂也有旦癖，便不说了。', 'Ziyu realized Wang Xun also had a fondness for young dan, and dropped the subject.'],
    ],
  },
  {
    n: 47, title: ['To the theatre', '同到戏园'],
    description: ['Wang Xun takes Ziyu to hear the Lianjin troupe: a packed pit, Three Kingdoms drums, and none of the eight actors in sight.', '王恂带子玉去听联锦班：满园人山人海，锣鼓喧天，八旦一个不见。'],
    staging: 'the cousins deciding, the cart setting out, the packed theatre, and hustlers milling around their table',
    shots: [
      [0, 8, 'Broaden my horizons', '广广眼界', '你何不同我去听两出戏，使我广广眼界？', 'Wang Xun praises the eight; Ziyu, intrigued, asks to be taken to a play.', '王恂盛赞八人；子玉心异，请他同去听戏。'],
      [8, 15, 'Off to the Lianjin', '自然听联锦了', '即吩咐套了车，备了马，就随身便服。', 'Carriage harnessed, horses saddled, in casual dress: six of the eight are in the Lianjin troupe.', '套车备马，换了便服；八人中联锦有六个，自然听联锦。'],
      [15, 26, 'A sea of people', '人山人海', '子玉一进门，见人山人海坐满了一园……锣鼓盈天，好不热闹。', 'The theatre is packed; they squeeze to the stage’s edge. The Three Kingdoms is on, gongs and drums deafening.', '人山人海，挤到台口；正唱《三国演义》，锣鼓盈天。'],
      [26, 36, 'Dark-faced escorts', '黑相公', '身边走来走去的，都是些黑相公', 'No sign of the six actors—only dark-faced escorts flowing past, hunting for patrons.', '六旦不见一个，身边川流不息的都是黑相公。'],
    ],
    beats: [
      study2(`who.wangxun(-2.2, { cues: [[0.3, 'speaking'], [4, 'still']] })`, `who.ziyu(1, { cues: [[4, 'speaking']] })`),
      T(`place: 'street', cast: [{ kind: 'horse', x: -9, h: 2.6, walk: [-9, 8, 0.2, 6.6] }, { kind: 'cart', x: -12, walk: [-12, 1, 0.8, 6.8] }]`),
      T(`place: 'theatre', cast: [{ kind: 'warrior', x: 0, y: 1.4, h: 3.4, z: -1.4 }, { kind: 'escort', x: -4.6, h: 4 }, { kind: 'page', x: 4.4, h: 3.8 }, who.wangxun(8, { walk: [8, 1.8, 0.5, 6], flip: true }), who.ziyu(9.4, { walk: [9.4, 3.2, 0.8, 6.4], flip: true })], ${lines('锣鼓盈天')}`.replace(', lines', ', linesSide: \'left\', lines')),
      T(`place: 'theatre', table: { x: -2.6, w: 4.4 }, cast: [{ kind: 'warrior', x: 1.4, y: 1.4, h: 3.4, z: -1.4 },who.ziyu(-3.6, { gesture: 'thinking' }), who.wangxun(-1.6), { kind: 'escort', x: 7, walk: [7, -8, 0.5, 6.5], flip: true }, { kind: 'escort', x: -8, walk: [-8, 7, 3, 9.5] }]`),
    ],
    subtitles: [
      [0.4, 4, '王恂道：「好的呢也还有些，但总不及这八个，这是万选青钱。」', 'Wang Xun: “There are other good ones, but none compare to these eight—ten thousand times chosen.”'],
      [4, 7.6, '子玉便说道：「你何不同我去听两出戏，使我广广眼界？」', 'Ziyu said, “Why not take me to hear a couple of plays and broaden my horizons?”'],
      [8.4, 14.6, '即吩咐套了车，备了马。王恂道：「联锦有六个，联珠只有两个，自然听联锦了。」', 'Carriage and horses were readied. “Six are from Lianjin and only two from Lianzhu—naturally we hear Lianjin.”'],
      [15.4, 20.4, '子玉一进门，见人山人海坐满了一园，便有些懊悔。', 'Entering, Ziyu saw a sea of humanity packing the theatre, and felt a surge of regret.'],
      [20.4, 25.6, '此刻是唱的《三国演义》，锣鼓盈天，好不热闹。', 'They were performing “The Romance of the Three Kingdoms”; gongs and drums deafened the heavens.'],
      [26.4, 31, '王恂留心非但那六旦之中不见一个，', 'Wang Xun looked carefully, but could not spot a single one of the six,'],
      [31, 35.6, '身边走来走去的，都是些黑相公，四处去找吃饭的老斗。', 'only dark-faced escorts flowing endlessly past, looking for wealthy patrons.'],
    ],
  },
  {
    n: 48, title: ['The man in the grey fox fur', '灰色老狐裘'],
    description: ['Wang Xun chats with an acquaintance while a dazed man in a grey fox fur squeezes past Ziyu again and again.', '王恂与人说话；一个穿灰色老狐裘的人在子玉身边挤来挤去。'],
    staging: 'Wang Xun turning to an acquaintance, and the man in grey fur passing to and fro',
    shots: [
      [0, 12, 'An acquaintance calls', '招呼王恂', '只见那边桌子上来了一人，招呼王恂', 'A man at another table calls to Wang Xun, who turns to chat.', '那边桌子上一人招呼王恂，王恂转身与他讲话。'],
      [12, 36, 'Back and forth', '挤了过去，又挤了过来', '一刻之间就走了三四回。每近身时，必看他一眼', 'A broad, dazed man in an old grey fox fur squeezes past three or four times, glancing at Ziyu and Wang Xun.', '穿灰色老狐裘的人，一刻之间挤过三四回，每次必看子玉一眼。'],
    ],
    beats: [
      T(`place: 'theatre', table: { x: -1.6, w: 5.4 }, cast: [who.ziyu(-3.4, { gesture: 'thinking' }), who.wangxun(-1, { flip: true, cues: [[2, 'speaking']] }), who.zhongqing(3.2, { flip: true, cues: [[1, 'speaking'], [6, 'laughing']] })]`),
      T(`place: 'theatre', table: { x: -1.6, w: 5.4 }, cast: [who.ziyu(-3.4, { gesture: 'thinking' }), who.wangxun(-1, { flip: true, gesture: 'speaking' }), { kind: 'merchant', x: 8, z: 0.2, walk: [8, -8, 0.3, 5.6], flip: true, until: 6 }, { kind: 'merchant', x: -8, z: 0.2, walk: [-8, 8, 6, 11.5], from: 6, until: 12 }, { kind: 'merchant', x: 8, z: 0.2, walk: [8, -8, 12, 17.4], flip: true, from: 12, until: 18 }, { kind: 'merchant', x: -8, z: 0.2, walk: [-8, 1, 18, 21], from: 18 }]`),
    ],
    subtitles: [
      [0.4, 6, '子玉看了一会闷戏，只见那边桌子上来了一人，招呼王恂，', 'Ziyu watched the tedious play, then a man at a table over there called out to Wang Xun,'],
      [6, 11.6, '王恂便旋转身子与那人讲话。', 'and Wang Xun turned to converse with him.'],
      [12.4, 17.6, '又见一个人走将过来，穿一件灰色老狐裘，一双泥帮宽皂靴，', 'Another man came over, in an old grey fox fur and loose black boots caked with mud,'],
      [17.6, 22.6, '身材阔而且扁，歪着膀子，神气昏迷，在他身边挤了过去。', 'broad and flat, shoulders drooping, dazed, squeezing past right beside Ziyu.'],
      [22.6, 28, '停一会又挤了过来，一刻之间就走了三四回。', 'A moment later he squeezed back; in a short span he passed three or four times.'],
      [28, 35.6, '每近身时，必看他一眼，又看看王恂，似有照应王恂之意。', 'Each time he glanced at Ziyu, then at Wang Xun, as if meaning to greet him.'],
    ],
  },
  {
    n: 49, title: ['As if on burning coals', '如坐涂炭'],
    description: ['Just as Ziyu means to leave, a man brings over a dull-faced escort boy, who takes Ziyu’s hand.', '子玉正想回去，一人领来一个相公，挤坐桌中，摸着子玉的手问贵姓。'],
    staging: 'Ziyu fidgeting at the table, then the man and the escort boy squeezing in',
    shots: [
      [0, 12, 'On burning coals', '如坐涂炭', '子玉好不心烦，如坐涂炭。', 'Ziyu feels as if he were sitting on burning coals, and wants to go home.', '子玉心烦，如坐涂炭，想要回去。'],
      [12, 36, 'An escort boy', '领着一个相公', '只见一人领着一个相公……子玉颇不愿答他。', 'A beaming man brings over a heavy-headed boy with dark hands, who squeezes in and takes Ziyu’s hand.', '一人领着相公挤坐桌中；那相公蠢头笨脑，手是黑的，摸着子玉的手问贵姓。'],
    ],
    beats: [
      T(`place: 'theatre', table: { x: -1.6, w: 5.4 }, cast: [who.ziyu(-3.4, { gesture: 'thinking', cues: [[5, 'still'], [8, 'thinking']] }), who.wangxun(-1, { cues: [[1, 'speaking'], [4, 'still']] })]`),
      T(`place: 'theatre', table: { x: -1.6, w: 5.4 }, cast: [who.ziyu(-3.4), who.wangxun(-1), { kind: 'scholar', hair: 'cap', x: 8, walk: [8, 2.6, 0.4, 5], flip: true, cues: [[5.2, 'bow']] }, { kind: 'escort', x: 9.4, walk: [9.4, 0.6, 0.6, 6.4], flip: true, cues: [[8, 'tugging']] }]`),
    ],
    subtitles: [
      [0.4, 6, '子玉好不心烦，如坐涂炭。', 'Ziyu felt incredibly annoyed, as if sitting on burning coals.'],
      [6, 11.6, '王恂说完了话坐正了，子玉想要回去。', 'Wang Xun finished his conversation; Ziyu wanted to suggest they return.'],
      [12.4, 18, '只见一人领着一个相公，笑嘻嘻的走近来，请了两个安，便挤在桌子中间坐了。', 'A man leading an escort boy approached, beaming, offered two greetings, and squeezed in at the table.'],
      [18, 24, '那相公约有十五六岁，生得蠢头笨脑，脸上露着两块大孤骨，', 'The boy, about fifteen, had a dull, heavy head and two large, prominent cheekbones.'],
      [24, 29.4, '脸面虽白，手却是黑的。', 'Though his face was white, his hands were dark.'],
      [29.4, 35.6, '他倒摸着子玉的手问起贵姓来，子玉颇不愿答他。', 'He reached out to touch Ziyu’s hand and asked his surname; Ziyu was highly reluctant to answer.'],
    ],
  },
  {
    n: 50, title: ['“He’s called Baozhu”', '叫保珠'],
    description: ['The boy’s name is Baozhu—Ziyu laughs; the boy pesters Wang Xun, and Ziyu sends for the carriage.', '那相公名叫保珠，子玉忍不住一笑；保珠缠住王恂，子玉叫云儿看车。'],
    staging: 'the name that makes Ziyu laugh, the boy pestering Wang Xun, and Yun’er announcing the carriage',
    shots: [
      [0, 12, 'Baozhu', '叫保珠', '那人道：「叫保珠。」子玉听了，忍不住一笑。', 'Wang Xun asks the boy’s name: “Baozhu.” Ziyu cannot help laughing—the name of the album’s first beauty.', '那相公叫保珠，与《花选》第一人同音，子玉忍不住一笑。'],
      [12, 24, 'Pestering Wang Xun', '缠住了王恂', '那保珠便拉了王恂的手……要带他吃饭。', 'The boy grabs Wang Xun’s hand, pestering him to take him out to eat.', '保珠拉着王恂的手，缠着要他带去吃饭。'],
      [24, 36, 'The carriage is ready', '都伺候了', '便叫云儿去看车。云儿不一刻进来说：「都伺候了。」', 'Ziyu sends Yun’er to check the carriage: “It’s ready.” He tells Wang Xun he is going home.', '子玉叫云儿看车，云儿回说都伺候了；子玉要回去了。'],
    ],
    beats: [
      T(`place: 'theatre', table: { x: -1.6, w: 5.4 }, cast: [who.ziyu(-3.4, { cues: [[5, 'laughing']] }), who.wangxun(-1, { cues: [[0.4, 'speaking'], [3, 'still']] }), { kind: 'escort', x: 1.6 }], ${lines('保珠')}`),
      T(`place: 'theatre', table: { x: -1.6, w: 5.4 }, cast: [who.ziyu(-3.4, { gesture: 'thinking' }), who.wangxun(-1, { cues: [[6, 'speaking']] }), { kind: 'escort', x: 1.2, flip: true, gesture: 'tugging' }]`),
      T(`place: 'theatre', table: { x: -1.6, w: 5.4 }, cast: [who.ziyu(-3.4, { cues: [[6, 'speaking']] }), who.wangxun(-1), who.page(8, { walk: [8, 2.4, 0.4, 4.4], flip: true, cues: [[4.6, 'speaking'], [7, 'bow']] })]`),
    ],
    subtitles: [
      [0.4, 4.6, '王恂问那人道：「你这相公叫什么名字？」那人道：「叫保珠。」', 'Wang Xun asked, “What is this boy’s name?” The man replied, “He’s called Baozhu.”'],
      [4.6, 8, '子玉听了，忍不住一笑。', 'Hearing this, Ziyu couldn’t suppress a laugh.'],
      [8, 11.6, '「这保珠就住在桂保间壁，少爷今日叫保珠伺候？」', '“Baozhu lives next door to Guibao. Will the young master call for him today?”'],
      [12.4, 18, '那保珠便拉了王恂的手问道：「到什么地方去，也是时候了。」', 'Baozhu grabbed Wang Xun’s hand: “Where are we going? It’s about time.”'],
      [18, 23.6, '王恂道：「改日罢。」那相公便缠住了王恂，要带他吃饭。', '“Another day.” The boy pestered Wang Xun to take him out to eat.'],
      [24.4, 30, '子玉实在坐不住了，便叫云儿去看车。云儿进来说：「都伺候了。」', 'Ziyu could sit no longer and sent Yun’er to check the carriage. “It’s ready.”'],
      [30, 35.6, '子玉即对王恂道：「我要回去了。」', 'Ziyu immediately said to Wang Xun, “I am going back.”'],
    ],
  },
  {
    n: 51, title: ['Separate ways home', '各自分路而回'],
    description: ['They leave; the boy trails Wang Xun a few steps, then gives up; the cousins’ carts part in the street.', '二人出园，相公拉着王恂走了几步便自去了；子玉、王恂各自分路而回。'],
    staging: 'leaving the theatre with the boy trailing, and the two carts parting ways',
    shots: [
      [0, 14, 'The boy gives up', '便自去了', '那相公还拉着王恂走了几步，看不像带他吃饭的光景，便自去了。', '“Let’s come earlier next time.” The boy tugs at Wang Xun for a few steps, then leaves on his own.', '王恂道改日早些来；相公拉着王恂走了几步，便自去了。'],
      [14, 36, 'Separate ways', '各自分路而回', '子玉、王徇上了车，各自分路而回。', 'Ziyu and Wang Xun board their carriages and go their separate ways home.', '子玉、王恂上了车，各自分路而回。'],
    ],
    beats: [
      T(`place: 'street', cast: [who.ziyu(-2, { walk: [-2, -9, 1, 9], flip: true }), who.wangxun(0, { walk: [0, -7, 1, 11], flip: true }), { kind: 'escort', x: 1.4, walk: [1.4, -2, 1, 5], flip: true, gesture: 'tugging', until: 6 }, { kind: 'escort', x: -2, walk: [-2, 8, 6, 12], from: 6 }]`),
      T(`place: 'street', flurry: true, cast: [{ kind: 'cart', x: -1.4, walk: [-1.4, -13, 3, 16], flip: true }, { kind: 'cart', x: 1.8, walk: [1.8, 13, 3.4, 16.4] }]`),
    ],
    subtitles: [
      [0.4, 5, '「今日来迟了，歇一天早些来。」也就同了出来。', '“We arrived too late today; let’s come earlier next time.” They left together.'],
      [5, 9.4, '王恂的家人付了戏钱，那相公还拉着王恂走了几步，', 'Wang Xun’s servant paid; the escort boy still tugged at Wang Xun for a few steps,'],
      [9.4, 13.6, '看不像带他吃饭的光景，便自去了。', 'but seeing no prospect of a meal, left on his own.'],
      [14.4, 35.6, '子玉、王恂上了车，各自分路而回。', 'Ziyu and Wang Xun boarded their carriages and went their separate ways home.'],
    ],
  },
  {
    n: 52, title: ['A fragrance in the crowd', '一阵清香'],
    description: ['Ziyu laughs at the craze on his way home; wedged in traffic, he catches an unknown fragrance and looks out at the cart opposite.', '子玉一路自笑；车子挤住，闻得一阵清香，从玻璃窗望见对面车上两个妙童。'],
    staging: 'Ziyu’s cart rolling home, two carts wedged in the street, and the view through the glass window',
    shots: [
      [0, 12, 'Laughing to himself', '心里自笑', '何以这些人为几个小旦，颠倒得神昏目暗，皂白不分。', 'Ziyu laughs: how these people lose their wits over a few young dan!', '子玉自笑：这些人为几个小旦颠倒得神昏目暗。'],
      [12, 24, 'Neither orchid nor musk', '非兰非麝', '忽到一处挤了车，子玉觉得鼻中一阵清香，非兰非麝', 'The carts wedge together in a bottleneck; a pure fragrance drifts in, neither orchid nor musk.', '车子挤住，鼻中一阵清香，非兰非麝。'],
      [24, 36, 'Through the glass window', '从玻璃窗内一望', '见对面一辆车，车里坐着一个老年的，外面坐了两个妙童', 'Through the window: an old man in the cart opposite, and two wondrous boys of fourteen or fifteen outside.', '对面车里一个老年的，外面坐着两个妙童，都不过十四五岁。'],
    ],
    beats: [
      T(`place: 'street', flurry: true, cast: [{ kind: 'cart', x: -9, walk: [-9, 1, 0.3, 11] }], ${lines('神昏目暗', '颠倒得')}`),
      T(`place: 'street', petals: true, cast: [{ kind: 'cart', x: -7, walk: [-7, -2.4, 0.3, 4] }, { kind: 'cart', x: 8, walk: [8, 2.6, 0.3, 4], flip: true }], ${lines('非兰非麝', '一阵清香')}`),
      T(`place: 'street', window: true, petals: true, camera: { from: 10.6, to: 9.8, drift: 0.2 }, cast: [{ kind: 'cart', x: 0.4, h: 4, flip: true, z: -1 }, { kind: 'elder', x: -0.6, y: 1.2, h: 1.4, z: -0.9, opacity: 0.8 }, { kind: 'scholar', hair: 'bun', x: -2.4, y: 0.2, h: 3, z: -0.4 }, { kind: 'scholar', hair: 'bun', x: -3.4, y: 0.2, h: 3, z: -0.4, gesture: 'thinking' }]`),
    ],
    subtitles: [
      [0.4, 6, '子玉心里自笑不已：「何以这些人为几个小旦，颠倒得神昏目暗，皂白不分。', 'Ziyu laughed to himself: “Why do these people turn so blind over a few young dan?'],
      [6, 11.6, '设或如今有个真正绝色来，只怕他们倒说不好了。」', 'If a truly peerless beauty appeared, I fear they would say he looked terrible.”'],
      [12.4, 18, '一路思想，忽到一处挤了车，', 'Lost in thought, his carriage suddenly became wedged in a crowded bottleneck.'],
      [18, 23.6, '子玉觉得鼻中一阵清香，非兰非麝，', 'He caught a waft of pure fragrance—neither orchid nor musk—'],
      [24.4, 30, '便从帘子上玻璃窗内一望，见对面一辆车，车里坐着一个老年的，', 'and peeked through the glass window: in the carriage opposite sat an elderly man,'],
      [30, 35.6, '外面坐了两个妙童，都不过十四五岁。', 'and outside sat two wondrous boys, no more than fourteen or fifteen.'],
    ],
  },
  {
    n: 53, title: ['Jade for bones, the moon for a soul', '以玉为骨，以月为魂'],
    description: ['One boy is a crabapple blossom; the other a peerless immortal. Ziyu lifts the curtain and stares; the boy gazes back, and a radiance fills the air.', '一个似海棠花；一个天上神仙，人间绝色。子玉掀帘凝望，那绝色的也凝眸相对，异香满鼻。'],
    staging: 'the crabapple boy, the peerless boy in radiance, the gazes across the carts, and the dazzled scattering of light and fragrance',
    shots: [
      [0, 9, 'Like a crabapple blossom', '似海棠花', '一个已似海棠花，娇艳无比，眉目天然。', 'One is like a crabapple blossom, delicate and radiant, his features shaped by nature.', '一个似海棠花，娇艳无比，眉目天然。'],
      [9, 20, 'A peerless beauty', '人间绝色', '一个真是天上神仙，人间绝色，以玉为骨，以月为魂……', 'The other: an immortal, a peerless beauty—jade for bones, the moon for a soul, flowers for feeling, pearls for spirit.', '一个天上神仙，人间绝色：以玉为骨，以月为魂，以花为情，以珠光宝气为精神。'],
      [20, 30, 'Their eyes meet', '凝眸伫望', '子玉惊得呆了，不知不觉把帘子掀开……对着子玉出神。', 'Ziyu, struck dumb, lifts the curtain and stares; the boy gazes back at him, lost in thought.', '子玉惊呆，掀帘凝望；那绝色的也凝眸伫望，对着子玉出神。'],
      [30, 36, 'Dazzled', '心摇目眩', '子玉觉得心摇目眩……散作满鼻的异香。', 'Ziyu’s heart sways, his eyes dazzle; a radiance seems to fall on him, scattering into fragrance.', '子玉心摇目眩；那脸上似有光彩照来，散作满鼻异香。'],
    ],
    beats: [
      `portraitBeat(BOY, ['似海棠花', '娇艳无比', '眉目天然'])`,
      T(`place: 'moon-palace', aura: [-0.8, 0.4], petals: true, cast: [{ kind: 'scholar', hair: 'bun', x: -0.8, h: 4.8 }], ${lines('以珠光宝气为精神', '以花为情', '以月为魂', '以玉为骨')}`),
      T(`place: 'street', window: true, petals: true, aura: [-2.6, 0.6], camera: { from: 10.4, to: 9.2, drift: 0.2 }, cast: [{ kind: 'cart', x: 0.4, h: 4, flip: true, z: -1 }, { kind: 'scholar', hair: 'bun', x: -2.6, y: 0.2, h: 3.2, z: -0.4, gesture: 'thinking' }, { kind: 'scholar', hair: 'bun', x: -3.8, y: 0.2, h: 3, z: -0.4 }]`),
      T(`place: 'clouds', aura: [0, 0.4], petals: true, cast: [{ kind: 'scholar', hair: 'bun', x: 0, h: 4.8, opacity: 0.7, float: 0.12 }], ${lines('满鼻异香', '心摇目眩')}`),
    ],
    subtitles: [
      [0.4, 8.6, '一个已似海棠花，娇艳无比，眉目天然。', 'One was already like a crabapple blossom, incomparably delicate, his features perfectly shaped by nature.'],
      [9.4, 14.4, '一个真是天上神仙，人间绝色，', 'The other was truly a divine being from the heavens, a peerless beauty in the mortal world,'],
      [14.4, 19.6, '以玉为骨，以月为魂，以花为情，以珠光宝气为精神。', 'jade for bones, the moon for a soul, flowers for emotions, the aura of pearls for his spirit.'],
      [20.4, 25, '子玉惊得呆了，不知不觉把帘子掀开，凝神而望。', 'Ziyu was struck dumb; without realizing it, he lifted the curtain and stared.'],
      [25, 29.6, '那个绝色的更觉凝眸伫望，对着子玉出神。', 'The peerless one gazed back even more intently, lost in thought before Ziyu.'],
      [30.4, 33, '子玉觉得心摇目眩。', 'Ziyu felt his heart sway and his eyes dazzle.'],
      [33, 35.6, '那个绝色的脸上，似有一层光彩照过来，散作满鼻的异香。', 'A radiance seemed to fall from that face, scattering into an exotic fragrance.'],
    ],
  },
  {
    n: 54, title: ['Where have I seen him?', '似像见过'],
    description: ['The cart moves on, followed by ordinary carts of children; Ziyu is left hazy, sure he has seen that face before.', '车已过去，后头几辆坐些小孩子；子玉心里模糊，似曾见过此人。'],
    staging: 'the carts passing, and Ziyu lost in a half-remembered face',
    shots: [
      [0, 14, 'The cart passes', '车已过去', '正在好看，车已过去。后头又有三四辆，也坐些小孩子，恰不甚佳。', 'Just as he gazes, the cart moves on; three or four more follow, carrying ordinary children.', '车已过去，后头三四辆，也坐些小孩子，恰不甚佳。'],
      [14, 36, 'A half-remembered face', '似像见过', '似像见过这人的相貌，好像一个人，再想不起了。', 'Ziyu feels he has seen that face before—it resembles someone—but he cannot remember whom.', '子玉似曾见过这人相貌，好像一个人，再想不起。'],
    ],
    beats: [
      T(`place: 'street', cast: [{ kind: 'cart', x: 1, walk: [1, -13, 0.5, 5], flip: true }, { kind: 'cart', x: 12, walk: [12, -13, 3.5, 9.5], flip: true, from: 3.5 }, { kind: 'cart', x: 12, walk: [12, -13, 6.5, 12.5], flip: true, from: 6.5 }]`),
      T(`place: 'clouds', cast: [who.ziyu(-2, { gesture: 'thinking' }), { kind: 'scholar', hair: 'bun', x: 1.8, opacity: 0.3, float: 0.1 }], ${lines('再想不起', '似像见过')}`),
    ],
    subtitles: [
      [0.4, 5, '正在好看，车已过去。', 'Just as he was absorbed in the sight, the carriage passed by.'],
      [5, 13.6, '后头又有三四辆，也坐些小孩子，恰不甚佳。', 'Three or four more followed, also carrying children, though quite ordinary.'],
      [14.4, 22, '子玉心里有些模模糊糊起来，', 'A hazy confusion rose in Ziyu’s mind;'],
      [22, 35.6, '似像见过这人的相貌，好像一个人，再想不起了。', 'it was as if he had seen that face before, as if he resembled someone—but he couldn’t remember who.'],
    ],
  },
  {
    n: 55, title: ['He belongs in the moon palace', '当以广寒宫贮之'],
    description: ['Ziyu wonders who the boys are, so plainly dressed; such beauty deserves the palace of the moon.', '子玉猜这些孩子是何人，服饰不华；如此美貌，当以广寒宫贮之。'],
    staging: 'Ziyu’s cart going on through the street, and the boy imagined in the Guanghan palace',
    shots: [
      [0, 18, 'Plainly dressed', '服饰又不华美', '这些孩子是什么人？也像戏班子一样，但服饰又不华美。', 'Who are they? Like a troupe, yet plainly dressed—and that one unmatched under heaven.', '这些孩子像戏班子，服饰却不华美；那一个天下无双。'],
      [18, 36, 'The Guanghan palace', '广寒宫', '当以广寒宫贮之，岂特郁金堂、翡翠楼，即称其美。', 'Such beauty ought to be housed in the moon’s Guanghan palace; no jadeite tower would do him justice.', '当以广寒宫贮之，郁金堂、翡翠楼亦不足称其美。'],
    ],
    beats: [
      T(`place: 'street', cast: [{ kind: 'cart', x: -6, walk: [-6, 4, 0.3, 17] }], ${lines('天下无双', '服饰又不华美')}`),
      T(`place: 'moon-palace', aura: [0, 0.2], cast: [{ kind: 'scholar', hair: 'bun', x: 0, h: 4.4, opacity: 0.7, float: 0.15 }], ${lines('当以广寒宫贮之')}`),
    ],
    subtitles: [
      [0.4, 6, '心里想道：「这些孩子是什么人？也像戏班子一样，但服饰又不华美。', 'He thought: “Who are these children? Like a troupe, yet their clothes are not extravagant.'],
      [6, 11.6, '那一个直可称古今少有，天下无双。', 'That one is a rarity across all ages, unmatched under heaven.'],
      [11.6, 17.6, '他既具此美貌，何以倒又服御不鲜，真委屈了此人。', 'With such beauty, why is his attire so plain? It truly wrongs him.'],
      [18.4, 27, '当以广寒宫贮之，', 'He ought to be housed in the Guanghan Palace of the moon;'],
      [27, 35.6, '岂特郁金堂、翡翠楼，即称其美。」', 'a hall of curcuma or a jadeite tower would hardly do him justice.”'],
    ],
  },
  {
    n: 56, title: ['Not fit to be his servant', '做他的舆儓也还不配'],
    description: ['Ziyu decides “universally admired” was an empty boast: that Baozhu is not fit to be this boy’s lowliest servant. He rides home, and the chapter ends.', '子玉想“有目共赏”竟是妄言，那保珠做他的舆儓也还不配。一路想到家，且听下回分解。'],
    staging: 'the vulgar Baozhu beside the peerless boy, Ziyu’s cart arriving home, and the chapter’s closing words',
    shots: [
      [0, 14, 'Not even his servant', '舆儓也还不配', '把方才这个保珠比他，做他的舆儓，也还不配。', '“Universally admired” was an empty boast: that Baozhu is not fit to be this boy’s lowliest menial.', '“有目共赏”竟是妄言；那保珠做他的舆儓也还不配。'],
      [14, 28, 'Home again', '一路想到了家', '子玉一路想到了家', 'Ziyu ponders all the way home.', '子玉一路想到了家。'],
      [28, 36, 'To be continued', '且听下回分解', '不知后事如何。且听下回分解。', 'To know what happens next, listen to the next chapter.', '不知后事如何，且听下回分解。'],
    ],
    beats: [
      T(`place: 'paper', aura: [1.4, 0.4], cast: [{ kind: 'escort', x: -2.6 }, { kind: 'scholar', hair: 'bun', x: 1.4, h: 4.6 }], ${lines('也还不配', '做他的舆儓')}`),
      T(`place: 'gate', cast: [{ kind: 'cart', x: -11, walk: [-11, -1, 0.3, 9] }, who.page(-2.8, { gesture: 'bow', from: 9 })]`),
      poem('不知后事如何', '且听下回分解'),
    ],
    subtitles: [
      [0.4, 6.6, '这么看来，「有目共赏」的一句，竟是妄言了。', 'Looking at it this way, the phrase “universally appreciated” has proven an empty boast.'],
      [6.6, 13.6, '把方才这个保珠比他，做他的舆儓，也还不配。', 'That Baozhu from earlier would not even be fit to serve as his lowliest menial.'],
      [14.4, 27.6, '子玉一路想到了家；', 'Ziyu pondered this all the way home.'],
      [28.4, 35.6, '不知后事如何。且听下回分解。', 'To know what happens next, please listen to the explanation in the following chapter.'],
    ],
  },
];
