import { defineStory } from '../../define';

/**
 * Chapter 2, paragraph 40. Generated by `npm run build-cinemas -- 2 40` from
 * scripts/cinema/specs; edit the spec, not this file.
 *
 * 原文：第二三杯即系亮功自己的令，便道：「这装小旦倒是作法自弊了。也罢，让我来敬两个人。」随站起
 *   来，左手拿了杯酒，右手掩了胡子，把头扭了两扭，笑迷迷软腰细步的走到杨方猷面前，请了一个
 *   安，娇声娇气的道「敬杨老爷一杯酒，务必赏个脸儿。」说着，把眼睛四下里飞了一转，宛然联锦班
 *   内京丑谭八的丑态，引得合席大笑，桂保笑得如花枝乱颤，杨方猷只得饮了一杯。孙亮功掐了一枝梅
 *   花，插在帽边，又取了一个大杯，捻手蹑脚的走到陆宗沅面前，斟了酒道：「陆都老爷是向来疼我
 *   的，敬你这一杯。」陆宗玩道：「这大杯如何使得？」孙亮功道：「想来都老爷是要吃皮杯的。」说
 *   罢呷了一口，送到宗沅嘴边。综沅站起来笑道：「这个免劳照顾。」大家狂笑起来，亮功忍不住要
 *   笑，酒咽不及，喷了陆宗沅一脸。众人一发哄堂大笑。陆宗玩忙要水净了脸。第四杯是数瓜子令。亮
 *   功抓了一把，数一数是二十五粒，恰好数到自己，陆宗沅道：「这个极该。」第五六杯是飞花令，孙
 *   亮功看着桂保道：「岂宜重问后庭花。」数一数又是自饮。亮功道：「晦气，我改一句罢。」
 *
 * Translation: The second and third cups fell under Lianggong's own rule. He sighed, "This female
 *   impersonation has truly backfired on me. Very well, allow me to toast two gentlemen."
 *   Rising to his feet, he clasped a cup of wine in his left hand, obscured his beard with his
 *   right, tilted his head coquettishly twice, and, wearing a beguiling smile, minced
 *   delicately toward Yang Fangyou with a swaying gait. Executing a demure curtsy, he cooed in
 *   a sickeningly sweet voice, "I present Master Yang with a cup of wine, please do me the
 *   honor of accepting." As he spoke, his eyes darted flirtatiously around the table, perfectly
 *   mimicking the grotesque antics of the famous comic actor Tan Ba from the Lianjin troupe.
 *   The entire table convulsed with laughter, Guibao shaking like a branch of blossoms in the
 *   wind. Yang Fangyou had no choice but to down the cup. Sun Lianggong then plucked a sprig of
 *   plum blossom, tucked it jauntily into the brim of his hat, seized a large cup, and crept
 *   stealthily toward Lu Zongyuan. Filling the cup, he crooned, "The Metropolitan Censor Lu has
 *   always showered me with affection, I dedicate this cup to you." Lu Zongyuan protested, "How
 *   am I to manage such a massive cup?" Sun Lianggong teased, "I assume the Censor prefers a
 *   'skin cup' (a kiss)." With that, he took a sip and pressed the rim against Zongyuan's lips.
 *   Zongyuan leaped up, laughing, "Spare me the personal service." The guests roared with
 *   amusement. Lianggong, unable to suppress his own laughter and failing to swallow the wine
 *   in time, sprayed it directly into Lu Zongyuan's face. The room erupted into sheer
 *   pandemonium. Lu Zongyuan scrambled for water to wash his face. The fourth cup involved the
 *   melon seed counting rule. Lianggong grabbed a handful and counted them out, twenty-five
 *   seeds, landing precisely on himself. Lu Zongyuan remarked, "That is exceptionally fitting."
 *   The fifth and sixth cups were the flying flower toast. Sun Lianggong gazed at Guibao and
 *   quoted, "'How can one bear to ask again of the rear courtyard flowers?'" He counted it out,
 *   and once more, the penalty fell upon him. Lianggong grumbled, "Such wretched luck. Let me
 *   change a single word."
 *
 * Staging: Lianggong mincing across the room, toasting Yang, spraying Lu, and the unlucky verse.
 */
export default defineStory({
  title: { en: 'Lianggong plays the dan', zh: '装作小旦' },
  description: {
    en: 'Caught by his own rule, Lianggong covers his beard, minces over to toast Yang like the clown Tan Ba, offers Lu a “skin cup”, sprays him with wine—then loses at the seeds and the flying flower too.',
    zh: '亮功作法自弊，掩了胡子、软腰细步敬杨方猷，活像京丑谭八；又敬陆宗沅皮杯，喷了他一脸；数瓜子、飞花又轮到自己。',
  },
  shots: [
    {
      start: 0, end: 10,
      title: { en: 'Hand over his beard', zh: '右手掩了胡子' },
      quote: '随站起来，左手拿了杯酒，右手掩了胡子……软腰细步的走到杨方猷面前',
      caption: { en: 'Caught by his own rule, Lianggong rises, cup in one hand, the other over his beard, and minces over to Yang.', zh: '亮功作法自弊：左手拿酒，右手掩胡子，软腰细步走到杨方猷面前。' },
    },
    {
      start: 10, end: 18,
      title: { en: '“Do me the honour”', zh: '务必赏个脸儿' },
      quote: '娇声娇气的道「敬杨老爷一杯酒，务必赏个脸儿。」',
      caption: { en: 'In a sugary voice, eyes darting like the clown Tan Ba, he toasts Yang; the table roars.', zh: '娇声娇气敬酒，眼睛四下飞转，宛然京丑谭八；合席大笑。' },
    },
    {
      start: 18, end: 27,
      title: { en: 'A face full of wine', zh: '喷了陆宗沅一脸' },
      quote: '亮功忍不住要笑，酒咽不及，喷了陆宗沅一脸。',
      caption: { en: 'He offers Lu a sip from his own lips; laughing, he sprays the wine all over Lu’s face.', zh: '亮功要敬陆宗沅皮杯，忍不住笑，喷了陆宗沅一脸。' },
    },
    {
      start: 27, end: 36,
      title: { en: '“Rear courtyard flowers”', zh: '后庭花' },
      quote: '孙亮功看着桂保道：「岂宜重问后庭花。」数一数又是自饮。',
      caption: { en: 'The seeds count out to himself, and his flying-flower line lands on him again.', zh: '数瓜子恰数到自己；飞花「岂宜重问后庭花」，又是自饮。' },
    },
  ],
  subtitles: [
    { start: 0.4, end: 5, zh: '第二三杯即系亮功自己的令，便道：「这装小旦倒是作法自弊了。」', en: 'The second and third cups fell under his own rule. “This impersonation has backfired on me.”' },
    { start: 5, end: 9.6, zh: '随站起来，左手拿了杯酒，右手掩了胡子，笑迷迷软腰细步的走到杨方猷面前，', en: 'He rose, cup in his left hand, his right veiling his beard, and minced smiling over to Yang Fangyou,' },
    { start: 10.4, end: 14, zh: '请了一个安，娇声娇气的道：「敬杨老爷一杯酒，务必赏个脸儿。」', en: 'curtsied, and cooed: “A cup for Master Yang—please do me the honor.”' },
    { start: 14, end: 17.6, zh: '把眼睛四下里飞了一转，宛然联锦班内京丑谭八的丑态，引得合席大笑。', en: 'His eyes darted about, the very image of the clown Tan Ba; the whole table roared.' },
    { start: 18.4, end: 22.6, zh: '又取了一个大杯，走到陆宗沅面前：「想来都老爷是要吃皮杯的。」', en: 'With a large cup he crept to Lu Zongyuan: “I suppose the Censor wants a ‘skin cup.’”' },
    { start: 22.6, end: 26.6, zh: '亮功忍不住要笑，酒咽不及，喷了陆宗沅一脸。众人一发哄堂大笑。', en: 'He couldn’t help laughing and sprayed the wine all over Lu’s face. The room erupted.' },
    { start: 27.4, end: 31.6, zh: '第四杯是数瓜子令。亮功抓了一把，数一数是二十五粒，恰好数到自己。', en: 'The fourth cup: melon seeds. Lianggong grabbed twenty-five—landing on himself.' },
    { start: 31.6, end: 35.6, zh: '孙亮功看着桂保道：「岂宜重问后庭花。」数一数又是自饮。', en: 'Eyeing Guibao, he quoted, “How can one ask again of the rear-courtyard flowers?”—and it fell on him again.' },
  ],
});
